Repository gem/oq-engine, pull requests merged in 2018-04, with the labels that each got.

#3573 Deprecated stochastic_event_set
  debian/changelog
  openquake/hazardlib/calc/stochastic.py
Labels: enhancement

#3576 Improved the speed of the event based tests
  openquake/calculators/tests/event_based_test.py
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/blocksize/job.ini
  openquake/qa_tests_data/event_based/case_1/job.ini
  openquake/qa_tests_data/event_based/case_12/job.ini
  openquake/qa_tests_data/event_based/case_13/job.ini
  openquake/qa_tests_data/event_based/case_17/job.ini
  openquake/qa_tests_data/event_based/case_18/job.ini
  openquake/qa_tests_data/event_based/case_2/job.ini
  openquake/qa_tests_data/event_based/case_2/job_2.ini
  openquake/qa_tests_data/event_based/case_3/job.ini
  openquake/qa_tests_data/event_based/case_4/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_4/job.ini
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/job.ini
  openquake/qa_tests_data/event_based/case_8/job.ini
  openquake/qa_tests_data/event_based/case_9/job.ini
  openquake/qa_tests_data/event_based/mutex/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_1/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_2/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_4a/job_hazard.ini
Labels: enhancement, internal

#3575 Removed the attribute `mesh.from_site_model`
  openquake/commonlib/readinput.py
Labels: internal

#3577 Added an utility `reduce_source_model`
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_event_based.py
  openquake/commands/info.py
  openquake/commands/reduce.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/calc/stochastic.py
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/source_models/as_model.xml
  openquake/qa_tests_data/event_based/case_5/source_models/fs_bg_source_model.xml
  utils/extract_source
  utils/reduce_sm
Labels: enhancement, internal

#3578 Add information about the number of events generated by each source
  debian/changelog
Labels: enhancement

#3579 Added information about the statistics in agg_losses
  debian/changelog
  openquake/calculators/extract.py
  openquake/server/views.py
Labels: enhancement

#3582 Removed output disagg_by_src if there are multiple realizations
  openquake/calculators/classical.py
Labels: bug

#3581 Changed `DataStore.get_attrs` to look at the parent
  debian/changelog
  openquake/baselib/datastore.py
Labels: bug

#3569 Minor improvements to openquake.hmtk.plotting
  openquake/hmtk/plotting/faults/geology_mfd_plot.py
  openquake/hmtk/plotting/seismicity/catalogue_plots.py
  openquake/hmtk/plotting/seismicity/completeness/plot_stepp_1972.py
  openquake/hmtk/plotting/seismicity/max_magnitude/cumulative_moment.py
  openquake/hmtk/plotting/seismicity/occurrence/recurrence_plot.py
  openquake/hmtk/seismicity/occurrence/utils.py
  pylintrc
Labels: bug

#3586 Fixed a bug in realizations containing newlines in the path
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/qa_tests_data/event_based/case_10/__init__.py
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_10/exposure_model.xml
  openquake/qa_tests_data/event_based/case_10/job.ini
  openquake/qa_tests_data/event_based/case_10/logic_tree_gmpe_simplified.xml
  openquake/qa_tests_data/event_based/case_10/logic_tree_source_model.xml
  openquake/qa_tests_data/event_based/case_10/site_model_bog.xml
  openquake/qa_tests_data/event_based/case_10/source-gridded_seismicity_bog.xml
  openquake/qa_tests_data/event_based/case_10/source-int_col_bog.xml
  openquake/qa_tests_data/event_based/case_10/vulnerability_model_bog.xml
Labels: bug

#3588 Fix DOI and citation
  doc/manual/build.sh
  doc/manual/configuration/configuration.tex
  doc/manual/figures/oq_manual_cover.svg
  doc/manual/oq-manual.tex
Labels: documentation, enhancement

#3587 Fixed small bugs when extracting the avg_losses-stats
  openquake/calculators/classical_risk.py
  openquake/commonlib/source.py
  openquake/server/views.py
Labels: bug

#3590 Add missing output_ses.xml file
  doc/manual/oqum/hazard/02c_output_event_based.tex
  doc/manual/oqum/hazard/verbatim/output_ses.xml
Labels: bug, documentation

#3563 Manual updates
  doc/manual/oqum/hazard/00a_sources_floating_ruptures.tex
  doc/manual/oqum/hazard/01d_config_classical.tex
  doc/manual/oqum/hazard/01d_config_disaggregation.tex
  doc/manual/oqum/hazard/02_outputs.tex
  doc/manual/oqum/hazard/02a_output_classical.tex
  doc/manual/oqum/hazard/02b_output_disaggregation.tex
  doc/manual/oqum/hazard/02c_output_event_based.tex
  doc/manual/oqum/hazard/verbatim/output_ses.xml
  doc/manual/oqum/help.txt
Labels: documentation

#3589 What's new for engine 3.0
  doc/installing/cluster.md
  doc/whats-new.md
  openquake/qa_tests_data/scenario_risk/case_1g/sites.csv
Labels: documentation

#3596 Added information about the distribution mechanism used in the User-Agent
  openquake/engine/engine.py
Labels: enhancement

#3545 Shakemap to GMFs
  openquake/hazardlib/correlation.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/shakemapconverter.py
  openquake/hazardlib/tests/shakemap/ghorka_grid.xml
  openquake/hazardlib/tests/shakemap/ghorka_uncertainty.xml
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
  openquake/hazardlib/tests/shakemapconverter_test.py
Labels: enhancement

#3594 Added threadpool distribution mechanism
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
Labels: enhancement

#3598 Small changes to hazardlib.correlation to support the SMTK
  debian/changelog
  openquake/hazardlib/correlation.py
Labels: enhancement

#3602 Added an XML exporter for the site model
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/event_based/case_10/site_model_bog.xml
  openquake/qa_tests_data/scenario/case_4/site_model.xml
Labels: enhancement

#3603 Renamed 'fake' -> 'scenario' inside the realizations.csv output
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/source.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
Labels: enhancement

#3606 Utilities to download the shakemaps from the USGS site
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/shakemapconverter.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  utils/shakemap
Labels: enhancement

#3610 Dropping python 2 compatibility
  openquake/baselib/__init__.py
  openquake/baselib/node.py
  openquake/baselib/parallel.py
  openquake/baselib/python3compat.py
  openquake/calculators/views.py
  openquake/commands/extract.py
  openquake/commonlib/readinput.py
  openquake/engine/engine.py
  openquake/engine/tools/make_html_report.py
  openquake/engine/utils/__init__.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/mfd/youngs_coppersmith_1985.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/tests/source/simple_fault_test.py
  openquake/server/db/upgrade_manager.py
  openquake/server/tests/db/upgrade_manager_test.py
  openquake/server/views.py
Labels: internal

#3604 Exported the tags in the risk outputs
  debian/changelog
  openquake/commonlib/util.py
  openquake/commonlib/writers.py
  openquake/qa_tests_data/scenario_damage/case_1/expected/dmg_by_asset.csv
Labels: enhancement

#3580 Upgrade Python stack
  .travis.yml
  debian/changelog
  openquake/baselib/general.py
  openquake/baselib/parallel.py
  openquake/commonlib/calc.py
  openquake/commonlib/writers.py
  openquake/engine/celeryconfig.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/stats.py
  openquake/hazardlib/tests/source/multipoint_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-ref-a8-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/risklib/scientific.py
  openquake/server/middleware.py
  openquake/server/settings.py
  openquake/server/urls.py
  openquake/server/utils.py
  requirements-py35-linux64.txt
  requirements-py35-macos.txt
  requirements-py36-linux64.txt
  setup.py
Labels: blocked

#3612 Refactored the association mechanism
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: internal

#3617 Clean old Django stuff
  doc/installing/server.md
  openquake/commands/webui.py
  openquake/server/views.py
Labels: enhancement

#3615 Convert celery-status in an oq command
  debian/changelog
  doc/installing/cluster.md
  openquake/commands/celery.py
  packager.sh
  rpm/python3-oq-engine.spec.inc
  utils/celery-status
Labels: internal

#3618 Remove sys.path mangling from 'oq'
  bin/oq
Labels: enhancement, packaging

#3619 Warn the user about optimize_same_id_sources when it looks like he should do that
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/nrml.py
Labels: enhancement

#3620 Now the BCR exporter also exports the tags
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/commonlib/writers.py
  openquake/qa_tests_data/classical_bcr/case_1/expected/bcr-structural.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.15.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.85.csv
Labels: bug

#3616 Removed tests relying on having a calculation ID=1
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#3624 Renamed sitemesh-_xxx.csv -> sitemesh_xxx.csv
  openquake/baselib/datastore.py
Labels: enhancement

#3629 Fix migration path for python3-oq-engine-<master|worker> on RPM
  rpm/python3-oq-engine.spec.inc
Labels: bug, hotfix, packaging

#3627 Removed `model` field from the realizations outputs
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/commonlib/source.py
  openquake/qa_tests_data/classical/case_18/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_6/expected/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
Labels: enhancement

#3626 Renamed realizations.uid -> realizations.branch_path
  openquake/calculators/export/hazard.py
  openquake/commonlib/source.py
  openquake/qa_tests_data/classical/case_18/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_6/expected/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
Labels: enhancement

#3631 Added a check on duplicated GSIMs in the logic tree
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/scenario_risk/case_6a/wrong_gmpe_logic_tree.xml
Labels: enhancement

#3632 Added `dmg_by_event` and `losses_by_event` outputs
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/dmg_by_event-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/dmg_by_event-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_asset-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_asset-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event-rlz-001.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/server/db/actions.py
Labels: enhancement

#3634 Turned rtree into a required library
  debian/changelog
  doc/installing/development.md
  doc/installing/macos.md
  doc/requirements.md
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/utils.py
  setup.py
Labels: enhancement

#3635 Add a db command to show executing jobs
  doc/internals.md
  openquake/server/db/actions.py
Labels: internal

#3638 Removed rtree index optimization
  debian/changelog
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/utils.py
Labels: critical

#3639 Varios optimizations of the scenario_risk calculator for the Aristotle project
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/engine/engine.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
Labels: enhancement

#3644 Fixed shakemap units
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: bug

#3643 Fix on nonparametric ruptures
  openquake/hazardlib/source/rupture.py
Labels: bug

#3647 Fix groups members filtering
  openquake/server/utils.py
Labels: bug, user interface

#3645 Added a `cross_correlation` parameter used when working with shakemaps
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: enhancement

#3648 Unified `losses_by_event` and `agg_loss_table`
  debian/changelog
  demos/risk/ClassicalBCR/job_risk.ini
  demos/risk/ClassicalDamage/job_risk.ini
  demos/risk/ClassicalRisk/job_risk.ini
  demos/risk/EventBasedRisk/job_risk.ini
  demos/risk/ScenarioDamage/job_risk.ini
  demos/risk/ScenarioRisk/job.ini
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/calculators/views.py
  openquake/commands/extract.py
  openquake/commands/plot_losses.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/scientific.py
Labels: enhancement

#3640 Added a debugging utility to plot the histogram of the losses_by_event
  openquake/commands/plot_losses.py
Labels: enhancement

#3651 Added a .serial attribute to the hazardlib ruptures
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#3642 Moved some methods from RectangularMesh to the parent class Mesh
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/gridded.py
Labels: enhancement

#3656 Added a test for the International Date Line bug discovered by Kendra
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_30/__init__.py
  openquake/qa_tests_data/classical/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_30/gmmLT_3.xml
  openquake/qa_tests_data/classical/case_30/job.ini
  openquake/qa_tests_data/classical/case_30/ssm/shallow/gridded_seismicity_source_4.xml
  openquake/qa_tests_data/classical/case_30/ssm/shallow/shallow_faults.xml
  openquake/qa_tests_data/classical/case_30/ssmLT.xml
Labels: bug, critical

#3653 Removed prefiltering on the workers
  debian/changelog
  demos/risk/ClassicalDamage/exposure_model.xml
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_tiling_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/calc/stochastic_test.py
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/agg_losses-rlz000-structural.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_loss.txt
Labels: enhancement

#3657 Fixing Kendra's International Date Line bug
  debian/changelog
  openquake/calculators/classical.py
  openquake/commands/plot.py
  openquake/commands/plot_sites.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/polygon.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/characteristic.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
  openquake/hazardlib/tests/site_test.py
  openquake/hmtk/plotting/patch.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.01.xml
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.1.xml
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.2.xml
  openquake/qa_tests_data/classical/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_30/job.ini
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-PGA-10.099999999999994-40.1_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-SA(0.025)-10.099999999999994-40.1_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-PGA-10.099999999999994-40.1_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-SA(0.025)-10.099999999999994-40.1_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Mag_Dist.csv
Labels: bug, critical

#3660 Replaced the old hazardlib filtering mechanism with the `sitecol.within_bbox` filtering
  openquake/calculators/classical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/site.py
Labels: enhancement, internal

#3659 Removed Decimal from the PMF
  openquake/hazardlib/pmf.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/acceptance/_peer_test_data.py
  openquake/hazardlib/tests/acceptance/peer_test.py
  openquake/hazardlib/tests/pmf_test.py
  openquake/hazardlib/tests/source/non_parametric_test.py
  openquake/hazardlib/tests/source/point_test.py
  openquake/hazardlib/tests/source/rupture_test.py
Labels: enhancement, internal

#3662 Changed filter_sources_with_rtree->prefilter_sources
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/commands/plot_sites.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/filters.py
Labels: internal
