Repository gem/oq-engine, pull requests merged in 2018-08, with the labels that each got.

#3903 Honor `concurrent_tasks` in the prefiltering phase
  debian/changelog
  openquake/calculators/base.py
  openquake/commands/plot_sites.py
  openquake/commonlib/source.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/classical/case_17/job.ini
Labels: bug

#3904 Add a missing link and create a new subsection
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation

#3910 Speed-up the download of hazard maps
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/commonlib/calc.py
Labels: enhancement

#3912 Moved the check on the number of sites and IMTs in event_based earlier
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
Labels: bug

#3913 Pickle the source models
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#3908 Revised Montalva et al (2016) GMPE for published coefficients
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/montalva_2016.py
  openquake/hazardlib/gsim/montalva_2017.py
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SINTER_INTER_EVENT.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SINTER_INTRA_EVENT.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SINTER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SINTER_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SSLAB_INTER_EVENT.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SSLAB_INTRA_EVENT.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SSLAB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/mont17/MONTALVA_SSLAB_TOTAL.csv
  openquake/hazardlib/tests/gsim/montalva_2017_test.py
Labels: enhancement

#3916 Parallelize the hazard map computation again
  openquake/calculators/base.py
  openquake/calculators/getters.py
  openquake/qa_tests_data/classical/case_1/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_1/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_12/expected/hazard_curve-smltp_b1-gsimltp_b1_b2.csv
  openquake/qa_tests_data/classical/case_13/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_26/expected/hazard_curve-rlz-000.csv
  openquake/qa_tests_data/classical/case_3/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_4/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_5/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_6/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
Labels: enhancement

#3917 Used float32 as default dtype for floats
  debian/changelog
  openquake/commonlib/calc.py
  openquake/commonlib/tests/readinput_test.py
  openquake/commonlib/writers.py
  openquake/qa_tests_data/classical/case_13/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.01.xml
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.1.xml
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean-0.2.xml
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.csv
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.xml
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-rlz-007.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-rlz-007.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-rlz-007.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
Labels: enhancement

#3921 Making the IMTs extensible in user code
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/commonlib/calc.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/check_gsim.py
  openquake/hazardlib/tests/imt_test.py
  openquake/hazardlib/tests/valid_test.py
Labels: enhancement

#3923 Fix an error with the global mosaic tests
  openquake/baselib/general.py
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
Labels: bug

#3925 Added a registry for the GSIM classes
  openquake/hazardlib/gsim/__init__.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/get_available_gsims_test.py
Labels: enhancement

#3929 Optimized the parsing of the source model tree
  debian/changelog
  openquake/commands/info.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  utils/renumber_sources
Labels: enhancement

#3859 Disable spinning/floating over some distances
  debian/changelog
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/pmf.py
Labels: enhancement

#3933 Implemented tasks as generator functions
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/tests/workerpool_test.py
Labels: enhancement

#3819 Restored the individual_curves flag
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_4/job.ini
Labels: enhancement, internal

#3935 Skipped two correlation tests
  openquake/hazardlib/tests/correlation_test.py
Labels: bug

#3936 Back correlation tests
  openquake/hazardlib/tests/correlation_test.py
Labels: bug

#3937 PEP8 fixes to correlation.py
  CONTRIBUTORS.txt
  debian/changelog
  openquake/hazardlib/correlation.py
Labels: documentation

#3931 Generated one risk task per hazard site
  debian/changelog
  demos/risk/EventBasedRisk/job_risk.ini
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/risklib/riskinput.py
Labels: enhancement

#3940 Fixed the hazard curves XML exporter
  bin/run-demos.sh
  openquake/calculators/export/hazard.py
Labels: bug

#3939 Send back the GMFs in chunks
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/event_based.py
Labels: enhancement

#3943 Improved the GSIM deprecation mechanism
  debian/changelog
  openquake/hazardlib/gsim/akkar_2013.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/montalva_2016.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: bug

#3945 Improved the progress and monitoring
  openquake/baselib/parallel.py
Labels: enhancement

#3946 Unskip tests
  openquake/hazardlib/tests/geo/surface/base_surface_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: bug

#3947 Introduce a key `distribution.multi_node` in openquake.cfg
  doc/installing/cluster.md
  openquake/baselib/__init__.py
  openquake/engine/openquake.cfg
Labels: enhancement

#3949 Minor cleanup of event_based compute_hazard
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: internal

#3951 Fully parallelize the prefiltering if we are on a cluster
  debian/changelog
  openquake/calculators/base.py
  openquake/hazardlib/calc/filters.py
Labels: enhancement

#3952 Raise src ID length limit in validation
  debian/changelog
  openquake/hazardlib/valid.py
Labels: enhancement

#3957 Avoid rtree error in Index_Create
  openquake/calculators/base.py
Labels: bug

#3956 Do not propagate SIGINT to pool workers
  openquake/baselib/parallel.py
Labels: bug
