Repository gem/oq-engine, pull requests merged in 2018-02, with the labels that each got.

#3429 Fixed the MINWEIGHT
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/commonlib/source.py
Labels: bug

#3426 Allow sysadmins to configure a custom path for TMPDIR
  debian/changelog
  doc/faq.md
  doc/installing/cluster.md
  openquake/baselib/__init__.py
  openquake/engine/openquake.cfg
Labels: enhancement

#3424 Fixed the check on relative paths
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical_tiling/case_2/models/tree/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_4/models/tree/source_model_logic_tree.xml
Labels: bug

#3436 20180213 gridded ruptures
  debian/changelog
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
Labels: enhancement

#3438 Splitting the gridded nonparametric sources
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/source/non_parametric.py
  openquake/qa_tests_data/disagg/case_5/__init__.py
  openquake/qa_tests_data/disagg/case_5/gmpe_lt_col_2016_pga_EB.xml
  openquake/qa_tests_data/disagg/case_5/job.ini
  openquake/qa_tests_data/disagg/case_5/slab_buc0/6.05.nrml
  openquake/qa_tests_data/disagg/case_5/slab_buc1/6.75.nrml
  openquake/qa_tests_data/disagg/case_5/source_model_lt_col18_full_model_S_test_slab.xml
Labels: enhancement

#3439 Mutex sources cannot be split
  openquake/commonlib/source.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: bug

#3433 Set the db status to abort only if the job was actually killed
  openquake/commands/abort.py
  openquake/server/views.py
Labels: bug

#3440 Fixed HDF5 fork bug (again)
  openquake/calculators/base.py
  openquake/calculators/getters.py
  openquake/commonlib/readinput.py
Labels: bug

#3441 Fix hazard outputs in the case of no outputs
  debian/changelog
  demos/hazard/AreaSourceClassicalPSHA/job.ini
  demos/hazard/CharacteristicFaultSourceCase1ClassicalPSHA/job.ini
  demos/hazard/CharacteristicFaultSourceCase2ClassicalPSHA/job.ini
  demos/hazard/CharacteristicFaultSourceCase3ClassicalPSHA/job.ini
  demos/hazard/ComplexFaultSourceClassicalPSHA/job.ini
  demos/hazard/EventBasedPSHA/job.ini
  demos/hazard/PointSourceClassicalPSHA/job.ini
  demos/hazard/SimpleFaultSourceClassicalPSHA/job.ini
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
Labels: bug

#3434 Fixed %2A bug
  openquake/server/tests/tests.py
  openquake/server/views.py
Labels: bug

#3442 Honored concurrent_tasks in event based GMF
  openquake/calculators/event_based.py
Labels: bug

#3428 Yuetal
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/yu_2013.py
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_mean_active.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_mean_eastern.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_mean_stable.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_mean_tibetan.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_stddev_active.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_stddev_eastern.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_stddev_stable.csv
  openquake/hazardlib/tests/gsim/data/YU2013/yu_2013_stddev_tibetan.csv
  openquake/hazardlib/tests/gsim/yu_2013_test.py
Labels: enhancement

#3414 Supported retrofitted field in the CSV exposure
  debian/changelog
  demos/risk/ClassicalBCR/exposure_model.xml
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/classical_bcr_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical_bcr/case_1/exposure.xml
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.15.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.85.csv
  openquake/qa_tests_data/classical_bcr/case_2/exposure_model-header.xml
  openquake/qa_tests_data/classical_bcr/case_2/exposure_model.csv
  openquake/qa_tests_data/classical_bcr/case_2/exposure_model.xml
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/server/db/actions.py
  utils/expo2csv.py
Labels: enhancement

#3447 Improved error message for source model files with the wrong NRML version
  debian/changelog
  openquake/hazardlib/nrml.py
Labels: enhancement

#3435 Add missing obsoletes in rpm
  debian/changelog
  rpm/python3-oq-engine.spec.inc
Labels: bug, packaging

#3413 Added parameter `source_model_file` to the job.ini
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_1/job.ini
  openquake/qa_tests_data/classical/case_1/source_model_logic_tree.xml
Labels: enhancement

#3453 Avoid transferring the event IDs in event based risk from GMFs
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/commonlib/source.py
Labels: enhancement

#3451 Integrated the gmf_ebrisk calculator in the event_based_risk calculator
  debian/changelog
  doc/manual/oqum/risk/verbatim/config_gmf_event_based_risk.ini
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/getters.py
  openquake/calculators/gmf_ebrisk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/qa_tests_data/event_based_risk/case_2/job_ebrisk.ini
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_1/job_risk.ini
  openquake/qa_tests_data/gmf_ebrisk/case_2/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_2/report.rst
  openquake/qa_tests_data/gmf_ebrisk/case_3/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_3/report.rst
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_losses-all.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/job_risk.ini
  openquake/qa_tests_data/gmf_ebrisk/case_4/report.rst
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: enhancement

#3455 Added a test with asset_correlation=1
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_6c/__init__.py
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_6c/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_6c/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_6c/job_h.ini
  openquake/qa_tests_data/event_based_risk/case_6c/job_r.ini
  openquake/qa_tests_data/event_based_risk/case_6c/source_model.xml
  openquake/qa_tests_data/event_based_risk/case_6c/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_6c/vulnerability_model.xml
  openquake/risklib/riskinput.py
Labels: bug

#3449 Make sure that the proper installation of python is used by macros
  rpm/python3-oq-engine.spec.inc
Labels: enhancement, packaging

#3456 Moved the RuptureGetter inside getters
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/getters.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/calc.py
Labels: internal

#3427 Automatically update version number on manual cover page
  doc/manual/build.sh
Labels: documentation

#3458 Minor edits to whats-new for v2.9 [skip CI]
  doc/whats-new.md
Labels: documentation

#3459 Manual: Fix a LaTeX issue with a citation [skip CI]
  doc/manual/oqum/glossary.tex
Labels: documentation

#3462 Adds Rjb 0.1 km clip to Derras 2014
  debian/changelog
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/tests/gsim/data/derras14/DERRAS14_MEAN.csv
Labels: bug

#3457 What's New for engine 2.9
  doc/manual/build.sh
  doc/whats-new.md
Labels: documentation

#3452 Ubuntu Python 3.5
  debian/changelog
  debian/changelog_hazardlib
  debian/control
  debian/copyright
  debian/postinst
  debian/postrm
  debian/preinst
  debian/python3-oq-engine-master.postinst
  debian/python3-oq-engine-worker.install
  debian/python3-oq-engine-worker.postinst
  debian/python3-oq-engine-worker.postrm
  debian/python3-oq-engine.install
  debian/rules
  debian/supervisord/openquake-celery.conf
  debian/supervisord/openquake-dbserver.conf
  debian/supervisord/openquake-webui.conf
  debian/templates
  doc/installing/ubuntu-nightly.md
  doc/installing/ubuntu.md
  doc/sphinx/Makefile
  doc/upgrading/ubuntu.md
  packager.sh
Labels: packaging

#3464 Renamed oq -> o
  openquake/commands/shell.py
Labels: enhancement

#3468 Manual: Add downloadable examples for sites, gmfs csvs for scenarios
  doc/manual/oqum/hazard/02d_output_scenario.tex
  doc/manual/oqum/hazard/verbatim/output_gmf_scenario.tex
  doc/manual/oqum/hazard/verbatim/output_scenario_gmfs.csv
  doc/manual/oqum/hazard/verbatim/output_scenario_sites.csv
  doc/manual/oqum/hazard/verbatim/output_sitemesh.tex
  doc/manual/oqum/risk/02_config_scenario_damage.tex
  doc/manual/oqum/risk/verbatim/input_scenario_gmfs.csv
  doc/manual/oqum/risk/verbatim/input_scenario_sites.csv
Labels: documentation

#3467 Moved the asset_refs inside the AssetCollection
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/commonlib/readinput.py
  openquake/commonlib/util.py
  openquake/risklib/asset.py
Labels: enhancement

#3469 Extended `get_site_collection` to read the sites from the hazard curves when available
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: enhancement

#3470 Moved the asset-site association inside .read_exposure
  openquake/calculators/base.py
  openquake/calculators/classical_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/readinput.py
Labels: enhancement

#3431 Substantial simplification of the parallelization framework
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/workerpool.py
  openquake/baselib/zeromq.py
  openquake/calculators/base.py
  openquake/calculators/classical_risk.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_classical.py
  openquake/commands/__main__.py
  openquake/commands/run.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/server/db/actions.py
  openquake/server/dbserver.py
  utils/run_tiles.py
Labels: enhancement

#3465 Fixed the bug with negative PoEs for nonparametric sources
  debian/changelog
  openquake/hazardlib/source/rupture.py
Labels: bug

#3471 Using pre-imported exposure
  debian/changelog
  demos/risk/ClassicalBCR/job_risk.ini
  demos/risk/ClassicalDamage/job_risk.ini
  demos/risk/ClassicalRisk/job_risk.ini
  demos/risk/EventBasedRisk/job_hazard.ini
  demos/risk/EventBasedRisk/job_risk.ini
  demos/risk/ScenarioDamage/job_risk.ini
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
  openquake/qa_tests_data/gmf_ebrisk/case_4/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_5/job_haz.ini
  openquake/risklib/asset.py
Labels: enhancement

#3473 Added a distribution mode celery_zmq
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/tests/workerpool_test.py
  openquake/baselib/workerpool.py
  openquake/baselib/zeromq.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logs.py
  openquake/engine/celeryconfig.py
  openquake/engine/engine.py
  openquake/risklib/riskinput.py
  openquake/server/dbserver.py
  openquake/server/views.py
Labels: enhancement

#3472 Removing oq engine --run-hazard and --run-risk
  debian/changelog
  doc/manual/oqum/help.txt
  openquake/commands/engine.py
Labels: enhancement

#3475 asset_refs and assets now have the same ordering
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/commonlib/readinput.py
  openquake/commonlib/util.py
  openquake/risklib/asset.py
  openquake/risklib/riskinput.py
Labels: enhancement

#3478 Remove old stuff from debian inits and solve celery issue in packager.sh
  debian/supervisord/openquake-celery.conf
  debian/supervisord/openquake-dbserver.conf
  debian/supervisord/openquake-webui.conf
  packager.sh
Labels: bug, packaging

#3477 Import deductible and insuranceLimit even if insured_losses is false
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: enhancement

#3483 Discarding results coming from the wrong calculation
  debian/changelog
  openquake/baselib/parallel.py
Labels: bug, critical

#3482 Removed get_job_info
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/engine/openquake.cfg
Labels: documentation
