Repository gem/oq-engine, pull requests merged in 2018-10, with the labels that each got.

#4041 Using Python 3.6 __init_subclasses__ hook
  openquake/commands/__main__.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
Labels: internal

#4042 Removed support for Python 3.5
  packager.sh
  requirements-py35-linux64.txt
  requirements-py35-macos.txt
  setup.py
  tox.ini
Labels: internal

#4039 Improved the task distribution in the event based hazard even more
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commonlib/source.py
Labels: enhancement

#4043 Renamed the composite_risk_model dataset into fragility or vulnerability
  openquake/calculators/base.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/riskinput.py
Labels: internal

#4044 Removed ownership check on get_job_id
  debian/changelog
  openquake/commands/engine.py
Labels: enhancement

#4029 20180919 nrcan15
  debian/changelog
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/oceanic.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/sslab.py
  openquake/hazardlib/gsim/can15/utils.py
  openquake/hazardlib/gsim/can15/western.py
  openquake/hazardlib/tests/gsim/can15/eastern_test.py
  openquake/hazardlib/tests/gsim/can15/oceanic.py
  openquake/hazardlib/tests/gsim/can15/sinter_test.py
  openquake/hazardlib/tests/gsim/can15/sslab_test.py
  openquake/hazardlib/tests/gsim/can15/utils_test.py
  openquake/hazardlib/tests/gsim/can15/western_test.py
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEtInterface_Low_combo.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEtInterface_high_combo.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEtInterface_med_combo.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_high.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_low.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_med.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Inslab_high.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Inslab_low.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Inslab_med.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Wcrust_high.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Wcrust_low.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Wcrust_med.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_offshore_high.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_offshore_low.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_offshore_med.csv
  openquake/hazardlib/tests/gsim/utils.py
Labels: enhancement

#4045 Improved the saving of the avg_losses
  openquake/baselib/parallel.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/ucerf_event_based.py
  openquake/risklib/asset.py
Labels: enhancement

#4049 views porfolio_loss and portfolio_losses
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/calculators/views.py
  openquake/commands/run.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/ucerf/expected/portfolio_losses.txt
Labels: enhancement

#4050 20181004 ceus
  debian/changelog
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/sslab.py
  openquake/hazardlib/gsim/can15/western.py
  openquake/hazardlib/gsim/frankel_1996.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/pezeshk_2011.py
  openquake/hazardlib/gsim/silva_2002.py
  openquake/hazardlib/gsim/somerville_2001.py
  openquake/hazardlib/gsim/tavakoli_pezeshk_2005.py
  openquake/hazardlib/gsim/toro_1997.py
  openquake/hazardlib/tests/gsim/check_gsim.py
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Wcrust_med.csv
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
Labels: bug

#4051 Added the ability to run multiple job.ini one after the other
  openquake/calculators/base.py
  openquake/commands/engine.py
Labels: enhancement

#4053 Reduce the risk model to the taxonomies present in the exposure
  debian/changelog
  openquake/calculators/base.py
  openquake/risklib/riskinput.py
Labels: enhancement

#4056 Update macOS install instructions to include Mojave, fix typos [skip CI]
  doc/installing/development.md
  doc/installing/macos.md
  openquake/hazardlib/gsim/toro_1997.py
  openquake/hazardlib/gsim/toro_2002.py
Labels: documentation

#4058 20181009 can15
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/sslab.py
Labels: bug

#4059 Reduced the site collection instead of just filtering it
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/event_based/case_16/job.ini
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/agg_losses-rlz000-structural.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/server/tests/tests.py
Labels: enhancement

#4060 More work on the command `oq prepare_site_model`
  doc/oq-commands.md
  openquake/calculators/base.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/event_based/case_16/exposure_res.csv
  openquake/qa_tests_data/event_based/case_16/vs30.csv
Labels: documentation, enhancement, internal

#4063 More work on prepare_site_model
  doc/oq-commands.md
  openquake/calculators/views.py
  openquake/commands/plot_assets.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
Labels: enhancement, internal

#4065 Stored in the rupture the source index
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#4068 20181010 fix canada bug
  openquake/hazardlib/gsim/boore_atkinson_2008.py
Labels: bug

#4069 Do not discard assets unless `discard_assets=true` is set
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/event_based_risk/case_2/job.ini
  openquake/qa_tests_data/event_based_risk/case_2/job_ebrisk.ini
  openquake/qa_tests_data/event_based_risk/case_2/job_sampling.ini
  openquake/qa_tests_data/gmf_ebrisk/case_2/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_3/job.ini
  openquake/qa_tests_data/scenario_damage/case_5/job_haz.ini
  openquake/qa_tests_data/scenario_risk/case_8/job.ini
Labels: enhancement

#4070 Added a functional test for the site term feature
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/qa_tests_data/event_based/case_19/Vs30_Vancouver.xml
  openquake/qa_tests_data/event_based/case_19/__init__.py
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/gmmLT_analytical.xml
  openquake/qa_tests_data/event_based/case_19/job.ini
  openquake/qa_tests_data/event_based/case_19/nwHswRneHseH_0.xml
  openquake/qa_tests_data/event_based/case_19/ssmLT_0.xml
Labels: internal

#3979 Bugfix on hmtk plotting completeness adjusted table and more catalogue special methods
  debian/changelog
  openquake/hmtk/plotting/seismicity/catalogue_plots.py
  openquake/hmtk/seismicity/catalogue.py
Labels: enhancement

#4078 Fixed option oq engine --config-file
  bin/run-demos.sh
  debian/changelog
  openquake/commands/engine.py
Labels: bug

#4080 `oq engine --run` with space-separated job.ini files
  debian/changelog
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/commands/tests/commands_test.py
Labels: enhancement

#4082 Added check on inconsistent TRTs
  debian/changelog
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source_model/wrong-trt.xml
  openquake/hazardlib/tests/sourceconverter_test.py
Labels: enhancement

#4079 Offshore GMPEs - tested against results obtained using tables
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/gsim/can15/oceanic.py
  openquake/qa_tests_data/event_based/case_20/BC_Exposure.csv
  openquake/qa_tests_data/event_based/case_20/BC_Exposure.xml
  openquake/qa_tests_data/event_based/case_20/Vs30_BC.xml
  openquake/qa_tests_data/event_based/case_20/__init__.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/gmmLT_analytical.xml
  openquake/qa_tests_data/event_based/case_20/job.ini
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneHseH_0.xml
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneHseR_1_area.xml
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneHseY_2.xml
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneRseH_3_area.xml
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneRseR_4.xml
  openquake/qa_tests_data/event_based/case_20/ssm/nwHswRneRseY_5_area.xml
  openquake/qa_tests_data/event_based/case_20/ssmLT.xml
Labels: bug

#4085 Added a source_id filtering feature
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_1/job.ini
Labels: enhancement

#4086 Using non-deprecated GSIMs in the tests
  openquake/calculators/base.py
  openquake/engine/engine.py
  openquake/qa_tests_data/disagg/case_5/gmpe_lt_col_2016_pga_EB.xml
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_10/logic_tree_gmpe_simplified.xml
  openquake/qa_tests_data/event_based_risk/case_caracas/gmpe_logic_tree_sara_v3.xml
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-008.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/gsim_logic_tree.xml
Labels: enhancement

#4087 Added check for missing exposure both in hazard and risk
  openquake/calculators/base.py
Labels: enhancement

#4083 Pezeshk et al 2011 - New adjustment for NEHRP B/C
  openquake/hazardlib/gsim/pezeshk_2011.py
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_NEHRPBC_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_NEHRPBC_STD_TOTAL.csv
Labels: enhancement

#4081 Better error message for stddev=0 when computing shakemaps
  debian/changelog
  openquake/hazardlib/shakemap.py
Labels: enhancement

#4092 Made the export_dir relative to the input_dir
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
Labels: enhancement

#4076 Enhanced prepare_site_model to compute also z1pt0 and z2pt5
  doc/oq-commands.md
  openquake/baselib/node.py
  openquake/commands/db.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/commonlib/writers.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/event_based/case_19/Vs30_Vancouver.xml
  openquake/qa_tests_data/event_based/case_19/job.ini
Labels: enhancement

#4097 Removed the PlanarSurface check when unneeded
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
Labels: bug, documentation

#4103 Splitting the sources in ucerf_classical
  openquake/calculators/ucerf_base.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/readinput.py
Labels: enhancement

#4104 Turned vs30measured into an optional site parameter
  debian/changelog
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/calc/stochastic_test.py
  openquake/hazardlib/tests/correlation_test.py
  openquake/hazardlib/tests/gsim/nshmp_2014_test.py
  openquake/hazardlib/tests/site_test.py
  openquake/hazardlib/tests/source/base_test.py
Labels: enhancement

#4101 Reduce the GMPE logic tree upfront
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
Labels: enhancement

#4110 Fixed view inputs when reqv is enabled
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
Labels: bug

#4109 Optimized `_sample_ruptures` when there are a lot of SESs
  debian/changelog
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/nankai.xml
  openquake/hazardlib/tests/calc/stochastic_test.py
  openquake/qa_tests_data/event_based/mutex/expected/ruptures.csv
  openquake/qa_tests_data/event_based/mutex/expected/ses.xml
Labels: enhancement

#4112 Made the shakemap feature more tolerant for wrong vulnerability models
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/shakemap/__init__.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/risklib/riskinput.py
Labels: enhancement, internal

#4111 defining reference velocity as 800
  openquake/hazardlib/gsim/allen_2012.py
Labels: bug

#4115 Make --hc=-1 refer to the last calculation of the current user again
  openquake/commands/engine.py
Labels: bug, internal

#4117 Added a way to disable spatial correlation in shakemaps and disabled it by default
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
Labels: enhancement

#4118 Fixed shakemap download
  debian/changelog
  openquake/hazardlib/shakemap.py
Labels: bug

#4036 Added a configuration parameter for dask
  openquake/baselib/parallel.py
  openquake/engine/openquake.cfg
Labels: internal

#4120 20180830 sm pga
  debian/changelog
  openquake/hazardlib/gsim/si_midorikawa_1999.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/gsim/data/SM99/SM99ASC_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99ASC_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99ASC_MEAN_PGA_vs800.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99ASC_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SINTER_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInter_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSLAB_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlab_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/si_midorikawa_1999_test.py
  openquake/qa_tests_data/classical/case_27/job.ini
Labels: enhancement

#4123 Fixed a bug in preclassical with optimize_same_id_sources=true
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
Labels: bug, internal

#4121 Added a method sample_ruptures to the base source class
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/base.py
Labels: internal

#4124 Changed the seed algorithm
  openquake/commonlib/source.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-002.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-003.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-004.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-005.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-006.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-007.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-008.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/agg_losses-rlz000-structural.csv
Labels: internal

#4125 Send the sources by source model and pass the `rlz_slice` to sample_ruptures
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_event_based.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: internal, post-mortem

#4126 Changed the building convention for the event IDs and stored the number of occurrences for each rupture
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
Labels: enhancement, post-mortem

#4129 Fixed the case of no spatial correlation
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: bug

#4130 Made it possible to run risk on top on another user hazard again
  openquake/commands/engine.py
Labels: bug

#4132 adding ref velocity for nath 2012
  openquake/hazardlib/gsim/nath_2012.py
Labels: bug

#4133 Update requests requirements because of CVE-2018-18074
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  setup.py
Labels: packaging, security

#4134 Restored spatial correlationby default
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
Labels: bug, post-mortem

#4136 Extended oq checksum to source model logic tree files
  openquake/calculators/base.py
  openquake/commands/checksum.py
  openquake/commonlib/readinput.py
Labels: enhancement, internal

#4135 HUGE: event IDs by realization
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_maps-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_maps-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/rupture-nonstructural.xml
  openquake/qa_tests_data/event_based_risk/case_1/expected/rupture-structural.xml
  openquake/qa_tests_data/event_based_risk/case_4/expected/agg_losses-all.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-002.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-003.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-004.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-005.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-006.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-007.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-008.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement
