Repository gem/oq-engine, pull requests merged in 2019-07, with the labels that each got.

#4863 Calibrate the source weights by measuring the time spent by computing a subsample
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#4864 Added the ability to generate hazard curves without storing the GMFs
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job2.ini
Labels: enhancement

#4867 Improved the task splitting
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
Labels: enhancement, internal

#4866 Restored the grid site model associations
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job2.ini
  openquake/qa_tests_data/event_based_risk/case_miriam/site_model.csv
Labels: enhancement

#4859 Adds in finite rupture option to Germany-adjusted Cauzzi and Derras GMPEs
  debian/changelog
  openquake/hazardlib/gsim/germany_2018.py
  openquake/hazardlib/tests/gsim/data/germany_2018/C14_RHYPO_ADJUSTMENT_MEAN.csv
  openquake/hazardlib/tests/gsim/data/germany_2018/C14_RHYPO_FINITE_RUPTURE_MEAN.csv
  openquake/hazardlib/tests/gsim/data/germany_2018/D14_RHYPO_ADJUSTMENT_MEAN.csv
  openquake/hazardlib/tests/gsim/data/germany_2018/D14_RHYPO_FINITE_RUPTURE_MEAN.csv
  openquake/hazardlib/tests/gsim/germany_2018_test.py
Labels: enhancement

#4868 Changed .wkt->.csv for the multi_peril files
  bin/run-demos.sh
  openquake/calculators/multi_risk.py
  openquake/qa_tests_data/multi_risk/case_1/job_2.ini
  openquake/qa_tests_data/multi_risk/case_1/lahar-geom.csv
  openquake/qa_tests_data/multi_risk/case_1/lahar.wkt
Labels: enhancement

#4869 Added examples for LAVA and LAHARS
  debian/changelog
  openquake/calculators/tests/multi_risk_test.py
  openquake/qa_tests_data/multi_risk/case_1/expected/agg_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/qa_tests_data/multi_risk/case_1/exposure_model.zip
  openquake/qa_tests_data/multi_risk/case_1/job_2.ini
  openquake/qa_tests_data/multi_risk/case_1/lava-geom.csv
  openquake/qa_tests_data/multi_risk/case_1/pyro-geom.csv
Labels: enhancement

#4870 Added ASH peril to job_2.ini
  openquake/calculators/tests/multi_risk_test.py
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/qa_tests_data/multi_risk/case_1/job_2.ini
Labels: enhancement

#4871 Do not store information about the subtask outputs in performance_data
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/classical.py
Labels: internal

#4872 Added a test of conversion MFD to TOML
  openquake/baselib/node.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/expected_mfd.toml
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: internal

#4874 Storing the MFDs in TOML format
  debian/changelog
  openquake/baselib/node.py
  openquake/baselib/tests/node_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
Labels: enhancement, internal

#4875 Added some support for computing the mean MFD from the generated ruptures
  demos/hazard/EventBasedPSHA/gmpe_logic_tree.xml
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/plot.py
  openquake/hazardlib/mfd/__init__.py
  openquake/hazardlib/mfd/multi_mfd.py
  openquake/server/tests/views_test.py
Labels: enhancement

#4876 Improved the computation and plotting of the event based MFD
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/plot.py
  openquake/commonlib/readinput.py
  openquake/server/tests/views_test.py
Labels: enhancement, internal

#4877 Fixed mfd.from toml
  openquake/calculators/base.py
  openquake/hazardlib/mfd/__init__.py
  openquake/hazardlib/mfd/multi_mfd.py
  openquake/hazardlib/mfd/youngs_coppersmith_1985.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/mfd/youngs_coppersmith_1985_test.py
Labels: internal

#4865 New duration gsim
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/vanhoutte_2018.py
  openquake/hazardlib/tests/gsim/data/vanhoutte2018/VANHOUTTE_2018_RSD_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/vanhoutte2018/VANHOUTTE_2018_RSD_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/vanhoutte2018/VANHOUTTE_2018_RSD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/vanhoutte2018/VANHOUTTE_2018_RSD_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/vanhoutte_2018_test.py
Labels: enhancement

#4878 Moved the `get_source_models` logic into a new module `source_model_factory`
  openquake/calculators/classical.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#4879 Made the weight field optional in the taxonomy_mapping
  doc/adv-manual/index.rst
  doc/adv-manual/risk-features.rst
  doc/adv-manual/special-features.rst
  openquake/baselib/general.py
  openquake/commonlib/logictree.py
Labels: documentation

#4880 Added units to agg_curves in ebrisk too
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
Labels: bug

#4886 Minor edits to whats-new for v3.6
  doc/whats-new.md
Labels: documentation

#4887 Fixed a wrong check with applyToSources
  openquake/commonlib/logictree.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/logictree_test.py
Labels: bug

#4882 Removed extract/agg_curves
  openquake/calculators/extract.py
Labels: bug

#4881 What's New for engine 3.6
  doc/whats-new.md
Labels: documentation

#4888 Refactoring of the average losses calculation in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/risklib/scientific.py
Labels: internal

#4890 Implemented insured losses by event
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/event_based_risk/case_1/job_eb.ini
  openquake/risklib/scientific.py
Labels: enhancement

#4891 Improvements to the TOML representation of sources
  openquake/baselib/node.py
  openquake/commands/to_shapefile.py
  openquake/commonlib/shapefileparser.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/expected_mfd.toml
  openquake/hazardlib/tests/expected_sources.toml
  openquake/hazardlib/tests/sourcewriter_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/scenario_risk/case_3/taxonomy_mapping.toml
Labels: internal

#4892 Fixed bug with `max_sites_disagg`
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/commands/engine.py
  openquake/hazardlib/contexts.py
Labels: bug

#4893 Moved `max_sites_disagg` from openquake.cfg into the job.ini
  debian/changelog
  openquake/baselib/__init__.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/commands/engine.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/contexts.py
Labels: bug, enhancement

#4894 Start/stop the zworkers in `engine.run_job` via the DbServer
  openquake/baselib/workerpool.py
  openquake/commands/engine.py
  openquake/commonlib/logs.py
  openquake/server/db/actions.py
  openquake/server/dbserver.py
Labels: enhancement

#4896 Added an API extract/disagg_layer
  debian/changelog
  demos/hazard/Disaggregation/job.ini
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.02-rlz-0-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.02-rlz-0-SA(0.025)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.1-rlz-0-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.1-rlz-0-SA(0.025)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/PGA-sid-1-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/PGA-sid-1-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/SA(0.25)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/SA(0.25)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/SA(0.25)-sid-1-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/SA(0.25)-sid-1-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-PGA-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-SA(0.25)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-SA(0.25)-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-PGA-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-SA(0.25)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-PGA-sid-1-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-SA(0.25)-sid-0-poe-0_Mag_Dist.csv
Labels: enhancement

#4899 Optimized the memory consumption while sending disaggregation tasks
  debian/changelog
  openquake/calculators/disaggregation.py
Labels: performance

#4902 Changed the way the performance info is stored
  openquake/baselib/datastore.py
  openquake/baselib/general.py
  openquake/baselib/hdf5.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/hdf5_test.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_classical.py
  openquake/commands/prepare_site_model.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#4897 Update documentation of vulnerability distribution types [skip CI]
  openquake/risklib/scientific.py
Labels: documentation

#4903 Reading the ruptures from the datastore in disaggregation
  debian/changelog
  openquake/baselib/general.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/source_model_factory.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#4905 Filtered far away ruptures in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#4907 Restored `oq show performance` on-the-fly
  debian/changelog
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/performance_test.py
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/disagg.py
Labels: enhancement, internal

#4909 Removed unused function
  openquake/baselib/general.py
  openquake/baselib/tests/general_test.py
Labels: internal

#4910 Solves a failure in Jenkins
  openquake/baselib/parallel.py
  openquake/calculators/ebrisk.py
Labels: bug, internal

#4911 Storing the distances are 32 bit floats in disaggregation
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
Labels: performance

#4908 Avoid the error for POE_TOO_BIG
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
Labels: enhancement

#4915 Added a check for missing risk_investigation_time in ebrisk
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#4917 Reduced pytest tracebacks
  .travis.yml
Labels: internal

#4918 Rewritten things in terms of 8-dimensional disaggregation matrices instead of dictionaries
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: internal

#4919 Restored Socket.__iter__ as it was
  openquake/baselib/zeromq.py
Labels: internal, investigation

#4920 Removed some scary warnings in presence of a site model
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/commonlib/source_model_factory.py
Labels: bug

#4922 Raised the tolerance on case_22
  openquake/calculators/tests/classical_test.py
Labels: bug, internal

#4921 Remove obsolete NRML output examples [skip CI]
  openquake/risklib/nrml_examples/agg-loss-curve.xml
  openquake/risklib/nrml_examples/exposure-population.xml
  openquake/risklib/nrml_examples/gmf-event-based.xml
  openquake/risklib/nrml_examples/hazard-curves-mean.geojson
  openquake/risklib/nrml_examples/hazard-curves-pga.geojson
  openquake/risklib/nrml_examples/hazard-curves-quantile.geojson
  openquake/risklib/nrml_examples/hazard-curves-sa.geojson
  openquake/risklib/nrml_examples/ses.xml
Labels: documentation

#4923 Fixed export realizations for scenarios with parametric GSIMs
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_9/realizations.csv
Labels: bug

#4924 Blind attempts on test_case_18
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
Labels: bug, investigation

#4925 Restored the clean version of Socket.__iter__
  openquake/baselib/zeromq.py
Labels: internal

#4926 Avoided completely zmq for few events in get_eid_rlz
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
Labels: enhancement

#4927 Solved Jamal's bug
  debian/changelog
  openquake/commands/reduce_sm.py
  openquake/hazardlib/correlation.py
  openquake/hazardlib/tests/correlation_test.py
Labels: bug

#4929 Accepted loss ratios > 1
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/qa_tests_data/scenario_risk/case_master/structural_vulnerability_model.xml
  openquake/risklib/read_nrml.py
  openquake/risklib/scientific.py
Labels: bug, enhancement

#4933 Cleaned up the task distribution
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/tests/workerpool_test.py
Labels: internal

#4934 Added a check on the WorkerPool status
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/tests/workerpool_test.py
  openquake/baselib/workerpool.py
Labels: internal

#4935 Changed the `disagg_by_src` exporter
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-PGA-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-SA(0.025)-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-PGA-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-SA(0.025)-sid-0_Src.csv
Labels: enhancement

#4937 Moved the CompositeRiskModel inside riskmodels
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/multi_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/shakemap.py
  openquake/risklib/read_nrml.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#4939 Simplified the zmq configuration
  docker/conf/openquake.cfg.cluster-sample
  openquake/baselib/parallel.py
  openquake/baselib/tests/workerpool_test.py
  openquake/baselib/workerpool.py
  openquake/commands/engine.py
  openquake/engine/engine.py
  openquake/engine/openquake.cfg
  openquake/server/dbserver.py
Labels: internal

#4938 Setting the seed for VulnerabilityFunction with Beta Distribution
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1f/__init__.py
  openquake/qa_tests_data/event_based_risk/case_1f/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_1f/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_1f/job_h.ini
  openquake/qa_tests_data/event_based_risk/case_1f/job_r.ini
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_1f/source_model.xml
  openquake/qa_tests_data/event_based_risk/case_1f/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_1f/vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/case_1g/expected/avg_losses.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_1h/expected/losses_by_asset.csv
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: bug

#4944 Fixed the killing of the zmq streamer
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/engine/openquake.cfg
  openquake/server/dbserver.py
Labels: bug, internal

#4942 Added debug mode to the DbServer
  .travis.yml
  debian/systemd/openquake-dbserver.service
  docker/scripts/oq-start.sh
  openquake/commands/__main__.py
  openquake/commands/dbserver.py
  openquake/server/dbserver.py
Labels: internal

#4936 Extended disagg by src to the case of multiple realizations
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_master/job.ini
  openquake/qa_tests_data/disagg/case_master/job1.ini
Labels: enhancement

#4945 Small cleanup on the disaggregation
  openquake/calculators/reportwriter.py
  openquake/hazardlib/calc/disagg.py
Labels: internal

#4946 Fixed the seed management for Beta distribution
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/risklib/scientific.py
Labels: bug

#4947 Waiting for the workerpools to start
  openquake/engine/engine.py
  openquake/server/tests/views_test.py
Labels: enhancement, internal

#4948 Losses by event
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
Labels: enhancement

#4949 Change address of wheels
  requirements-extra-py36-linux64.txt
  requirements-extra-py36-macos.txt
  requirements-extra-py37-linux64.txt
  requirements-extra-py37-macos.txt
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
Labels: internal, packaging

#4950 The zmq workers must be starting after polling the queue
  openquake/baselib/workerpool.py
  openquake/engine/engine.py
  openquake/server/tests/views_test.py
Labels: internal

#4952 Removed some experimental code
  .travis.yml
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/source_model_factory.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/scenario/case_11/__init__.py
  openquake/qa_tests_data/scenario/case_11/gsim_logic_tree.xml
  openquake/qa_tests_data/scenario/case_11/job.ini
  openquake/qa_tests_data/scenario/case_11/rupture_model.xml
Labels: internal

#4931 Youngs and Coppersmith 1985 from_total_moment_rate fix
  openquake/hazardlib/mfd/youngs_coppersmith_1985.py
  openquake/hazardlib/tests/mfd/youngs_coppersmith_1985_test.py
Labels: bug

#4953 Make StdDev.TOTAL mandatory at class level
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: enhancement, internal

#4928 Updates for manual 3.7 [WIP]
  doc/manual/oqum/hazard/01a_logic_trees.tex
  doc/manual/oqum/hazard/01d_config_classical.tex
  doc/manual/oqum/hazard/01d_config_event_based.tex
  doc/manual/oqum/hazard/01d_config_scenario.tex
  doc/manual/oqum/hazard/02c_output_event_based.tex
  doc/manual/oqum/hazard/02d_output_scenario.tex
  doc/manual/oqum/hazard/03c_eventbased_demos.tex
  doc/manual/oqum/hazard/verbatim/config_classical.ini
  doc/manual/oqum/hazard/verbatim/output_gmf.xml
  doc/manual/oqum/hazard/verbatim/output_gmf_scenario.xml
  doc/manual/oqum/hazard/verbatim/output_realizations.tex
  doc/manual/oqum/help.txt
  doc/manual/oqum/introduction.tex
  doc/manual/oqum/preamble.tex
  doc/manual/oqum/risk/02_config_classical_risk.tex
  doc/manual/oqum/risk/03_outputs_probabilistic_risk.tex
  doc/manual/oqum/risk/verbatim/config_classical_risk.ini
  doc/manual/oqum/risk/verbatim/config_event_based_risk_combined.ini
  doc/manual/oqum/risk/verbatim/config_gmf_event_based_risk.ini
Labels: documentation

#4956 Mark oq dbserver restart as broken
  debian/changelog
  openquake/commands/dbserver.py
Labels: bug

#4958 Changed split_task to use random sampling
  openquake/baselib/parallel.py
Labels: internal, performance

#4959 Simplified the way the number of sites per source and the number of ruptures per group are stored
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/ucerf_classical.py
  openquake/calculators/ucerf_event_based.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_14/report.rst
Labels: internal

#4955 Hide but do not delete removed calcs
  debian/changelog
  openquake/server/db/actions.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/views_test.py
Labels: enhancement, internal

#4960 Added attributes to agg_curves-stats
  openquake/calculators/ebrisk.py
  openquake/hazardlib/stats.py
Labels: enhancement

#4961 Restored `oq show task_hazard:-1`
  openquake/calculators/classical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/qa_tests_data/classical/case_14/expected/hazard_curve-rlz-000_PGA.csv
  openquake/qa_tests_data/classical/case_14/expected/hazard_curve-rlz-001_PGA.csv
Labels: internal

#4962 Set site_effects=False
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/qa_tests_data/scenario_damage/case_8/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
Labels: enhancement

#4963 Added another test for the ShakeMap
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/tests/shakemap/test_shaking.xml
  openquake/hazardlib/tests/shakemap/test_uncertainty.xml
Labels: enhancement

#4965 More refactoring of the disaggregation
  .travis.yml
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#4964 20190730 azimuth
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/tests/geo/surface/base_surface_test.py
Labels: enhancement

#4967 Fixed a bug in disaggregation with nonparametric sources
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Dist.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Mag_Dist_Eps.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_5/expected/PGA-sid-0-poe-0_TRT.csv
Labels: bug
