Repository gem/oq-engine, pull requests merged in 2019-02, with the labels that each got.

#4383 adding conversion from geometric mean to larger horizontal component in bradley_2013.py
  openquake/hazardlib/gsim/bradley_2013.py
Labels: enhancement

#4409 Forced ebrisk to start from precomputed ruptures
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/export/risk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job.ini
Labels: bug, enhancement

#4412 Tried RtreeFilter in South America
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: internal, performance

#4415 Some refactoring of ebrisk
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
Labels: internal

#4413 Refactored the management of SourceGroups
  openquake/calculators/classical.py
  openquake/commonlib/source.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/calc/hazard_curve_cluster_test.py
  openquake/hazardlib/tests/calc/hazard_curve_rupture_mutex.py
Labels: enhancement, internal

#4417 Refactored the RuptureGetter
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
Labels: internal

#4419 Removed several deprecation warnings
  openquake/baselib/__init__.py
  openquake/baselib/node.py
  openquake/baselib/parallel.py
  openquake/baselib/sap.py
  openquake/baselib/tests/datastore_test.py
  openquake/baselib/tests/workerpool_test.py
  openquake/baselib/zeromq.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/ucerf_event_based.py
  openquake/commands/prepare_site_model.py
  openquake/commands/show.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/rlzs_assoc.py
  openquake/commonlib/tests/nrml_test.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/gsim/mgmpe/dummy_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
  openquake/hazardlib/valid.py
  openquake/hmtk/faults/fault_models.py
  openquake/hmtk/parsers/catalogue/csv_catalogue_parser.py
  openquake/hmtk/parsers/strain/strain_csv_parser.py
  openquake/risklib/asset.py
  openquake/risklib/read_nrml.py
  openquake/risklib/riskmodels.py
  openquake/server/dbserver.py
  openquake/server/utils.py
  openquake/server/views.py
  pytest.ini
Labels: internal

#4418 Introduced the ability to launch subtasks from tasks
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/commands/show.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/classical/case_19/job.ini
Labels: enhancement, internal

#4370 GMPE for average SA calculation
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/mgmpe/akkar_coeff_table.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/tests/gsim/mgmpe/data/GENERIC_GMPE_AVGSA_MEAN_STD_TOTAL_AKKAR.csv
  openquake/hazardlib/tests/gsim/mgmpe/data/GENERIC_GMPE_AVGSA_MEAN_STD_TOTAL_BAKER_JAYARAM.csv
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/qa_tests_data/classical/case_34/__init__.py
  openquake/qa_tests_data/classical/case_34/expected/hazard_curve-mean-AverageSA.csv
  openquake/qa_tests_data/classical/case_34/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_34/job.ini
  openquake/qa_tests_data/classical/case_34/source_model.xml
  openquake/qa_tests_data/classical/case_34/source_model_logic_tree.xml
Labels: enhancement

#4423 Stored information for nonparametric ruptures
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement, internal

#4429 Renamed AverageSA-> AvgSA
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/qa_tests_data/classical/case_34/expected/hazard_curve-mean-AvgSA.csv
  openquake/qa_tests_data/classical/case_34/job.ini
Labels: proposal

#4432 ebrisk: replace losses_by_site with avg_losses
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses_by_site.csv
Labels: enhancement

#4433 Removed the limit in the number of sites in event based calculation
  debian/changelog
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#4434 Implemented single file mode for ebrisk
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/base_test.py
  openquake/calculators/ucerf_classical.py
  openquake/calculators/ucerf_event_based.py
  openquake/calculators/views.py
  openquake/commands/extract.py
  openquake/commands/purge.py
  openquake/commands/run.py
  openquake/commonlib/logictree.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/valid.py
Labels: enhancement

#4431 Remove depth check
  openquake/hazardlib/geo/mesh.py
Labels: enhancement

#4422 When computing the hazard curves, also determine the realization closest to mean curve
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/util.py
Labels: enhancement

#4435 ebrisk: the task_info table was not saved correctly
  openquake/baselib/parallel.py
  openquake/calculators/ebrisk.py
Labels: bug, enhancement

#4436 Moved the Akkar coefficient table into a csv
  openquake/hazardlib/gsim/mgmpe/akkar_coeff_table.csv
  openquake/hazardlib/gsim/mgmpe/akkar_coeff_table.py
Labels: internal

#4437 ebrisk: renamed avg_losses-rlzs as agg_losses-rlzs
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
Labels: enhancement

#4439 Added a parameter `ebrisk_maxweight`
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job.ini
Labels: enhancement

#4441 Add csv located in ./gsim/mgmpe in py package
  MANIFEST.in
Labels: bug, packaging

#4440 Saving the event loss table in ebrisk similarly to event_based_risk
  openquake/calculators/ebrisk.py
  openquake/risklib/scientific.py
Labels: enhancement

#4443 Fixed portfolio_loss
  openquake/calculators/views.py
Labels: bug, internal

#4444 Fixed FEWSITES misprint [skip hazardlib]
  openquake/calculators/classical.py
Labels: bug

#4430 Removed the rlzi column from the GMF csv export
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/readinput.py
  openquake/commonlib/rlzs_assoc.py
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/hazardlib/shakemap.py
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_13/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_18/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/minimum-intensity-gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_4a/expected/gmf-data.csv
  openquake/qa_tests_data/scenario/case_1/BooreAtkinson2008_gmf.csv
  openquake/qa_tests_data/scenario/case_1/expected.xml
  openquake/qa_tests_data/scenario/case_9/YoungsEtAl1997SSlab_gmf.xml
  openquake/qa_tests_data/scenario/case_9/gmf.csv
  openquake/qa_tests_data/scenario/case_9/gmf.xml
  openquake/qa_tests_data/scenario_risk/case_1/expected/gmf-FromFile.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg-gsimltp_b1_structural.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg-gsimltp_b2_structural.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/server/db/actions.py
Labels: enhancement

#4446 Improved the hazard curve plotter
  demos/hazard/LogicTreeCase3ClassicalPSHA/job.ini
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/commands/plot.py
  openquake/commands/plot_uhs.py
  openquake/commands/show.py
  openquake/commonlib/logs.py
  openquake/commonlib/rlzs_assoc.py
Labels: enhancement

#4451 Serialization GsimLogicTree -> HDF5
  openquake/baselib/node.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/rlzs_assoc.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/logictree_test.py
Labels: enhancement, internal

#4452 Removed obsolete __metaclass__ hooks
  openquake/hmtk/faults/fault_geometries.py
  openquake/hmtk/faults/mfd/anderson_luco_arbitrary.py
  openquake/hmtk/faults/mfd/anderson_luco_area_mmax.py
  openquake/hmtk/faults/mfd/base.py
  openquake/hmtk/parsers/catalogue/base.py
  openquake/hmtk/parsers/source_model/base.py
  openquake/hmtk/seismicity/completeness/base.py
  openquake/hmtk/seismicity/declusterer/base.py
  openquake/hmtk/seismicity/declusterer/distance_time_windows.py
  openquake/hmtk/seismicity/max_magnitude/base.py
  openquake/hmtk/seismicity/occurrence/base.py
  openquake/hmtk/seismicity/smoothing/kernels/base.py
Labels: internal

#4453 Changing the storage of the hazard maps
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/commonlib/calc.py
Labels: internal

#4447 More refactoring of the plotters
  demos/hazard/LogicTreeCase3ClassicalPSHA/job.ini
  openquake/commands/plot_uhs.py
Labels: enhancement

#4456 Refactored nga_east GMPE
  openquake/hazardlib/gsim/nga_east.py
Labels: internal

#4457 Temporary hack to fix the GMPE tables issue
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
Labels: bug

#4458 Added a mechanism to delay the initialization of the GMPEs
  debian/changelog
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/tests/gsim/check_gsim.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/nga_east_full_uncertainty_test.py
  openquake/hazardlib/tests/gsim/nga_east_total_sigma_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: enhancement, internal

#4455 Changed the syntax of gsimByImt
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based/case_1/gsim_by_imt_logic_tree.xml
Labels: enhancement

#4459 Added another missing __init__.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/tests/gsim/campbell_2003_test.py
  openquake/hazardlib/tests/gsim/mgmpe/__init__.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_linear_test.py
Labels: bug

#4465 Replaced sets as GSIM class attributes with frozensets
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: enhancement, internal

#4466 Added a check against mispellings in REQUIRES_DISTANCES
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
Labels: enhancement

#4463 Added a forgotten ses_ratio in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses.csv
Labels: bug

#4468 Small improvement in split_in_blocks
  openquake/baselib/general.py
  openquake/baselib/tests/general_test.py
Labels: internal, performance

#4461 Added toml to the dependencies
  debian/changelog
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  setup.py
Labels: packaging

#4469 Deserialization HDF5 -> GsimLogicTree
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/rlzs_assoc.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_12/expected/hazard_curve-smltp_b1-gsimltp_b1_b2.csv
  openquake/qa_tests_data/classical/case_12/gsim_logic_tree.xml
  openquake/qa_tests_data/classical/case_18/expected/realizations.csv
  openquake/qa_tests_data/classical/case_34/expected/hazard_curve-mean-AvgSA.csv
  openquake/qa_tests_data/classical/case_34/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based/case_1/gsim_by_imt_logic_tree.xml
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_6/expected/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
Labels: enhancement

#4454 Removed most of nose usage
  .travis.yml
  doc/testing.md
  openquake/baselib/tests/config_test.py
  openquake/calculators/tests/classical_bcr_test.py
  openquake/calculators/tests/classical_damage_test.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/hazardlib/tests/gsim/nga_east_full_uncertainty_test.py
  openquake/hazardlib/tests/source/rupture_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/hmtk/plotting/beachball.py
  packager.sh
  rpm/python3-oq-engine.spec.inc
Labels: internal

#4471 Raise an error for disaggregation with atomic groups
  debian/changelog
  openquake/calculators/disaggregation.py
Labels: enhancement

#4470 Plotting remote hmaps
  debian/changelog
  demos/hazard/SimpleFaultSourceClassicalPSHA/job.ini
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/commands/plot_hmaps.py
  openquake/commands/plot_uhs.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/gsim/nga_east.py
  openquake/server/views.py
Labels: enhancement

#4472 Update yu13 gmpe
  debian/changelog
  openquake/hazardlib/gsim/yu_2013.py
  openquake/hazardlib/tests/gsim/yu_2013_ms_test.py
  openquake/hazardlib/tests/gsim/yu_2013_mw_test.py
Labels: enhancement

#4473 More work on plot hmaps
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/engine.py
  openquake/commands/export.py
  openquake/commands/extract.py
  openquake/commands/plot.py
  openquake/commands/plot_agg_curve.py
  openquake/commands/plot_assets.py
  openquake/commands/plot_hmaps.py
  openquake/commands/plot_lc.py
  openquake/commands/plot_losses.py
  openquake/commands/plot_memory.py
  openquake/commands/plot_sites.py
  openquake/commands/plot_uhs.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/util.py
Labels: internal

#4474 Moved the nose dependency in extras_require
  setup.py
Labels: packaging

#4477 Removed mixed case test filename
  debian/changelog
  openquake/baselib/tests/lowercase_test.py
  openquake/hazardlib/tests/gsim/yu_2013_Mw_test.py
  openquake/hazardlib/tests/gsim/yu_2013_test.py
Labels: bug

#4479 Documented the Extractor classes
  doc/adv-manual/extract-api.rst
  doc/adv-manual/index.rst
  doc/faq-hazard.md
  openquake/calculators/extract.py
Labels: documentation

#4438 Removed the realization index from the event loss table export
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_risk.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/agg_losses-all.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_losses-all.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
Labels: enhancement

#4482 Used the Extractor in the hazard curves plotter
  bin/run-demos.sh
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commands/plot_hmaps.py
Labels: enhancement, internal

#4483 Using the Extractor in plot_uhs
  openquake/calculators/extract.py
  openquake/commands/plot_uhs.py
Labels: enhancement

#4475 Keeping open the DbServer client socket
  debian/changelog
  openquake/commonlib/logs.py
Labels: bug

#4484 Implemented remote site selection
  debian/changelog
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commands/plot_hmaps.py
  openquake/commands/plot_uhs.py
Labels: enhancement

#4485 More parallel prefiltering
  openquake/calculators/base.py
Labels: performance

#4449 Add some provisional doc about Windows and dev
  doc/installing/development-windows.md
  doc/installing/development.md
  setup.py
Labels: documentation

#4489 Make sure the IMTs are sorted by period in the job.ini
  debian/changelog
  openquake/hazardlib/valid.py
Labels: enhancement

#4490 Displaying the investigation time in the plots
  openquake/commands/plot.py
  openquake/commands/plot_hmaps.py
  openquake/commands/plot_uhs.py
Labels: enhancement

#4491 Using the Extractor in oq extract
  bin/run-demos.sh
  openquake/baselib/hdf5.py
  openquake/commands/extract.py
Labels: internal

#4492 Unified the hazard plotting commands
  bin/run-demos.sh
  debian/changelog
  doc/oq-commands.md
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commands/plot_hmaps.py
  openquake/commands/plot_uhs.py
  openquake/engine/engine.py
  openquake/hazardlib/geo/utils.py
Labels: enhancement

#4493 Made it possible to plot the statistics together with the realizations
  bin/run-demos.sh
  openquake/baselib/hdf5.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/server/tests/views_test.py
  openquake/server/views.py
Labels: enhancement

#4494 Fixed a bytes/string issue breaking the QGIS exports
  openquake/baselib/hdf5.py
  openquake/server/views.py
Labels: bug

#4495 Merged the plost of hazard curves and UHS in case of two calculations
  openquake/commands/plot.py
Labels: enhancement

#4487 Decluster window
  debian/changelog
  openquake/hmtk/seismicity/declusterer/dec_gardner_knopoff.py
  openquake/hmtk/seismicity/declusterer/distance_time_windows.py
  openquake/hmtk/tests/seismicity/declusterer/data/gardner_knopoff_test_catalogue.csv
  openquake/hmtk/tests/seismicity/declusterer/dec_gardner_knopoff_test.py
Labels: enhancement

#4500 Fixed export_agg_curve_rlzs
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_loss-rlz-000.csv
Labels: bug

#4498 Using the Extractor in oq compare
  openquake/commands/compare.py
  openquake/hazardlib/sourceconverter.py
Labels: internal
