Repository gem/oq-engine, pull requests merged in 2019-01, with the labels that each got.

#3448 Deprecate insuranceLimit/deductible
  openquake/risklib/asset.py
Labels: documentation

#4334 Manual: Add a section describing exposure in csv [skip CI]
  doc/manual/oqum/glossary.tex
  doc/manual/oqum/risk/01a_exposure.tex
  doc/manual/oqum/risk/verbatim/input_exposure_csv.xml
  doc/manual/oqum/risk/verbatim/input_exposure_wa.csv
  doc/manual/oqum/risk/verbatim/input_exposure_wa.tex
Labels: documentation

#4335 Moved the insured_losses from riskmodels into event_based_risk
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/mean_avg_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/risklib/riskmodels.py
Labels: internal

#4336 Added a check for missing retrofitted values
  debian/changelog
  openquake/calculators/classical_bcr.py
  openquake/risklib/asset.py
Labels: enhancement

#4337 Extract the hazard sites from the site_model, not the exposure
  debian/changelog
  openquake/calculators/base.py
  openquake/commands/plot_assets.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/job.ini
  openquake/qa_tests_data/event_based_risk/case_4/expected/agg_losses-all.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_3/job.ini
  openquake/qa_tests_data/scenario_damage/case_5/job_risk.ini
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_5/job.ini
  openquake/qa_tests_data/scenario_risk/case_8/job.ini
  openquake/server/tests/data/archive_ok.zip
Labels: enhancement

#4338 Not splitting the sources in event_based
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/source_test.py
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_1/job.ini
  openquake/qa_tests_data/event_based/case_12/expected/hazard_curve-smltp_b1-gsimltp_b1_b2.csv
  openquake/qa_tests_data/event_based/case_12/job.ini
  openquake/qa_tests_data/event_based/case_13/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_13/job.ini
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.xml
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
  openquake/qa_tests_data/event_based/case_17/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_18/job.ini
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/job_grid.ini
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_2/expected/hc-mean.csv
  openquake/qa_tests_data/event_based/case_2/job.ini
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_4/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_6/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_6/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_7/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based/case_7/expected/quantile_curve-0.9.csv
  openquake/qa_tests_data/event_based/case_7/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_1/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_2/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/event_based_risk/case_1g/job_h.ini
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/curves_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/job.ini
  openquake/qa_tests_data/event_based_risk/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/job.ini
  openquake/qa_tests_data/event_based_risk/case_4a/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/loss_maps-rlz-000.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_losses-all.csv
Labels: performance

#4340 Changed the event_based_risk demo to use a single job.ini file
  demos/risk/EventBasedRisk/job.ini
  demos/risk/EventBasedRisk/job_risk.ini
Labels: documentation

#4343 Implemented AccumDict.__ipow__
  openquake/baselib/general.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/probability_map_test.py
Labels: enhancement

#4345 Added an API `/extract/event_info/eid`
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement

#4346 Added a check to forbid to set `ses_per_logic_tree_path = 0`
  debian/changelog
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#4349 Initial work on the ebrisk calculator
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/engine.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job.ini
  openquake/risklib/asset.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: enhancement

#4351 Fixed master
  openquake/commands/engine.py
Labels: bug

#4354 Implemented avglosses_by_rlz in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses.txt
Labels: enhancement

#4357 Fixed the GMF export to export the event IDs again
  openquake/calculators/export/hazard.py
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_13/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_18/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/minimum-intensity-gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_4a/expected/gmf-data.csv
  openquake/qa_tests_data/scenario/case_1/BooreAtkinson2008_gmf.csv
  openquake/qa_tests_data/scenario/case_9/gmf.csv
Labels: bug

#4355 Ordered the events by realization
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_maps-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_maps-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-curves-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by-taxonomy,occupancy-curves-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/curves_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-002.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/loss_maps-rlz-003.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
Labels: enhancement

#4358 Use less memory in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
Labels: performance

#4359 Changed the agg_curves exporter
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_loss-mean.csv
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: enhancement

#4360 20190111 rup weights
  debian/changelog
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/calc/hazard_curve_rupture_mutex.py
  openquake/hazardlib/tests/source_model/nonparametric-source-mutex-ruptures.xml
  openquake/hazardlib/tests/source_model/rupture_mutex_wrong.xml
  openquake/hazardlib/tests/source_model/source_group_collection.xml
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: enhancement

#4362 Made avglosses exportable in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses.txt
Labels: enhancement

#4363 Reading the exposures in parallel
  debian/changelog
  openquake/commonlib/tests/readinput_test.py
  openquake/risklib/asset.py
Labels: enhancement, performance

#4365 Fixed export bug
  debian/changelog
  openquake/calculators/export/hazard.py
Labels: bug

#4366 Removed saving_sources_by_task
  openquake/calculators/classical.py
Labels: internal

#4367 Shutdown the processpool after parallel_split_filter
  openquake/commonlib/readinput.py
Labels: enhancement

#4368 Computed and exported losses_by_site in ebrisk
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses_by_site.csv
Labels: enhancement

#4369 Fixed a wrong coefficient in the ShakeMap amplification
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: bug

#4372 Speed-up store_source_info [aka Australia runs!]
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/ucerf_classical.py
Labels: critical

#4373 Tl16 fix coeff
  debian/changelog
  openquake/hazardlib/gsim/tusa_langer_2016.py
  openquake/hazardlib/tests/gsim/data/TL16/TusaLanger2016BA08SE_MEAN.csv
Labels: bug

#4378 Fixed ebrisk with --hc
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_event_based.py
Labels: bug, internal

#4379 Fixed management of task_no
  openquake/baselib/parallel.py
Labels: internal

#4381 Changed the rupture weight to depend on the number of affected assets
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/ucerf_classical.py
  openquake/hazardlib/calc/filters.py
  openquake/risklib/asset.py
Labels: enhancement

#4384 Change the rupture weight in ebrisk
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/risklib/asset.py
Labels: internal

#4385 Refactored the minimum_intensity feature
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
Labels: internal

#4350 20181215 tom
  debian/changelog
  openquake/baselib/general.py
  openquake/baselib/tests/general_test.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/source.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/source/__init__.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/calc/hazard_curve_cluster_test.py
  openquake/hazardlib/tests/source_model/source_group_cluster.xml
  openquake/hazardlib/tests/source_model/source_group_with_tom.xml
  openquake/hazardlib/tests/source_model/tom_poisson_no_rate.xml
  openquake/hazardlib/tests/source_model/tom_poisson_with_rate.xml
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
  openquake/hazardlib/tests/tom_test.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/classical/case_35/__init__.py
  openquake/qa_tests_data/classical/case_35/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_35/gsim_logic_tree.xml
  openquake/qa_tests_data/classical/case_35/job.ini
  openquake/qa_tests_data/classical/case_35/source_model.xml
  openquake/qa_tests_data/classical/case_35/source_model_logic_tree.xml
Labels: enhancement

#4387 Fixed an error in oq show fullreport
  openquake/calculators/classical.py
Labels: bug

#4388 More work on the slow tasks in ebrisk
  openquake/baselib/general.py
  openquake/baselib/tests/general_test.py
  openquake/baselib/zeromq.py
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/hazardlib/source/rupture_collection.py
  openquake/risklib/asset.py
Labels: internal

#4391 Refactored the GmfGetter in terms of the RuptureGetter
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
Labels: internal

#4393 Postfilter the ruptures after sampling
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: internal

#4395 Optimized a bit ebrisk
  openquake/calculators/ebrisk.py
Labels: performance

#4398 Doubled the speed of the ebrisk calculator
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
Labels: performance

#4400 Some refactoring of the ebrisk calculator
  openquake/calculators/ebrisk.py
  openquake/risklib/riskmodels.py
Labels: internal

#4376 Remove risk stats
  debian/changelog
  demos/risk/EventBasedRisk/job.ini
  doc/manual/oqum/risk/verbatim/config_classical_risk.ini
  doc/manual/oqum/risk/verbatim/config_event_based_risk_combined.ini
  doc/manual/oqum/risk/verbatim/config_gmf_event_based_risk.ini
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/classical_bcr/case_2/job.ini
  openquake/qa_tests_data/classical_risk/case_4/job_risk.ini
  openquake/qa_tests_data/classical_risk/case_master/job.ini
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/event_based_risk/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
  openquake/server/tests/data/classical_psha_based_risk/job.ini
  openquake/server/tests/data/end-to-end-hazard-risk/job_risk_classical.ini
  openquake/server/tests/data/end-to-end-hazard-risk/job_risk_event_based.ini
Labels: internal

#4399 Export the aggregate loss ratios
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_loss-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_loss-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avglosses.txt
  openquake/risklib/asset.py
Labels: enhancement

#4402 Saving only the mean losses_by_site
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/risklib/riskmodels.py
Labels: performance

#4397 Allow only REST API to be exposed
  openquake/server/settings.py
  openquake/server/urls.py
Labels: enhancement, user interface

#4403 Speedup losses_by_site even more
  openquake/calculators/ebrisk.py
Labels: performance

#4404 Prefiltering on the workers to save memory on the master
  debian/changelog
  openquake/calculators/base.py
Labels: enhancement, performance

#4406 Fixed bug in applyToSources
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
  openquake/qa_tests_data/classical/case_36/__init__.py
  openquake/qa_tests_data/classical/case_36/job.ini
  openquake/qa_tests_data/classical/case_36/source_model.xml
  openquake/qa_tests_data/classical/case_36/source_model_logic_tree.xml
Labels: bug
