Repository gem/oq-engine, pull requests merged in 2019-09, with the labels that each got.

#5028 Do not sort site coordinates if site_ids are provided by user
  debian/changelog
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/gmf_ebrisk/case_2/vulnerability_2IM.xml
Labels: bug

#5030 Reduced data transfer in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
Labels: performance

#5031 Small simplification of `srcfilter.close_sids`
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/stochastic.py
Labels: internal

#5032 Log number of cores available when using *pool
  openquake/engine/engine.py
Labels: enhancement

#5034 Stored the time to compute the GMFs for each rupture in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/hazardlib/calc/gmf.py
Labels: internal

#5033 Removed obsolete tests for the removed calculator ucerf_risk
  openquake/calculators/tests/ucerf_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/ucerf/expected/losses_by_period-mean.csv
  openquake/qa_tests_data/ucerf/expected/losses_by_period2-mean.csv
  openquake/qa_tests_data/ucerf/expected/portfolio_loss.txt
  openquake/qa_tests_data/ucerf/expected/portfolio_loss2.txt
  openquake/qa_tests_data/ucerf/job_ebr.ini
Labels: internal

#5035 Fixed the order of the events in ebrisk
  openquake/baselib/parallel.py
Labels: bug

#5037 Refactored split_task
  openquake/baselib/parallel.py
  openquake/calculators/ebrisk.py
Labels: internal, performance

#5036 Fixed the seed management for the beta distribution again
  debian/changelog
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/classical_test.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: bug

#5038 Sort the computers properly
  openquake/baselib/parallel.py
  openquake/calculators/ebrisk.py
Labels: internal, performance

#5039 Reduce the data transfer by 20x in the Canada ebrisk calculation
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: performance

#5040 Bump numpy to 1.16 and scipy to 1.3
  debian/changelog
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  setup.py
Labels: packaging

#5042 Renamed serial->rup_id
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
Labels: enhancement

#5043 Replaced the 64 bit event IDs with 32 bit integers
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/multi_risk.py
  openquake/calculators/scenario.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/ucerf_event_based.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/blocksize/expected/sig-eps.csv
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based/case_1/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/gsim_by_imt.csv
  openquake/qa_tests_data/event_based/case_13/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.xml
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_18/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/minimum-intensity-gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/sig-eps.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_22/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/mutex/expected/ses.xml
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/rupture-nonstructural.xml
  openquake/qa_tests_data/event_based_risk/case_1/expected/rupture-structural.xml
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_4a/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_3/gmfs.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario/case_1/BooreAtkinson2008_gmf.csv
  openquake/qa_tests_data/scenario/case_9/gmf.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/dmg_by_event.csv
Labels: enhancement

#5044 Fixed the events exporter to export the rup_id
  openquake/calculators/export/hazard.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
Labels: enhancement

#5048 Fixed the multiplicity in the ses.xml file
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/hazard_writers.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.xml
Labels: bug

#5053 Slow tasks for risk-dominated calculations
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
Labels: performance

#5052 Small renaming
  openquake/baselib/hdf5.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_risk.py
Labels: internal

#5055 Added `ArrayWrapper.sum_all`
  openquake/baselib/hdf5.py
Labels: enhancement, internal

#5056 add the shapefile source of 'lahar-geom.csv' geometry field
  openquake/qa_tests_data/multi_risk/case_1/lahar-geom.zip
Labels: internal

#5054 Changed the agg_curves exporter to use ArrayWrapper.to_table
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves-rlzs.csv
Labels: internal

#5058 Changed ebrisk to produce an output avg_losses-stats instead of avg_losses
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/server/db/actions.py
Labels: enhancement

#5059 Added view task_ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/views.py
Labels: internal

#5060 Some refactoring of the ebrisk calculator
  openquake/baselib/parallel.py
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/views.py
Labels: internal

#5061 Refined the task queue and added some debug logging
  openquake/baselib/parallel.py
  openquake/commands/__main__.py
Labels: internal

#5062 Sending two tasks from the queue at once
  openquake/baselib/parallel.py
  openquake/baselib/zeromq.py
  openquake/calculators/ebrisk.py
Labels: performance

#5063 Changed the realizations.csv exporter to undestand ShakeMaps
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/realizations.csv
Labels: enhancement

#5064 Accepted also geometry files without quotes in the multi_risk calculator
  debian/changelog
  openquake/calculators/multi_risk.py
  openquake/qa_tests_data/multi_risk/case_1/pyro-geom.csv
Labels: enhancement

#5057 undesired file removed from shapefile zip archive
  openquake/qa_tests_data/multi_risk/case_1/lahar-geom.zip
Labels: internal

#5065 Raised a clear error for unquoted geometries
  debian/changelog
  openquake/calculators/multi_risk.py
  openquake/qa_tests_data/multi_risk/case_1/pyro-geom.csv
Labels: enhancement

#5066 Fixed the performance of the GMPE logic tree sampling
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/rlzs_assoc.py
  openquake/commonlib/source.py
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_loss_12.csv
  openquake/qa_tests_data/event_based_risk/case_master/job12.ini
Labels: bug, enhancement, performance

#5069 Added test for a long complex fault source in South America
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_42/__init__.py
  openquake/qa_tests_data/classical/case_42/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_42/expected/hazard_map-mean-PGA.csv
  openquake/qa_tests_data/classical/case_42/gmmLT_A15.xml
  openquake/qa_tests_data/classical/case_42/int_2.xml
  openquake/qa_tests_data/classical/case_42/job.ini
  openquake/qa_tests_data/classical/case_42/ssmLT.xml
Labels: bug

#5068 Removed references to the branchingLevel from the manual
  doc/manual/oqum/glossary.tex
  doc/manual/oqum/hazard/01a_logic_trees.tex
  doc/manual/oqum/hazard/01b_seismic_source_system.tex
  doc/manual/oqum/hazard/verbatim/input_gmlt.xml
  doc/manual/oqum/hazard/verbatim/input_gmlt_demo.xml
  doc/manual/oqum/hazard/verbatim/input_gmlt_demo_LogicTreeCase1ClassicalPSHA.xml
  doc/manual/oqum/hazard/verbatim/input_gmlt_demo_LogicTreeCase2ClassicalPSHA.xml
  doc/manual/oqum/hazard/verbatim/input_sslt.xml
  doc/manual/oqum/hazard/verbatim/input_sslt_demo_LogicTreeCase1ClassicalPSHA.xml
  doc/manual/oqum/hazard/verbatim/input_sslt_demo_LogicTreeCase3ClassicalPSHA.xml
  doc/manual/oqum/hazard/verbatim/input_sslt_simple_lt.xml
  doc/manual/oqum/risk/verbatim/input_scenario_gmlt.xml
Labels: documentation

#5070 Fixed the complex fault source split/filtering bug
  debian/changelog
  openquake/hazardlib/source/rupture_collection.py
  openquake/qa_tests_data/classical/case_42/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_42/expected/hazard_map-mean-PGA.csv
Labels: bug

#5073 Fixed disaggregation around the international date line
  debian/changelog
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_6/__init__.py
  openquake/qa_tests_data/disagg/case_6/expected/PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_6/gmmLT.xml
  openquake/qa_tests_data/disagg/case_6/job.ini
  openquake/qa_tests_data/disagg/case_6/ssm/shallow/shallow_faults.xml
  openquake/qa_tests_data/disagg/case_6/ssmLT.xml
Labels: bug

#5076 Added some fast aggregation routines
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/views.py
  openquake/risklib/asset.py
Labels: performance

#5077 Now the engine automatically sorts the user-provided intensity_measure_types
  debian/changelog
  openquake/hazardlib/valid.py
Labels: enhancement

#5078 Ported the rup_loss_table to ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: internal

#5079 Collapsed the task_info tables in a single table
  openquake/baselib/performance.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/ebrisk.py
  openquake/calculators/extract.py
  openquake/calculators/reportwriter.py
  openquake/calculators/views.py
Labels: internal

#5080 Made oq reset safer
  debian/changelog
  openquake/commands/purge.py
  openquake/commands/reset.py
Labels: bug

#5083 Replaced rup_id with the rupture index
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/calc/stochastic.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
Labels: internal

#5084 Replace fast_agg2 with fast_agg when possible
  openquake/calculators/event_based_risk.py
  openquake/calculators/views.py
Labels: internal, performance

#5085 Simplified extend3
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/datastore_test.py
  openquake/baselib/tests/hdf5_test.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/ebrisk.py
Labels: internal

#5086 Moved the cache file to SWMR mode
  openquake/calculators/base.py
  openquake/hazardlib/calc/filters.py
Labels: internal

#5089 Minor refactoring of the monitor
  openquake/baselib/performance.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/scenario.py
  openquake/calculators/scenario_risk.py
Labels: internal

#5090 Some work on the SWMR mode
  .travis.yml
  openquake/baselib/hdf5.py
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
Labels: internal

#5091 Introduced a task_sent dataset
  openquake/baselib/datastore.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/views.py
Labels: internal

#5092 Restored `oq show performance` on-the-fly
  openquake/baselib/datastore.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
Labels: internal

#5093 Pass the HDF5 file object to Starmap
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/source_model_factory.py
Labels: internal

#5095 Removed set_nbytes
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/tests/commands_test.py
Labels: internal

#5097 Enable SWMR mode in classical and disaggregation calculators
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/performance.py
  openquake/baselib/tests/hdf5_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/__init__.py
  openquake/engine/engine.py
Labels: internal

#5098 Removed the `poes` cache in classical calculations
  openquake/calculators/base.py
  openquake/calculators/classical.py
Labels: internal

#5099 Transfer the rupture arrays in event based calculations
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
Labels: internal

#5100 Used the SWMR mode in ebrisk
  openquake/calculators/ebrisk.py
Labels: internal

#5102 Removed `DataStore.extend`
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
Labels: internal

#5103 Passing to the RuptureGetter the filename pointing to rupgeoms
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
Labels: internal

#5105 Removed the `rupgeoms` dataset from the cache
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: internal

#5106 Storing the performance info directly in the datastore
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
Labels: internal

#3874 Update atkinson_2015.py
  openquake/hazardlib/gsim/atkinson_2015.py
Labels: bug

#5108 Skipped Atkinson2015TestCase
  openquake/hazardlib/tests/gsim/atkinson_2015_test.py
Labels: bug

#5107 Removed `sitecol` from the cache file
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/scenario.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/filters.py
Labels: internal

#5109 Remove early usage of the SWMR mode in classical
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
Labels: bug, internal

#5111 Removed `weights` from the cache file
  openquake/calculators/base.py
Labels: internal

#5087 Extended agg_curves to the case with tags
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
Labels: enhancement

#5112 Removed the epsilons from the cache
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/risklib/riskinput.py
Labels: internal

#5113 Fixed the SMWR mode by closing/reopening the datastore
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
Labels: internal

#5114 Extended the task queue to classical, disaggregation and event based hazard calculators
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
Labels: enhancement

#5110 Decoded attribute `stats` in avg_losses-stats
  openquake/baselib/python3compat.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: bug

#5115 aggregate_by is implented only for ebrisk
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#5104 Ameri 2017
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Heteroscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Heteroscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Heteroscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Heteroscedastic_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Heteroscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Heteroscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Heteroscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Heteroscedastic_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_TOTAL_STDDEV.csv
Labels: enhancement

#5116 Changed the separator in ruptures.csv to a comma
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/commonlib/writers.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/event_based/mutex/expected/ruptures.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement

#5117 Taking into account the maximum_distance when inferring the task_duration
  openquake/calculators/classical.py
Labels: enhancement

#5119 Added a check on the truncation_level
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
Labels: enhancement

#5120 Changed task_info and job_info datasets to fix `oq plot`
  openquake/baselib/performance.py
  openquake/calculators/extract.py
Labels: bug

#5121 Managed the case of few sources (i.e. not enough task submissions)
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
Labels: bug

#5124 Turn num_cores into a class attribute of Starmap
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/commands/compare.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
Labels: enhancement

#5126 Fixed the check for filtered out sources
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
Labels: bug

#5127 Simplified close_sids
  openquake/hazardlib/calc/filters.py
Labels: internal

#5128 Small optimization for non-spinning point sources
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
Labels: internal

#5123 Updated the whats new for engine 3.7
  doc/whats-new.md
Labels: documentation

#5130 Building the PDF of the advanced manual in travis
  .travis.yml
Labels: documentation

#5133 Turn the task queue from LIFO to FIFO
  openquake/baselib/parallel.py
Labels: internal

#5134 Store the sources in TOML format
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#5137 Avoided transferring the SiteCollection in classical calculations
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_risk.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_model_factory.py
  openquake/risklib/riskinput.py
Labels: performance

#5139 Simplified `get_composite_source_model`
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#5140 Parallelized the TOML conversion of the sources
  openquake/commonlib/readinput.py
  openquake/commonlib/source_model_factory.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal, performance

#5141 Fix the WebUI start and improve SIG management
  docker/Dockerfile.base
  docker/Dockerfile.engine
  docker/Dockerfile.master
  docker/Dockerfile.worker
  docker/scripts/celery-wait.sh
  docker/scripts/oq-start.sh
Labels: bug, needs-backport, packaging

#5142 Added a check for no GMFs in event_based_risk
  debian/changelog
  openquake/calculators/base.py
Labels: enhancement
