Repository gem/oq-engine, pull requests merged in 2019-06, with the labels that each got.

#4768 Solved absurd bug in tagcol.id
  openquake/baselib/hdf5.py
  openquake/risklib/asset.py
Labels: bug

#4769 Removed field rlzi from scenario
  openquake/calculators/base.py
Labels: internal

#4770 Fixed --hc across users (again)
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
Labels: bug

#4773 Doc: Minor edits to oq-commands.md [skip-ci]
  doc/oq-commands.md
Labels: documentation

#4772 Documented site_model.csv
  doc/manual/oqum/hazard/01d_config_classical.tex
  doc/manual/oqum/hazard/verbatim/input_site_model.csv
  doc/manual/oqum/hazard/verbatim/input_site_model.xml
Labels: documentation

#4776 Make CSV the default internal format
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/risklib/asset.py
Labels: internal, performance

#4777 Reduced the data transfer in the PmapGetter
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/commonlib/rlzs_assoc.py
  openquake/hazardlib/stats.py
Labels: enhancement

#4778 Enabled the job queue by default
  docker/conf/openquake.cfg.cluster-sample
  openquake/engine/engine.py
  openquake/engine/openquake.cfg
Labels: internal

#4779 Really solved the vstr bug
  openquake/baselib/hdf5.py
Labels: bug

#4780 Refactored hdf5.File.__setitem__
  openquake/baselib/hdf5.py
  openquake/calculators/tests/base_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
  openquake/risklib/asset.py
Labels: internal

#4782 Do not update source_info.num_sites if there are too many sources
  openquake/calculators/classical.py
Labels: internal, performance

#4784 Moved around the disaggregation code
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#4785 Changed disaggregation routines to use a single site at once
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/acceptance/disagg_test.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: internal

#4786 Removed statistics from the disaggregation calculator
  debian/changelog
  doc/oq-commands.md
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Mag_Dist_Eps.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Mag_Dist_Eps.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Mag_Dist_Eps.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Mag_Dist_Eps.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/mean-SA(0.1)-sid-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/mean-SA(0.1)-sid-1_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-0.xml
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1.xml
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-1-PGA--3.0--3.0.xml
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-1-PGA-0.0-0.0.xml
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-2-PGA-0.0-0.0.xml
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-3-PGA-0.0-0.0.xml
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.02-rlz-0-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.02-rlz-0-SA(0.025)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.1-rlz-0-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/poe-0.1-rlz-0-SA(0.025)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-PGA-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-SA(0.25)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.01-rlz-6-SA(0.25)-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-PGA-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-PGA-sid-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-SA(0.25)-sid-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/poe-0.05-rlz-6-SA(0.25)-sid-1_Mag_Dist.csv
  openquake/server/db/actions.py
  setup.py
Labels: enhancement, performance

#4790 Add a consistency check between hazard and risk stats
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_7a/job_h.ini
  openquake/qa_tests_data/event_based_risk/case_7a/job_r.ini
Labels: bug

#4791 Fixed an export agg_curves issue with pre-imported exposures
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/risklib/asset.py
Labels: bug

#4793 Use h5py 2.9.0 wheels
  debian/control
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  rpm/python3-oq-engine.spec.inc
Labels: packaging

#4795 Updated the manual for the new disaggregation
  doc/manual/oqum/hazard/01d_config_disaggregation.tex
  doc/manual/oqum/hazard/02b_output_disaggregation.tex
Labels: documentation

#4794 Changed the name of the disaggregation outputs
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/commands/plot.py
  openquake/qa_tests_data/disagg/case_1/expected_output/hazard_curve/PGA/hazard_curve-smltp_b1-gsimltp_b1.xml
  openquake/qa_tests_data/disagg/case_1/expected_output/hazard_curve/SA-0.025/hazard_curve-smltp_b1-gsimltp_b1.xml
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-PGA-10.1-40.1_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-rlz-0-SA(0.025)-10.1-40.1_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1.xml
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-PGA-10.1-40.1_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1.xml
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-rlz-0-SA(0.025)-10.1-40.1_TRT.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-PGA-sid-1-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-PGA-sid-1-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-SA(0.25)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-SA(0.25)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-SA(0.25)-sid-1-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/rlz-6-SA(0.25)-sid-1-poe-1_Mag_Dist.csv
Labels: enhancement

#4797 Introduced a RupData class
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: internal

#4801 Speedup disaggregate_pne
  debian/changelog
  openquake/hazardlib/calc/disagg.py
Labels: performance

#4803 Discard the ruptures outside the integration distance in disaggregation
  debian/changelog
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: bug, performance

#4804 Turned the disaggregation calculator into a classical post-calculator
  debian/changelog
  openquake/baselib/__init__.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/source.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-0-SA(0.1)-sid-1_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-1-SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-3-SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: enhancement, performance

#4802 Rename outdated parameter in a job file
  openquake/qa_tests_data/classical/case_38/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.16-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.5-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.84-PGA.csv
  openquake/qa_tests_data/classical/case_38/job.ini
Labels: internal

#4805 Deprecated the XML disaggregation exporters in favor of the CSV exporters
  debian/changelog
  openquake/calculators/export/hazard.py
Labels: documentation

#4806 Restored the name sitemesh.csv
  openquake/calculators/export/hazard.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based/blocksize/expected/sites.csv
Labels: internal

#4808 Replaced the incremental rupture code with an unique checksum
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/geo/surface/base_surface_test.py
Labels: internal

#4809 Added a test with a comma in the CSV exposure
  openquake/baselib/__init__.py
  openquake/baselib/hdf5.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/qa_tests_data/event_based/case_20/BC_Exposure.csv
  openquake/qa_tests_data/scenario_damage/case_8/exposure_abruzzo.csv
Labels: bug

#4810 Added a check on suspiciously large sources
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: internal

#4811 Removed some unused code
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
Labels: internal

#4813 Changed the realizations for scenario
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/commands/extract.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
Labels: enhancement

#4812 Removing the mock module since it is included in the standard library since Python 3.3
  openquake/baselib/tests/general_test.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/commands/checksum.py
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqzip.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hmtk/tests/registry_test.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/server/tests/db/upgrade_manager_test.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  setup.py
Labels: packaging

#4807 Some parts in debian were still referring to python2.7
  debian/postrm
  debian/preinst
Labels: bug, packaging

#4799 Disable dbserver and webui services on workers when using ubuntu
  debian/python3-oq-engine-worker.postinst
Labels: bug, packaging

#4814 Removed some lines of code
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/commands/show.py
  openquake/risklib/riskinput.py
Labels: internal

#4815 Fixed a performance bug in the computation of the hazard statistics
  .travis.yml
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/commands/importcalc.py
  openquake/qa_tests_data/classical_risk/case_master/job.ini
  openquake/risklib/riskinput.py
Labels: bug, performance

#4816 Cleaned up the .get_hazard API
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/risklib/riskinput.py
Labels: internal

#4817 Solved the memory issue when computing the statistical hazard curves
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
Labels: performance

#4819 Switch packager.sh to pytest
  packager.sh
Labels: internal

#4822 Made more uniform the storage of `gsim_lt` and `source_model_lt`
  openquake/calculators/extract.py
  openquake/commonlib/logictree.py
Labels: internal

#4823 Move some Travis tests to oq-engine-celery
  .travis.yml
Labels: internal

#4825 Stored rlzs_by_grp
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/commonlib/logictree.py
  openquake/commonlib/rlzs_assoc.py
  openquake/qa_tests_data/event_based/case_10/job.ini
Labels: internal

#4820 Scenario risk exporters
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_2/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/agg_loss.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/agg_loss.csv
Labels: enhancement

#4824 Allow oq abort to be used when status is created
  openquake/commands/abort.py
Labels: internal

#4828 Made the losses_by_event exporter for ebrisk more similar to the one for event_based_risk
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
Labels: enhancement

#4827 Do not autostart/autoenable celery in Ubuntu pkg [skip ci]
  debian/rules
  packager.sh
Labels: enhancement, packaging

#4829 Store infor about the magnitudes in the source model
  openquake/commonlib/readinput.py
Labels: internal

#4826 Extended `oq db` to run generic queries
  openquake/commands/db.py
  openquake/server/dbserver.py
  openquake/server/tests/views_test.py
Labels: enhancement, internal

#4831 Fixed an issue with the QGIS plugin
  openquake/server/views.py
Labels: bug

#4832 Exporting the surface boundaries as 3D multipolygons
  debian/changelog
  openquake/baselib/parallel.py
  openquake/commonlib/calc.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement

#4833 Improved the task distribution
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b1.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b2.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-mean.csv
Labels: performance

#4834 Make possible to abort submitted jobs
  openquake/commands/abort.py
Labels: bug

#4835 Improved the progress report
  debian/changelog
  openquake/baselib/parallel.py
Labels: internal

#4836 Update docs for scenarios from ShakeMaps [skip CI]
  doc/scenario-from-shakemap.md
Labels: documentation

#4839 Added a method `gsim_lt.get_integration_distance`
  openquake/calculators/classical.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/nodalplane.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(1.0).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_18/job.ini
  openquake/qa_tests_data/classical/case_18/report.rst
  openquake/qa_tests_data/classical/case_19/job.ini
  openquake/qa_tests_data/scenario/case_11/__init__.py
  openquake/qa_tests_data/scenario/case_11/gsim_logic_tree.xml
  openquake/qa_tests_data/scenario/case_11/job.ini
  openquake/qa_tests_data/scenario/case_11/rupture_model.xml
Labels: internal

#4842 Fixed ucerf_classical by splitting before filtering
  debian/changelog
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/readinput.py
Labels: bug

#4843 Introduced `max_sites_per_gmf`
  debian/changelog
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#4844 Fixed the Australia calculation
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/calc/filters_test.py
Labels: bug

#4845 Replace the converter obj -> hdf5 with an obj -> toml
  openquake/baselib/hdf5.py
  openquake/baselib/node.py
  openquake/baselib/tests/node_test.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: internal

#4846 Removed flag `optimize_same_id` sources
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/views.py
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical/case_30/job.ini
  openquake/qa_tests_data/classical/case_7/job.ini
Labels: enhancement

#4840 Removed also the cache file when removing a calculation
  debian/changelog
  openquake/commands/dbserver.py
  openquake/commands/purge.py
  openquake/server/db/actions.py
Labels: bug

#4848 Added checks for vulnerability functions with the Beta distribution
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/risklib/read_nrml.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement

#4849 Partial fix for the oq-risk-tests
  openquake/commonlib/readinput.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: bug

#4850 Changed the source model weight to take into account duplicated sources
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/commonlib/source.py
  openquake/hazardlib/calc/stochastic.py
Labels: enhancement

#4851 Supported WKT-based binary perils
  debian/changelog
  openquake/calculators/multi_risk.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/imt.py
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/qa_tests_data/multi_risk/case_1/job_2.ini
  openquake/qa_tests_data/multi_risk/case_1/lahar.wkt
Labels: enhancement

#4853 Stored in source_data the information coming from the workers
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/calculators/views.py
Labels: internal

#4854 Made it possible to run a calculation only on specified sources
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/valid.py
Labels: enhancement, internal

#4855 Added a plot task_info functionality
  bin/run-demos.sh
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: enhancement, internal

#3766 Fixed deletion of calculations
  .travis.yml
  debian/changelog
  openquake/commands/purge.py
  openquake/commands/reset.py
  openquake/hazardlib/tests/valid_test.py
  openquake/server/db/actions.py
Labels: bug

#4856 Removed unused mesh from EBRupture.export
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/commonlib/hazard_writers.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.xml
  openquake/qa_tests_data/event_based/mutex/expected/ses.xml
Labels: bug, internal

#4857 Refactored the GMFs importer
  openquake/calculators/base.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/views.py
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/qa_tests_data/event_based/blocksize/expected/sig-eps.csv
  openquake/qa_tests_data/event_based/case_2/expected/sig-eps.csv
Labels: bug, internal

#4858 Improved the task distribution by splitting the heavy sources on the master
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commands/show.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
Labels: internal

#4861 Included `oq plot_memory` into `oq plot`
  .travis.yml
  bin/run-demos.sh
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commands/plot_memory.py
  openquake/commonlib/source.py
Labels: internal
