Repository gem/oq-engine, pull requests merged in 2019-11, with the labels that each got.

#5265 Export the rupture bounding box in valid WKT
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
Labels: internal

#5266 Fixed `oq plot rupture_info`
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: bug

#5264 Supported generic file-reading GMPEs
  debian/changelog
  doc/adv-manual/parametric-gmpes.rst
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/valid.py
Labels: enhancement

#5267 Reverted https://github.com/gem/oq-engine/pull/5265
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: internal

#5270 Fixed QGIS integration tests
  openquake/commonlib/logictree.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: bug

#5268 Changed how the input files are saved in the datastore
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/export/__init__.py
  openquake/engine/engine.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: internal

#5271 Storing the input files after read_inputs
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/commands/restore.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/engine/engine.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/valid.py
Labels: internal

#5272 Managed GMPETables as BytesIO objects
  openquake/commonlib/logictree.py
  openquake/hazardlib/gsim/gmpe_table.py
Labels: internal

#5273 Fix CAN mosaic
  openquake/baselib/tests/datastore_test.py
  openquake/hazardlib/gsim/gmpe_table.py
Labels: bug

#5275 Added `units` attribute required by the QGIS plugin
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
Labels: enhancement

#5274 Added a method GMPE.open
  openquake/commonlib/logictree.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: internal

#5276 Restored exporting of boundary how it was
  debian/changelog
  openquake/calculators/extract.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
Labels: enhancement

#5279 Added min_mag filter to /extract/rupture_info
  bin/run-demos.sh
  openquake/calculators/extract.py
  openquake/calculators/getters.py
Labels: enhancement

#5278 Rupture serialization in TOML
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/extract.py
  openquake/commands/plot.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_15/expected/rupture_0.toml
  openquake/qa_tests_data/event_based/case_15/expected/rupture_1.toml
  openquake/qa_tests_data/event_based/case_15/scenario.ini
Labels: enhancement

#5280 Refactoring work on TOML ruptures
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/extract.py
  openquake/commands/plot.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#5281 Removed the boundary information from the CSV rupture exporter
  debian/changelog
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_23/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/event_based/mutex/expected/ruptures.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
  openquake/server/tests/views_test.py
Labels: bug, enhancement, outputs

#5283 A few small fixes
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/commands/extract.py
  openquake/commands/plot.py
  openquake/server/views.py
Labels: enhancement, internal

#5284 Implemented split_by_magnitude
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
  openquake/qa_tests_data/classical/case_15/job.ini
Labels: internal

#5285 Extended pointsource_distance to non-point sources
  openquake/hazardlib/contexts.py
Labels: performance

#5286 Added some code to estimate the effect of a rupture in single-site classical hazard
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_19/job.ini
Labels: internal, performance

#5288 Extended the preclassical calculator in the single site case
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
Labels: internal

#5289 Replaced threshold with minimum_intensity
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_19/job.ini
Labels: internal

#5290 Removed the max_radius optimization
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/job.ini
Labels: internal, performance

#5292 Cached CoeffsTable.__getitem__
  openquake/hazardlib/gsim/base.py
Labels: performance

#5293 Added view_maximum_intensity
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
Labels: internal

#5296 Forbid the instantiation of CoeffsTable in get_mean_and_stddevs
  openquake/calculators/views.py
  openquake/hazardlib/gsim/base.py
Labels: enhancement, internal

#5298 Fixed the case of duplicated sources
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
Labels: api, bug, internal

#5297 Enhanced the pointsource_distance approximation
  debian/changelog
  demos/hazard/AreaSourceClassicalPSHA/job.ini
  doc/adv-manual/common-mistakes.rst
  doc/manual/oqum/hazard/01d_config_classical.tex
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_19/job.ini
  openquake/qa_tests_data/classical/case_36/job.ini
  openquake/qa_tests_data/classical/case_39/job.ini
  openquake/qa_tests_data/classical/case_43/job.ini
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.02-PGA-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-PGA-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/poe-0.1-SA(0.025)-sid-0_Src.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_6/job.ini
  openquake/qa_tests_data/event_based/case_19/job_grid.ini
  openquake/qa_tests_data/event_based_risk/case_4/job.ini
Labels: performance

#5299 Changed from filter_split -> split_filter
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
Labels: bug

#5300 Made it possible to import a GMF.csv file with more IMTs than needed
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_10/Exposicion_Res_Tijuana.csv
  openquake/qa_tests_data/scenario_damage/case_10/__init__.py
  openquake/qa_tests_data/scenario_damage/case_10/expected/dmg_by_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_10/exposure_model.xml
  openquake/qa_tests_data/scenario_damage/case_10/fragility_ejemplo.xml
  openquake/qa_tests_data/scenario_damage/case_10/gmf-data_from_OQ.csv
  openquake/qa_tests_data/scenario_damage/case_10/job.ini
  openquake/qa_tests_data/scenario_damage/case_10/sitemesh_median_Tijuana.csv
  openquake/qa_tests_data/scenario_damage/case_10/taxonomy_mapping.csv
Labels: enhancement

#5302 Refactored a bit the ContextMaker
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: internal

#5303 Changed the source weight and added a max_weight parameter
  bin/run-demos.sh
  openquake/calculators/classical.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/base.py
Labels: internal, performance

#5291 20191004 adjustments
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/projects/__init__.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/rietbrock_edwards_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/scalerel/leonard2010.py
  openquake/hazardlib/tests/gsim/data/YA15/ya15_mean_cena.csv
  openquake/hazardlib/tests/gsim/data/projects/kappa.txt
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/yenier_atkinson_2015_test.py
Labels: enhancement

#5306 Renamed ordinal->rlz_id
  debian/changelog
  openquake/calculators/extract.py
  openquake/qa_tests_data/classical/case_18/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_10/expected/realizations.csv
  openquake/qa_tests_data/event_based/case_6/expected/realizations.csv
  openquake/qa_tests_data/scenario/case_9/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/realizations.csv
Labels: enhancement

#5301 Report (and use?) the number of visible cores, not total system cores
  openquake/baselib/parallel.py
Labels: enhancement, proposal

#5309 cpu_affinity is not available on macOS
  CONTRIBUTORS.txt
  debian/changelog
  openquake/baselib/parallel.py
Labels: bug

#5310 Renamed rupid -> rup_id in ruptures.csv
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_23/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/event_based/mutex/expected/ruptures.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement

#5311 Reduced the number of small subtasks
  openquake/calculators/classical.py
Labels: internal

#5312 Renamed rlzi->rlz_id in dmg_by_event
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_8/expected/dmg_by_event.csv
Labels: enhancement

#5305 Change export dir default behavior to current working dir
  openquake/commonlib/oqvalidation.py
Labels: proposal

#5315 Fixed the logging from a worker
  openquake/commonlib/logs.py
Labels: bug

#5317 Three subtle fixes
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#5318 Implement a plugin system for consequences
  openquake/calculators/multi_risk.py
  openquake/calculators/scenario_damage.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#5307 Get ini defaults
  debian/changelog
  doc/web-api.md
  openquake/commonlib/oqvalidation.py
  openquake/server/tests/views_test.py
  openquake/server/urls.py
  openquake/server/views.py
Labels: api

#5320 Managed case of missing calculation in /v1/calc/ID/status
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/server/views.py
Labels: api, bug

#5321 Renamed rlzi -> rlzi in the sigma-epsilon dataset and exporter
  debian/changelog
  openquake/calculators/getters.py
  openquake/qa_tests_data/event_based/blocksize/expected/sig-eps.csv
  openquake/qa_tests_data/event_based/case_2/expected/sig-eps.csv
Labels: outputs

#5322 Renamed the missing asset->asset_id
  debian/changelog
  openquake/calculators/export/loss_curves.py
  openquake/qa_tests_data/classical_risk/case_2/expected/loss_curves.csv
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-ref-a8-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-sid-1-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/loss_curves-mean.csv
Labels: enhancement

#5323 Making it possible to read generic consequence files
  openquake/baselib/hdf5.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/qa_tests_data/scenario_damage/case_9/job.ini
  openquake/risklib/read_nrml.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#5324 Added an API /v1/calc/ID/extract/num_events
  debian/changelog
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
Labels: enhancement

#5325 Added an API /v1/calc/ID/extract/gmf_data?event_id=XXX
  debian/changelog
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
Labels: enhancement

#5326 Changed the way consequence coefficients are stored
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_9/ccara_consequence_model_CARA.xml
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-1.csv
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
Labels: internal

#5328 Event based damage calculator
  debian/changelog
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/dmg_by_asset-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/dmg_by_asset-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_1/fragility.xml
  openquake/qa_tests_data/event_based_risk/case_1/job_damage.ini
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: enhancement

#5329 Speedup of classical/case_19
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_19/job.ini
Labels: internal

#5330 Removed some debugging info
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#5333 Make WebUI ACL more flexible
  openquake/server/local_settings.py.pam
  openquake/server/settings.py
  openquake/server/utils.py
  openquake/server/views.py
Labels: bug, enhancement, user interface

#5332 Upgrade to Django 2.2 to be compatible with recent SQLite
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
Labels: bug, packaging

#5331 Added a check on duplicate sites coming from the site model
  debian/changelog
  openquake/baselib/general.py
  openquake/baselib/hdf5.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/scenario/case_11/__init__.py
  openquake/qa_tests_data/scenario/case_11/exposure.csv
  openquake/qa_tests_data/scenario/case_11/exposure.xml
  openquake/qa_tests_data/scenario/case_11/job.ini
  openquake/qa_tests_data/scenario/case_11/site_model.csv
  openquake/risklib/asset.py
  utils/strip_dupl_sites
Labels: enhancement

#5335 Fixed `IntegrationDistance.__call__`
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: internal

#5336 Avoid transferring the GMFs
  openquake/calculators/base.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
Labels: enhancement

#5338 Log the number of nonzero damage fractions
  openquake/calculators/scenario_damage.py
Labels: internal

#5340 dmg_by_event from event_based_damage
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/riskmodels.py
Labels: enhancement
