Repository gem/oq-engine, pull requests merged in 2020-05, with the labels that each got.

#5793 HDF5 format for gridded sources
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/oqzip.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/sourcewriter_test.py
  openquake/qa_tests_data/classical/case_27/expected/hazard_curve.csv
  openquake/qa_tests_data/classical/case_27/source_model.hdf5
  openquake/qa_tests_data/classical/case_27/source_model.xml
  utils/gridded2hdf5
Labels: enhancement

#5795 Upgraded to pyzmq == 19.0.0
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
Labels: packaging

#5794 Changed the algorithm for the lon,lat bins
  bin/run-demos.sh
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/tests/acceptance/disagg_test.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_5/expected/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_5/expected/rlz-0-PGA-sid-0-poe-0_Lon_Lat_TRT.csv
  openquake/qa_tests_data/disagg/case_5/expected/rlz-0-PGA-sid-0-poe-0_Mag_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_6/expected/PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_6/expected/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_6/expected/rlz-1-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_6/expected/rlz-2-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
Labels: bug

#5797 Update adv-manual/risk.rst [skip CI]
  doc/adv-manual/risk.rst
Labels: documentation

#5801 Using Ubuntu Bionic on travis
  .travis.yml
Labels: internal

#5800 Added rlz_id to disagg_layer
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
Labels: enhancement

#5803 Logging the size of the disaggregation outputs
  openquake/calculators/disaggregation.py
Labels: enhancement

#5804 Extended the documentation in developing.rst
  .travis.yml
  doc/adv-manual/developing.rst
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/nrml.py
Labels: documentation

#5805 Changed /extract/disagg_layer to export a single super-large layer
  bin/run-demos.sh
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
Labels: enhancement

#5806 Distribute by IMT in disaggregation
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5807 Changed oq extract to save in .npz format
  openquake/baselib/hdf5.py
  openquake/commands/extract.py
  openquake/server/utils.py
  openquake/server/views.py
Labels: internal

#5799 Support sigmas in amplify_gmfs
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement

#5808 Special case when num_epsilon_bins=1
  debian/changelog
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_1/job.ini
Labels: performance

#5810 Fixed the QGIS tests
  openquake/baselib/hdf5.py
  openquake/commands/extract.py
  openquake/server/views.py
Labels: bug

#5811 Less monitoring in the inner loop of disagg._disaggregate
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5812 Vectorized the disaggregation formula
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5813 Raised a clear error for amplification calculations with missing intensity measure types and levels
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#5817 Refactored the disaggregation calculation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#5818 Vectorized even more disagg.disaggregate
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tom.py
Labels: performance

#5819 Distribute by magnitude bin in the disaggregation
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5820 26x speedup in extracting PMFs with a bit of numpy literacy
  debian/changelog
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5822 Fixed oq extract rupture/XXX
  openquake/commands/extract.py
Labels: bug

#5823 Added a test of (non)disaggregation for Japan
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
Labels: internal

#5824 Removed the need to set intensity_measure_types_and_levels in event based calculations with amplification
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/event_based/case_16/job.ini
Labels: bug

#5826 Simplified the management of the hazardlib contexts
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
Labels: internal

#5827 More refactoring of the hazardlib contexts
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
Labels: internal

#5828 Fixed issue with non-homogenous number of grp_ids
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
Labels: bug

#5829 Optimized the disaggregation in the case of multiple realizations
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5830 Made it possible to store the ruptures for the Japan model
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_27/expected/hazard_curve.csv
  openquake/qa_tests_data/classical/case_27/source_model.xml
Labels: internal

#5831 Supported different levels per each amplification function
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/event_based/case_16/invalid_amplification.csv
Labels: enhancement

#5833 Added error for max_sites_disagg < N
  debian/changelog
  openquake/calculators/base.py
Labels: enhancement

#5834 Added TRT information inside source_info
  openquake/calculators/tests/classical_test.py
  openquake/commands/reduce_sm.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b1-gsimltp_b1-ltr_0.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_1.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_2.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_3.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_4.csv
  openquake/qa_tests_data/classical/case_17/source_model_1.xml
  openquake/qa_tests_data/classical/case_17/source_model_2.xml
Labels: enhancement

#5836 Forbidden setting both rlz_index and num_rlzs_disagg
  openquake/calculators/disaggregation.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
Labels: enhancement

#5835 Optimized even more the disaggregation with complex logic trees
  openquake/calculators/disaggregation.py
  openquake/commonlib/logictree.py
Labels: performance

#5838 Refactored `set_rlzs_stats`
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/hazardlib/stats.py
Labels: internal

#5840 Turned utils/postrisk into a command oq recompute_losses
  openquake/commands/recompute_losses.py
Labels: internal

#5841 Raised the tolerance in some event based tests
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/event_risk_test.py
Labels: internal

#5842 Added exporter for the source loss table
  debian/changelog
  doc/faq-risk.md
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commands/recompute_losses.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/server/db/actions.py
Labels: enhancement

#5843 Some cleanup of the disaggregation
  openquake/baselib/general.py
  openquake/calculators/disaggregation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/disagg.py
Labels: internal

#5844 Added a check on ebrisk to avoid generating too many loss curves
  debian/changelog
  openquake/calculators/ebrisk.py
Labels: enhancement

#5839 New API for storing JSON information inside npz arrays
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#5846 Replaced dmg_by_asset with avg_damages-rlzs (i.e. remove stddev fields)
  openquake/calculators/base.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-contents-007.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-nonstructural-007.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-structural-007.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/dmg_by_asset-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/dmg_by_asset-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_10/expected/avg_damages-rlzs-0.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_2/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_3/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/dmg_by_asset-000.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/dmg_by_asset-001.csv
  openquake/qa_tests_data/scenario_damage/case_6/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/avg_damages-rlzs-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/avg_damages-rlzs-1.csv
  openquake/server/db/actions.py
Labels: enhancement, outputs

#5845 Replaced losses_by_asset with avg_losses-rlzs (i.e. remove stddev fields)
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/avg_losses-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/avg_losses-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_asset-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_asset-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-1.csv
  openquake/qa_tests_data/scenario_risk/case_1h/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/asset-loss.csv
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/asset-loss.csv
Labels: enhancement, outputs

#5847 Fixes bug in mixture model usage in LT with multiple GMPEs
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/base.py
  openquake/qa_tests_data/classical/case_47/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_47/expected/hazard_curve-rlz-001-PGA.csv
  openquake/qa_tests_data/classical/case_47/gmpe_logic_tree.xml
Labels: bug

#5779 Update engine-outputs.rst
  doc/engine-outputs.rst
Labels: documentation

#5848 Computed the averages correctly in even based damage
  debian/changelog
  doc/engine-outputs.rst
  doc/web-api.md
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/event_based/case_15/scenario.ini
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/dmg_by_taxon.csv
Labels: bug

#5849 Made avg_losses-rlzs and avg_damages-rlzs readable by pandas
  openquake/baselib/datastore.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
Labels: enhancement, internal

#5850 Statistics for scenario_risk and scenario_damage
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-001.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/avg_damages-000.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-rlz-001.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/server/db/actions.py
Labels: enhancement

#5852 Removed negative values from disaggregation outputs
  openquake/calculators/disaggregation.py
Labels: internal

#5853 Solved the issue of negative probabilities in disaggregation
  debian/changelog
  openquake/hazardlib/contexts.py
Labels: bug

#5855 Restored output_type=damages-rlzs
  openquake/calculators/classical_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/classical_damage_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-007.csv
  openquake/server/db/actions.py
Labels: internal

#5856 Fixed dmg_by_event exporter
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-001.csv
  openquake/qa_tests_data/scenario_damage/case_1/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_10/expected/avg_damages-0.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/avg_damages-000.csv
  openquake/qa_tests_data/scenario_damage/case_2/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_3/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_6/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/avg_damages-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/avg_damages-1.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/avg_damages-2.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/dmg_by_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/dmg_by_asset-1.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-1.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-2.csv
  openquake/qa_tests_data/scenario_damage/case_9/gmpe.xml
Labels: bug

#5857 Optimized the number of calls to `get_probability_no_exceedance` in disaggregate
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5858 Added a test for `oq extract`
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/commands/extract.py
  openquake/commands/tests/commands_test.py
Labels: internal

#5859 Collapsing nonparametric ruptures
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_24/job.ini
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/job.ini
  openquake/qa_tests_data/disagg/case_5/job.ini
Labels: enhancement

#5861 Better monitoring of disaggregation
  openquake/calculators/disaggregation.py
Labels: internal

#5862 Restored vectorization by IMT and optimized reading ruptures
  openquake/baselib/hdf5.py
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5865 Experimental visualization with stacked bar chart for `oq plot disagg`
  openquake/commands/plot.py
Labels: user interface

#5866 Refined the task weight in disaggregation
  openquake/baselib/parallel.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5868 Made hcurves and hmaps readable as DataFrames
  debian/changelog
  doc/adv-manual/developing.rst
  doc/adv-manual/extract-api.rst
  doc/adv-manual/index.rst
  doc/adv-manual/pandas.rst
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_20/job.ini
Labels: enhancement

#5870 Removed the old disagg_by_src
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
Labels: internal

#5871 Re-implemented the disagg_by_src functionality
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_11/job.ini
  openquake/qa_tests_data/classical/case_13/job.ini
  openquake/qa_tests_data/classical/case_2/job.ini
  openquake/server/db/actions.py
Labels: enhancement

#5872 More work on the disaggregation plots
  openquake/commands/plot.py
Labels: enhancement

#5873 Implemented comparison for disaggregation plots
  openquake/commands/plot.py
Labels: enhancement

#5874 Adds PGV coefficients to USGS CEUS GMPE Tables (where possible)
  debian/changelog
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_1CCSP.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_1CVSP.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_2CCSP.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_2CVSP.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_a04.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_ab14.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_ab95.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_bca10d.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_bs11.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_B_sgd02.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_Frankel.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_Graizer.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_Graizer16.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_Graizer17.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_HA15.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_PEER_EX.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_PEER_GP.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_PZCT15_M1SS.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_PZCT15_M2ES.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_SP15.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_YA15.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_1.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_10.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_11.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_12.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_13.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_14.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_15.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_16.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_17.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_2.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_3.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_4.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_5.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_6.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_7.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_8.hdf5
  openquake/hazardlib/gsim/usgs_nga_east_tables/nga_east_usgs_9.hdf5
Labels: enhancement

#5877 Logging less when saving the disaggregation outputs
  openquake/calculators/disaggregation.py
Labels: performance

#5878 Optimized the storage of the disaggregation outputs (less, bigger datasets)
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
Labels: performance

#5879 Tripled the speed of disaggregation for SGC (again)
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#5881 More work on `disagg_by_src`
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
Labels: internal

#5880 Removed some obsolete code
  openquake/calculators/base.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/qa_tests_data/ucerf/expected/hmap.rst
Labels: internal

#5883 Exported IML information in disagg_layer
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
Labels: enhancement

#5886 Fixed minimum_magnitude in UCERF
  debian/changelog
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
  openquake/qa_tests_data/ucerf/job.ini
Labels: bug

#5887 Slightly changed the weights in classical calculations
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
Labels: performance
