Repository gem/oq-engine, pull requests merged in 2020-12, with the labels that each got.

#6312 Refined the point source weighting
  openquake/commands/shell.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/source/point_test.py
Labels: bug, internal

#6313 modify dockerfile for nightly build
  .github/workflows/macos_pyapp.yml
  .github/workflows/zmq.yml
  docker/Dockerfile.devel
Labels: packaging

#6314 Moved back weight_sources in classical
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
Labels: internal

#6315 More work on the weighting of the sources
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/site.py
Labels: internal, performance

#6316 Computing the distances only once in _gen_rups
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/site_test.py
  openquake/hazardlib/tests/source/point_test.py
Labels: internal

#6318 Removed the single site approximation for BooreAtkinson2008
  openquake/hazardlib/gsim/boore_atkinson_2008.py
Labels: bug

#6317 Plotting the gridded point sources
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source/point.py
Labels: enhancement

#6319 Logging the total number of rupture contexts
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: internal

#6323 Send the light tasks last
  openquake/calculators/classical.py
Labels: performance

#6321 add actions for macOS 11.0 and update shapely==1.7.1
  .github/workflows/bigsur_pyapp.yml
  .github/workflows/docker.yml
  .github/workflows/macos_pyapp.yml
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
Labels: packaging

#6325 Extended the install.py to download the demos
  install.py
Labels: packaging

#6326 Implemented minimum_asset_loss in scenario_risk
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/scenario_risk.py
  openquake/qa_tests_data/scenario_risk/case_1/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/job_risk.ini
Labels: enhancement

#6328 Temporarily disabled check on complex fault surfaces
  openquake/hazardlib/geo/surface/complex_fault.py
Labels: bug

#6331 Speed up save poes by orders of magnitude
  openquake/calculators/classical.py
Labels: performance

#6330 Update site-associations documentation
  doc/adv-manual/asset-site-association.rst
Labels: documentation

#6332 Fixed the bug with the disappearing log
  openquake/calculators/classical.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/engine.py
Labels: bug

#6333 Now setting `ps_grid_spacing` also sets `pointsource_distance`
  openquake/calculators/tests/__init__.py
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/engine.py
Labels: enhancement

#6334 Merged `losses_by_event` inside the `event_loss_table`
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/views.py
  openquake/risklib/scientific.py
Labels: internal

#6322 This fixes a bug with the KiteSurface
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: bug

#6337 Refactored the aggregation of losses in ebrisk
  openquake/calculators/ebrisk.py
  openquake/risklib/scientific.py
Labels: internal

#6342 Implemented InsuredLosses as SecondaryLosses
  openquake/calculators/ebrisk.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/scientific.py
Labels: internal

#6343 Explained how the rupture sampling works
  .github/workflows/python-app.yml
  doc/adv-manual/rupture-sampling.rst
  doc/faq-hazard.md
  openquake/hazardlib/source/base.py
Labels: documentation

#6339 add GDAL manylinux1 to requirements files
  .github/workflows/oq-role.yml
  .github/workflows/playbook_ansible.yml
  .github/workflows/python.yml
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
Labels: packaging

#6338 Lan2019
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_RJB_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_Rrup_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_Rrup_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/lanzano_2019_test.py
Labels: enhancement

#6344 Changed source splitting a bit
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: internal, performance

#6345 Renamed serial->seed
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
Labels: internal

#6329 Fixed oq nrml_to
  debian/changelog
  doc/adv-manual/oq-commands.rst
  openquake/commands/nrml_to.py
  openquake/commands/plot_sites.py
Labels: bug, documentation

#6346 Fixed the WebUI tests
  openquake/engine/engine.py
  openquake/server/db/actions.py
  openquake/server/tests/views_test.py
  openquake/server/views.py
Labels: bug, internal

#6349 Made the loss type occupants a bit less special
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/scenario_risk.py
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6351 Replaced precision error with a warning in scenario_risk
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/scenario_risk_test.py
Labels: investigation

#6350 Refactored the code underlying the association taxonomy->loss_type->imt
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#6352 Fixed 32bit rounding issues in scenario_risk
  debian/changelog
  openquake/calculators/scenario_risk.py
  openquake/calculators/views.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
Labels: enhancement

#6348 GitHub actions for Mac OS Catalina and Big Sur
  .github/workflows/bigsur_pyapp.yml
  .github/workflows/macos_pyapp.yml
Labels: internal

#6259 Added a check for zero coefficient of variations for the Beta distribution
  debian/changelog
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: bug, enhancement

#6354 Added view avg_gmf to event_based_risk and saved avg_gmf in ebrisk
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
Labels: internal

#6355 Renamed risk_imtls->risk_imts
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/oqvalidation_test.py
Labels: internal

#6356 Fixed the behavior for ignore_covs=true
  debian/changelog
  openquake/qa_tests_data/scenario_risk/case_2/expected/agg.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/riskmodels_test.py
Labels: bug

#6358 Added a limit to the maximum number of aggregation tags in ebrisk
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/scientific.py
Labels: internal

#6359 Enhanced DataStore.read_df to perform selections on pandas-friendly datasets
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
Labels: performance

#6360 Using pandas to save in the GEM csv format
  openquake/calculators/export/hazard.py
  openquake/commonlib/tests/writers_test.py
  openquake/commonlib/writers.py
Labels: performance

#6361 Added a method `DataStore.create_dframe`
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/scenario_damage.py
Labels: enhancement, internal

#6363 Simplifying a bit the aggregation
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/commands/recompute_losses.py
Labels: internal

#6364 Storing agg_keys
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/risklib/asset.py
Labels: internal

#6366 Fixed zero losses in agg_losses.csv and renamed oq recompute_losses -> oq reaggregate
  debian/changelog
  doc/adv-manual/oq-commands.rst
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/reaggregate.py
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
Labels: bug, outputs

#6365 Storing agg_losses/tot_losses at fixed dimensionality
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
Labels: internal

#6367 Using more pandas in the exporters
  openquake/baselib/hdf5.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commands/show.py
  openquake/commonlib/writers.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
Labels: outputs

#6369 Fixed the dimensionality of the agg_curves too
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: internal

#6377 Optimized writing and reading the agg_loss_table
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_losses-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/tot_curves-rlzs.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/risklib/scientific.py
Labels: performance

#6378 Fixed tot_losses/tot_losses exporters
  openquake/calculators/post_risk.py
  openquake/calculators/tests/__init__.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_losses-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/tot_curves-rlzs.csv
Labels: bug, performance

#6379 Improved the aggregation performance
  openquake/calculators/post_risk.py
  openquake/risklib/scientific.py
Labels: performance

#6380 Some cleanup in the aggregation procedure
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/risklib/asset.py
Labels: internal

#6381 Fixed the case of all zero covs for the beta distribution
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: bug

#6382 Fully restored the functionality of `oq reaggregate`
  openquake/calculators/ebrisk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/risklib/asset.py
Labels: internal

#6370 Fixes for multi fault ruptures with KiteSurfaces
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
Labels: bug

#6385 Removed tot_losses-XXX
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/server/db/actions.py
Labels: outputs

#6386 Fixed the event loss table exporter
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/job_eb.ini
Labels: bug

#6387 Removed the tot_curves-XXX outputs
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/outputs/tot_curves-rlzs.csv
  openquake/calculators/tests/outputs/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves-rlzs.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/server/db/actions.py
Labels: outputs

#6353 Small changes to CI for macos
  .github/workflows/macos_pyapp.yml
  requirements-py36-macos.txt
  requirements-py37-macos.txt
  requirements-py38-macos.txt
Labels: internal

#6384 Extending support for the Kite Fault Source
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/source/kite_fault.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/source/kite_fault_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_61/__init__.py
  openquake/qa_tests_data/classical/case_61/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_61/gmcLT.xml
  openquake/qa_tests_data/classical/case_61/job.ini
  openquake/qa_tests_data/classical/case_61/sscLT.xml
  openquake/qa_tests_data/classical/case_61/ssmkf.xml
Labels: enhancement

#6388 Fixed QGIS integration test
  openquake/server/views.py
Labels: bug

#6389 Perform the disaggregation checks before starting the classical part
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
Labels: enhancement

#6390 Another QGIS fix
  bin/run-demos.sh
  openquake/calculators/base.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/views.py
  openquake/commands/show.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
Labels: bug

#6391 Fixed inconsistency in the agg_curves exporter
  debian/changelog
  openquake/baselib/datastore.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
Labels: outputs

#6394 Unified agg_losses-XXX outputs between ebrisk, event_based_risk and scenario_risk
  debian/changelog
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_risk/case_1/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_1h/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_2/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/agg_loss.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_0.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_1.csv
  openquake/qa_tests_data/scenario_risk/case_8/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_8/job.ini
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/agg_loss.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: outputs

#6393 Made it possible to specify the engine version in the installation script
  install.py
Labels: enhancement, packaging

#6395 Removed loss_maps output from event_based_risk
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/risklib/scientific.py
Labels: outputs

#6396 Making event_based_risk and scenario_risk more similar
  openquake/baselib/datastore.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_risk.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#6397 Unified event_based_risk with scenario_risk
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/portfolio_loss.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.15.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.5.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
Labels: enhancement, internal

#6398 Implemented aggregate_by=site_id
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_7/job.ini
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: enhancement

#6399 Support for aggregate_by=id
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.15.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.5.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_1g/job_risk.ini
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: enhancement

#6400 Accepted 2**32 tags
  openquake/calculators/ebrisk.py
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: enhancement

#6401 Using pandas in .get_gmfdata()
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/gmf.py
  openquake/risklib/riskinput.py
  openquake/sep/classes.py
Labels: internal

#6403 Some fixes for the event_based_risk/scenario unification
  openquake/calculators/base.py
  openquake/calculators/scenario_risk.py
  openquake/risklib/riskinput.py
Labels: internal

#6404 Using a dictionary with double keys for the AggLossTable
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/scientific.py
Labels: performance

#6406 Run the hazardlib tests at each PR, not at each merge in master
  .github/workflows/demos.yml
  .github/workflows/python-app.yml
Labels: internal

#6408 Fixed agg_losses output attribute K
  bin/run-demos.sh
  openquake/calculators/post_risk.py
Labels: bug, internal

#6409 Storing the shape_descr as a json
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commands/show.py
  openquake/hazardlib/stats.py
Labels: internal

#6410 Replacing DictArray
  openquake/baselib/general.py
Labels: internal

#6407 Fixes edge calculation for kite fault
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: WIP, bug

#6411 Made sure DictArray is not empty
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/event_based/case_25/job_common.ini
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/scenario/case_10/job.ini
  openquake/qa_tests_data/scenario/case_11/job.ini
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6412 Splitting the HW term
  openquake/hazardlib/gsim/abrahamson_2014.py
Labels: internal

#6413 Simplified DictArray
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/reportwriter.py
  openquake/calculators/views.py
  openquake/commands/compare.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#6414 Storing the CompositeRiskModel as a DataFrame
  openquake/baselib/datastore.py
  openquake/baselib/general.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/risklib/read_nrml.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6415 Reading the CompositeRiskModel dataframe
  openquake/baselib/hdf5.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6416 Removed now unused code
  openquake/calculators/base.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal
