Repository gem/oq-engine, pull requests merged in 2020-09, with the labels that each got.

#6044 Distribution by GSIM
  debian/changelog
  openquake/calculators/getters.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario/case_9/gmf.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/avg_losses-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/avg_losses-rlz-001.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/avg_damages-mean.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
Labels: enhancement

#6045 Fixed a 32 bit/64 bit bug in `oq prepare_site_model when sites.csv is the same as the vs30.csv file
  debian/changelog
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
Labels: bug

#6047 Initial work for the integration of the secondary perils
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/sec_perils.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/event_based/case_26/__init__.py
  openquake/qa_tests_data/event_based/case_26/as_model_full.xml
  openquake/qa_tests_data/event_based/case_26/exposure.xml
  openquake/qa_tests_data/event_based/case_26/exposure_res.csv
  openquake/qa_tests_data/event_based/case_26/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based/case_26/job.ini
  openquake/qa_tests_data/event_based/case_26/report.rst
  openquake/qa_tests_data/event_based/case_26/site_model.csv
  openquake/qa_tests_data/event_based/case_26/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based/case_26/vs30.csv
Labels: enhancement

#6048 Moved openquake.sep into the engine
  .travis.yml
  debian/changelog
  openquake/sep/__init__.py
  openquake/sep/calculators.py
  openquake/sep/landslide/__init__.py
  openquake/sep/landslide/common.py
  openquake/sep/landslide/newmark.py
  openquake/sep/landslide/rotational.py
  openquake/sep/liquefaction/__init__.py
  openquake/sep/liquefaction/lateral_spreading.py
  openquake/sep/liquefaction/liquefaction.py
  openquake/sep/tests/data/Dn_set.nc
  openquake/sep/tests/data/Dn_single.nc
  openquake/sep/tests/data/cohesion.tif
  openquake/sep/tests/data/dem_small.tif
  openquake/sep/tests/data/friction.tif
  openquake/sep/tests/data/pga.nc
  openquake/sep/tests/data/relief_out.tif
  openquake/sep/tests/data/saturation.tif
  openquake/sep/tests/data/slope_small.tif
  openquake/sep/tests/data/test_events.csv
  openquake/sep/tests/data/test_gmfs.csv
  openquake/sep/tests/data/test_pga.nc
  openquake/sep/tests/data/test_ruptures.csv
  openquake/sep/tests/data/test_site_params.csv
  openquake/sep/tests/data/test_sites.csv
  openquake/sep/tests/landslide/test_common.py
  openquake/sep/tests/landslide/test_newmark.py
  openquake/sep/tests/liquefaction/test_lateral_spreading.py
  openquake/sep/tests/liquefaction/test_liquefaction.py
  openquake/sep/tests/test_calculators.py
  openquake/sep/tests/test_sep_suite_1.py
  openquake/sep/tests/test_sep_suite_2.py
  openquake/sep/tests/test_utils.py
  openquake/sep/utils.py
  requirements-extra-py38-linux64.txt
  requirements-py38-linux64.txt
  setup.py
Labels: enhancement

#6049 add wheel for GDAL 3.1.2 on manylinux2014
  requirements-py38-linux64.txt
Labels: packaging

#6052 Managed the case of missing GDAL
  openquake/sep/calculators.py
  openquake/sep/tests/test_calculators.py
  openquake/sep/tests/test_sep_suite_1.py
  openquake/sep/tests/test_utils.py
  openquake/sep/utils.py
Labels: packaging

#6053 Made it possible to redefine ``GMPE.__str__``
  openquake/commonlib/logictree.py
Labels: bug

#6050 Optimized scenario_damage for the case of many sites
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/scenario_damage.py
Labels: performance

#6054 Added check for missing intensity_measure_types in event based
  openquake/commonlib/oqvalidation.py
Labels: internal

#6055 Added flag `oq engine --run --many`
  debian/changelog
  doc/adv-manual/common-mistakes.rst
  openquake/commands/engine.py
  openquake/commands/tests/commands_test.py
Labels: internal

#6057 Removed unused now redundant code
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/sourceconverter.py
Labels: internal

#6058 Fixed bug in eri_by_ltp
  openquake/commonlib/logictree.py
Labels: bug

#6059 Fixed multirun syntax
  debian/changelog
  openquake/commands/engine.py
Labels: internal

#6060 Fixed realization sampling
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: internal

#6061 Removed wrong docstring
  openquake/calculators/base.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_curve-max-SA(0.1).csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_curve-std-SA(0.1).csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-max.csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
  openquake/qa_tests_data/classical/case_15/job.ini
  openquake/qa_tests_data/classical/case_15/source_model_2.xml
  openquake/qa_tests_data/classical/case_15/source_model_logic_tree.xml
Labels: documentation

#6062 Avoided instantiating the source_model_lt multiple times
  openquake/commonlib/readinput.py
Labels: internal

#6063 Removed a wrong assert in get_eids_by_rlz
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/source/rupture.py
Labels: bug, internal

#6064 Added an example of calc_by_rlz
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/classical/case_15/calc_by_rlz.py
Labels: internal

#6041 Added Stewart et al. (2016) GMPE
  openquake/hazardlib/gsim/stewart_2016.py
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CAL_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_CHN_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15/SBSA15_JPN_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/stewart_2016_test.py
Labels: enhancement

#6065 Improved sending/saving of tasks in scenario_risk and damage
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/engine/engine.py
Labels: performance

#6066 Small refactoring of the RiskInputs
  openquake/calculators/base.py
Labels: internal

#6068 Fix for the sourcewriter
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
Labels: bug

#6069 Reading less from the datastore for gmf calculations
  openquake/calculators/base.py
  openquake/calculators/getters.py
Labels: performance

#6067 replaced 'doc/installing/overview.md' occurences with 'doc/installing/README.md'
  README.md
  doc/manual/oqum/introduction.tex
Labels: bug, documentation

#6070 Improved Pandas support
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
Labels: internal

#6071 Removed the GMF npz exporter
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commands/extract.py
Labels: enhancement

#6074 Added /extract/relevant_events
  debian/changelog
  openquake/baselib/datastore.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement

#6075 Added test for landslides
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/event_based/case_26/__init__.py
  openquake/qa_tests_data/event_based/case_26/as_model_full.xml
  openquake/qa_tests_data/event_based/case_26/cali_newmark_decimated.csv
  openquake/qa_tests_data/event_based/case_26/exposure.xml
  openquake/qa_tests_data/event_based/case_26/exposure_res.csv
  openquake/qa_tests_data/event_based/case_26/gmmLT_2019.xml
  openquake/qa_tests_data/event_based/case_26/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based/case_26/job.ini
  openquake/qa_tests_data/event_based/case_26/report.rst
  openquake/qa_tests_data/event_based/case_26/site_model.csv
  openquake/qa_tests_data/event_based/case_26/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based/case_26/ssm/int/int_col_50km.xml
  openquake/qa_tests_data/event_based/case_26/ssmLT_2019.xml
  openquake/qa_tests_data/event_based/case_26/vs30.csv
  openquake/sep/classes.py
Labels: enhancement, internal

#6077 Documented gmvs_to_poes
  doc/adv-manual/pandas.rst
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based/case_1/expected/gsim_by_imt.csv
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_1/job.ini
  openquake/qa_tests_data/event_based/case_1/source_model.xml
  openquake/qa_tests_data/event_based/case_3/job.ini
Labels: documentation

#6078 Logging the time needed to send the data
  openquake/baselib/parallel.py
Labels: performance

#6013 Manual 3.10 Part 1 – Event based damage calculator
  doc/adv-manual/asset-site-association.rst
  doc/docker/advanced.md
  doc/docker/cluster.md
  doc/docker/single.md
  doc/faq-cluster.md
  doc/faq.md
  doc/hardware-suggestions.md
  doc/installing/README.md
  doc/installing/development-windows.md
  doc/installing/development.md
  doc/installing/docker.md
  doc/installing/fedora-nightly.md
  doc/installing/fedora.md
  doc/installing/linux-generic.md
  doc/installing/rhel-nightly.md
  doc/installing/rhel.md
  doc/installing/server.md
  doc/installing/tools.md
  doc/installing/ubuntu-nightly.md
  doc/installing/ubuntu.md
  doc/installing/windows.md
  doc/manual/figures/risk/io-structure-event-based-damage.pdf
  doc/manual/oq-manual.tex
  doc/manual/oqum/glossary.tex
  doc/manual/oqum/help.txt
  doc/manual/oqum/risk/00_intro.tex
  doc/manual/oqum/risk/00_workflow_event_based_damage.tex
  doc/manual/oqum/risk/00_workflow_event_based_risk.tex
  doc/manual/oqum/risk/02_config.tex
  doc/manual/oqum/risk/02_config_event_based_damage.tex
  doc/manual/oqum/risk/02_export.tex
  doc/manual/oqum/risk/04_demos.tex
  doc/manual/oqum/risk/04_demos_event_based_damage.tex
  doc/manual/oqum/risk/verbatim/config_event_based_damage.ini
  doc/requirements.md
  doc/running/server.md
  doc/running/unix.md
  doc/running/windows.md
  doc/testing.md
  doc/upgrading/rhel.md
  doc/upgrading/ubuntu.md
Labels: WIP, documentation

#6079 Raised the limit on the asset ID from 20 to 50 characters
  debian/changelog
  openquake/hazardlib/valid.py
  openquake/risklib/asset.py
Labels: enhancement

#6080 Changed /extract/events to return the relevant events
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement

#6083 Fixed a bug with site models containing non-float parameters
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
Labels: bug

#6085 Documented the magnitude-dependent distance and a fix for event based
  doc/adv-manual/common-mistakes.rst
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_14/job.ini
Labels: bug, documentation

#6086 ￼Fixed issue when saving a sitecol with string fields in npz format
  openquake/baselib/hdf5.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/multi_risk_test.py
  openquake/commands/extract.py
  openquake/risklib/asset.py
  openquake/server/tests/views_test.py
Labels: bug, enhancement

#6088 Small refactoring of the risk models
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#6089 Added test of liquefaction
  openquake/baselib/hdf5.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/qa_tests_data/event_based/case_26/liquefaction_sites.csv
  openquake/sep/classes.py
  openquake/sep/liquefaction/liquefaction.py
Labels: enhancement

#6090 Extract asset_risk as json
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/server/views.py
Labels: bug

#6092 Refactored the management of risk functions
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#6094 Added a general way to store pickled objects in the cache file
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/classical/case_13/job.ini
Labels: internal

#6096 Storing the CompositeRiskModel on the cache file.
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
  openquake/risklib/riskinput.py
Labels: performance

#6097 Reading the srcfilter from the workers even in the GMF calculators
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
Labels: internal

#6098 Logging info about the mean portfolio loss
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/portfolio_loss.txt
Labels: enhancement

#6091 Added more liquefaction classes
  debian/changelog
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/sep/classes.py
  openquake/sep/liquefaction/lateral_spreading.py
Labels: enhancement

#6099 Whats new for engine 3.10
  doc/whats-new.md
Labels: documentation

#6100 Manual: Describe change in scenario damage algorithm
  doc/manual/oqum/risk/00_workflow_event_based_damage.tex
  doc/manual/oqum/risk/00_workflow_scenario_damage.tex
  doc/manual/oqum/risk/00_workflow_scenario_risk.tex
  doc/manual/oqum/risk/01a_exposure.tex
  doc/manual/oqum/risk/02_config_event_based_damage.tex
  doc/manual/oqum/risk/verbatim/input_exposure_cagg.csv
Labels: documentation

#6101 Pandas-friendly GMFs
  doc/adv-manual/pandas.rst
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/event_based/blocksize/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/gsim_by_imt.csv
  openquake/qa_tests_data/event_based/case_13/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_18/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_19/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/minimum-intensity-gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_22/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_4a/expected/gmf-data.csv
  openquake/qa_tests_data/scenario/case_1/BooreAtkinson2008_gmf.csv
  openquake/qa_tests_data/scenario/case_12/gmf.csv
  openquake/qa_tests_data/scenario/case_9/gmf.csv
  openquake/qa_tests_data/scenario_damage/case_10/expected/avg_damages-0.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/gmf-FromFile.csv
  openquake/risklib/riskinput.py
Labels: enhancement

#6102 Final unification of scenario_damage and event_based_damage
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/scenario_damage/case_5a/expected/dmg_by_taxon.csv
Labels: internal

#6104 Added the ability to pass a slice to `dstore.read_df`
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
Labels: enhancement
