Repository gem/oq-engine, pull requests merged in 2020-06, with the labels that each got.

#5889 Cleaning
  openquake/hazardlib/site_amplification.py
Labels: internal

#5882 Documented how to extract the magnitude-frequency distribution in event based
  doc/adv-manual/pandas.rst
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
Labels: documentation

#5890 Added a warning about suspiciously large complex fault sources
  openquake/calculators/base.py
  openquake/calculators/classical.py
Labels: enhancement

#5894 disagg_by_src with MultiPointSources
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5895 Formatting edits to risk-features.rst
  doc/adv-manual/risk-features.rst
Labels: documentation

#5896 Fix bug in ShakeMaps ('events' not found)
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
Labels: bug

#5897 Fixed a small bug in `oq show hcurves-stats`
  openquake/baselib/hdf5.py
Labels: bug, internal

#5898 Removed lines of code
  openquake/baselib/hdf5.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commands/plot.py
  openquake/qa_tests_data/classical/case_10/expected/hazard_curve-smltp_b1_b3-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_15/job.ini
Labels: internal

#5899 Fixed seed in KijkoSmitTest
  openquake/hmtk/tests/seismicity/occurrence/kijko_smit_test.py
Labels: internal

#5900 Log the maximum value reached by the hazard maps
  openquake/calculators/classical.py
Labels: enhancement

#5902 Solved Bucaramanga issue
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/classical/case_29/expected/hazard_curve-PGA.csv
Labels: bug

#5903 Make sure the sum of probabilities is exactly 1 in valid.pmf
  openquake/hazardlib/valid.py
Labels: internal

#5904 Fixed a TypeError in ``oq run --params``
  openquake/commands/run.py
  openquake/hazardlib/valid.py
Labels: internal

#5905 Fixed Sphinx docs
  doc/sphinx/openquake.baselib.rst
  doc/sphinx/openquake.calculators.rst
  doc/sphinx/openquake.commands.rst
  doc/sphinx/openquake.commonlib.rst
  openquake/baselib/general.py
  openquake/baselib/parallel.py
  openquake/calculators/disaggregation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/tromans_2019.py
  openquake/hazardlib/sourceconverter.py
Labels: documentation

#5906 Fixed the Popoyan bug
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_49/__init__.py
  openquake/qa_tests_data/classical/case_49/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_49/expected/hcurves-SA(0.21).csv
  openquake/qa_tests_data/classical/case_49/expected/hcurves-SA(1.057).csv
  openquake/qa_tests_data/classical/case_49/expected/uhs.csv
  openquake/qa_tests_data/classical/case_49/gmmLT.xml
  openquake/qa_tests_data/classical/case_49/job.ini
  openquake/qa_tests_data/classical/case_49/saf_popayan.csv
  openquake/qa_tests_data/classical/case_49/site_model.xml
  openquake/qa_tests_data/classical/case_49/ssm/as/area_source_CC_00.xml
  openquake/qa_tests_data/classical/case_49/ssmLT.xml
Labels: bug

#5907 Added a view extreme_sites
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.csv
Labels: enhancement

#5909 Added an extractor for disagg_by_src
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#5910 Restored scenario_damage with fractional asset number
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/scenario_damage/case_1c/expected/dmg_by_event.csv
  openquake/risklib/riskmodels.py
Labels: enhancement

#5916 Extended `oq nrml_to_csv` to nonparametric sources
  openquake/commands/nrml_to_csv.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5911 Called `check_complex_fault` when serializing the source in XML
  debian/changelog
  openquake/hazardlib/sourcewriter.py
Labels: enhancement

#5917 Fixed random seed in a few HMTK tests
  openquake/hmtk/tests/seismicity/test_seismicity_utils.py
Labels: bug, internal

#5918 Conversion for characteristic fault sources
  openquake/commands/nrml_to_csv.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5920 Using csv.writer in csv_writer
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commands/nrml_to_csv.py
  openquake/commands/show.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/writers.py
Labels: internal

#5919 Added test for oq nrml_to_csv
  debian/changelog
  openquake/commands/nrml_to_csv.py
  openquake/commands/tests/commands_test.py
Labels: internal

#5921 Fixed the WKT conversion
  openquake/commands/nrml_to_csv.py
  openquake/commonlib/writers.py
  openquake/hazardlib/geo/polygon.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/geo/polygon_test.py
  openquake/hmtk/tests/parsers/source_models/nrml_04_parser_test.py
Labels: internal

#5922 Supported year and ses_id >= 65536 in event based
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/qa_tests_data/event_based/case_1/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/event_based/case_1/job.ini
Labels: bug

#5923 Fixed `oq show oqparam`
  openquake/commands/show.py
  openquake/commands/tests/commands_test.py
Labels: enhancement

#5924 Implemented `oq nrml_to gpkg`
  debian/changelog
  openquake/commands/nrml_to.py
  openquake/commands/nrml_to_csv.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/geo/packager.py
  openquake/hazardlib/geo/polygon.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5926 Installing fiona in Travis
  .travis.yml
Labels: internal

#5927 Changed the exposure in case_6c
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_6c/exposure_model.csv
Labels: internal

#5929 Removed unneeded quotes from some risk exports
  openquake/commonlib/util.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/scenario_damage/case_1/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_10/expected/avg_damages-0.csv
Labels: enhancement, outputs

#5930 Simplified a bit the rupture storage
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#5931 Further simplification of the rupture storage
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_risk_test.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#5932 Full CSV format for the ruptures
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
  openquake/commands/extract.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/commonlib/writers.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#5935 Changed the rlz->events association in scenario
  debian/changelog
  openquake/calculators/scenario.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/calc.py
Labels: enhancement

#5936 Added warning against numeric errors in scenario_damage and event_based_damage
  debian/changelog
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-001.csv
Labels: bug, enhancement

#5934 Add demo for event_based_damage calculator #5933
  debian/changelog
  demos/risk/EventBasedDamage/README.md
  demos/risk/EventBasedDamage/consequences_by_taxonomy.csv
  demos/risk/EventBasedDamage/exposure_model.csv
  demos/risk/EventBasedDamage/exposure_model.xml
  demos/risk/EventBasedDamage/gmpe_logic_tree.xml
  demos/risk/EventBasedDamage/job.ini
  demos/risk/EventBasedDamage/site_model.csv
  demos/risk/EventBasedDamage/source_model.xml
  demos/risk/EventBasedDamage/source_model_logic_tree.xml
  demos/risk/EventBasedDamage/structural_fragility_model.xml
  openquake/baselib/general.py
  openquake/calculators/scenario_damage.py
  openquake/risklib/riskinput.py
Labels: documentation

#5939 Fixed a bug in event based when a rupture occurs more than 65535 times
  debian/changelog
  openquake/hazardlib/calc/stochastic.py
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
Labels: bug

#5940 Added a test for extract_ruptures
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
Labels: enhancement, internal

#5941 Added multiplicity field to rupture CSV
  openquake/calculators/extract.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_15/expected/rupture_0.toml
  openquake/qa_tests_data/event_based/case_15/expected/rupture_1.toml
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
Labels: enhancement

#5942 Implemented multi-rupture scenario calculator
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_13/__init__.py
  openquake/qa_tests_data/scenario/case_13/gmpe_logic_tree.xml
  openquake/qa_tests_data/scenario/case_13/job.ini
  openquake/qa_tests_data/scenario/case_13/ruptures.csv
  openquake/qa_tests_data/scenario/case_13/sites.csv
Labels: enhancement

#5943 Clarify input parameters for continuous fragility functions
  doc/manual/oqum/risk/01b_fragility.tex
Labels: documentation

#5944 Removed TOML ruptures
  doc/adv-manual/special-features.rst
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_15/expected/rupture_0.toml
  openquake/qa_tests_data/event_based/case_15/expected/rupture_1.toml
  utils/srcs_to_rups
Labels: internal, outputs

#5945 Removed RuptureSerializer
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
Labels: internal

#5946 Fixed `noDamageLimit` not being honored in continuous fragility functions
  debian/changelog
  openquake/qa_tests_data/classical_damage/case_2a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_2b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_3a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_5a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_6b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-007.csv
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: bug

#5947 Calc
  openquake/calculators/extract.py
  openquake/commands/extract.py
Labels: enhancement

#5948 Added a test for post_risk
  openquake/calculators/event_based.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/event_based_risk/recompute/__init__.py
  openquake/qa_tests_data/event_based_risk/recompute/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/recompute/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/recompute/job.ini
  openquake/qa_tests_data/event_based_risk/recompute/ruptures.csv
  openquake/qa_tests_data/event_based_risk/recompute/site_model.csv
  openquake/qa_tests_data/event_based_risk/recompute/structural_vulnerability.xml
Labels: internal

#5949 Implemented post-aggregation of loss curves
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/recompute_losses.py
  openquake/qa_tests_data/event_based_risk/recompute/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/recompute/job.ini
  openquake/qa_tests_data/event_based_risk/recompute/site_model.csv
  openquake/risklib/scientific.py
Labels: enhancement

#5950 Logging an error for duplicate sources
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/base.py
Labels: enhancement, internal

#5951 Added csm_cache functionality
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_1/job.ini
Labels: internal

#5953 Simplified get_checksum32
  openquake/calculators/tests/classical_test.py
  openquake/commands/engine.py
  openquake/commonlib/readinput.py
Labels: internal

#5954 Update minimum_intensity documentation in manual
  doc/manual/oqum/risk/02_config_event_based_risk.tex
Labels: documentation

#5955 Small fixes to get_composite_source_model
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
Labels: internal

#5957 Changed `oq engine --reuse-hazard` to just reuse the source model
  debian/changelog
  openquake/commands/engine.py
  openquake/commands/tests/commands_test.py
Labels: internal
