Repository gem/oq-engine, pull requests merged in 2020-11, with the labels that each got.

#6183 Chao20
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/tests/gsim/chao_2020_test.py
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020Asc_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020Asc_MEAN2.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020Asc_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020SInter_MEAN2.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CHAO20/ChaoEtAl2020SSlab_STDDEV.csv
Labels: enhancement

#6214 Optimized get_poes
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_function_test.py
Labels: performance

#6215 20201101 double truncated
  debian/changelog
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/tests/mfd/truncated_gr_test.py
Labels: enhancement

#6217 Fixed the GMF exporter for secondary perils
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/event_based_test.py
Labels: bug

#6220 Moved UCERF point sources in a different group
  openquake/calculators/classical.py
  openquake/commonlib/source_reader.py
Labels: internal

#6221 Raised an error for soil_intensities with amplification_method != convolution
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#6222 Removed some unused code
  openquake/commonlib/calc.py
  openquake/commonlib/logictree.py
Labels: internal

#6224 Refactored UcerfFilter
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/ucerf_base.py
Labels: internal

#6223 Avoided too many readings in UCERF
  openquake/calculators/classical.py
  openquake/calculators/ucerf_base.py
Labels: performance

#6226 Removed UCERF filtering
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_base.py
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: performance

#6227 Small renaming in UCERF
  openquake/calculators/ucerf_base.py
Labels: internal

#6225 Add two methods to the modifiable GMPE
  debian/changelog
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
Labels: enhancement

#6228 Avoided reading data from the workers in UCERF classical
  openquake/calculators/ucerf_base.py
  openquake/commonlib/source_reader.py
Labels: enhancement, performance

#6232 Changed `gsim.get_mean_std` to accept multiple contexts
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
Labels: internal

#6234 Fixed bug when computing the damage distributions per asset and event
  debian/changelog
  openquake/calculators/scenario_damage.py
Labels: bug

#6231 Implemented `truncGutenbergRichterMFD` from slip rate and rigidity
  debian/changelog
  openquake/hazardlib/mfd/multi_mfd.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/source_model/complex-fault-source.xml
  openquake/hazardlib/tests/source_model/source_with_slip_rate.xml
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: enhancement

#6230 Phung20
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020Asc_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020Asc_MEAN2.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020Asc_MEAN3.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020Asc_MEAN4.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SInter_MEAN2.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SInter_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SInter_STDDEV2.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PHUNG20/PhungEtAl2020SSlab_MEAN2.csv
  openquake/hazardlib/tests/gsim/phung_2020_test.py
Labels: enhancement

#6233 Pandas-friendly storage for dd_data
  .github/workflows/python-app.yml
  debian/changelog
  doc/adv-manual/developing.rst
  openquake/baselib/datastore.py
  openquake/calculators/base.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/commands/run.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: enhancement, outputs

#6238 Fixed the portfolio_damage_error view
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/scenario_damage/case_4b/expected/portfolio_damage.rst
Labels: bug

#6240 Removed `idx` field from the storage of the classical ruptures
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#6235 Adding the `TruncatedGRFromSlipAbsolute` uncertainty type
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_058/__init__.py
  openquake/qa_tests_data/classical/case_058/gmcLT.xml
  openquake/qa_tests_data/classical/case_058/job.ini
  openquake/qa_tests_data/classical/case_058/job_case01.ini
  openquake/qa_tests_data/classical/case_058/job_case02.ini
  openquake/qa_tests_data/classical/case_058/source_model.xml
  openquake/qa_tests_data/classical/case_058/source_model_case02.xml
  openquake/qa_tests_data/classical/case_058/sscLT.xml
  openquake/qa_tests_data/classical/case_058/sscLTcase01.xml
  openquake/qa_tests_data/classical/case_058/sscLTcase02.xml
Labels: enhancement

#6241 Changed the classical rupture storage to be pandas-friendly
  debian/changelog
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#6243 Upgraded to h5py 2.10.0
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/contexts.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  setup.py
Labels: packaging

#6245 Reduced the data storage required for disaggregation
  debian/changelog
  openquake/calculators/classical.py
Labels: bug, performance

#6246 Reduced the data storage in classical ruptures
  openquake/calculators/classical.py
Labels: performance

#6247 Pandas-friendly classical rupture storage
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
Labels: WIP, internal, performance

#6248 Store `src_id` in the contexts
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
Labels: enhancement, internal

#6249 Added a command `oq compare rups calc1 calc2`
  openquake/commands/compare.py
Labels: internal

#6250 Fixed bug in the SourceConverter in presence of slipRate
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_058/source_model.xml
Labels: bug

#6253 Exporting the secondary intensities
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement, outputs, performance

#6252 Added a test for UCERF multiplanar surfaces
  openquake/calculators/ucerf_base.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/tests/geo/surface/msurface18.csv
  openquake/hazardlib/tests/geo/surface/msurface19.csv
  openquake/hazardlib/tests/geo/surface/msurface20.csv
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: internal

#6257 Introduced the environment variable OQ_REDUCE
  debian/changelog
  openquake/commands/run.py
  openquake/commonlib/readinput.py
Labels: internal

#6256 Removed parallel tiling and more source splitting
  openquake/calculators/classical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_49/expected/uhs.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(0.2).csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(2.0).csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
Labels: internal

#6258 Moved the parameter `num_cores` into openquake.cfg
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
Labels: bug

#6244 Ansible Role and github action
  .github/workflows/ansible.yml
  ansible/oqengine/.travis.yml
  ansible/oqengine/README.md
  ansible/oqengine/defaults/main.yml
  ansible/oqengine/files/db_server.bash
  ansible/oqengine/files/py_ver.py
  ansible/oqengine/handlers/main.yml
  ansible/oqengine/meta/main.yml
  ansible/oqengine/molecule/default/Dockerfile.j2
  ansible/oqengine/molecule/default/converge.yml
  ansible/oqengine/molecule/default/files/job.zip
  ansible/oqengine/molecule/default/molecule.yml
  ansible/oqengine/molecule/default/tests/conftest.py
  ansible/oqengine/molecule/default/tests/test_default.py
  ansible/oqengine/molecule/default/verify.yml
  ansible/oqengine/tasks/main.yml
  ansible/oqengine/tasks/oq_to_check.yml
  ansible/oqengine/tasks/oq_to_inst.yml
  ansible/oqengine/tests/inventory
  ansible/oqengine/tests/test.yml
  ansible/oqengine/vars/main.yml
Labels: internal

#6261 Added the infrastructure for the single site optimization get_mean_std1
  .github/workflows/ansible.yml
  openquake/hazardlib/contexts.py
Labels: performance

#6262 ￼ Splitting complex fault sources by magnitude only
  debian/changelog
  demos/hazard/ComplexFaultSourceClassicalPSHA/job.ini
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/rupture_collection.py
Labels: performance

#6264 Splitting all sources in classical_split_filter
  openquake/calculators/classical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
Labels: internal

#6265 Single-site optimization for BooreAtkinson
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: enhancement, performance

#6269 Find pyexec
  .github/workflows/ansible.yml
  .github/workflows/docker.yml
  .travis/py_executables.sh
Labels: bug

#6268 Added a CollapsedPointSource class
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/source/point_test.py
Labels: enhancement

#6270 Moved splitting and filtering in the preclassical phase
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_24/job.ini
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_45/expected/hazard_curve-mean-MMI.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(0.2).csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(2.0).csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/job.ini
Labels: internal

#6271 Implemented gridding of point sources
  demos/hazard/MultiPointClassicalPSHA/job.ini
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement, performance

#6272 Storing information about the task_no in source_info
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
Labels: internal

#6273 update docker documentation
  doc/docker/cluster.md
  doc/docker/single.md
  doc/installing/docker.md
  docker/docker-compose.yml
Labels: documentation

#6274 Faster preclassical
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/polygon.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/source/point_test.py
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: performance

#6278 Reverted the BooreAtkinson2008 refactoring in https://github.com/gem/oq-engine/pull/6265
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: bug

#6279 Added a serious test for NRCan15SiteTerm
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_59/BC_Exposure.csv
  openquake/qa_tests_data/classical/case_59/BC_Exposure.xml
  openquake/qa_tests_data/classical/case_59/__init__.py
  openquake/qa_tests_data/classical/case_59/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_59/gmmLT_analytical.xml
  openquake/qa_tests_data/classical/case_59/job.ini
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneHseH_0.xml
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneHseR_1_area.xml
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneHseY_2.xml
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneRseH_3_area.xml
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneRseR_4.xml
  openquake/qa_tests_data/classical/case_59/ssm/nwHswRneRseY_5_area.xml
  openquake/qa_tests_data/classical/case_59/ssmLT.xml
  openquake/qa_tests_data/classical/case_59/vs30_a.xml
  openquake/qa_tests_data/classical/case_59/vs30_b.xml
Labels: internal

#6275 Fixed a bug in the calculation of averages losses in scenario_risk
  debian/changelog
  openquake/calculators/scenario_risk.py
  openquake/qa_tests_data/scenario_risk/case_3/expected/asset-loss.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural.csv
Labels: bug

#6280 Restore single-site-approx for BooreAtksinson2008
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement

#6281 migrate from travis to github action
  .github/workflows/zmq.yml
  doc/docker/single.md
  docker/tests/README.md
  docker/tests/docker-compose.yml
Labels: internal

#6282 Fixed prefiltering in event_based
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: bug

#6285 Initial work to support multi surfaces
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement

#6283 Show all calculations when the authentication is off
  debian/changelog
  openquake/server/utils.py
Labels: bug

#6286 Supported MultiSurfaces of KiteSurfaces
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commands/plot.py
  openquake/commands/run.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement, internal

#6289 Some small fixes
  doc/adv-manual/developing.rst
  openquake/calculators/classical.py
  openquake/commands/purge.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/boore_1997.py
  openquake/hazardlib/site.py
Labels: internal

#6290 Fixed strike, dip and rake in PointRuptures
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_60/__init__.py
  openquake/qa_tests_data/classical/case_60/expected/hazard_curve.csv
  openquake/qa_tests_data/classical/case_60/gmmLT.xml
  openquake/qa_tests_data/classical/case_60/job.ini
  openquake/qa_tests_data/classical/case_60/source_model.xml
  openquake/qa_tests_data/classical/case_60/ssmLT.xml
Labels: bug

#6291 Removed special case for pointsource_distance=0
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
Labels: internal

#6293 demos.yml for actions to replace travis
  .deploy_docs.enc
  .github/workflows/ansible.yml
  .github/workflows/demos.yml
  .github/workflows/docker.yml
  .github/workflows/zmq.yml
  openquake/commands/plot.py
Labels: internal

#6288 Generic linux installation script
  install.py
Labels: enhancement, packaging

#6292 Parallelized the point sources gridding
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_1/job.ini
Labels: performance

#6294 Speeding up the demos
  bin/run-demos.sh
  debian/changelog
  demos/hazard/LogicTreeCase3ClassicalPSHA/job.ini
  demos/risk/ClassicalDamage/job_hazard.ini
  demos/risk/ClassicalRisk/job_hazard.ini
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/engine.py
Labels: internal, performance

#6295 Exported the outputs of recompute_losses in the database
  bin/run-demos.sh
  debian/changelog
  openquake/commands/purge.py
  openquake/commands/recompute_losses.py
  openquake/engine/tools/make_html_report.py
Labels: bug

#6297 Removed collapse_point_ruptures
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_51/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(0.2).csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(2.0).csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
Labels: internal

#6298 Tried to save memory in the classical calculator
  openquake/hazardlib/contexts.py
Labels: internal

#6299 Converted _get_rups into a generator
  openquake/hazardlib/contexts.py
Labels: internal

#6296 SET GITHUB_DEF_BR on demos
  .github/workflows/demos.yml
Labels: internal

#6300 Fixes animations
  openquake/hazardlib/tests/source/kite_fault_test.py
Labels: internal

#6301 Turned `CollapsedPointSource.point_ruptures` into a generator to save memory
  openquake/hazardlib/source/point.py
Labels: performance

#6302 Moved gridding_point_sources in the preclassical phase
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
Labels: internal

#6303 Moved the preclassical phase inside `get_composite_source_model`
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/ucerf/job_classical_redux.ini
Labels: internal

#6304 Install the requirements always
  install.py
Labels: packaging

#6306 Split get_composite_source_model in two helper functions
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_29/job.ini
Labels: internal

#6308 Added a Timer class to store the times needed to process each source
  openquake/hazardlib/contexts.py
Labels: internal

#6309 Simplified the task distribution in classical
  openquake/calculators/classical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/ucerf_base.py
Labels: internal

#6310 Reduced the slow tasks due to point sources in classical calculations
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_2/expected/hcurve.csv
Labels: internal, performance
