Repository gem/oq-engine, pull requests merged in 2020-08, with the labels that each got.

#6030 Added tests for late_weights sampling
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/data/source_specific_uncertainty/sscLt.xml
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
  openquake/qa_tests_data/classical/case_51/report.rst
  openquake/qa_tests_data/classical/case_52/__init__.py
  openquake/qa_tests_data/classical/case_52/gsim_logic_tree.xml
  openquake/qa_tests_data/classical/case_52/job.ini
  openquake/qa_tests_data/classical/case_52/report.rst
  openquake/qa_tests_data/classical/case_52/source_model.xml
  openquake/qa_tests_data/classical/case_52/source_model_logic_tree.xml
Labels: enhancement

#6031 Replaced random.choice with random_choice
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
Labels: enhancement

#6033 Changed the disaggregation demo to use two realizations
  demos/hazard/Disaggregation/gmpe_logic_tree.xml
  demos/hazard/Disaggregation/job.ini
  openquake/calculators/disaggregation.py
  openquake/commonlib/util.py
Labels: documentation

#6036 Fix bug in deserialization of the source model logic tree
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
Labels: bug

#6032 Implemented latin hypercube sampling
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/logictree.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/lt.py
Labels: enhancement

#6037 Unified source model logic tree sampling with gsim logic tree sampling
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_2.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_4.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: enhancement

#6038 Worked around latin sampling of size=1 in the source model logic tree
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/lt.py
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_7/job.ini
Labels: bug

#6039 Changed the sampling algorithm
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
  openquake/qa_tests_data/classical/case_16/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/classical/case_16/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/classical/case_16/expected/quantile_curve-0.9.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_1.csv
  openquake/qa_tests_data/classical/case_17/expected/hazard_curve-smltp_b2-gsimltp_b1-ltr_4.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.05).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.2).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.5)
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_30/expected/hcurve-PGA.csv
  openquake/qa_tests_data/classical/case_30/expected/hcurve-SA(1.0).csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_17/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_18/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/ucerf/expected/hazard_curve-sampling.csv
Labels: internal

#6040 Using GDAL 2.4.2
  requirements-extra-py38-linux64.txt
Labels: packaging

#6034 Added Gulerce et al. (2017) GMPE
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/gulerce_2017.py
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegCAL.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegCHN.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegITA.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegJPN.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegMID.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResMEAN_RegTWN.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResStdPhi_RegCAL.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResStdPhi_RegJPN.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResStdTot_RegCAL.csv
  openquake/hazardlib/tests/gsim/data/GKAS16/GKAS16_ResStdTot_RegJPN.csv
  openquake/hazardlib/tests/gsim/gulerce_2017_test.py
Labels: enhancement
