Repository gem/oq-engine, pull requests merged in 2020-04, with the labels that each got.

#5707 Replaced `RUPTURES_PER_BLOCK` with `ruptures_per_block` in UCERF
  openquake/calculators/event_based.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source_reader.py
Labels: enhancement, internal

#5708 Splitting the UCERFSource more
  openquake/calculators/classical.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
Labels: internal

#5709 Enhanced `oq check_input` to check complex fault geometries
  debian/changelog
  openquake/commands/check_input.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/__init__.py
Labels: enhancement, internal

#5706 [Doc] Fix some typos [skip CI]
  doc/installing/development-windows.md
  doc/installing/development.md
Labels: documentation

#5711 Reduced the data transfer in ruptures
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement

#5712 Added ClassicalCalculator.submit_tasks
  openquake/calculators/classical.py
Labels: internal

#5710 Improved the task distribution in the classical calculator
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_map-mean.csv
Labels: performance

#5713 Fixed a recent regression in UCERF
  openquake/commonlib/calc.py
  openquake/commonlib/source_reader.py
Labels: bug

#5714 Changed the rupture storage for disaggregation
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_39/job.ini
Labels: internal

#5715 Fixed the tot_curves exporter
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
Labels: bug

#5716 Fixed the tot_losses exporter in ebrisk calculations
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
Labels: bug, outputs

#5717 Removed NaNs from the loss curves
  debian/changelog
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/risklib/scientific.py
Labels: enhancement

#5718 Fixed the disaggregation plot
  bin/run-demos.sh
  openquake/commands/plot.py
Labels: bug

#5719 Added ses and year to the events table
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.xml
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_3/expected/ses.xml
  openquake/qa_tests_data/event_based/mutex/expected/ses.xml
Labels: enhancement

#5721 Refined the source weight
  openquake/calculators/classical.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_19/job.ini
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_map-mean.csv
Labels: internal

#5722 Added .rst to the default export formats
  debian/changelog
  openquake/commands/engine.py
Labels: enhancement, outputs

#5720 Raised the dependencies for Python 3.8
  .travis.yml
  requirements-py38-linux64.txt
  setup.py
Labels: packaging

#5723 Added parameter `point_rupture_bins`
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
Labels: internal

#5724 Added function getters.get_ebruptures
  openquake/calculators/getters.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement, internal

#5725 Fixed sorting bug in /extract/rupture_info
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/scenario.py
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
Labels: bug

#5727 Fixed the bug affecting the PAC calculation by Kendra
  openquake/hazardlib/contexts.py
Labels: bug

#5728 Checking the boundaries extracted from rupture_info
  openquake/server/tests/views_test.py
Labels: enhancement, internal

#5729 Sanity check on agg_losses/tot_losses
  openquake/calculators/post_risk.py
Labels: internal

#5734 Add a second trt to the EventBasedPSHA demo
  demos/hazard/EventBasedPSHA/gmpe_logic_tree.xml
  demos/hazard/EventBasedPSHA/source_model.xml
Labels: internal

#5741 Fixed the mean disagg output
  openquake/calculators/extract.py
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_6/expected/PGA-sid-0-poe-0_Lon_Lat.csv
Labels: bug

#5742 Fixed sigma_epsilon dataset in scenario calculations
  openquake/calculators/scenario.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_12/sig_eps.csv
Labels: bug

#5739 Regenerated the outputs for engine 3.9
  openquake/calculators/tests/outputs/PGA-sid-.-poe-._Lon_Lat.csv
  openquake/calculators/tests/outputs/SA(.)-sid-.-poe-._Mag.csv
  openquake/calculators/tests/outputs/agg_curves-rlzs.csv
  openquake/calculators/tests/outputs/agg_curves-stats.csv
  openquake/calculators/tests/outputs/agg_losses-mean.csv
  openquake/calculators/tests/outputs/agg_losses-rlz-.csv
  openquake/calculators/tests/outputs/agglosses.csv
  openquake/calculators/tests/outputs/aggregate_by_avg_losses_tag-occupancy_kind-mean.csv
  openquake/calculators/tests/outputs/aggregate_by_avg_losses_tag-taxonomy_kind-rlz-._loss_type-structural.csv
  openquake/calculators/tests/outputs/aggregate_by_avg_losses_tag-taxonomy_kind-rlz-.csv
  openquake/calculators/tests/outputs/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/calculators/tests/outputs/avg_losses-mean.csv
  openquake/calculators/tests/outputs/avg_losses-quantile-.csv
  openquake/calculators/tests/outputs/avg_losses-rlz-.csv
  openquake/calculators/tests/outputs/bcr-mean.csv
  openquake/calculators/tests/outputs/bcr-quantile-.csv
  openquake/calculators/tests/outputs/bcr-rlz-.csv
  openquake/calculators/tests/outputs/damages-contents-rlz-.csv
  openquake/calculators/tests/outputs/damages-nonstructural-rlz-.csv
  openquake/calculators/tests/outputs/damages-structural-mean.csv
  openquake/calculators/tests/outputs/damages-structural-rlz-.csv
  openquake/calculators/tests/outputs/dmg_by_asset-rlz-.csv
  openquake/calculators/tests/outputs/gmf-data.csv
  openquake/calculators/tests/outputs/hazard_curve-max-PGA.csv
  openquake/calculators/tests/outputs/hazard_curve-max-SA(.).csv
  openquake/calculators/tests/outputs/hazard_curve-mean-AvgSA.csv
  openquake/calculators/tests/outputs/hazard_curve-mean-PGA.csv
  openquake/calculators/tests/outputs/hazard_curve-mean-PGV.csv
  openquake/calculators/tests/outputs/hazard_curve-mean-SA(.).csv
  openquake/calculators/tests/outputs/hazard_curve-rlz-.-PGA.csv
  openquake/calculators/tests/outputs/hazard_curve-rlz-.-SA(.).csv
  openquake/calculators/tests/outputs/hazard_curve-std-PGA.csv
  openquake/calculators/tests/outputs/hazard_curve-std-SA(.).csv
  openquake/calculators/tests/outputs/hazard_map-mean.csv
  openquake/calculators/tests/outputs/hazard_map-rlz-.csv
  openquake/calculators/tests/outputs/hazard_uhs-max.csv
  openquake/calculators/tests/outputs/hazard_uhs-mean.csv
  openquake/calculators/tests/outputs/hazard_uhs-rlz-.csv
  openquake/calculators/tests/outputs/hazard_uhs-std.csv
  openquake/calculators/tests/outputs/loss_maps-mean.csv
  openquake/calculators/tests/outputs/loss_maps-quantile-.csv
  openquake/calculators/tests/outputs/loss_maps-rlz-.csv
  openquake/calculators/tests/outputs/losses_by_asset-rlz-.csv
  openquake/calculators/tests/outputs/losses_by_event.csv
  openquake/calculators/tests/outputs/quantile_curve-.-PGA.csv
  openquake/calculators/tests/outputs/quantile_curve-.-SA(.).csv
  openquake/calculators/tests/outputs/quantile_map-.csv
  openquake/calculators/tests/outputs/realizations.csv
  openquake/calculators/tests/outputs/ruptures.csv
  openquake/calculators/tests/outputs/sigma_epsilon.csv
  openquake/calculators/tests/outputs/sitemesh.csv
  openquake/calculators/tests/outputs/tot_curves-rlzs.csv
  openquake/calculators/tests/outputs/tot_curves-stats.csv
  openquake/calculators/tests/outputs/tot_losses-mean.csv
  openquake/calculators/tests/outputs/tot_losses-rlz-.csv
Labels: internal, outputs

#5730 Fixed storage of AvgGMPE
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/hazardlib/gsim/mgmpe/avg_gmpe.py
Labels: bug

#5737 Fixed calc_hazard_curves for the case of multiple TRTs
  debian/changelog
  openquake/hazardlib/calc/hazard_curve.py
Labels: bug

#5743 Fixed an export bug with modal_damage_state=true
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_1c/expected/dmg_by_asset-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_1c/job.ini
Labels: bug, outputs

#5732 Implements Pitilakis et al., (2020) Site Amplification Model
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/tests/gsim/data/sera_site/Pitilakis2020Amplification_MEAN.csv
  openquake/hazardlib/tests/gsim/sera_site_amplification_test.py
Labels: enhancement

#5745 Logged a warning when the pointsource_distance is too small
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/valid.py
Labels: enhancement

#5746 Make `curves-rlzs` and `curves-stats` readable as DataFrames
  openquake/baselib/datastore.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/util.py
Labels: internal

#5749 Refactoring of the pointsource_distance
  openquake/calculators/classical.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_2/job.ini
  openquake/qa_tests_data/event_based/case_14/job.ini
Labels: internal

#5750 Changed pointsource_distance
  debian/changelog
  demos/hazard/MultiPointClassicalPSHA/job.ini
  doc/adv-manual/common-mistakes.rst
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/job.ini
Labels: enhancement

#5747 Exporting the loss ratio in the asset loss curves
  openquake/calculators/base.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/qa_tests_data/classical_risk/case_2/expected/loss_curves.csv
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-ref-a8-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-sid-1-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/loss_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/loss_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/loss_curves-quantile-0.15.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/loss_curves-quantile-0.5.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/loss_curves-quantile-0.85.csv
  openquake/risklib/asset.py
Labels: enhancement, outputs

#5752 Fixed the bug with missing TRTs affecting KOR and SEA
  openquake/calculators/classical.py
Labels: bug

#5753 Added flag save_disk_space
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
Labels: internal

#5751 Fixed the asset_ref association
  debian/changelog
  openquake/calculators/export/loss_curves.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-ref-a8-000.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/loss_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/exposure1.zip
  openquake/risklib/asset.py
Labels: bug

#5755 Removed assetcol["id"]
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/util.py
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_loss_12.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/job12.ini
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/qa_tests_data/scenario_damage/case_1/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_10/expected/dmg_by_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/dmg_by_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/dmg_by_asset-1.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-0.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset-1.csv
  openquake/risklib/asset.py
  openquake/server/tests/views_test.py
Labels: internal, outputs

#5756 Fixed the usual hdf5 damn bug
  openquake/calculators/extract.py
  openquake/risklib/asset.py
Labels: bug, internal

#5754 [Doc] Update page on floating-point arithmetic [skip CI]
  doc/adv-manual/addition-is-non-associative.rst
Labels: documentation

#5759 Removed asset_refs since they are now unneeded
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
  openquake/risklib/asset.py
Labels: internal

#5761 Added asset.tags dictionary
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/event_based_risk/case_2/exposure.csv
  openquake/qa_tests_data/event_based_risk/case_2/exposure.xml
  openquake/risklib/asset.py
  utils/expo2csv
Labels: bug

#5762 Fixed BOM bug
  debian/changelog
  openquake/qa_tests_data/event_based_risk/case_2/exposure.csv
  openquake/qa_tests_data/event_based_risk/case_2/job.ini
  openquake/risklib/asset.py
Labels: bug, inputs

#5763 Restored asset_id->id in the asset collection
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/commonlib/util.py
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/risklib/asset.py
Labels: bug

#5764 Added a function getters.get_rupdict
  openquake/calculators/getters.py
  openquake/calculators/scenario.py
Labels: internal

#5765 Save memory in large classical calculations
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
Labels: performance

#5766 Added test with pointsource_distance
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_13/job.ini
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(1.0).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
Labels: internal

#5768 Split the sources in get_sources_sites
  openquake/hazardlib/calc/filters.py
Labels: bug

#5769 Renamed collapse_ctxs -> collapse_level
  demos/hazard/LogicTreeCase2ClassicalPSHA/job.ini
  demos/hazard/MultiPointClassicalPSHA/job.ini
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/classical/case_24/job.ini
Labels: documentation

#5771 Small renaming of a field in source_info
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
Labels: internal

#5774 Improved the suggested pointsource_distance
  debian/changelog
  demos/hazard/GMPETablePSHA/job.ini
  demos/hazard/MultiPointClassicalPSHA/README.txt
  demos/hazard/MultiPointClassicalPSHA/job.ini
  doc/adv-manual/common-mistakes.rst
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/job.ini
Labels: enhancement

#5775 Fixed export ruptures.xml for scenario
  demos/hazard/LogicTreeCase3ClassicalPSHA/job.ini
  openquake/calculators/scenario.py
Labels: bug

#5777 Fixed bug with `oq engine --run --params`
  debian/changelog
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/hazardlib/valid.py
Labels: bug

#5770 Updated "What's new" for engine 3.9
  doc/whats-new.md
Labels: documentation

#5778 [Doc] Minor edits to whats-new [skip CI]
  doc/whats-new.md
Labels: documentation

#5783 Fixed disagg_layer for the single realization case
  bin/run-demos.sh
  openquake/calculators/extract.py
Labels: bug

#5782 Convert XML source models into CSV
  openquake/calculators/ucerf_base.py
  openquake/commands/sm_to_csv.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5758 add requirement wheel for python38 on macos
  openquake/baselib/tests/datastore_test.py
  openquake/server/utils.py
  openquake/server/views.py
  requirements-extra-py38-macos.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  setup.py
Labels: packaging

#5785 Implemented nrml_to_csv for simple fault and complex fault sources
  openquake/commands/nrml_to_csv.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5787 Added a converter XML->HDF5 for gridded sources
  debian/changelog
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/sourceconverter.py
  utils/gridded2hdf5
Labels: enhancement, internal

#5790 Fixed a bug when extracting into HDF5 format
  openquake/baselib/hdf5.py
Labels: bug, internal
