Repository gem/oq-engine, pull requests merged in 2020-03, with the labels that each got.

#5576 parse_uncertainty
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
Labels: internal

#5577 validate_uncertainty
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
Labels: internal

#5578 apply_uncertainty
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#5579 Removed more lines of code
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#5581 Fixed SourceModelLogicTree.__from_h5__
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
Labels: internal

#5583 Moved source model validation inside parsing and saved a few lines
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
Labels: internal

#5582 Improved the bounding box error message
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/utils.py
Labels: enhancement

#5585 Fixed the formula used in the ShakeMap calculator
  debian/changelog
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/qa_tests_data/scenario_damage/case_8/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
Labels: bug

#5587 Added a sanity check on the total number of assets for each event
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/scenario_damage/case_1c/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_8/expected/dmg_by_event.csv
Labels: bug

#5588 Made sure the number of buildings is the same for each event in scenario_damage
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/dmg_by_event.csv
Labels: bug

#5589 Removed some more lines of code
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/source_test.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
Labels: internal

#5590 Moving the parsing of the source models completely in apply_uncertainties
  openquake/calculators/disaggregation.py
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
Labels: internal

#5562 [Doc] Minor updates to implementing-new-gsim.md [skip CI]
  doc/implementing-new-gsim.md
Labels: documentation

#5591 Removed more lines of code
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/source_test.py
Labels: internal

#5592 Added an utility to plot logic trees
  utils/plot_lt
Labels: enhancement

#5598 Fixed the warning about discard_trts in event based
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/job.ini
Labels: internal

#5599 Sources are not split when sampling ruptures anymore
  openquake/hazardlib/calc/filters.py
Labels: internal

#5602 Changed the `calculation_mode` from `ucerf_hazard` to `ucerf_event_based`
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/ucerf/job.ini
  openquake/qa_tests_data/ucerf/job_ebh.ini
Labels: internal

#5604 Removed some unused code
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
Labels: internal

#5605 Small refactoring of UCERF
  openquake/calculators/ucerf_base.py
  openquake/calculators/ucerf_classical.py
  openquake/calculators/ucerf_event_based.py
Labels: internal

#5606 Made ucerf_event_based less special
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/hmap.rst
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: enhancement

#5607 Made ucerf_event_based even less special
  openquake/calculators/ucerf_base.py
  openquake/calculators/ucerf_event_based.py
Labels: enhancement, internal

#5608 Removed the ucerf_event_based calculator
  debian/changelog
  doc/sphinx/openquake.calculators.rst
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_base.py
  openquake/calculators/ucerf_event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/ucerf/job.ini
  openquake/qa_tests_data/ucerf/job_ebh.ini
Labels: internal

#5609 Fixed performance regression in UCERF
  openquake/calculators/event_based.py
Labels: internal

#5610 Second change of the seed algorithm
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/ucerf_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_25/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_6/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_6/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/hazard_map-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: internal

#5611 Using protocol=4 for the source checksum
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: bug

#5612 Removed some lines of code
  openquake/calculators/event_based.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/sourceconverter.py
Labels: internal

#5613 Removed another few lines of code
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
Labels: internal

#5614 Removed some lines of code
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
Labels: internal

#5615 Removed the slots from hazardlib
  openquake/baselib/general.py
  openquake/baselib/slots.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/polygon.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/mfd/arbitrary_mfd.py
  openquake/hazardlib/mfd/evenly_discretized.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/pmf.py
  openquake/hazardlib/scalerel/ceus2011.py
  openquake/hazardlib/scalerel/peer.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/characteristic.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/tests/__init__.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: enhancement, internal

#5616 Removed a few lines of code
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
Labels: internal

#5595 Improved oq reduce_sm to distinguish sources with same ID but different codes
  openquake/calculators/classical.py
  openquake/commands/reduce_sm.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical/case_15/source_model_1.xml
  openquake/qa_tests_data/classical/case_15/source_model_2.xml
Labels: enhancement

#5594 Add a warning to reduce_sm command if duplicate source ids are found
  debian/changelog
  openquake/commands/reduce_sm.py
Labels: enhancement

#5597 Reduce "Classical PSHA Non-parametric sources Demo"
  demos/hazard/NonparametricSourcesClassicalPSHA/slab/7.45.nrml
Labels: internal

#5618 Renamed src_group_id -> grp_id
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/source/multipoint_test.py
Labels: internal

#5619 Removed the ucerf_classical calculator
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/ucerf_base.py
  openquake/calculators/ucerf_classical.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
Labels: enhancement, internal

#5620 Turned the BBoxError into a log.error
  openquake/hazardlib/calc/filters.py
Labels: internal

#5621 Minor fixes
  openquake/baselib/hdf5.py
  openquake/calculators/classical.py
  openquake/commands/reduce_sm.py
Labels: internal

#5622 Managed OQ_SAMPLE_SOURCES in UCERF
  openquake/commonlib/source_reader.py
Labels: bug, internal

#5623 Some cleanup in the logic tree code (1)
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/sourceconverter.py
Labels: internal

#5624 More refactoring of the logic tree code (2)
  openquake/calculators/base.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/valid.py
Labels: internal

#5625 Renamed CompositionInfo -> FullLogicTree (3)
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/post_risk.py
  openquake/calculators/reportwriter.py
  openquake/calculators/scenario.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/tests/gmf_ebrisk_test.py
  openquake/calculators/views.py
  openquake/commands/info.py
  openquake/commands/plot.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/source_test.py
  openquake/engine/engine.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/event_based_risk/case_3/__init__.py
  utils/tot_ruptures.py
Labels: internal

#5626 Changed the storage of gsim_lt (4)
  doc/adv-manual/parametric-gmpes.rst
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/commands/info.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: internal

#5628 More cleanup of the logic tree code (5)
  openquake/calculators/tests/ucerf_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
  openquake/qa_tests_data/ucerf/expected/ruptures.csv
Labels: internal

#5631 Moved the check on invalid TRTs earlier
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical/case_1/source_model.xml
Labels: enhancement

#5632 Avoided reading multiple times the source models
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_6/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_6/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/tot_curves-stats.csv
Labels: enhancement

#5633 Saving the source serial in source_info
  openquake/commands/reduce_sm.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/base.py
Labels: internal

#5634 Compute less checksums
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
Labels: enhancement, internal

#5636 Changed the order of the sources in reduce_sources
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/area.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/tot_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/agglosses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
Labels: internal

#5639 Fixed the log message about received data
  openquake/baselib/parallel.py
Labels: bug, internal

#5640 More refactoring around the logic tree code (6)
  openquake/commonlib/logictree.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#5641 More refactoring of the logic tree code (7)
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/source/base.py
Labels: internal

#5638 [Doc] Edits to the seeds section in faq-risk [skip CI]
  doc/faq-risk.md
Labels: documentation

#5642 Fixed `oq info source_model_logic_tree.xml`
  debian/changelog
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
Labels: bug, internal

#5643 Fixed eff_ruptures in event based
  openquake/hazardlib/calc/stochastic.py
Labels: internal

#5644 Fixed mosaic/EUR
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/oqzip.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
Labels: bug

#5645 Restored the extendModel functionality
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/source_reader.py
Labels: internal

#5646 Added a test for the case of common source models
  openquake/calculators/extract.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_25/job_common.ini
  openquake/qa_tests_data/event_based/case_25/ssmLT.xml
Labels: internal

#5647 Improved baselib.parallel docs
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/calculators/views.py
Labels: documentation

#5649 Disabled NonParametricSeismicSource.wkt for speed
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/non_parametric.py
Labels: bug

#5650 Call `src.count_ruptures()` later
  debian/changelog
  openquake/commonlib/lt.py
  openquake/commonlib/source.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: performance

#5651 Moved around some logic tree code
  openquake/calculators/base.py
  openquake/calculators/scenario.py
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
  openquake/commonlib/source.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/source_test.py
Labels: internal

#5652 Restored NonParametricSeismicSource.wkt
  openquake/commands/plot.py
  openquake/hazardlib/source/non_parametric.py
Labels: internal

#5653 Test `reduce_sm` in a case with two sources having the same ID and different codes
  openquake/commands/tests/__init__.py
  openquake/commands/tests/commands_test.py
  openquake/commands/tests/data/__init__.py
  openquake/commands/tests/data/to_reduce/__init__.py
  openquake/commands/tests/data/to_reduce/gmpe_logic_tree.xml
  openquake/commands/tests/data/to_reduce/job.ini
  openquake/commands/tests/data/to_reduce/source_model_1.xml
  openquake/commands/tests/data/to_reduce/source_model_2.xml
  openquake/commands/tests/data/to_reduce/source_model_logic_tree.xml
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#5655 Slightly changed the syntax of `oq info`
  debian/changelog
  doc/adv-manual/effective-realizations.rst
  doc/adv-manual/oq-commands.rst
  doc/manual/oqum/hazard/01a_logic_trees.tex
  doc/manual/oqum/hazard/01d_config_scenario.tex
  openquake/commands/export.py
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
Labels: internal

#5656 Renamed oq reduce -> oq sample
  openquake/commands/sample.py
  openquake/commands/tests/commands_test.py
Labels: enhancement, internal

#5657 Added info about MFDs and sources
  debian/changelog
  openquake/baselib/general.py
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/source/rupture.py
Labels: documentation

#5659 Removed some lines of code
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/source_test.py
Labels: internal

#5661 Computed the mean disaggregation if multiple realizations are requested
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/SA(0.1)-sid-1-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_6/expected/PGA-sid-0-poe-0_Lon_Lat.csv
Labels: enhancement

#5660 Avoided duplication of the tectonicRegion in nrml/0.5
  demos/risk/ClassicalBCR/source_model.xml
  demos/risk/ClassicalDamage/source_model.xml
  openquake/commands/reduce_sm.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/expected_sources.toml
  openquake/hazardlib/tests/source/multipoint_test.py
  openquake/hazardlib/tests/source_model/alternative-mfds_4test.xml
  openquake/hazardlib/tests/source_model/mixed.xml
  openquake/hazardlib/tests/source_model/multi-point-source.xml
  openquake/hazardlib/tests/source_model/nonparametric-source-mutex-ruptures.xml
  openquake/hazardlib/tests/source_model/nonparametric-source.xml
  openquake/hazardlib/tests/source_model/source_group_collection.xml
  openquake/hmtk/parsers/source_model/nrml04_parser.py
Labels: internal

#5662 Collapsing of logic trees (1)
  openquake/commonlib/logictree.py
  openquake/commonlib/lt.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/multi.py
  openquake/hazardlib/source/simple_fault.py
Labels: enhancement

#5663 Collapsing of logic trees (2)
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
Labels: internal

#5664 Collapsing of logic trees (3)
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/multi.py
  openquake/hazardlib/tests/lt_test.py
Labels: internal

#5666 Some refactoring of `Context.get_pmap_by_grp`
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
Labels: internal

#5667 Reduced the rupture storage for disaggregation
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#5669 Added a check for missing TRTs
  debian/changelog
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/readinput_test.py
Labels: enhancement

#5668 Storing the source_info by source_id and not src.id
  bin/run-demos.sh
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/ucerf_base.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commands/reduce_sm.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/server/tests/views_test.py
Labels: internal

#5670 Some internal improvements
  openquake/calculators/base.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/server/tests/views_test.py
Labels: internal

#5671 Restored the pointsource_distance approximation
  openquake/calculators/tests/classical_test.py
  openquake/commands/plot.py
  openquake/hazardlib/contexts.py
Labels: bug

#5672 Split the case of src_mutex from the case of src_indep in the PmapMaker
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
Labels: internal

#5673 Improved the rupture collapsing in the case of collapsed logic trees
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_26/expected/hazard_curve-rlz-000.csv
  openquake/qa_tests_data/classical/case_3/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_34/expected/hazard_curve-mean-AvgSA.csv
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_44/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_44/expected/hc-shift-hypo-PGA.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: enhancement, internal

#5674 Collapse only if all the ruptures are parametric
  openquake/hazardlib/contexts.py
Labels: internal

#5675 Moved the rupture filtering after the collapse
  openquake/calculators/export/risk.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_30/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_30/expected/hcurve-PGA.csv
  openquake/qa_tests_data/classical/case_30/expected/hcurve-SA(1.0).csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b1.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b2.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-mean.csv
Labels: bug, internal

#5676 Removed the experimental rupture collapsing mechanism
  demos/hazard/LogicTreeCase2ClassicalPSHA/job.ini
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg1_cog2_char_complex-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg1_cog2_char_plane-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg1_cog2_char_simple-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg2_cog2_char_complex-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg2_cog2_char_plane-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_20/expected/hazard_curve-smltp_sm1_sg2_cog2_char_simple-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd1_high_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd1_low_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd1_mid_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd2_high_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd2_low_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd2_mid_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd3_high_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_21/expected/hazard_curve-smltp_b1_mfd3_mid_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_24/job.ini
  openquake/qa_tests_data/classical/case_26/expected/hazard_curve-rlz-000.csv
  openquake/qa_tests_data/classical/case_3/expected/hazard_curve-smltp_b1-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_34/expected/hazard_curve-mean-AvgSA.csv
  openquake/qa_tests_data/classical/case_42/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_44/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_44/expected/hc-shift-hypo-PGA.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-0_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
Labels: internal

#5677 files requirement python3.8
  requirements-py38-linux64.txt
Labels: internal

#5678 Strongly improved the collapse of the ruptures
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
Labels: enhancement, performance

#5679 Some fixes
  openquake/calculators/base.py
  openquake/calculators/tests/classical_test.py
  openquake/commands/info.py
  openquake/commonlib/readinput.py
  openquake/hmtk/seismicity/gcmt_catalogue.py
Labels: bug, internal

#5680 Fixed a small array-shape bug in the hazard maps
  openquake/calculators/classical.py
Labels: bug, internal

#5681 Added a check on classical calculations which are too big to be run
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commands/info.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/commonlib/tests/logictree_test.py
Labels: enhancement

#5683 Small change to the AccumDict interface
  openquake/baselib/general.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
Labels: internal

#5685 Improved the message in case of duplicated values
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#5684 Upgrading the libraries for Python 3.8 on travis
  .travis.yml
  openquake/commands/plot.py
  openquake/engine/engine.py
  setup.py
Labels: packaging

#5682 Added cauzzi_2014scaled, bindi_2014scaled, bindi_2011scaled
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/bindi_2011scaled.py
  openquake/hazardlib/gsim/bindi_2014scaled.py
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/gsim/cauzzi_2014scaled.py
  openquake/hazardlib/tests/gsim/bindi_2011scaled_test.py
  openquake/hazardlib/tests/gsim/cauzzi_2014scaled_test.py
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014scaled/B14_Rhypo_EC8scaled_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014scaled/B14_Rhypo_EC8scaled_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014scaled/B14_Rhypo_EC8scaled_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014scaled/B14_Rhypo_EC8scaled_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14scaled/CAUZZI_EC8_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14scaled/CAUZZI_EC8_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14scaled/CAUZZI_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14scaled/CAUZZI_EC8_TOTAL_STD.csv
Labels: enhancement

#5687 Do not store empty agg_curves
  openquake/calculators/post_risk.py
Labels: bug

#5686 Removed HMTKBaseMap
  openquake/hmtk/plotting/mapping.py
Labels: packaging

#5689 Substantial improvement of the pointsource_distance approximation
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/source/point_test.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
Labels: performance

#5691 Extended the pointsource_distance approximation to the case of few sites
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_2/expected/hcurve.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_map-mean.csv
Labels: performance

#5693 Added a MultiPointDemo to test the rupture collapsing feature
  demos/hazard/MultiPointClassicalPSHA/README.txt
  demos/hazard/MultiPointClassicalPSHA/gmmLT.xml
  demos/hazard/MultiPointClassicalPSHA/job.ini
  demos/hazard/MultiPointClassicalPSHA/multipoint.xml
  demos/hazard/MultiPointClassicalPSHA/ssmLT.xml
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_39/expected/hazard_map-mean.csv
Labels: documentation

#5696 [Doc] Updates to faq-risk [skip CI]
  doc/adv-manual/oq-commands.rst
  doc/adv-manual/risk-features.rst
  doc/faq-risk.md
Labels: documentation

#5692 Raise a warning for intensity measure levels with a different number of levels per IMT
  debian/changelog
  openquake/commonlib/oqvalidation.py
Labels: proposal

#5697 Restored the disagg_by_src functionality
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/qa_tests_data/classical/case_20/job.ini
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Lon_Lat.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-PGA-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/rlz-0-SA(0.025)-sid-0-poe-1_Mag_Dist.csv
  openquake/qa_tests_data/disagg/case_6/job.ini
Labels: internal

#5699 Parallelized `reduce_sm`
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: internal, performance

#5688 Implements possibility to use GMPEs with Gaussian Mixture Models in the Standard Deviation
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/qa_tests_data/classical/case_47/__init__.py
  openquake/qa_tests_data/classical/case_47/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_47/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_47/job.ini
  openquake/qa_tests_data/classical/case_47/source_model.xml
  openquake/qa_tests_data/classical/case_47/source_model_logic_tree.xml
Labels: enhancement

#5701 Removed several annoying warnings coming from the HMTK code
  openquake/hmtk/parsers/faults/fault_yaml_parser.py
  openquake/hmtk/seismicity/catalogue.py
  openquake/hmtk/seismicity/selector.py
  openquake/hmtk/strain/shift.py
Labels: internal

#5700 20200325 yea97
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/youngs_1997.py
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SSlab_MEAN.csv
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-PGA.csv
Labels: bug

#5703 Small fixes to the report generation
  openquake/calculators/base.py
  openquake/calculators/reportwriter.py
  openquake/commands/info.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based/case_14/report.rst
Labels: internal

#5704 Some improvements to the workerpool
  openquake/baselib/workerpool.py
Labels: internal

#5702 Added a warning against magnitude-dependent maximum_distance
  debian/changelog
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based/case_14/job.ini
Labels: bug

#5705 Reducing the number of tasks spawned by the ebrisk calculator
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based_risk/case_miriam/job2.ini
Labels: internal
