Repository gem/oq-engine, pull requests merged in 2021-07, with the labels that each got.

#6926 Methods->functions/19
  openquake/hazardlib/gsim/stewart_2016.py
  openquake/hazardlib/tests/gsim/stewart_2016_test.py
Labels: internal

#6927 Methods->functions/20
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/edwards_fah_2013a.py
  openquake/hazardlib/gsim/edwards_fah_2013f.py
  openquake/hazardlib/gsim/raghukanth_iyengar_2007.py
  openquake/hazardlib/tests/gsim/akkar_cagnan_2010_test.py
Labels: internal

#6928 Changed again the numpy-oriented API
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
Labels: investigation, performance

#6929 Methods->functions/21
  openquake/hazardlib/gsim/can15/eastern.py
Labels: internal

#6931 Methods->functions/22
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
Labels: internal

#6932 Methods->functions/23
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
Labels: internal

#6934 Methods->functions/24
  openquake/hazardlib/gsim/bindi_2011.py
  openquake/hazardlib/gsim/bindi_2011_ipe.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/fukushima_tanaka_1990.py
  openquake/hazardlib/tests/gsim/bindi_2011_backbone_delta_test.py
Labels: internal

#6936 Methods->functions/25
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/idini_2017.py
  openquake/hazardlib/gsim/projects/acme_2019.py
Labels: internal

#6938 Methods->functions/27
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
Labels: internal

#6937 Methods->function/26
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/bradley_2013b.py
Labels: internal

#6939 Methods->functions/28
  openquake/hazardlib/gsim/ameri_2014.py
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/gsim/bindi_2017.py
  openquake/hazardlib/gsim/morikawa_fujiwara_2013.py
  openquake/hazardlib/tests/gsim/ameri_2014_test.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
Labels: internal

#6940 Methods->functions/29
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/bindi_2014.py
  openquake/hazardlib/gsim/bindi_2017.py
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/gsim/germany_2018.py
  openquake/hazardlib/gsim/kale_2015.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
Labels: internal

#6941 Methods->functions/30
  openquake/hazardlib/gsim/armenia_2016.py
  openquake/hazardlib/gsim/boore_1997.py
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/gsim/cauzzi_2014scaled.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/tests/gsim/cauzzi_2014_test.py
  openquake/hazardlib/tests/gsim/cauzzi_2014scaled_test.py
Labels: internal

#6942 Methods->functions/31
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/stewart_2016.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/zalachoris_rathje_2019.py
  openquake/hazardlib/tests/gsim/stewart_2016_test.py
Labels: internal

#6945 Changed the new API again
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/gsim/check_gsim.py
Labels: internal

#6946 From numba objects to structured arrays/1
  openquake/calculators/export/hazard.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bindi_2011.py
  openquake/hazardlib/gsim/bindi_2014.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/climent_1994.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/gsim/dost_2004.py
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
  openquake/hazardlib/gsim/drouet_2015_brazil.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
  openquake/hazardlib/gsim/edwards_fah_2013a.py
  openquake/hazardlib/gsim/edwards_fah_2013f.py
  openquake/hazardlib/gsim/faccioli_2010.py
  openquake/hazardlib/gsim/ghofrani_atkinson_2014.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/idriss_2014.py
  openquake/hazardlib/gsim/kanno_2006.py
  openquake/hazardlib/gsim/kotha_2016.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/lanzano_luzi_2019.py
  openquake/hazardlib/gsim/megawati_2003.py
  openquake/hazardlib/gsim/megawati_pan_2010.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/rietbrock_2013.py
  openquake/hazardlib/gsim/rietbrock_edwards_2019.py
  openquake/hazardlib/gsim/shahjouei_pezeshk_2016.py
  openquake/hazardlib/gsim/si_midorikawa_1999.py
  openquake/hazardlib/gsim/skarlatoudis_2013.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/yu_2013.py
  openquake/hazardlib/gsim/zalachoris_rathje_2019.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/tests/imt_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/sep/classes.py
Labels: internal

#6947 Methods->functions/32
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008.py
  openquake/hazardlib/gsim/faccioli_2010.py
  openquake/hazardlib/gsim/kotha_2016.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/zhao_2006.py
  openquake/hazardlib/tests/gsim/bozorgnia_campbell_2016_test.py
  openquake/hazardlib/tests/gsim/can15/sinter_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/faccioli_2010_test.py
Labels: internal

#6948 Methods->functions/33
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/megawati_2003.py
  openquake/hazardlib/gsim/montalva_2016.py
Labels: internal

#6949 Methods->functions/34
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/montalva_2016.py
  openquake/hazardlib/gsim/montalva_2017.py
Labels: internal

#6950 Methods->functions/35
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/montalva_2016.py
  openquake/hazardlib/gsim/montalva_2017.py
Labels: internal

#6951 Methods->functions/36
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/sgobba_2020.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
Labels: internal

#6943 Updates test tables for Atkinson 2015 plus minor adjustments
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/tests/gsim/atkinson_2015_test.py
  openquake/hazardlib/tests/gsim/data/ATKINSON2015/ATKINSON2015_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ATKINSON2015/ATKINSON2015_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/ATKINSON2015/ATKINSON2015_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/ATKINSON2015/ATKINSON2015_STD_TOTAL.csv
  openquake/qa_tests_data/classical/case_44/expected/hazard_curve-mean-PGA.csv
Labels: enhancement

#6953 Implemented the Boore (2020) GSIM
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/boore_2020.py
  openquake/hazardlib/tests/gsim/boore_2020_test.py
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_inter_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_intra_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_mean.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_total_std.csv
  openquake/qa_tests_data/event_based/case_24/expected/hazard_curve-mean-PGA.csv
Labels: enhancement

#6900 Corrected Campbell and Bozorgnia (2014) GMPE
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2014_test.py
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_JAPAN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_JAPAN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_JAPAN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_JAPAN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_HIGHQ_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_JAPAN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_JAPAN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_JAPAN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_JAPAN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_JAPAN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_JAPAN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_JAPAN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_JAPAN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_LOWQ_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_MEAN.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/CB14/CB2014_STD_TOTAL.csv
Labels: bug

#6887 LAN2020
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/lanzano_2020.py
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_CLUSTER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_CLUSTER_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_EC8_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_REF_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2020/LAN2020_REF_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/lanzano_2020_test.py
Labels: enhancement

#6954 Methods->functions/38
  debian/changelog
  openquake/hazardlib/gsim/lanzano_2020.py
Labels: internal

#6889 Added the Gulerce and Abrahamson (2011) GMPE
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/const.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
  openquake/hazardlib/tests/gsim/data/GA11/GA11_Fig_7_8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/GA11/GA11_Fig_9_10_MEAN.csv
  openquake/hazardlib/tests/gsim/gulerce_abrahamson_2011_test.py
Labels: enhancement

#6952 Methods->functions/37
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: internal

#6956 Methods->functions/39
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
Labels: bug, internal

#6958 Added a numba-based compile decorator
  openquake/baselib/performance.py
  openquake/hazardlib/gsim/base.py
Labels: performance

#6959 Methods->functions/40
  debian/changelog
  openquake/hazardlib/gsim/base.py
Labels: enhancement

#6962 Changed the shape of the array mean_std
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/stats.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/check_gsim.py
Labels: internal

#6964 Turned get_probability_no_exceedence from method into function
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/rupture_test.py
Labels: internal

#6965 Refactored get_poes_site
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: internal

#6955 Added the Bozorgnia & Campbell (2016) GMPE for V/H (PR Re-open)
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/bozorgnia_campbell_2016_vh.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/tests/gsim/bozorgnia_campbell_2016_vh_test.py
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_AVEQ_JPN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_AVEQ_JPN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_AVEQ_JPN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_AVEQ_JPN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_GLOBAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_GLOBAL_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_GLOBAL_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_GLOBAL_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_JPN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_JPN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_JPN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_JPN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_HIGHQ_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_JPN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_JPN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_JPN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_JPN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BC15b/BC15b_LOWQ_STD_TOTAL.csv
Labels: enhancement

#6966 Minor fix in RuptureContext.size
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#6961 Added an example of the `compute` API
  openquake/baselib/performance.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_2020.py
  openquake/hazardlib/gsim/raghukanth_iyengar_2007.py
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
Labels: enhancement

#6970 Fixed mispelling in the name of the AbrahamsonEtAl2014RegXXX gsims
  openquake/hazardlib/gsim/abrahamson_2014.py
Labels: bug

#6967 Added the Stewart et al. (2016) GMPE for V/H
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/stewart_2016_vh.py
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CAL_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_CHN_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_PERIOD_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_INTER_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_INTRA_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_MEAN_NOSOF.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/SBSA15b/SBSA15b_JPN_RJB_TOTAL_STD_NOSOF.csv
  openquake/hazardlib/tests/gsim/stewart_2016_vh_test.py
Labels: enhancement

#6972 Fixing the SMTK
  openquake/hazardlib/const.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: bug

#6974 recarray type annotation
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/example_a_2021.py
Labels: performance

#6976 Fixes two small regressions
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/can15/eastern.py
Labels: bug

#6978 Fixed the management of gsim aliases
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: bug

#6979 Refined the size of the poes arrays
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: performance

#6981 Fixed GroundShakingIntensityModel.get_mean_and_stddevs
  openquake/hazardlib/gsim/base.py
Labels: bug, internal

#6983 Added decorator vectorize_arg
  openquake/baselib/performance.py
Labels: performance

#6984 Compute API/3
  openquake/hazardlib/gsim/morikawa_fujiwara_2013.py
Labels: performance

#6977 Compute API/2
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/can15/sslab.py
  openquake/hazardlib/gsim/faccioli_cauzzi_2006.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/zhao_2006.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
  openquake/hazardlib/tests/gsim/zhao_2006_test.py
Labels: internal

#6930 Fixed the management of consequence functions in presence of a taxonomy mapping
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/commonlib/readinput.py
  openquake/risklib/riskmodels.py
  openquake/server/db/actions.py
Labels: bug

#6985 Now check_gsim.py understands OQ_DEBUG
  openquake/hazardlib/tests/gsim/check_gsim.py
Labels: internal

#6987 Removed usages of SitesContext and DistancesContext
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/frankel_1996_test.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/sadigh_1997_test.py
  openquake/hazardlib/tests/gsim/sharma_2009_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
Labels: internal

#6986 Compute API/4
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008_swiss.py
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss_coeffs.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
  openquake/hazardlib/gsim/stewart_2016_vh.py
  openquake/hazardlib/gsim/utils.py
  openquake/hazardlib/gsim/utils_swiss_gmpe.py
  openquake/hazardlib/gsim/zhao_2006.py
  openquake/hazardlib/gsim/zhao_2006_swiss.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2008_test.py
  openquake/hazardlib/tests/gsim/zhao_2006_swiss_test.py
Labels: internal

#6989 Compute API/5
  openquake/hazardlib/gsim/lin_lee_2008.py
  openquake/hazardlib/gsim/toro_2002.py
  openquake/hazardlib/gsim/youngs_1997.py
Labels: internal

#6990 Compute API/6
  openquake/hazardlib/gsim/atkinson_boore_2003.py
Labels: internal

#6991 Compute API/7
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim/atkinson_boore_2003.py
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/gsim/gupta_2010.py
  openquake/hazardlib/tests/gsim/mgmpe/split_sigma_gmpe_test.py
Labels: internal

#6992 54x speedup when computing the mean hazard curves
  debian/changelog
  openquake/hazardlib/probability_map.py
Labels: performance

#6994 Vectorized the GMPEs for Europe
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2003.py
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/faccioli_cauzzi_2006.py
  openquake/hazardlib/gsim/lin_lee_2008.py
  openquake/hazardlib/gsim/toro_2002.py
  openquake/hazardlib/gsim/utils_swiss_gmpe.py
  openquake/hazardlib/gsim/youngs_1997.py
  openquake/hazardlib/gsim/zhao_2006.py
Labels: performance

#6995 Fixed the event based damage in case of missing consequences
  openquake/commonlib/readinput.py
Labels: bug

#6971 Implements Si et al. (2020) NGA subduction model
  CONTRIBUTORS.txt
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/si_2020.py
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTERFACE_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTERFACE_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTERFACE_MEAN.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTERFACE_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTRASLAB_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTRASLAB_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTRASLAB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/si2020/SI2020_INTRASLAB_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/si_2020_test.py
Labels: enhancement

#6944 Modify pga_threshold_table from job.ini for HAZUS lateral spreading
  openquake/sep/classes.py
  openquake/sep/liquefaction/lateral_spreading.py
Labels: enhancement

#6996 update documentation for universal installer and cluster
  doc/installing/cluster.md
  doc/installing/universal.md
Labels: documentation

#6997 Refactored some Canadian GMPEs
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/boore_atkinson_2011.py
  openquake/hazardlib/gsim/can15/oceanic.py
  openquake/hazardlib/gsim/can15/western.py
  openquake/hazardlib/gsim/can15/western_rjb.py
  openquake/hazardlib/tests/gsim/can15/oceanic.py
  openquake/hazardlib/tests/gsim/can15/western_rjb_test.py
Labels: internal

#6998 Refactored the BCHydro subclasses
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
Labels: internal

#6999 Compute API/8
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/ghofrani_atkinson_2014.py
  openquake/hazardlib/gsim/nshmp_2014.py
Labels: internal

#7000 Compute API/9
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/can15/sinter.py
Labels: internal

#7001 Compute API/10
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
Labels: internal

#7004 Compute API/12
  openquake/hazardlib/gsim/berge_thierry_2003.py
Labels: internal

#7003 Compute API/11
  openquake/hazardlib/gsim/akkar_2014.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
Labels: internal

#7005 Compute API/13
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/zhao_2016.py
Labels: internal

#7007 Compute API/15
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/utils.py
Labels: internal

#7008 Compute API/16
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/can15/western.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
Labels: internal

#7009 GMM for the TEM20 model
  debian/changelog
  openquake/hazardlib/gsim/tem20/__init__.py
  openquake/hazardlib/gsim/tem20/lin_2011.py
  openquake/hazardlib/tests/gsim/data/tem20/lin2011_mean_fw.csv
  openquake/hazardlib/tests/gsim/data/tem20/lin2011_mean_hw.csv
  openquake/hazardlib/tests/gsim/data/tem20/lin2011_std_fw.csv
  openquake/hazardlib/tests/gsim/data/tem20/lin2011_std_hw.csv
  openquake/hazardlib/tests/gsim/tem20/lin_2011_foot_test.py
  openquake/hazardlib/tests/gsim/tem20/lin_2011_hanging_test.py
Labels: enhancement

#7010 Restored module boore_atkinson_2008.py
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/sharma_2009.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/boore_atkinson_2008_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
Labels: internal

#7013 Move the `adjust_mfd_from_slip` to the `ParametricSeismicSource` class
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/characteristic.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/kite_fault.py
  openquake/hazardlib/source/simple_fault.py
Labels: internal

#7023 Compute API/17
  openquake/hazardlib/gsim/drouet_2015_brazil.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
  openquake/hazardlib/gsim/pankow_pechmann_2004.py
  openquake/hazardlib/gsim/rietbrock_2013.py
  openquake/hazardlib/gsim/rietbrock_edwards_2019.py
  openquake/hazardlib/gsim/sadigh_1997.py
  openquake/hazardlib/gsim/somerville_2001.py
  openquake/hazardlib/gsim/somerville_2009.py
  openquake/hazardlib/gsim/tavakoli_pezeshk_2005.py
  openquake/hazardlib/gsim/toro_1997.py
  openquake/hazardlib/gsim/tusa_langer_2016.py
  openquake/hazardlib/gsim/vanhoutte_2018.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/yu_2013.py
  openquake/hazardlib/tests/gsim/drouet_2015_test.py
  openquake/hazardlib/tests/gsim/mgmpe/dummy.py
  openquake/hazardlib/tests/gsim/pankow_pechmann_2004_test.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/sadigh_1997_test.py
Labels: internal

#7025 Compute API/19
  openquake/hazardlib/gsim/mcverry_2006.py
Labels: internal

#7019 Fixing base class and homogenising child classes
  openquake/hazardlib/scalerel/allenhayes2017.py
  openquake/hazardlib/scalerel/base.py
  openquake/hazardlib/scalerel/strasser2010.py
  openquake/hazardlib/scalerel/wc1994.py
  openquake/hazardlib/scalerel/wc1994_qcss.py
  openquake/hazardlib/tests/scalerel/asr_test.py
  openquake/hmtk/faults/fault_models.py
  openquake/hmtk/faults/mfd/anderson_luco_arbitrary.py
  openquake/hmtk/faults/mfd/anderson_luco_area_mmax.py
  openquake/hmtk/faults/mfd/characteristic.py
  openquake/hmtk/faults/mfd/youngs_coppersmith.py
Labels: internal

#7024 Compute API/18
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/mcverry_2006.py
Labels: internal

#7026 Porting more GMPEs to the compute API
  openquake/hazardlib/gsim/silva_2002.py
Labels: internal

#7027 Compute API/21
  openquake/hazardlib/gsim/megawati_2003.py
  openquake/hazardlib/gsim/megawati_pan_2010.py
  openquake/hazardlib/gsim/munson_thurber_1997.py
  openquake/hazardlib/gsim/pezeshk_2011.py
Labels: internal

#7028 Compute API/22
  openquake/hazardlib/gsim/climent_1994.py
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/gsim/dost_2004.py
Labels: internal

#7029 Compute API/23
  openquake/hazardlib/gsim/convertito_2012.py
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
  openquake/hazardlib/gsim/frankel_1996.py
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/gsim/lanzano_2020.py
  openquake/hazardlib/gsim/lin_2009.py
  openquake/hazardlib/tests/gsim/convertito_2012_test.py
  openquake/hazardlib/tests/gsim/frankel_1996_test.py
Labels: internal

#7031 Improved the compatibility of the compute API with get_means_and_stddevs
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: enhancement

#7033 Compute API/25
  openquake/hazardlib/gsim/bindi_2014.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/tests/gsim/stewart_2016_vh_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
Labels: internal

#7035 Compute API/26
  openquake/hazardlib/gsim/armenia_2016.py
Labels: internal

#7036 Compute API/27
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/shahjouei_pezeshk_2016.py
  openquake/hazardlib/gsim/skarlatoudis_2013.py
  openquake/hazardlib/gsim/travasarou_2003.py
Labels: internal

#7037 Compute API/28
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_2018.py
  openquake/hazardlib/gsim/abrahamson_silva_1997.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/afshari_stewart_2016.py
  openquake/hazardlib/gsim/allen_2012.py
  openquake/hazardlib/gsim/allen_2012_ipe.py
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/gsim/baumont_2018.py
  openquake/hazardlib/gsim/bommer_2009.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
Labels: internal

#7038 Compute API/29
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/gulerce_2017.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/hong_goda_2007.py
  openquake/hazardlib/gsim/idini_2017.py
  openquake/hazardlib/gsim/idriss_2014.py
  openquake/hazardlib/gsim/kanno_2006.py
  openquake/hazardlib/gsim/kotha_2020.py
Labels: internal

#7039 Compute API/30
  openquake/hazardlib/gsim/atkinson_boore_1995.py
  openquake/hazardlib/gsim/boore_1993.py
  openquake/hazardlib/gsim/boore_1997.py
  openquake/hazardlib/gsim/campbell_1997.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/dowrickrhoades_2005.py
  openquake/hazardlib/gsim/fukushima_tanaka_1990.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/lanzano_luzi_2019.py
  openquake/hazardlib/gsim/nath_2012.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/sharma_2009.py
  openquake/hazardlib/gsim/zalachoris_rathje_2019.py
  openquake/hazardlib/tests/gsim/sharma_2009_test.py
Labels: internal

#7040 Compute API/31
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/edwards_fah_2013a.py
  openquake/hazardlib/gsim/edwards_fah_2013f.py
  openquake/hazardlib/gsim/fukushima_tanaka_1990.py
  openquake/hazardlib/gsim/garcia_2005.py
  openquake/hazardlib/gsim/geomatrix_1993.py
Labels: internal

#7041 Refactoring SgobbaEtAl2020
  openquake/hazardlib/gsim/sgobba_2020.py
  openquake/hazardlib/tests/gsim/sgobba_2020_test.py
Labels: enhancement, performance

#7042 Refactoring SgobbaEtAl2020/2
  openquake/hazardlib/tests/gsim/sgobba_2020_test.py
Labels: internal, performance

#7043 Compute API/32
  openquake/hazardlib/gsim/sgobba_2020.py
  openquake/hazardlib/tests/gsim/sgobba_2020_test.py
Labels: internal

#7044 Compute API/33
  openquake/hazardlib/gsim/campbell_bozorgnia_2003.py
  openquake/hazardlib/gsim/ecos_2009.py
  openquake/hazardlib/gsim/eshm20_craton.py
Labels: internal

#7046 Compute API/34
  openquake/hazardlib/const.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
Labels: internal

#7047 Compute API/35
  openquake/hazardlib/gsim/bozorgnia_campbell_2016_vh.py
Labels: internal

#7021 update DEFINED_FOR_REFERENCE_VELOCITY
  openquake/hazardlib/gsim/akkar_2014.py
  openquake/hazardlib/gsim/atkinson_boore_2003.py
  openquake/hazardlib/gsim/lin_lee_2008.py
  openquake/hazardlib/gsim/youngs_1997.py
Labels: bug

#7048 Compute API/36
  openquake/hazardlib/gsim/mgmpe/cy14_site_term.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/tromans_2019.py
Labels: internal

#7050 Compute API/37
  openquake/hazardlib/const.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/avg_gmpe.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: internal

#7052 Compute API/39
  openquake/hazardlib/gsim/sera_amplification_models.py
Labels: internal

#7053 Compute API/40
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/gsim/multi.py
Labels: internal

#7054 Compute API/41
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/avg_gmpe.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: bug

#7049 20201025 planar
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
Labels: enhancement

#7055 Compute API/42
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/projects/acme_2019.py
Labels: internal

#7056 Compute API/43
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
Labels: internal

#7057 Compute API/43
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: internal
