Repository gem/oq-engine, pull requests merged in 2021-03, with the labels that each got.

#6562 Using the Philox random generator when generating the epsilons
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_0.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_1.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  openquake/risklib/riskinput.py
Labels: internal

#6563 Finally removed the matrix of epsilons
  openquake/calculators/ebrisk.py
  openquake/calculators/scenario_risk.py
  openquake/risklib/riskinput.py
Labels: enhancement, performance

#6564 Fixed stress_hdf5 for Python < 3.8
  utils/stress_hdf5.py
Labels: bug

#6567 Removed redundant field e1 from ruptures dataset
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
Labels: internal

#6568 Changed the default for master_seed to 123456789
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_1h/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_0.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_1.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
Labels: internal

#6569 Storing the agg_loss_table as 64 bit floats
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/scientific.py
Labels: internal

#6571 Merged scenario_risk and ebrisk
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/scenario_risk/case_1/job_risk.ini
  openquake/qa_tests_data/scenario_risk/case_1g/job_risk.ini
  openquake/risklib/asset.py
Labels: internal

#6573 Refactored the risk calculators
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/risklib/asset.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#6574 Changed the EpsilonGetter to use one random stream for each event
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_2d/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_0.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_1.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#6575 Cleaned up the API of the risk distributions
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#6576 Generating different epsilons for different loss types
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.85.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/elt.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#6578 kubernetes readme
  k8s/README.md
  k8s/docker-compose.yaml
Labels: documentation

#6577 Initial work for the beta distribution
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6580 Refactored the survival methods
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#6581 Finally achieved concurrent_tasks independency for "PM" and "BT" distributions
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/util.py
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_1g/expected/avg_losses.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_1h/expected/losses_by_asset.csv
  openquake/risklib/read_nrml.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement

#6582 Fixed the avg_losses exporter when aggregate_by=id
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
Labels: bug

#6583 More refactoring of the risk calculators
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/risklib/riskinput.py
  openquake/risklib/scientific.py
Labels: internal

#6584 More refactoring of the risk calculators (2)
  openquake/calculators/ebrisk.py
  openquake/calculators/scenario_damage.py
  openquake/hazardlib/calc/gmf.py
  openquake/risklib/riskinput.py
  openquake/risklib/scientific.py
Labels: internal

#6586 Changed how the `agg_loss_table` is stored
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/scientific.py
Labels: internal, performance

#6588 More refactoring of the risk calculators (3)
  openquake/calculators/base.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
  openquake/calculators/getters.py
  openquake/calculators/scenario_damage.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6589 Changed event_based_risk to use sparse matrices
  openquake/calculators/ebrisk.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement, internal

#6590 More refactoring of the risk calculators (4)
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#6592 More refactoring of the risk calculators (5)
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#6593 More refactoring of the risk calculators (6)
  openquake/qa_tests_data/event_based_risk/case_1g/expected/avg_losses.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#6594 Vectorized event_based_risk and scenario_risk by asset
  debian/changelog
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/avg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: performance

#6597 Supported zero coefficient of variations with the beta distribution
  debian/changelog
  openquake/qa_tests_data/event_based_risk/case_1f/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_1f/vulnerability_model.xml
  openquake/risklib/riskinput.py
  openquake/risklib/scientific.py
Labels: enhancement

#6600 configuration files for zmq
  docker/zmq/docker-compose.yml
  docker/zmq/openquake.cfg
Labels: internal

#6601 Weighted the heavy sources in parallel in event based calculations
  debian/changelog
  openquake/calculators/event_based.py
Labels: performance

#6596 Fixed a small regression in the case of zero covs in the beta distribution
  openquake/qa_tests_data/event_based_risk/case_1f/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_1f/vulnerability_model.xml
  openquake/risklib/scientific.py
Labels: bug

#6603 Fixed the issue of negative coefficients in the beta distribution
  openquake/calculators/ebrisk.py
  openquake/commands/__main__.py
  openquake/risklib/riskinput.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/classical_test.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/riskmodels_test.py
Labels: bug

#6604 Removed computation of `avg_gmf` unless ground_motion_fields=true
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/risklib/scientific.py
Labels: internal, performance

#6605 Huge speedup in the calculation of avg_losses
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/risklib/tests/scientific_test.py
Labels: performance

#6606 Refactored scientific.py
  openquake/risklib/scientific.py
Labels: internal

#6607 Huge speedup for the case of no CoVs
  openquake/calculators/ebrisk.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: performance

#6608 Saving memory in event_based_risk
  openquake/calculators/ebrisk.py
Labels: performance

#6609 Yielding the losses by realization in event_based_risk to save memory
  openquake/calculators/ebrisk.py
  openquake/risklib/scientific.py
Labels: performance

#6610 Honored concurrent_tasks in event_based_risk again
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
Labels: performance

#6611 Huge speedup of aggregate losses
  openquake/calculators/base.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: performance

#6612 Yielding less arrays from event_based_risk
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/agglosses_taxo.txt
Labels: performance

#6613 Fixed bug with aggregate_by and --hc
  openquake/calculators/post_risk.py
Labels: bug

#6614 Optimized again avglosses
  openquake/calculators/ebrisk.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: performance

#6615 new dockerfile and add test on action docker
  .github/workflows/docker.yml
  docker/Dockerfile.dev
  docker/Dockerfile.engine
Labels: packaging

#6616 Optimized event_based_risk for covs != 0
  openquake/risklib/scientific.py
Labels: performance

#6617 Fixed bug in `oq engine --run job_h.ini job_r.ini`
  .github/workflows/docker.yml
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#6619 Removed the documentation on the ebrisk calculator
  doc/adv-manual/risk.rst
  doc/continental-scale-risk-calculations.md
  doc/engine-outputs.rst
Labels: documentation

#6618 Dockerfile for nigthly and latest
  .github/workflows/docker.yml
  .github/workflows/zmq.yml
  doc/docker/advanced.md
  doc/docker/cluster.md
  doc/docker/single.md
  doc/installing/docker.md
  docker/Dockerfile.dev
  docker/README.md
  docker/dask/Dockerfile.dev_master
  docker/dask/Dockerfile.dev_worker
  docker/dask/Dockerfile.master
  docker/dask/Dockerfile.worker
  docker/dask/docker-compose.yml
  docker/dask/openquake.cfg
  docker/docker-compose.yml
  docker/openquake.cfg
  docker/tests/README.md
  docker/tests/docker-compose.yml
  docker/zmq/Dockerfile.dev_master
  docker/zmq/Dockerfile.dev_worker
  docker/zmq/Dockerfile.master
  docker/zmq/Dockerfile.worker
  docker/zmq/docker-compose.yml
  docker/zmq/openquake.cfg
Labels: internal

#6620 Added parameter cholesky_limit
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap.py
Labels: enhancement

#6621 Cleaned the db before running the server tests
  .github/workflows/python-app.yml
  openquake/server/tests/views_test.py
  openquake/server/views.py
Labels: internal

#6623 Fixed big with oq checksum ssmLT.xml
  openquake/commands/checksum.py
Labels: bug

#6624 Shakemap functions
  debian/changelog
  openquake/hazardlib/shakemap.py
Labels: performance

#6626 fix(shakemap): correct logic in get_sitecol_shakemap to handle imts
  openquake/hazardlib/shakemap.py
Labels: bug

#6627 Extended get_ruptures to read MultiSurfaces
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/event_based_risk/recompute/ruptures.csv
  openquake/qa_tests_data/scenario/case_13/ruptures.csv
Labels: bug, enhancement

#6630 Removed discard_assets in ShakeMaps
  openquake/calculators/base.py
  openquake/hazardlib/shakemap.py
Labels: internal

#6633 Added a view `gsim_for_event`
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
Labels: enhancement, internal

#6632 Fixed hdf5.dumps
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/baselib/tests/hdf5_test.py
Labels: bug

#6634 Fixed scenario from ruptures to work with multiple TRTs
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_13/job.ini
Labels: enhancement

#6635 Optimized aggregating losses
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
Labels: performance

#6638 Removing sparse matrices for the losses
  openquake/calculators/event_based_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#6636 Added a generic shakemap.get_array
  openquake/calculators/base.py
  openquake/commands/download_shakemap.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: enhancement

#6643 Restored RuptureContext.__len__
  openquake/hazardlib/contexts.py
Labels: internal

#6645 Raised an error for aValue=-Inf
  debian/changelog
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/mfd/truncated_gr_test.py
Labels: enhancement

#6646 Refactoring/ground motion maps
  .gitignore
  openquake/calculators/base.py
  openquake/commands/download_shakemap.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/shakemap/maps.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemapconverter.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
Labels: internal

#6647 Honored `custom_site_id` in the hazard curves and UHS CSV exporters
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_38/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.16-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.5-PGA.csv
  openquake/qa_tests_data/classical/case_38/expected/quantile_curve-0.84-PGA.csv
  openquake/qa_tests_data/classical/case_38/job.ini
  openquake/qa_tests_data/classical/case_38/site_model.xml
Labels: enhancement

#6641 remove -c from bash from Dockerfile.dev
  docker/Dockerfile.dev
  openquake/baselib/zeromq.py
Labels: internal

#6648 Supporting flexible exposures
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/scenario/case_16/Example_Exposure.csv
  openquake/qa_tests_data/scenario/case_16/Example_Exposure.xml
  openquake/qa_tests_data/scenario/case_16/__init__.py
  openquake/qa_tests_data/scenario/case_16/job.ini
  openquake/risklib/asset.py
Labels: enhancement

#6651 Refactor get_sitecol_shakemap
  openquake/calculators/base.py
  openquake/hazardlib/shakemap/maps.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: internal

#6652 Fixes a bug in the calculation of ztor with a kite fault surface
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
Labels: bug

#6650 Ya15 j vs30 760
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
Labels: bug

#6656 Fixed `pandas.read_csv`
  openquake/baselib/hdf5.py
  openquake/calculators/classical.py
  openquake/calculators/getters.py
Labels: bug, internal

#6657 Added a check on dbserver.host
  openquake/baselib/parallel.py
Labels: enhancement, internal

#6654 Refactor to_gmfs and faster calculation method
  debian/changelog
  openquake/calculators/base.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: performance

#6659 Removed MAXSITES check in ShakeMaps
  openquake/hazardlib/shakemap/gmfs.py
Labels: internal

#6662 Ignoring RankWarning
  openquake/hazardlib/gsim/projects/acme_2019.py
Labels: internal
