Repository gem/oq-engine, pull requests merged in 2021-09, with the labels that each got.

#7142 Improved error for area_source_discretization too large
  debian/changelog
  openquake/commands/info.py
  openquake/hazardlib/geo/polygon.py
Labels: enhancement

#7143 Changed the aggcurves exporter
  demos/risk/EventBasedDamage/job.ini
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
Labels: outputs

#7145 Added command `oq info consequences`
  debian/changelog
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
  openquake/risklib/scientific.py
  utils/build_vtable
Labels: documentation

#7144 Check number_of_logic_tree_samples with collect_rlzs and hazard_calculation_id
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#7147 Fixed the API docs
  doc/sphinx/openquake.baselib.rst
  doc/sphinx/openquake.calculators.rst
  doc/sphinx/openquake.commonlib.rst
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/calculators/getters.py
  openquake/commonlib/datastore.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008.py
  openquake/hazardlib/gsim/gulerce_2017.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/stewart_2016.py
  openquake/hazardlib/gsim/stewart_2016_vh.py
Labels: documentation

#7148 Added missing pre-headers in some outputs
  openquake/calculators/export/hazard.py
Labels: outputs

#7149 Minor edits to whats-new for 3.12
  doc/whats-new.md
Labels: documentation

#7152 A few additional minor edits to whats-new 3.12
  doc/whats-new.md
Labels: documentation

#7151 Trying to reproduce the extreme GMVs
  openquake/calculators/extract.py
  openquake/hazardlib/contexts.py
  utils/max_gmv0
Labels: investigation

#7140 Work on the What's New
  doc/whats-new.md
Labels: documentation

#7136 Fixes ASK14
  debian/changelog
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/tests/gsim/abrahamson_2014_test.py
  openquake/hazardlib/tests/gsim/data/ASK14/ASK14_ResMEAN_RegCAL.csv
  openquake/hazardlib/tests/gsim/data/ASK14/ASK14_ResMEAN_RegCHN.csv
  openquake/hazardlib/tests/gsim/data/ASK14/ASK14_ResMEAN_RegJPN.csv
  openquake/hazardlib/tests/gsim/data/ASK14/ASK14_ResMEAN_RegTWN.csv
Labels: bug

#7154 Supporting h5py 3.1
  openquake/calculators/base.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/util.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/valid.py
  openquake/risklib/asset.py
  setup.py
Labels: packaging

#7132 Restored the classical tiling calculator
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_14/job.ini
Labels: performance

#7155 Reduced the memory occupation of the tiling calculator
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/calculators/views.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/lt_test.py
Labels: performance

#7156 Renamed "number"-> "value-number"
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/multi_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/multi_risk/case_1/expected/agg_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk.csv
  openquake/qa_tests_data/multi_risk/case_1/expected/asset_risk_2.csv
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/server/tests/views_test.py
Labels: internal

#7157 Disabled version check
  openquake/engine/engine.py
Labels: enhancement

#7158 Fixed a bug in abrahamson_gulerce_2020
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/qa_tests_data/classical/case_70/__init__.py
  openquake/qa_tests_data/classical/case_70/area.xml
  openquake/qa_tests_data/classical/case_70/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_70/gmmLT_corrected_for_site_effects_ecu.xml
  openquake/qa_tests_data/classical/case_70/job.ini
  openquake/qa_tests_data/classical/case_70/site_model_uniform_grid_ampcodes.csv
  openquake/qa_tests_data/classical/case_70/ssmLT.xml
Labels: bug

#7160 Added conditional spectrum in hazardlib
  openquake/hazardlib/__init__.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/cross_correlation.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/data/lt01.xml
  openquake/hazardlib/tests/calc/data/sm01.xml
  openquake/hazardlib/tests/calc/data/ssm.xml
  openquake/hazardlib/tests/calc/expected/spectra1.csv
Labels: enhancement

#7161 Added conditional spectrum in hazardlib/2
  openquake/hazardlib/__init__.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/data/lt01.xml
  openquake/hazardlib/tests/calc/data/lt02.xml
  openquake/hazardlib/tests/calc/data/sm02.xml
  openquake/hazardlib/tests/calc/expected/spectra1.csv
  openquake/hazardlib/tests/calc/expected/spectra2.csv
  openquake/hazardlib/tests/calc/expected/spectra6.csv
Labels: internal

#7163 Added conditional spectrum in hazardlib/3
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/data/lt01.xml
  openquake/hazardlib/tests/calc/data/lt02.xml
  openquake/hazardlib/tests/calc/data/point.xml
  openquake/hazardlib/tests/calc/expected/spectra2.csv
  openquake/hazardlib/tests/calc/expected/spectra6.csv
Labels: enhancement

#7164 Conditional spectrum engine side/1
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/qa_tests_data/conditional_spectrum/case_1/job.ini
Labels: enhancement

#7168 Improved the documentation on rupture sampling
  demos/hazard/EventBasedPSHA/job.py
  doc/adv-manual/rupture-sampling.rst
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/gsim_lt.py
Labels: documentation

#7165 Conditional spectrum, engine side/2
  debian/changelog
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/job.ini
  openquake/server/db/actions.py
Labels: enhancement

#7170 Added occupants fields to agg_values dataset
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: internal

#7171 Fixed the ShakeMap calculator failing with `get_array_usgs_id() got an unexpected keyword argument 'id'`
  debian/changelog
  openquake/hazardlib/shakemap/parsers.py
Labels: bug, backport

#7166 Systemd services dependencies
  install.py
Labels: internal

#7172 Relaxed the type of backarc
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/ghofrani_atkinson_2014.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
Labels: enhancement

#7173 TimeoutError for the DbServer commands
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/baselib/zeromq.py
Labels: internal

#7176 Removed the deprecated disaggregation XML exporters
  debian/changelog
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/tests/expected_disagg.xml
  openquake/commonlib/tests/hazard_writers_test.py
Labels: outputs

#7177 Made the kind of installation mandatory in `install.py`
  install.py
Labels: installation

#7179 add version option to ansible playbook
  ansible/cluster/oq_cluster.yaml
  ansible/cluster/oq_zmq.yaml
  ansible/oqengine/vars/main.yml
Labels: installation

#7181 Removed requirements-extra files
  requirements-extra-py36-linux64.txt
  requirements-extra-py36-macos.txt
  requirements-extra-py36-win64.txt
  requirements-extra-py37-linux64.txt
  requirements-extra-py37-macos.txt
  requirements-extra-py37-win64.txt
  requirements-extra-py38-linux64.txt
  requirements-extra-py38-macos.txt
  requirements-extra-py38-win64.txt
Labels: installation

#7182 Removed prctl
  openquake/baselib/parallel.py
  requirements-py36-linux64.txt
  requirements-py37-linux64.txt
  setup.py
Labels: installation, internal

#7183 Renamed individual_curves->individual_rlzs
  debian/changelog
  demos/hazard/Disaggregation/job.ini
  demos/hazard/LogicTreeCase1ClassicalPSHA/job.ini
  demos/risk/EventBasedRisk/job.ini
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/qa_tests_data/classical/case_10/job.ini
  openquake/qa_tests_data/classical/case_11/job.ini
  openquake/qa_tests_data/classical/case_14/job.ini
  openquake/qa_tests_data/classical/case_16/job.ini
  openquake/qa_tests_data/classical/case_17/job.ini
  openquake/qa_tests_data/classical/case_18/job.ini
  openquake/qa_tests_data/classical/case_20/job.ini
  openquake/qa_tests_data/classical/case_21/job.ini
  openquake/qa_tests_data/classical/case_28/job.ini
  openquake/qa_tests_data/classical/case_52/job.ini
  openquake/qa_tests_data/classical/case_58/job.ini
  openquake/qa_tests_data/classical/case_58/job_case01.ini
  openquake/qa_tests_data/classical/case_58/job_case02.ini
  openquake/qa_tests_data/classical/case_59/job.ini
  openquake/qa_tests_data/classical/case_61/job.ini
  openquake/qa_tests_data/classical/case_7/job.ini
  openquake/qa_tests_data/classical/case_73/job.ini
  openquake/qa_tests_data/classical/case_8/job.ini
  openquake/qa_tests_data/disagg/case_2/job.ini
  openquake/qa_tests_data/disagg/case_3/job.ini
  openquake/qa_tests_data/disagg/case_6/job.ini
  openquake/qa_tests_data/disagg/case_7/job.ini
  openquake/qa_tests_data/event_based/case_2/job_2.ini
  openquake/qa_tests_data/event_based/case_25/job.ini
  openquake/qa_tests_data/event_based/case_25/job2.ini
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/event_based_risk/case_1/job_eb.ini
  openquake/qa_tests_data/event_based_risk/case_2/job.ini
  openquake/qa_tests_data/event_based_risk/case_2/job_loss.ini
  openquake/qa_tests_data/event_based_risk/case_4/job.ini
  openquake/qa_tests_data/event_based_risk/case_7a/job_r.ini
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
  openquake/qa_tests_data/event_based_risk/case_miriam/job.ini
  openquake/qa_tests_data/event_based_risk/occupants/job.ini
  openquake/qa_tests_data/scenario/case_15/job.ini
Labels: enhancement, inputs

#7184 Replaces 15 classes with aliases in boore_2014
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/stewart_2016_vh.py
  openquake/hazardlib/tests/gsim/boore_2014_test.py
Labels: internal

#7185 Documented the difference between sampling and full enumeration in event_based
  doc/adv-manual/rupture-sampling.rst
  openquake/calculators/tests/event_based_test.py
  openquake/qa_tests_data/event_based/case_3/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_3/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_3/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based/case_3/job.ini
Labels: documentation

#7186 Added a check for invalid consequence files
  openquake/commonlib/readinput.py
Labels: enhancement

#7180 Made it possible to pass a port to install.py
  install.py
Labels: installation

#7187 remove Celery from requirements files
  .github/workflows/linux_gdal_test.yml
  .github/workflows/macos_gdal_test.yml
  .github/workflows/windows_gdal_test.yml
  requirements-py36-linux64.txt
  requirements-py37-linux64.txt
  requirements-py38-linux64.txt
Labels: installation

#7175 Removed multi_user flag
  ansible/cluster/templates/openquake.zmq.cfg.j2
  debian/patches/openquake.cfg.patch
  doc/installing/cluster-celery.md
  doc/installing/cluster.md
  docker/openquake.cfg
  install.py
  openquake/baselib/__init__.py
  openquake/commands/db.py
  openquake/commands/dbserver.py
  openquake/commands/engine.py
  openquake/commands/workers.py
  openquake/engine/openquake.cfg
  openquake/server/dbserver.py
Labels: proposal

#7191 Exporting enough information to compute the mean disaggregation
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
Labels: outputs

#7189 Change requirements files for new version of h5py and setproctitle
  .github/workflows/linux_install.yml
  .github/workflows/macos_install.yml
  .github/workflows/windows_install.yml
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/ucerf_base.py
  openquake/commands/reduce_sm.py
  openquake/risklib/asset.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
Labels: installation

#7192 switch from download.openquake.org to github run demos
  .github/workflows/linux_gdal_test.yml
  .github/workflows/linux_install.yml
  .github/workflows/macos_gdal_test.yml
  .github/workflows/macos_install.yml
  .github/workflows/windows_gdal_test.yml
  .github/workflows/windows_install.yml
Labels: internal

#7193 Renamed conversion -> risk_id in the header of the taxonomy mapping file
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map_structural.csv
Labels: inputs

#7195 Fixed the multi_user check in oq dbserver
  openquake/server/dbserver.py
Labels: bug

#7190 adding get_top_edge_depth to gridded surfaces
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
Labels: bug

#7196 Improved error checking when reading the taxonomy mapping file
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario_risk/case_master/taxonomy_mapping.csv
Labels: enhancement

#7197 Made sure the latest commit of a branch is downloaded
  install.py
Labels: installation

#7198 Update docker action to test multi_user behavior
  .github/workflows/docker_dev.yml
  .github/workflows/windows_install.yml
Labels: installation

#7199 Added a disaggregation warning for non-contributing realizations
  openquake/calculators/disaggregation.py
  openquake/qa_tests_data/disagg/case_6/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_6/job.ini
Labels: internal

#7202 Fixed bug in the Mag_Lon_Lat exporter
  openquake/calculators/extract.py
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
Labels: bug, backport

#7201 Minor edits to rupture sampling doc page
  doc/adv-manual/rupture-sampling.rst
Labels: documentation

#7200 use path /run/systemd/system to create systemd files
  install.py
Labels: installation

#7203 Making easier to compute the mean disaggregation
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/commands/plot.py
  openquake/qa_tests_data/disagg/case_1/expected_output/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat_TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_6/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_6/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-traditional-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-1.csv
Labels: outputs

#7204 Add intensity_measure_types_and_levels to classical_risk example
  doc/manual/oqum/risk/verbatim/config_classical_hazard.ini
Labels: documentation

#7206 Fixed the recognition of source specific logic trees
  openquake/calculators/classical.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/lt.py
Labels: internal

#7207 Fixed order of arguments in re.match"
  install.py
Labels: bug

#7208 Extended the conditional_spectrum calculator to multiple sites
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/job.ini
  openquake/server/db/actions.py
Labels: enhancement

#7209 Fixed the disaggregation outputs in the manual
  doc/manual/oqum/hazard/02_outputs.tex
  doc/manual/oqum/hazard/02b_output_disaggregation.tex
  doc/manual/oqum/hazard/verbatim/output_disaggregation_matrix.tex
Labels: documentation

#7213 Started documenting Source Specific Logic Trees
  doc/adv-manual/index.rst
  doc/adv-manual/sslt.rst
  openquake/commonlib/logictree.py
  openquake/hazardlib/lt.py
Labels: documentation

#7212 Improved the view `branch_ids`
  openquake/calculators/views.py
  openquake/commonlib/logictree.py
Labels: enhancement

#7215 Added a check against duplicated branchset IDs
  debian/changelog
  doc/manual/oqum/risk/02_config_classical_risk.tex
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/classical/case_58/sscLT.xml
  openquake/qa_tests_data/classical/case_58/sscLTcase01.xml
Labels: enhancement

#7118 Manea 2021
  CONTRIBUTORS.txt
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/manea_2021.py
  openquake/hazardlib/tests/gsim/data/MANEA20/Manea_2020_inter.csv
  openquake/hazardlib/tests/gsim/data/MANEA20/Manea_2020_intra.csv
  openquake/hazardlib/tests/gsim/data/MANEA20/Manea_2020_mean.csv
  openquake/hazardlib/tests/gsim/data/MANEA20/Manea_2020_total.csv
  openquake/hazardlib/tests/gsim/manea_2021_test.py
Labels: enhancement

#7217 Updated csm2rup to use the preclassical calculator
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  utils/csm2rup
Labels: internal

#7220 Documented the event based damage demo
  demos/risk/EventBasedDamage/job.ini
  doc/adv-manual/event-based-damage.rst
  doc/adv-manual/index.rst
  doc/adv-manual/risk-features.rst
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
Labels: documentation

#7221 Deprecated consequence models in XML format
  debian/changelog
  openquake/risklib/riskmodels.py
Labels: enhancement, inputs

#7222 Replaced the XML consequence model with a CSV in the ScenarioDamage demo
  demos/risk/ScenarioDamage/consequence_model.xml
  demos/risk/ScenarioDamage/consequences.csv
  demos/risk/ScenarioDamage/job_risk.ini
  doc/adv-manual/event-based-damage.rst
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_damage/case_11/job.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_a.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_b.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_c.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_d.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_a.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_b.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_c.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_d.ini
  openquake/qa_tests_data/event_based_damage/case_14/job.ini
  utils/cons2csv
Labels: documentation

#7218 actions for upgrade procedure of engine using install.py
  .github/workflows/docker_dev.yml
  .github/workflows/upgrade_procedure.yml
  install.py
Labels: installation

#7224 Added parameter `discrete_damage_distribution`
  debian/changelog
  openquake/calculators/scenario_damage.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_11/job.ini
Labels: enhancement

#7226 Changed default discrete_damage_distribution=false
  debian/changelog
  openquake/calculators/scenario_damage.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_1/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_2/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_3/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_4/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_5/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_5a/expected/damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/dmg_by_taxon.csv
  openquake/qa_tests_data/scenario_damage/case_7/job_r.ini
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_9/job.ini
Labels: performance

#7227 Replaced agg_losses-XXX datasets with a single aggrisk dataframe
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/engine/engine.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk_sampling.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_2/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/agg_loss.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_0.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/agg_structural_1.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_8/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/agg_loss.csv
  openquake/server/db/actions.py
Labels: outputs

#7228 Added `aggrisk` output to event based damage calculation
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk_sampling.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_1g/expected/agg-gsimltp_@.csv
  openquake/qa_tests_data/scenario_risk/case_2/expected/agg.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/agg_loss.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_6a/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_8/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/agg_loss.csv
  openquake/risklib/scientific.py
Labels: outputs

#7229 Refactored the aggcurves exporter to export more columns
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
Labels: outputs

#7225 Changed csm2rup to be fast on point sources
  openquake/hazardlib/geo/surface/planar.py
  utils/csm2rup
Labels: performance

#7230 Replaced agg_curves-rlzs with aggcurves
  doc/adv-manual/oq-commands.rst
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/outputs/agg_curves-rlzs.csv
  openquake/engine/engine.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/agg_curves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/agg_curves-rlz-001.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/agg_curves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/aggcurves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/agg_curves-rlz-000.csv
  openquake/qa_tests_data/event_based_risk/occupants/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_curves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/aggcurves.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/aggcurves_5439.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.15.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.5.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/agg_curves-quantile-0.85.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves.csv
  openquake/server/db/actions.py
Labels: outputs

#7232 Changed the algorithm to compute risk_by_event to use DataFrames and not arrays
  openquake/calculators/event_based_risk.py
Labels: internal

#7233 Removed parallelization from the post_risk calculator
  openquake/calculators/post_risk.py
Labels: internal

#7234 Extended event_based_damage to work with discrete damage distributions
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/job_a.ini
  openquake/risklib/scientific.py
Labels: enhancement

#7236 Replacing scenario_damage with event_based_damage
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages2.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_2.csv
  openquake/qa_tests_data/scenario_damage/case_2/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_3/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_5a/gmpe_logic_tree.xml
  openquake/qa_tests_data/scenario_damage/case_5a/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/damages.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/losses_asset.csv
Labels: performance

#7237 Restored secondary losses
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages2.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_2.csv
Labels: internal

#7238 Introduced parameter `gmf_max_gb`
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
Labels: internal

#7239 Enhanced the avg_gmf plotter
  openquake/commands/plot.py
Labels: internal

#7240 Storing `aggrisk` inconditionally in event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_9/expected/aggrisk.csv
  openquake/risklib/asset.py
Labels: outputs
