Repository gem/oq-engine, pull requests merged in 2021-06, with the labels that each got.

#6827 Stored the damage distribution for the most dangerous event
  openquake/calculators/event_based_damage.py
Labels: internal

#6829 Fixed extract damages-rlzs
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_damage_test.py
Labels: bug

#6830 Focal enabled
  packager.sh
Labels: packaging

#6832 Introduced consequences != losses
  openquake/calculators/event_based_damage.py
  openquake/qa_tests_data/event_based_damage/case_15/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/dmgcsq.csv
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#6833 write_csv in UTF-8
  debian/changelog
  openquake/baselib/writers.py
  openquake/commands/check_input.py
Labels: bug

#6834 Removed the dmgcsq output
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/dmgcsq.csv
Labels: internal

#6835 Added a plotter for the damage curves
  demos/risk/EventBasedDamage/job.ini
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: enhancement, internal

#6836 Renamed cname->consequence
  debian/changelog
  demos/risk/EventBasedDamage/consequences_by_taxonomy.csv
  doc/adv-manual/risk-features.rst
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_damage/case_14/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_15/consequences_by_taxonomy.csv
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#6826 Some support to fix latin1 files
  openquake/commands/shell.py
  openquake/risklib/asset.py
Labels: enhancement

#6837 Producing aggcurves only if there are consequences
  openquake/calculators/event_based_damage.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/commands/plot.py
  openquake/commands/shell.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
Labels: outputs

#6839 Added a check on known consequences
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/risklib/scientific.py
Labels: enhancement

#6840 Add ignore_encoding_errors
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_17/Exposure_Chile_all_costs.xml
  openquake/qa_tests_data/scenario/case_17/Exposure_Res_Chile.csv
  openquake/qa_tests_data/scenario/case_17/__init__.py
  openquake/qa_tests_data/scenario/case_17/agg_keys.org
  openquake/qa_tests_data/scenario/case_17/job.ini
  openquake/risklib/asset.py
Labels: enhancement, inputs

#6841 Small update for MSR
  openquake/hazardlib/scalerel/__init__.py
Labels: internal

#6842 Forbid multiple inheritance in GMPE hierarchies
  debian/changelog
  openquake/hazardlib/gsim/atkinson_boore_2003.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/multi.py
Labels: enhancement

#6844 Removed 50 lines of code
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/projects/acme_base.py
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
Labels: internal

#6845 Refactored the CoeffsTable
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_atkinson_2011.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#6846 Added a limit of 12 characters to IMT names
  debian/changelog
  openquake/hazardlib/imt.py
Labels: enhancement

#6847 Introduced jittable decorator
  openquake/baselib/performance.py
Labels: performance

#6851 Improved SingleSiteOptTestCase
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: performance

#6853 Disabled (temporarily) the infrastructure for the single-site optimization
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
Labels: internal

#6852 Infrastructure for the numpy-oriented API
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/test_2021.py
  openquake/hazardlib/gsim/toro_2002.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/valid.py
Labels: internal, performance

#6854 Doctesting hazardlib
  .github/workflows/engine_test.yml
  openquake/hazardlib/gsim/base.py
Labels: bug, internal

#6855 Vectorized by gsim in `get_mean_stdt`
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_gmpe.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/test_2021.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: internal

#6856 Export avg_risk.csv instead of avg_damages-rlz-000
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_risk.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk.csv
Labels: enhancement, outputs

#6857 Fixed scenario with KiteSurfaces
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/calc/stochastic.py
  openquake/qa_tests_data/classical/case_65/expected/full_ruptures.csv
  openquake/qa_tests_data/classical/case_65/expected/gmf_data.csv
  openquake/qa_tests_data/classical/case_65/expected/ruptures.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_risk-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-rlz-000.csv
  openquake/qa_tests_data/scenario/case_18/__init__.py
  openquake/qa_tests_data/scenario/case_18/gmpe_rrup.xml
  openquake/qa_tests_data/scenario/case_18/issykata_kite_earthquake_rupture_model.xml
  openquake/qa_tests_data/scenario/case_18/job.ini
Labels: bug

#6858 Fixed a bug in scenarios from CSV ruptures with wrong TRTs
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_19/__init__.py
  openquake/qa_tests_data/scenario/case_19/gmpe_sif.xml
  openquake/qa_tests_data/scenario/case_19/job.ini
  openquake/qa_tests_data/scenario/case_19/ruptures.csv
  openquake/qa_tests_data/scenario/case_19/sitemodel.csv
Labels: bug

#6859 Renamed Test2021 as ExampleA2021
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: internal

#6860 Added test for ExampleA2021 with two sites
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: internal

#6861 Passing the ContextMaker to `hazard_curve.classical`
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/classical/case_39/job.ini
Labels: internal

#6862 Removed the ? syntax for MagDepDist
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/filters.py
Labels: internal

#6863 Compiling and caching the jittable function when instantiating the ContextMaker
  openquake/baselib/performance.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: performance

#6864 No splitting the sources with the new API with 1 site
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
Labels: performance

#6865 Made visible the warning on non-contributing TRTs for all calculators
  debian/changelog
  openquake/calculators/base.py
Labels: enhancement

#6868 By default store the individual curves if N==1
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_16/job.ini
Labels: outputs

#6869 Improved the warning about non-contributing TRTs
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/tests/calc/stochastic_test.py
  openquake/qa_tests_data/classical/case_56/expected/hcurves.csv
  openquake/qa_tests_data/classical/case_56/source_model2.xml
Labels: enhancement

#6870 Added support for clustering UHS
  openquake/calculators/base.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commonlib/logictree.py
  openquake/qa_tests_data/classical/case_56/source_model_logic_tree.xml
Labels: enhancement

#6872 Improved disagg_by_grp
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/stochastic.py
Labels: internal

#6875 Stored the missing branchset attributes
  openquake/commonlib/logictree.py
Labels: internal

#6876 First version of `oq reduce_lt`
  openquake/commands/reduce_lt.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/data/gmmLT.xml
  openquake/commonlib/tests/data/ssmLT.xml
  openquake/commonlib/tests/logictree_test.py
Labels: enhancement

#6808 Multi tests
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/data/profiles08/cs_50a.txt
  openquake/hazardlib/tests/geo/surface/data/profiles08/cs_50b.txt
  openquake/hazardlib/tests/geo/surface/data/profiles08/cs_51a.txt
  openquake/hazardlib/tests/geo/surface/data/profiles08/cs_51b.txt
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: WIP

#6877 Added an utility to print the site parameters around a given city
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
Labels: internal

#6878 Moved the GsimLogicTree class in hazardlib
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/gsim_lt.py
Labels: internal

#6880 Added method `ProbabilityMap.combine`
  openquake/calculators/classical.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_test.py
Labels: internal

#6879 Refactored check_gsim to support the numpy-oriented API
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/check_gsim.py
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_high.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_low.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_ENA_med.csv
  openquake/hazardlib/tests/gsim/data/SADIGH97/SADIGH1997_ROCK_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SADIGH97/SADIGH1997_ROCK_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/sadigh_1997_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: internal

#6881 Added stdtypes to the signature of calc_mean_stds
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: internal

#6883 Minor cleanup of the GmfComputer
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/check_gsim.py
Labels: internal

#6882 Supported consequences split in multiple files
  debian/changelog
  openquake/commonlib/readinput.py
Labels: enhancement, inputs

#6885 Support the numpy-oriented API in scenario and event_based calculations
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/const.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/check_gsim.py
  openquake/hazardlib/tests/gsim/mgmpe/cy14_site_term_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_linear_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
  openquake/hazardlib/tests/gsim/mgmpe/split_sigma_gmpe_test.py
Labels: internal

#6884 Changed the minimum_distance
  debian/changelog
  doc/adv-manual/special-features.rst
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/outputs/realizations.csv
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_12/expected/hazard_curve-smltp_b1-gsimltp_b1_b2.csv
  openquake/qa_tests_data/classical/case_12/job.ini
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
  openquake/qa_tests_data/event_based_risk/case_master/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
  openquake/qa_tests_data/scenario/case_9/gmf.csv
  openquake/qa_tests_data/scenario/case_9/gsim_logic_tree.xml
  openquake/qa_tests_data/scenario/case_9/job.ini
Labels: enhancement

#6886 Push docker image nightly from the action
  .github/workflows/docker.yml
Labels: packaging

#6890 Turned get_mean_stds, get_pmap and gen_poes into methods of the ContextMaker
  doc/tutorials/the-datastore/datastore.org
  doc/tutorials/the-datastore/ex4.py
  doc/tutorials/the-datastore/ex5.py
  openquake/calculators/conditional_spectrum.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/check_gsim.py
Labels: internal

#6888 Refactored sadigh_1997
  openquake/hazardlib/gsim/sadigh_1997.py
Labels: internal

#6892 Moved the kotha_2016 CoeffsTable into an external file
  openquake/hazardlib/gsim/kotha_2016.csv
  openquake/hazardlib/gsim/kotha_2016.py
Labels: internal

#6891 Removed duplicate field in the kotha_2016 CoeffsTable
  openquake/hazardlib/gsim/kotha_2016.csv
Labels: bug

#6893 Added classmethod CoeffsTable.fromdict
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_base.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/tromans_2019.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#6894 Replace dicts with numpy structs
  openquake/baselib/general.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/kanno_2006.py
  openquake/hazardlib/gsim/nath_2012.py
  openquake/hazardlib/gsim/raghukanth_iyengar_2007.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#6895 Explicited the underlying GSIMs in can15/sinter.py
  openquake/hazardlib/gsim/can15/sinter.py
Labels: internal

#6896 Explicited more underlying GSIMs
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/tests/gsim/kotha_2020_test.py
  openquake/qa_tests_data/event_based/case_19/gmmLT_analytical.xml
Labels: internal

#6897 Replaced IMT classes with factory functions
  debian/changelog
  openquake/baselib/general.py
  openquake/commands/info.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/bradley_2013b.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
  openquake/hazardlib/gsim/frankel_1996.py
  openquake/hazardlib/gsim/germany_2018.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/gsim/munson_thurber_1997.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/tests/imt_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/hazard_curve-mean-PGA.xml
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/sep/classes.py
Labels: enhancement

#6899 Replace methods with functions in dozens of GMPEs
  openquake/commands/info.py
  openquake/hazardlib/gsim/__init__.py
  openquake/hazardlib/gsim/abrahamson_silva_1997.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/allen_2012.py
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/gsim/baumont_2018.py
  openquake/hazardlib/gsim/bommer_2009.py
  openquake/hazardlib/gsim/campbell_1997.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2003.py
  openquake/hazardlib/gsim/climent_1994.py
  openquake/hazardlib/gsim/convertito_2012.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/faccioli_cauzzi_2006.py
  openquake/hazardlib/gsim/geomatrix_1993.py
  openquake/hazardlib/gsim/hong_goda_2007.py
  openquake/hazardlib/gsim/idriss_2014.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/lanzano_luzi_2019.py
  openquake/hazardlib/gsim/megawati_pan_2010.py
  openquake/hazardlib/gsim/mgmpe/cy14_site_term.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/gsim/pankow_pechmann_2004.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/shahjouei_pezeshk_2016.py
  openquake/hazardlib/gsim/sharma_2009.py
  openquake/hazardlib/gsim/skarlatoudis_2013.py
  openquake/hazardlib/gsim/somerville_2001.py
  openquake/hazardlib/gsim/travasarou_2003.py
  openquake/hazardlib/gsim/vanhoutte_2018.py
  openquake/hazardlib/tests/gsim/mgmpe/split_sigma_gmpe_test.py
Labels: internal

#6901 Methods->functions/3
  openquake/hazardlib/gsim/toro_2002.py
  openquake/hazardlib/gsim/yu_2013.py
Labels: internal

#6902 Methods->functions/4
  openquake/hazardlib/gsim/youngs_1997.py
Labels: internal

#6905 Methods->functions/7
  openquake/hazardlib/gsim/zhao_2016.py
Labels: internal

#6903 Methods->functions/5
  openquake/hazardlib/gsim/tavakoli_pezeshk_2005.py
Labels: internal

#6904 Methods->functions/6
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_2018.py
  openquake/hazardlib/gsim/atkinson_boore_1995.py
  openquake/hazardlib/gsim/bradley_2013b.py
  openquake/hazardlib/tests/gsim/abrahamson_2014_test.py
Labels: internal

#6906 Methods->functions/8
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/yu_2013.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/nga_east_total_sigma_test.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
Labels: internal

#6907 Methods->functions/9
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2003.py
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
Labels: internal

#6908 Some changes to the numpy-oriented API
  openquake/baselib/general.py
  openquake/commands/show.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/example_a_2021.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#6909 Restored monitoring in the ContextMaker, accidentally removed
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: bug, internal

#6910 Forced a name convention on the coefficient tables
  debian/changelog
  openquake/hazardlib/gsim/armenia_2016.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bindi_2011.py
  openquake/hazardlib/gsim/boore_atkinson_2011.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/sslab.py
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/hong_goda_2007.py
  openquake/hazardlib/gsim/mcverry_2006_chch.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/pezeshk_2011.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/zhao_2016.py
Labels: internal

#6911 Methods->functions/10
  openquake/hazardlib/gsim/allen_2012_ipe.py
  openquake/hazardlib/gsim/tromans_2019.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
Labels: internal

#6912 Improved the numba support
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
Labels: internal

#6913 Methods->functions/11
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
Labels: internal

#6916 Methods->functions/12
  openquake/hazardlib/gsim/si_midorikawa_1999.py
Labels: internal

#6918 Methods->functions/13
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/lin_lee_2008.py
  openquake/hazardlib/gsim/tusa_langer_2016.py
Labels: internal

#6917 Making sure risk_by_event has no duplicates
  openquake/calculators/event_based_risk.py
Labels: bug, investigation

#6919 Methods->functions/14
  openquake/hazardlib/gsim/atkinson_boore_1995.py
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
  openquake/hazardlib/gsim/ecos_2009.py
  openquake/hazardlib/gsim/frankel_1996.py
  openquake/hazardlib/gsim/garcia_2005.py
  openquake/hazardlib/gsim/germany_2018.py
  openquake/hazardlib/gsim/gulerce_2017.py
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term_linear.py
  openquake/hazardlib/gsim/nath_2012.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/silva_2002.py
  openquake/hazardlib/gsim/somerville_2009.py
  openquake/hazardlib/gsim/toro_1997.py
  openquake/hazardlib/gsim/zhao_2006.py
  openquake/hazardlib/gsim/zhao_2006_swiss.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_linear_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
Labels: internal

#6920 Methods->functions/15
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/gsim/mcverry_2006_chch.py
  openquake/hazardlib/tests/gsim/mcverry_2006_test.py
Labels: internal

#6921 Fixed eid to be an uint32, not float64!
  debian/changelog
  openquake/risklib/riskmodels.py
Labels: bug

#6922 Methods->functions/16
  openquake/hazardlib/gsim/akkar_2014.py
  openquake/hazardlib/gsim/boore_1993.py
  openquake/hazardlib/gsim/drouet_2015_brazil.py
  openquake/hazardlib/gsim/ghofrani_atkinson_2014.py
  openquake/hazardlib/gsim/kanno_2006.py
  openquake/hazardlib/gsim/lin_2009.py
Labels: internal

#6923 Methods->functions/16
  openquake/hazardlib/gsim/afshari_stewart_2016.py
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/berge_thierry_2003.py
  openquake/hazardlib/gsim/campbell_2003.py
  openquake/hazardlib/gsim/dost_2004.py
  openquake/hazardlib/gsim/rietbrock_edwards_2019.py
Labels: internal

#6924 Methods->functions/17
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss.py
  openquake/hazardlib/gsim/dowrickrhoades_2005.py
  openquake/hazardlib/gsim/rietbrock_2013.py
Labels: internal

#6925 Methods->functions/18
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/pezeshk_2011.py
Labels: internal
