Repository gem/oq-engine, pull requests merged in 2021-05, with the labels that each got.

#6739 Improving convolution and adding test for a case where the output included steps
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/data/convolution/amplification.csv
  openquake/hazardlib/tests/data/convolution/hazard_curve.csv
  openquake/hazardlib/tests/data/convolution/hazard_curve_expected.csv
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/classical/case_49/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_49/expected/hcurves-SA(0.21).csv
  openquake/qa_tests_data/classical/case_49/expected/hcurves-SA(1.057).csv
  openquake/qa_tests_data/classical/case_49/expected/uhs.csv
Labels: bug, enhancement

#6741 Restored the *most important action* and renamed it to main.yml
  .github/workflows/main.yml
  openquake/qa_tests_data/classical/case_55/expected/ampl_curve-PGA.csv
  openquake/qa_tests_data/classical/case_55/expected/ampl_curve-bis.csv
  openquake/qa_tests_data/classical/case_55/expected/hazard_curve-mean-PGA.csv
Labels: internal

#6742 Small refactoring of the datastore
  openquake/baselib/hdf5.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/scenario_damage/case_4b/expected/portfolio_damage.rst
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
Labels: internal

#6744 Small renaming
  openquake/commonlib/logictree.py
  openquake/commonlib/source_reader.py
Labels: internal

#6745 Changed the validation of the parameters to be on by default
  .github/workflows/engine_test.yml
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
Labels: internal

#6747 Removed the validate flag in get_oqparam
  openquake/commonlib/oqzip.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#6746 Refactored the logging mechanism
  doc/adv-manual/developing.rst
  openquake/calculators/event_based.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/check_input.py
  openquake/commands/reaggregate.py
  openquake/commands/run.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/datastore_test.py
  openquake/engine/engine.py
  openquake/server/views.py
  utils/csm2rup
Labels: internal

#6748 Refactored the logging mechanism (2)
  doc/adv-manual/developing.rst
  openquake/calculators/event_based.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/check_input.py
  openquake/commands/engine.py
  openquake/commands/reaggregate.py
  openquake/commands/run.py
  openquake/commands/shell.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/datastore_test.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/server/db/actions.py
  openquake/server/views.py
  utils/csm2rup
Labels: internal

#6750 Extended rst_table->text_table
  openquake/calculators/export/hazard.py
  openquake/calculators/reportwriter.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/commands/compare.py
  openquake/commands/db.py
  openquake/commands/info.py
  openquake/commands/run.py
  openquake/commands/show.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves4.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves8.csv
  openquake/qa_tests_data/event_based_risk/case_1f/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/scenario_damage/case_4b/expected/portfolio_damage.rst
  openquake/qa_tests_data/scenario_risk/case_6a/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  utils/tot_ruptures.py
Labels: internal

#6751 Refactored the logging mechanism (3)
  openquake/calculators/base.py
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/commands/shell.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logs.py
  openquake/commonlib/readinput.py
  openquake/engine/engine.py
  openquake/qa_tests_data/classical/case_1/job.ini
  openquake/server/db/actions.py
  openquake/server/views.py
Labels: internal

#6752 Added an early check for fragility functions in place of vulnerability functions or viceversa
  debian/changelog
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_1/job_bad.ini
  openquake/qa_tests_data/scenario_damage/case_1/vulnerability.xml
Labels: enhancement

#6755 Added a section on the manual about multiple tag aggregation
  doc/adv-manual/risk.rst
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
Labels: documentation

#6754 Implements Ameri (2014) Rjb GMPE
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/ameri_2014.py
  openquake/hazardlib/tests/gsim/ameri_2014_test.py
  openquake/hazardlib/tests/gsim/data/ameri14/Ameri_2014_inter_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/ameri14/Ameri_2014_intra_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/ameri14/Ameri_2014_mean.csv
  openquake/hazardlib/tests/gsim/data/ameri14/Ameri_2014_total_stddev.csv
Labels: enhancement

#6756 Refactored calculators/views.py
  openquake/calculators/classical_damage.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/commonlib/datastore.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.csv
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.rst
Labels: internal

#6757 Fixed error in org tables
  doc/tutorials/the-datastore/datastore.org
  openquake/calculators/views.py
  openquake/commands/reaggregate.py
Labels: internal

#6758 Moved tests around
  openquake/calculators/tests/event_based_damage_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_damage/__init__.py
  openquake/qa_tests_data/event_based_damage/case_12/__init__.py
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/d_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_12/exposure.csv
  openquake/qa_tests_data/event_based_damage/case_12/exposure1.xml
  openquake/qa_tests_data/event_based_damage/case_12/fragility.xml
  openquake/qa_tests_data/event_based_damage/case_12/gmfs.csv
  openquake/qa_tests_data/event_based_damage/case_12/job_a.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_b.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_c.ini
  openquake/qa_tests_data/event_based_damage/case_12/job_d.ini
  openquake/qa_tests_data/event_based_damage/case_12/report.rst
  openquake/qa_tests_data/event_based_damage/case_12/sites.csv
  openquake/qa_tests_data/event_based_damage/case_13/__init__.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_13/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_damage/case_13/exposure.csv
  openquake/qa_tests_data/event_based_damage/case_13/exposure1.xml
  openquake/qa_tests_data/event_based_damage/case_13/fragility.xml
  openquake/qa_tests_data/event_based_damage/case_13/gmfs.csv
  openquake/qa_tests_data/event_based_damage/case_13/job_a.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_b.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_c.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_d.ini
  openquake/qa_tests_data/event_based_damage/case_13/report.rst
  openquake/qa_tests_data/event_based_damage/case_13/sites.csv
  openquake/qa_tests_data/event_based_damage/case_13/structural_consequence_model.xml
  openquake/qa_tests_data/event_based_damage/case_14/__init__.py
  openquake/qa_tests_data/event_based_damage/case_14/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_14/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_14/exposure_model.csv
  openquake/qa_tests_data/event_based_damage/case_14/exposure_model.xml
  openquake/qa_tests_data/event_based_damage/case_14/job.ini
  openquake/qa_tests_data/event_based_damage/case_14/nepal.hdf5
  openquake/qa_tests_data/event_based_damage/case_14/report.rst
  openquake/qa_tests_data/event_based_damage/case_14/structural_fragility_model.xml
Labels: internal

#6759 Fixed bug in ShakeMaps: the GMFs were stored in the wrong order
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
Labels: bug

#6761 Small refactoring of event based risk
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commands/engine.py
  openquake/commonlib/calc.py
  openquake/commonlib/datastore.py
Labels: internal

#6762 Small refactoring of event based risk (2)
  openquake/baselib/parallel.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/views.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/datastore_test.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#6763 Solved the issue of slow tasks in event_based
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/getters.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/commonlib/datastore.py
  openquake/commonlib/tests/datastore_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves-quantile-0.25.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
Labels: performance

#6764 Fixes the usual hdf5 bug, appearing again in event_based_risk
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
Labels: bug

#6768 Renamed multi->multipoint
  openquake/hazardlib/source/__init__.py
  openquake/hazardlib/source/multi_point.py
  openquake/hazardlib/tests/source/multipoint_test.py
Labels: enhancement

#6769 Added MultiFaultSource
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/source/data/profiles00/cs_00.txt
  openquake/hazardlib/tests/source/data/profiles00/cs_01.txt
  openquake/hazardlib/tests/source/data/profiles01/cs_00.txt
  openquake/hazardlib/tests/source/data/profiles01/cs_01.txt
  openquake/hazardlib/tests/source/data/profiles02/cs_00.txt
  openquake/hazardlib/tests/source/data/profiles02/cs_01.txt
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/source/multi_point_test.py
Labels: enhancement

#6771 Added classical and event_based tests for multi fault sources
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source/multi_fault.py
  openquake/qa_tests_data/classical/case_65/expected/gmf_data.csv
  openquake/qa_tests_data/classical/case_65/expected/ruptures.csv
Labels: enhancement

#6749 Differentiate between Windows and macOS/Linux in universal install docs
  doc/installing/universal.md
Labels: WIP

#6776 Solve (not all) problems of MultiFaultSources
  debian/changelog
  openquake/commonlib/source_reader.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/mfd/tapered_gr_mfd.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/data/sections/sections_kite.xml
  openquake/hazardlib/tests/data/sections/sections_mix.xml
  openquake/hazardlib/tests/nrml_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/qa_tests_data/classical/case_65/job.ini
  openquake/qa_tests_data/classical/case_65/sections.xml
  openquake/qa_tests_data/classical/case_65/ssm.xml
  openquake/qa_tests_data/classical/case_65/ssmLT.xml
Labels: enhancement

#6775 Added a view over the branch IDs
  openquake/calculators/views.py
Labels: enhancement

#6777 Added an XML writer for MultiFaultSource
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/data/sections/sources.xml
  openquake/hazardlib/tests/source_model/multi-fault-source.xml
  openquake/hazardlib/tests/source_model/sections_mix.xml
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: enhancement

#6779 Fixed event_based_damage exporter
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_11/__init__.py
  openquake/qa_tests_data/event_based_damage/case_11/assets.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_11/exposure_model.xml
  openquake/qa_tests_data/event_based_damage/case_11/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_11/job.ini
  openquake/qa_tests_data/event_based_damage/case_11/source_model.xml
  openquake/qa_tests_data/event_based_damage/case_11/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_11/structural_consequence_model.xml
  openquake/qa_tests_data/event_based_damage/case_11/structural_fragility_model.xml
Labels: bug

#6778 Multi source improve
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/__init__.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/qa_tests_data/classical/README.md
Labels: enhancement

#6780 Test that ruptures can be extracted from MultiFaultSurfaces
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_65/expected/full_ruptures.csv
Labels: internal

#6782 Fixed event_based_damage with no ruptures
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/calculators/views.py
  openquake/engine/engine.py
Labels: bug

#6783 Some work on rupture geometries
  openquake/calculators/getters.py
  openquake/calculators/views.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#6784 Fixed extract/rupture_info
  openquake/calculators/extract.py
Labels: bug

#6785 Refactored get_rupture_getter
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
Labels: internal

#6786 Do not store losses in the DamageCalculator
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: bug

#6787 Renamed losses_by_event -> risk_by_event
  openquake/calculators/export/risk.py
  openquake/calculators/tests/outputs/risk_by_event.csv
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/risk_by_event.csv
Labels: outputs

#6788 Making scenario_damage more similar to event_based_damage
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_1.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_2.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/risk_by_event.csv
  openquake/risklib/riskmodels.py
Labels: outputs

#6790 Fixed the `agg_loss_table` in scenario_damage
  debian/changelog
  doc/adv-manual/oq-commands.rst
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_1.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_2.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_8/expected/dmg_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
  openquake/server/db/actions.py
Labels: outputs

#6794 Moved writers.py from commonlib to baselib
  openquake/baselib/node.py
  openquake/baselib/writers.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/commands/ltcsv.py
  openquake/commands/nrml_to.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tidy.py
  openquake/commonlib/tests/writers_test.py
Labels: internal

#6793 Removed the rupture XML exporter
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/hazard_writers.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.xml
  openquake/qa_tests_data/event_based/case_17/expected/ses.xml
  openquake/qa_tests_data/event_based/case_3/expected/ses.xml
  openquake/qa_tests_data/event_based/mutex/expected/ses.xml
Labels: outputs

#6792 Removed the SES XML output from the manual
  doc/manual/oqum/hazard/02c_output_event_based.tex
  doc/manual/oqum/hazard/verbatim/output_ses.tex
  doc/manual/oqum/hazard/verbatim/output_ses.xml
Labels: documentation, outputs

#6796 modification to install.py to use with windows installer
  install.py
  requirements-py38-win64.txt
Labels: packaging

#6801 Unify damages and consequences in damages-rlzs and damages-stats
  openquake/calculators/event_based_damage.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_damages-rlz-000.csv
Labels: enhancement, outputs

#6798 Adding test for distance calculation with a mesh with NaNs
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/data/profiles07/cs_00.txt
  openquake/hazardlib/tests/geo/surface/data/profiles07/cs_01.txt
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/qa_tests_data/classical/case_65/expected/ruptures.csv
Labels: bug

#6802 Adding algorithm to compute rjb for kite + test
  debian/changelog
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/qa_tests_data/classical/case_61/expected/hcurve-mean.csv
Labels: enhancement

#6803 Added a sanity check on event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/views.py
Labels: internal

#6804 Fixed the sanity check in scenario_damage/event_based_damage
  debian/changelog
  openquake/calculators/scenario_damage.py
Labels: bug

#6805 Earlier validation for event_based_damage
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#6806 Fixed a subtle bug with the taxonomy mapping
  openquake/baselib/parallel.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: bug, performance

#6807 Enhanced `oq workers kill`
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
Labels: internal

#6810 Saving memory in event_based_risk
  openquake/calculators/event_based_risk.py
Labels: performance

#6811 Added EventBasedDamage demo with convergency analysis
  demos/risk/EventBasedDamage/README.md
  demos/risk/EventBasedDamage/consequences_by_taxonomy.csv
  demos/risk/EventBasedDamage/exposure_model.csv
  demos/risk/EventBasedDamage/exposure_model.xml
  demos/risk/EventBasedDamage/gmpe_logic_tree.xml
  demos/risk/EventBasedDamage/job.ini
  demos/risk/EventBasedDamage/source_model.xml
  demos/risk/EventBasedDamage/source_model_logic_tree.xml
  demos/risk/EventBasedDamage/structural_fragility_model.xml
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/engine/engine.py
  openquake/qa_tests_data/event_based_damage/case_15/__init__.py
  openquake/qa_tests_data/event_based_damage/case_15/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/dmgcsq.csv
  openquake/qa_tests_data/event_based_damage/case_15/exposure_model.csv
  openquake/qa_tests_data/event_based_damage/case_15/exposure_model.xml
  openquake/qa_tests_data/event_based_damage/case_15/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_15/job.ini
  openquake/qa_tests_data/event_based_damage/case_15/source_model.xml
  openquake/qa_tests_data/event_based_damage/case_15/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_15/structural_fragility_model.xml
Labels: enhancement

#6812 Skipping the test requiring fiona if not installed
  openquake/hazardlib/tests/nrml_to_test.py
Labels: internal

#6813 Some refactoring of ebr and ebd
  openquake/calculators/event_based_damage.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#6815 Speedup by 14x the SURA calculation
  openquake/calculators/event_based_risk.py
  openquake/hazardlib/stats.py
  openquake/risklib/riskmodels.py
Labels: performance

#6814 change name from cleanup to requirements
  .github/workflows/linux_gdal_test.yml
  .github/workflows/macos_gdal_test.yml
  .github/workflows/macos_install.yml
  .github/workflows/windows_gdal_test.yml
Labels: internal

#6816 Improved post_risk to use all available cores
  debian/changelog
  openquake/calculators/post_risk.py
Labels: performance

#6818 Fixed no_damage in event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_damages-rlz-000.csv
Labels: bug

#6817 Cleaning up the risk calculators
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/scenario_damage.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#6819 Added view portfolio_dmgdist
  openquake/calculators/event_based_damage.py
  openquake/calculators/views.py
Labels: internal

#6820 Storing damages consistently with scenario_damage
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_damages-quantile-0.25.csv
Labels: enhancement

#6821 Stored damages-rlzs consistently with scenario_damage and classical_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
Labels: internal

#6823 Ported the fix to avg_damages from 3.11 to master
  openquake/calculators/export/risk.py
Labels: bug

#6824 Added limit_states to oqparam
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
Labels: internal

#6825 Fixed formatting of floating point numbers
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.rst
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves1.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves6.csv
Labels: internal

#6797 Updates model/coefficients for KothaEtAl2020ESHMSlopeGeology
  debian/changelog
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_TOTAL_STDDEV.csv
  openquake/qa_tests_data/classical/case_41/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_41/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_41/gmpe_logic_tree_site_amp.xml
  openquake/qa_tests_data/classical/case_41/job.ini
Labels: enhancement
