Repository gem/oq-engine, pull requests merged in 2021-04, with the labels that each got.

#6667 Removed assets_per_site_limit in scenario_damage
  openquake/calculators/base.py
Labels: enhancement

#6669 Preliminary work to support h5py 3+
  openquake/baselib/parallel.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/logictree.py
Labels: internal

#6670 Removed LiteralAttrs
  openquake/baselib/datastore.py
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/valid.py
Labels: internal

#6672 Fix to LanzanoEtAl2016
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_64/GRID_Mascandola.csv
  openquake/qa_tests_data/classical/case_64/__init__.py
  openquake/qa_tests_data/classical/case_64/br8_ItaliaShareGRtot_ML_M2_150518_stat_MOD.xml
  openquake/qa_tests_data/classical/case_64/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_64/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_64/job.ini
  openquake/qa_tests_data/classical/case_64/site_model.csv
  openquake/qa_tests_data/classical/case_64/source_model_logic_tree.xml
Labels: bug

#6642 Estimate uncertainty on the losses due to the vulnerability functions
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_4/expected/losses_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/stddevs.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/job.ini
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/event_based_test.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement

#6673 shakemaps: use relative paths
  openquake/hazardlib/shakemap/parsers.py
Labels: internal

#6675 Added collect_rlzs flag
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#6677 Converted the exposures in the demos into CSV
  debian/changelog
  demos/risk/ClassicalBCR/exposure_model.csv
  demos/risk/ClassicalDamage/exposure_model.csv
  demos/risk/ClassicalDamage/exposure_model.xml
  demos/risk/ClassicalDamage/job_hazard.ini
  demos/risk/EventBasedRisk/exposure_model.csv
  demos/risk/EventBasedRisk/exposure_model.xml
  demos/risk/ScenarioDamage/exposure_model.csv
  demos/risk/ScenarioDamage/exposure_model.xml
Labels: documentation

#6678 Added an HDF5 exporter for gmf_data
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement

#6681 Storing the SiteCollection in a pandas-friendly way
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/site.py
Labels: internal

#6682 Removed `reference_siteclass`
  debian/changelog
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.csv
  openquake/qa_tests_data/classical/case_32/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_32/job.ini
  openquake/qa_tests_data/classical/case_32/sites.csv
  openquake/qa_tests_data/event_based/case_23/expected/sitecol.csv
Labels: enhancement

#6684 Added a check for suspicious loss curves
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/risklib/scientific.py
Labels: enhancement

#6685 Associating the risk sites when importing the GMFs
  openquake/calculators/base.py
  openquake/calculators/export/hazard.py
  openquake/qa_tests_data/gmf_ebrisk/case_1/gmf-data.hdf5
Labels: enhancement

#6666 New GSIM Idini2017
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/idini_2017.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SINTER_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SINTER_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SINTER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SINTER_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SSLAB_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SSLAB_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SSLAB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/Idini2017/IDINI_2017_SSLAB_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/idini_2017_test.py
  openquake/qa_tests_data/classical/case_63/__init__.py
  openquake/qa_tests_data/classical/case_63/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_63/expected/quantile_curve-0.16-PGA.csv
  openquake/qa_tests_data/classical/case_63/expected/quantile_curve-0.5-PGA.csv
  openquake/qa_tests_data/classical/case_63/expected/quantile_curve-0.84-PGA.csv
  openquake/qa_tests_data/classical/case_63/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_63/job.ini
  openquake/qa_tests_data/classical/case_63/report.rst
  openquake/qa_tests_data/classical/case_63/site_model.xml
  openquake/qa_tests_data/classical/case_63/source_model.xml
  openquake/qa_tests_data/classical/case_63/source_model_logic_tree.xml
Labels: enhancement

#6653 Added support for conditional disaggregation
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_7/expected/rlz-0-PGA-sid-0-poe-1-cond_TRT.csv
  openquake/qa_tests_data/disagg/case_7/expected/rlz-0-PGA-sid-0-poe-1_TRT.csv
Labels: enhancement

#6686 Dynamic site parameters
  debian/changelog
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.csv
  openquake/qa_tests_data/event_based/case_23/expected/sitecol.csv
Labels: internal

#6688 Fixed bug in scenario_damage for few events
  openquake/calculators/scenario_damage.py
Labels: bug

#6689 Supported zero coefficient of variations with the beta distribution
  debian/changelog
  openquake/qa_tests_data/event_based_risk/case_1f/vulnerability_model.xml
  openquake/risklib/scientific.py
Labels: bug

#6691 Added method MultiEventRNG.discrete_dmg_dist
  openquake/risklib/scientific.py
Labels: enhancement

#6693 Event based damage
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_damage_table.txt
  openquake/qa_tests_data/event_based_risk/case_1/job_damage.ini
Labels: enhancement

#6694 Added scenario_damage/case_12
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_damage_table.txt
  openquake/qa_tests_data/event_based_risk/case_1/job_damage.ini
  openquake/qa_tests_data/scenario_damage/README.md
  openquake/qa_tests_data/scenario_damage/case_12/__init__.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/agg_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/exposure.csv
  openquake/qa_tests_data/scenario_damage/case_12/exposure1.xml
  openquake/qa_tests_data/scenario_damage/case_12/fragility.xml
  openquake/qa_tests_data/scenario_damage/case_12/gmfs.csv
  openquake/qa_tests_data/scenario_damage/case_12/job.ini
  openquake/qa_tests_data/scenario_damage/case_12/report.rst
  openquake/qa_tests_data/scenario_damage/case_12/sites.csv
Labels: internal

#6696 event_based_risk starting from a different user calculation
  debian/changelog
  openquake/baselib/datastore.py
  openquake/baselib/tests/datastore_test.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/export.py
  openquake/commands/plot_assets.py
  openquake/commands/reaggregate.py
  openquake/commands/reduce_sm.py
  openquake/commands/run.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/util.py
Labels: bug

#6697 Moved baselib.datastore in commonlib
  doc/adv-manual/char_count_par.py
  doc/adv-manual/pandas.rst
  doc/adv-manual/parallelization.rst
  doc/datastore.md
  doc/sphinx/openquake.baselib.rst
  doc/sphinx/openquake.commonlib.rst
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_test.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/engine.py
  openquake/commands/export.py
  openquake/commands/importcalc.py
  openquake/commands/plot_assets.py
  openquake/commands/prepare_site_model.py
  openquake/commands/purge.py
  openquake/commands/reaggregate.py
  openquake/commands/reduce_sm.py
  openquake/commands/run.py
  openquake/commands/shell.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/datastore_test.py
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/commonlib/util.py
  openquake/engine/export/core.py
  openquake/engine/tools/make_html_report.py
  openquake/server/db/actions.py
  openquake/server/settings.py
  openquake/server/views.py
  utils/tot_ruptures.py
Labels: internal

#6699 Event based damage with float_dmg_dist=True
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/e_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/e_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/job_e.ini
Labels: performance

#6701 Made it possible to read an old calculation
  openquake/calculators/tests/event_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_master/calc_311.hdf5
Labels: internal

#6702 Event based damage: fixed ordering issue
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/a_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/b_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/c_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/d_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/e_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/e_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/job_e.ini
Labels: performance

#6700 Feature/shakemap shapefiles
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/shakemap/maps.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
  openquake/hazardlib/tests/shakemap/shapefiles_test/output.dbf
  openquake/hazardlib/tests/shakemap/shapefiles_test/output.prj
  openquake/hazardlib/tests/shakemap/shapefiles_test/output.shp
  openquake/hazardlib/tests/shakemap/shapefiles_test/output.shx
  openquake/qa_tests_data/scenario_risk/case_shapefile/__init__.py
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/realizations.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/exposure.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/exposure.xml
  openquake/qa_tests_data/scenario_risk/case_shapefile/job.ini
  openquake/qa_tests_data/scenario_risk/case_shapefile/prepare_job.ini
  openquake/qa_tests_data/scenario_risk/case_shapefile/shp/output.dbf
  openquake/qa_tests_data/scenario_risk/case_shapefile/shp/output.prj
  openquake/qa_tests_data/scenario_risk/case_shapefile/shp/output.shp
  openquake/qa_tests_data/scenario_risk/case_shapefile/shp/output.shx
  openquake/qa_tests_data/scenario_risk/case_shapefile/structural_vulnerability_MMI.xml
Labels: enhancement

#6703 Installation scripts for Windows
  .github/workflows/windows_install.yml
  install.py
Labels: packaging

#6704 Implemented consequences in event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/__init__.py
  openquake/qa_tests_data/scenario_damage/case_13/expected/a_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/agg_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/b_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/c_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/d_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/exposure.csv
  openquake/qa_tests_data/scenario_damage/case_13/exposure1.xml
  openquake/qa_tests_data/scenario_damage/case_13/fragility.xml
  openquake/qa_tests_data/scenario_damage/case_13/gmfs.csv
  openquake/qa_tests_data/scenario_damage/case_13/job_a.ini
  openquake/qa_tests_data/scenario_damage/case_13/job_b.ini
  openquake/qa_tests_data/scenario_damage/case_13/job_c.ini
  openquake/qa_tests_data/scenario_damage/case_13/job_d.ini
  openquake/qa_tests_data/scenario_damage/case_13/report.rst
  openquake/qa_tests_data/scenario_damage/case_13/sites.csv
  openquake/qa_tests_data/scenario_damage/case_13/structural_consequence_model.xml
  openquake/risklib/riskmodels.py
Labels: enhancement

#6705 Renamed agg_damage_table->agg_loss_table
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/b_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/c_damages.txt
  openquake/qa_tests_data/scenario_damage/case_12/expected/d_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/d_damages.txt
  openquake/risklib/scientific.py
Labels: internal

#6706 Documentation ShakeMap
  doc/adv-manual/risk-features.rst
Labels: documentation

#6707 Moved `create_df` and `read_df`
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/scenario_damage.py
  openquake/commonlib/datastore.py
Labels: internal

#6708 Fixed event_based_damage in absence of value-fields
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/risklib/asset.py
Labels: bug

#6709 Made sure `oq zip` works with shapefiles
  doc/adv-manual/risk-features.rst
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqzip.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
Labels: bug

#6713 Improved the aggcurves exporter
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_12/expected/agg_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/a_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/a_damages.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/agg_damage_table.txt
  openquake/qa_tests_data/scenario_damage/case_13/expected/aggcurves.csv
  openquake/qa_tests_data/scenario_damage/case_13/expected/dmgcsq.csv
  openquake/qa_tests_data/scenario_damage/case_14/expected/aggcurves.csv
  openquake/qa_tests_data/scenario_damage/case_14/expected/dmgcsq.csv
Labels: enhancement

#6714 Added function contexts.read_cmakers
  openquake/baselib/hdf5.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based_damage.py
  openquake/hazardlib/contexts.py
Labels: internal

#6716 Added view composite_source_model
  debian/changelog
  openquake/calculators/views.py
Labels: internal

#6717 Added attribute grp_id to the ContextMaker
  openquake/calculators/conditional_spectrum.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
Labels: internal

#6718 Removed some code
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: internal

#6720 Renamed et_id -> trt_smrlz
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/ucerf_base.py
  openquake/calculators/views.py
  openquake/commands/tests/data/to_reduce/__init__.py
  openquake/commonlib/calc.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/calc/filters_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/lt_test.py
  openquake/hazardlib/tests/source/multipoint_test.py
  openquake/qa_tests_data/classical/case_15/__init__.py
  openquake/qa_tests_data/classical/case_16/__init__.py
  openquake/qa_tests_data/classical/case_17/__init__.py
Labels: internal

#6722 Removed some code
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#6724 Turned read_ctxs into a method of the ContextMaker
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
Labels: internal

#6725 Managed properly the TOM
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/rupture_test.py
  openquake/hazardlib/tests/tom_test.py
  openquake/qa_tests_data/classical/case_20/source_model_logic_tree.xml
  openquake/qa_tests_data/classical/case_8/source_model_logic_tree.xml
Labels: internal

#6726 Managed properly the TOM (2)
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/lt_test.py
Labels: internal

#6719 Adds reference velocity to Douglas (2013) GMPEs
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
Labels: bug

#6727 Removed `ContextMaker.gen_cxt_poes`
  openquake/calculators/conditional_spectrum.py
  openquake/hazardlib/contexts.py
Labels: internal

#6729 Simplified read_ctxs
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
Labels: internal

#6728 Fixed bug with multipoint sources and applyToSources
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/mfd/multi_mfd.py
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.05).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.2).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(0.5)
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-000.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-001.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-002.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-003.csv
  openquake/qa_tests_data/classical/case_28/job.ini
  openquake/qa_tests_data/classical/case_28/source_model_logic_tree.xml
  openquake/qa_tests_data/classical/case_7/source_model_logic_tree.xml
Labels: bug

#6730 Added cross_correlation module
  debian/changelog
  openquake/hazardlib/cross_correlation.py
  openquake/hazardlib/tests/cross_correlation_test.py
  openquake/risklib/asset.py
Labels: enhancement

#6712 shakmap input
  doc/adv-manual/risk-features.rst
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/ghorka_grid.zip
  openquake/hazardlib/tests/shakemap/ghorka_uncertainty.zip
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/tests/shakemap/test_shaking.zip
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
  openquake/qa_tests_data/scenario_risk/case_shakemap/shakefile/usp000fjta.npy
  openquake/qa_tests_data/scenario_risk/case_shapefile/job_zipped.ini
  openquake/qa_tests_data/scenario_risk/case_shapefile/shp/shapefiles.zip
Labels: enhancement

#6731 Stopped pandas from converting nan in numpy.nan
  openquake/baselib/hdf5.py
Labels: bug

#6732 Avoided nearly circular imports between datastore and logs
  doc/adv-manual/developing.rst
  openquake/calculators/base.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/check_input.py
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/commands/shell.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/datastore_test.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: internal

#6733 Made it possible to pass oqparam to datastore.new
  openquake/commonlib/datastore.py
Labels: enhancement

#6734 Fixed the losses_by_event exporter in event_based_damage
  openquake/calculators/export/risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_13/expected/losses_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/losses_by_event.csv
Labels: bug

#6736 Small cleanup of oqparam
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/commands/show.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_1/job.ini
  utils/plot_lt
Labels: internal

#6737 Added utility stats.combine_probs
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/stats.py
Labels: enhancement
