Repository gem/oq-engine, pull requests merged in 2021-01, with the labels that each got.

#6417 Implemented deformation_component in secondary perils
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/imt.py
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/sep/classes.py
  openquake/sep/liquefaction/lateral_spreading.py
Labels: enhancement

#6418 Extended ArrayWrapper.to_dframe
  openquake/baselib/hdf5.py
  openquake/risklib/riskmodels.py
Labels: internal

#6419 setup action for macos
  .github/workflows/macos_pyapp.yml
Labels: internal

#6421 Some refactoring to support secondary perils
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/scenario_damage.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/riskinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#6423 Added Vitor's test for secondary perils
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_11/__init__.py
  openquake/qa_tests_data/scenario_damage/case_11/exposure.csv
  openquake/qa_tests_data/scenario_damage/case_11/exposure.xml
  openquake/qa_tests_data/scenario_damage/case_11/fragility.xml
  openquake/qa_tests_data/scenario_damage/case_11/gdfs.csv
  openquake/qa_tests_data/scenario_damage/case_11/job.ini
  openquake/qa_tests_data/scenario_damage/case_11/vulnerability.xml
Labels: enhancement

#6425 Implemented secondary simulations for secondary perils
  openquake/calculators/scenario_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages1.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages2.csv
  openquake/qa_tests_data/scenario_damage/case_11/job.ini
  openquake/risklib/riskmodels.py
Labels: enhancement

#6420 Small fix to CompositeRiskModel.read
  openquake/calculators/base.py
  openquake/qa_tests_data/event_based_risk/case_1g/job_h.ini
  openquake/qa_tests_data/event_based_risk/case_1g/job_r.ini
  openquake/risklib/riskmodels.py
Labels: bug

#6426 Added a check on get_mean_std1
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
Labels: internal

#6428 Extended sap to manage nested subcommands
  openquake/baselib/sap.py
  openquake/baselib/tests/sap_test.py
  openquake/commands/abort.py
  openquake/commands/celery.py
  openquake/commands/check_input.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/db.py
  openquake/commands/dbserver.py
  openquake/commands/download_shakemap.py
  openquake/commands/dump.py
  openquake/commands/engine.py
  openquake/commands/export.py
  openquake/commands/extract.py
  openquake/commands/from_shapefile.py
  openquake/commands/importcalc.py
  openquake/commands/info.py
  openquake/commands/ltcsv.py
  openquake/commands/plot.py
  openquake/commands/plot_agg_curve.py
  openquake/commands/plot_assets.py
  openquake/commands/plot_losses.py
  openquake/commands/plot_pyro.py
  openquake/commands/prepare_site_model.py
  openquake/commands/purge.py
  openquake/commands/reduce_sm.py
  openquake/commands/reset.py
  openquake/commands/restore.py
  openquake/commands/run.py
  openquake/commands/sample.py
  openquake/commands/shell.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commands/tests/commands_test.py
  openquake/commands/tidy.py
  openquake/commands/to_hdf5.py
  openquake/commands/to_shapefile.py
  openquake/commands/upgrade_nrml.py
  openquake/commands/webui.py
  openquake/commands/workers.py
  openquake/commands/zip.py
  openquake/engine/tools/viewlog.py
  utils/addcol.py
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
Labels: internal

#6433 Extended install.py to install from a branch
  install.py
Labels: enhancement, packaging

#6432 Support for input URLs
  debian/changelog
  openquake/commonlib/readinput.py
Labels: enhancement

#6434 Big changes to sap
  openquake/baselib/sap.py
  openquake/baselib/tests/sap_test.py
  openquake/baselib/workerpool.py
  openquake/commands/__main__.py
  openquake/commands/abort.py
  openquake/commands/celery.py
  openquake/commands/check_input.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/db.py
  openquake/commands/dbserver.py
  openquake/commands/download_shakemap.py
  openquake/commands/dump.py
  openquake/commands/engine.py
  openquake/commands/export.py
  openquake/commands/extract.py
  openquake/commands/from_shapefile.py
  openquake/commands/importcalc.py
  openquake/commands/info.py
  openquake/commands/ltcsv.py
  openquake/commands/nrml_to.py
  openquake/commands/plot.py
  openquake/commands/plot_agg_curve.py
  openquake/commands/plot_assets.py
  openquake/commands/plot_losses.py
  openquake/commands/plot_pyro.py
  openquake/commands/postzip.py
  openquake/commands/prepare_site_model.py
  openquake/commands/purge.py
  openquake/commands/reaggregate.py
  openquake/commands/reduce_sm.py
  openquake/commands/renumber_sm.py
  openquake/commands/reset.py
  openquake/commands/restore.py
  openquake/commands/run.py
  openquake/commands/sample.py
  openquake/commands/shell.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commands/tests/commands_test.py
  openquake/commands/tidy.py
  openquake/commands/to_hdf5.py
  openquake/commands/to_shapefile.py
  openquake/commands/upgrade_nrml.py
  openquake/commands/webui.py
  openquake/commands/workers.py
  openquake/commands/zip.py
  openquake/engine/tools/viewlog.py
  utils/addcol.py
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
Labels: internal

#6435 Final refactoring of sap
  bin/slowtests
  openquake/baselib/sap.py
  openquake/baselib/workerpool.py
  openquake/commands/__main__.py
  openquake/commands/abort.py
  openquake/commands/celery.py
  openquake/commands/check_input.py
  openquake/commands/checksum.py
  openquake/commands/compare.py
  openquake/commands/db.py
  openquake/commands/dbserver.py
  openquake/commands/download_shakemap.py
  openquake/commands/dump.py
  openquake/commands/engine.py
  openquake/commands/export.py
  openquake/commands/extract.py
  openquake/commands/from_shapefile.py
  openquake/commands/importcalc.py
  openquake/commands/info.py
  openquake/commands/ltcsv.py
  openquake/commands/nrml_to.py
  openquake/commands/plot.py
  openquake/commands/plot_agg_curve.py
  openquake/commands/plot_assets.py
  openquake/commands/plot_losses.py
  openquake/commands/plot_pyro.py
  openquake/commands/postzip.py
  openquake/commands/prepare_site_model.py
  openquake/commands/purge.py
  openquake/commands/reaggregate.py
  openquake/commands/reduce_sm.py
  openquake/commands/renumber_sm.py
  openquake/commands/reset.py
  openquake/commands/restore.py
  openquake/commands/run.py
  openquake/commands/sample.py
  openquake/commands/shell.py
  openquake/commands/show.py
  openquake/commands/show_attrs.py
  openquake/commands/tests/commands_test.py
  openquake/commands/tidy.py
  openquake/commands/to_hdf5.py
  openquake/commands/to_shapefile.py
  openquake/commands/upgrade_nrml.py
  openquake/commands/webui.py
  openquake/commands/workers.py
  openquake/commands/zip.py
  openquake/engine/tools/viewlog.py
  utils/addcol.py
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
  utils/expo2csv
  utils/extract_sites
  utils/extract_source
  utils/gridded2hdf5
  utils/plot_lt
  utils/strip_dupl_sites
  utils/xml2hdf5
  utils/yaml2toml
Labels: internal

#6438 Fixed extract/losses_by_asset breaking the QGIS plugin
  openquake/baselib/sap.py
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
Labels: bug

#6437 Honor `individual_curves` in risk results too
  debian/changelog
  demos/risk/EventBasedRisk/job_eb.ini
  openquake/calculators/ebrisk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/__init__.py
  openquake/engine/engine.py
Labels: bug

#6405 NI15 GMPE
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_RJB_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_RJB_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_RJB_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_Rhypo_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_Rhypo_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_Rhypo_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/LAN2016/NI15_Rhypo_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/lanzano_2016_test.py
Labels: enhancement

#6439 Changed the logic in `oq workers`
  openquake/commands/workers.py
  openquake/server/dbserver.py
Labels: internal

#6440 Speedup in "saving hazard"
  openquake/calculators/classical.py
Labels: performance

#6441 Another fix for losses_by_asset
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/ebrisk.py
Labels: bug

#6371 Refactor of Chiou & Youngs (2014)
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/mgmpe/cy14_site_term.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
  openquake/hazardlib/tests/gsim/data/NGA/CY14/CY14_Italy_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NGA/CY14/CY14_Japan_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NGA/CY14/CY14_Wenchuan_MEAN.csv
Labels: enhancement

#6442 Stored avg_gmf also in event_based
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
Labels: internal

#6443 Added a command `oq plot avg_gmf?imt=IMT`
  debian/changelog
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: enhancement, investigation

#6444 Fixed `oq reaggregate`
  openquake/commands/reaggregate.py
Labels: bug

#6445 Improved commands_test.py
  openquake/baselib/sap.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
Labels: internal

#6451 Moved the computation to avg_gmf at the end of the calculation
  openquake/calculators/event_based.py
Labels: performance

#6453 Fixed install script for server installation
  install.py
Labels: bug

#6452 Added a sanity check on suspicious zero losses
  openquake/calculators/event_based.py
  openquake/calculators/post_risk.py
  openquake/calculators/scenario_risk.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement

#6447 SSH command to start workerpools
  docker/Dockerfile.volcano
  docker/scripts/oq-db_start.sh
  docker/zmq/openquake.cfg
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
Labels: internal

#6455 Fixed a bug with multiSurfaces of KiteFaults
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source/non_parametric.py
  openquake/qa_tests_data/classical/case_62/Source_model_1_bis.xml
  openquake/qa_tests_data/classical/case_62/__init__.py
  openquake/qa_tests_data/classical/case_62/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_62/gmmLT.xml
  openquake/qa_tests_data/classical/case_62/job.ini
  openquake/qa_tests_data/classical/case_62/ssmLT.xml
Labels: bug

#6456 Molecule display
  .github/workflows/playbook_ansible.yml
  ansible/oqengine/molecule/default/molecule.yml
  ansible/playbook/molecule/default/molecule.yml
Labels: internal

#6457 Update a logging message in scenario_damage and scenario_risk
  openquake/calculators/scenario_damage.py
  openquake/calculators/scenario_risk.py
Labels: documentation

#6458 Fixed the check on zero losses
  debian/changelog
  openquake/calculators/scenario_risk.py
Labels: bug

#6459 Accepted consequence functions associate to missing taxonomies
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/scenario_damage.py
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/risklib/riskmodels.py
Labels: enhancement

#6462 Removed check too strict
  debian/changelog
  demos/risk/ScenarioRisk/structural_vulnerability_model.xml
  openquake/risklib/riskmodels.py
Labels: bug

#6461 Refactored the extraction of job.ini files from an archive
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/server/tests/data/archive_err_3.zip
  openquake/server/tests/data/archive_ok.zip
  openquake/server/tests/views_test.py
  openquake/server/views.py
Labels: enhancement

#6463 Updated `oq workers` to optionally start dask
  openquake/baselib/workerpool.py
  openquake/commands/workers.py
Labels: enhancement, internal

#6460 Resolve problems related with ruptures containing NaNs
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/non_parametric.py
  openquake/qa_tests_data/classical/case_62/Source_model_1_bis.xml
  openquake/qa_tests_data/classical/case_62/expected/hcurve-mean.csv
Labels: bug

#6467 Fixed wrong check
  debian/changelog
  openquake/risklib/asset.py
Labels: bug

#6468 Fixes additional issue
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/utils.py
Labels: WIP

#6450 Implementing a Tapered GR mfd
  debian/changelog
  openquake/hazardlib/mfd/__init__.py
  openquake/hazardlib/mfd/multi_mfd.py
  openquake/hazardlib/mfd/tapered_gr_mfd.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/mfd/tapered_gr_test.py
  openquake/qa_tests_data/classical/case_2/expected/hcurve.csv
  openquake/qa_tests_data/classical/case_2/source_model.xml
  openquake/qa_tests_data/classical/case_62/__init__.py
  openquake/qa_tests_data/classical/case_62/report.rst
Labels: enhancement

#6469 Merged commands `oq workers status` and `oq workers inspect`
  openquake/baselib/workerpool.py
Labels: internal

#6470 Splitting large classical calculations in bunches of tasks to save memory
  openquake/baselib/__init__.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commands/engine.py
  openquake/engine/openquake.cfg
Labels: enhancement

#6471 Unified the various distribution mechanisms
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/workerpool.py
  openquake/commands/workers.py
  openquake/engine/engine.py
  openquake/server/dbserver.py
Labels: internal

#6472 Added command `oq workers kill`
  openquake/baselib/parallel.py
  openquake/commands/workers.py
Labels: internal

#6473 Solved the case of a closed parent datastore
  openquake/baselib/datastore.py
Labels: bug

#6474 Made the celery distribution consistent with zmq
  openquake/baselib/parallel.py
  openquake/engine/engine.py
Labels: internal

#6476 Store the poes on-the-fly and not at the end
  debian/changelog
  openquake/calculators/classical.py
Labels: performance

#6477 Error for for zero probabilities in the hypocenter/nodal plane distributions
  debian/changelog
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#6478 Extended `oq plot` to more than 2 plots
  debian/changelog
  openquake/commands/plot.py
Labels: enhancement

#6479 Fix to the install.py script when the venv directory exists but it is empty
  install.py
Labels: enhancement

#6481 Updated the documentation about installing the engine for development
  doc/installing/development.md
Labels: documentation

#6483 Update the documentation about installing on macOS
  doc/installing/macos.md
Labels: packaging

#6482 Saving memory in the classical calculator without splitting the calculation in bunches
  openquake/calculators/classical.py
  openquake/engine/openquake.cfg
Labels: performance

#6484 Reduced storage time for the poes from 10 hours to 5 minutes
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/getters.py
  openquake/risklib/riskinput.py
Labels: performance

#6487 Replace wget with curl in Mac installation instructions
  doc/installing/macos.md
Labels: documentation

#6486 Fixed `vs30measured` and `backarc` CSV fields
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_2/expected_output/rlz-1-SA(0.1)-sid-0-poe-0_Mag.csv
  openquake/qa_tests_data/disagg/case_2/site_model.csv
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
Labels: bug

#6488 Improved installation instructions
  doc/faq.md
  doc/installing/linux-generic.md
  doc/installing/overview.md
  doc/whats-new.md
  openquake/baselib/sap.py
  openquake/commands/info.py
Labels: documentation

#6490 update Copyright to year 2021
  docker/Dockerfile.base
  docker/Dockerfile.dask
  docker/Dockerfile.engine
  docker/zmq/Dockerfile.master
  docker/zmq/Dockerfile.worker
Labels: documentation

#6489 Updated install.py to install the standalone apps
  doc/installing/universal.md
  install.py
Labels: packaging

#6491 Fixed `oq plot hmaps`
  openquake/commands/plot.py
Labels: bug, internal

#6492 Reduce by 10x the weight of point sources
  openquake/hazardlib/source/base.py
Labels: performance

#6493 Storing the gmf standard deviation
  openquake/baselib/general.py
  openquake/calculators/ebrisk.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/stats.py
Labels: enhancement

#6494 Refactored a bit the taxonomy mapping
  openquake/calculators/base.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#6495 Made the calculation report exportable with `--exports rst`
  debian/changelog
  openquake/calculators/base.py
Labels: bug

#6496 Read parallel.CT from openquake.cfg
  openquake/baselib/parallel.py
Labels: enhancement
