Repository gem/oq-engine, pull requests merged in 2021-08, with the labels that each got.

#7058 Saved memory in gen_poes
  openquake/hazardlib/contexts.py
Labels: performance

#7061 Fixed the USA model in engine-3.11
  openquake/calculators/views.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/qa_tests_data/event_based_risk/case_1/job_damage.ini
Labels: bug, critical

#7060 Documented the base compute method
  openquake/hazardlib/gsim/base.py
Labels: documentation

#7059 Fixed a bug in the adjustment term in NSHMP2014 breaking the USA model
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/qa_tests_data/classical/case_72/__init__.py
  openquake/qa_tests_data/classical/case_72/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_72/gmmLT.xml
  openquake/qa_tests_data/classical/case_72/job.ini
  openquake/qa_tests_data/classical/case_72/lookup_reqv_asc.hdf5
  openquake/qa_tests_data/classical/case_72/sites.csv
  openquake/qa_tests_data/classical/case_72/ssm/WUSActiveShallowSources.xml
  openquake/qa_tests_data/classical/case_72/ssmLT.xml
Labels: bug

#7062 cluster ansible playbook
  .github/workflows/cluster_ansible.yml
  ansible/cluster/inst_nfs.yaml
  ansible/cluster/molecule/default/Dockerfile.j2
  ansible/playbook/molecule/default/molecule.yml
Labels: internal

#7064 Require the imtls dictionary in the ContextMaker
  doc/performance-mosaic.org
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#7068 Enhanced backward-compatibility of GSIMs taking recarrays
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: bug

#7076 Fast tests/1
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/stewart_2016_vh_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/zalachoris_rathje_2019_test.py
Labels: performance, internal

#7077 Fast tests/2
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/zhao_2016_test.py
Labels: performance, internal

#7078 Fast tests/3
  openquake/hazardlib/tests/gsim/abrahamson_2014_test.py
  openquake/hazardlib/tests/gsim/abrahamson_2015_test.py
  openquake/hazardlib/tests/gsim/abrahamson_2018_test.py
  openquake/hazardlib/tests/gsim/abrahamson_gulerce_2020_test.py
  openquake/hazardlib/tests/gsim/abrahamson_silva_1997_test.py
  openquake/hazardlib/tests/gsim/afshari_stewart_2016_test.py
  openquake/hazardlib/tests/gsim/akkar_2013_test.py
  openquake/hazardlib/tests/gsim/akkar_2014_test.py
  openquake/hazardlib/tests/gsim/akkar_bommer_2010_swiss_test.py
  openquake/hazardlib/tests/gsim/akkar_bommer_2010_test.py
  openquake/hazardlib/tests/gsim/akkar_cagnan_2010_test.py
  openquake/hazardlib/tests/gsim/allen_2012_ipe_test.py
  openquake/hazardlib/tests/gsim/allen_2012_test.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
  openquake/hazardlib/tests/gsim/armenia_2016_test.py
  openquake/hazardlib/tests/gsim/atkinson_2015_test.py
  openquake/hazardlib/tests/gsim/atkinson_boore_1995_test.py
  openquake/hazardlib/tests/gsim/data/AB95/AB95GSCBest_MEAN.csv
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/zhao_2006_test.py
Labels: performance, internal

#7079 Fast tests/4
  openquake/hazardlib/tests/gsim/atkinson_boore_2003_test.py
  openquake/hazardlib/tests/gsim/atkinson_macias_2009_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/tests/gsim/baumont_2018_test.py
  openquake/hazardlib/tests/gsim/bchydro_2016_epistemic_test.py
  openquake/hazardlib/tests/gsim/berge_thierry_2003_test.py
  openquake/hazardlib/tests/gsim/bindi_2011_ipe_test.py
  openquake/hazardlib/tests/gsim/bindi_2011_test.py
  openquake/hazardlib/tests/gsim/bindi_2011scaled_test.py
  openquake/hazardlib/tests/gsim/bindi_2017_test.py
  openquake/hazardlib/tests/gsim/bommer_2009_test.py
  openquake/hazardlib/tests/gsim/boore_1993_test.py
  openquake/hazardlib/tests/gsim/boore_1997_test.py
  openquake/hazardlib/tests/gsim/boore_2014_test.py
  openquake/hazardlib/tests/gsim/boore_2020_test.py
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BINDI2011scaled/BINDI2011scaled_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_inter_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_intra_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_mean.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_total_std.csv
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SInter_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/YOUNGS97/Y97SSlab_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/youngs_1997_test.py
  openquake/hazardlib/tests/gsim/yu_2013_ms_test.py
  openquake/hazardlib/tests/gsim/yu_2013_mw_test.py
Labels: performance, internal

#7080 Fast tests/5
  openquake/hazardlib/tests/gsim/abrahamson_silva_2008_test.py
  openquake/hazardlib/tests/gsim/afshari_stewart_2016_test.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/baumont_2018_test.py
  openquake/hazardlib/tests/gsim/bindi_2014_test.py
  openquake/hazardlib/tests/gsim/boore_atkinson_2008_test.py
  openquake/hazardlib/tests/gsim/boore_atkinson_2011_test.py
  openquake/hazardlib/tests/gsim/bozorgnia_campbell_2016_test.py
  openquake/hazardlib/tests/gsim/bozorgnia_campbell_2016_vh_test.py
  openquake/hazardlib/tests/gsim/bradley_2013_test.py
  openquake/hazardlib/tests/gsim/campbell_1997_test.py
  openquake/hazardlib/tests/gsim/campbell_2003_test.py
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2003_test.py
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2008_test.py
  openquake/hazardlib/tests/gsim/can15/eastern_test.py
  openquake/hazardlib/tests/gsim/can15/sinter_test.py
  openquake/hazardlib/tests/gsim/can15/sslab_test.py
  openquake/hazardlib/tests/gsim/can15/utils_test.py
  openquake/hazardlib/tests/gsim/can15/western_rjb_test.py
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_NoSOF_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_NoSOF_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_NoSOF_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_NoSOF_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_EC8_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_Vs30_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_Vs30_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_Vs30_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rhypo_Vs30_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_NoSOF_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_NoSOF_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_NoSOF_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_NoSOF_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_EC8_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_Vs30_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_Vs30_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_Vs30_MEAN.csv
  openquake/hazardlib/tests/gsim/data/BINDI2014/B14_Rjb_Vs30_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C03/C03SHARE_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C03/C03SHARE_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/C03/C03_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C03/C03_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CAN15/GMPEt_Wcrust_med.csv
  openquake/hazardlib/tests/gsim/data/NGA/BA08/A10H_MEDIAN_1KM.csv
  openquake/hazardlib/tests/gsim/data/NGA/BA08/A10H_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance, internal

#7081 Fast tests/6
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2014_test.py
  openquake/hazardlib/tests/gsim/cauzzi_2014_test.py
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_EC8_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_EC8_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_EC8_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_FIXEDVS_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_FIXEDVS_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_FIXEDVS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_FIXEDVS_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_EC8_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_EC8_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_EC8_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_EC8_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_FIXEDVS_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_FIXEDVS_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_FIXEDVS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_FIXEDVS_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_INTER_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_INTRA_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_MEAN.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_NoSOF_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/C14/CAUZZI_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance, internal

#7083 Fast tests/7
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_swiss_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/chao_2020_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2008_swiss_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2008_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
  openquake/hazardlib/tests/gsim/climent_1994_test.py
  openquake/hazardlib/tests/gsim/convertito_2012_test.py
  openquake/hazardlib/tests/gsim/drouet_2015_test.py
Labels: performance, internal

#7085 Fast tests/8
  openquake/engine/engine.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd10_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd120_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd20_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd30_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd50_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd75_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/alp_sd90_table.csv
  openquake/hazardlib/tests/gsim/data/EF13a/ef_2013_phis_ss_embeded.csv
  openquake/hazardlib/tests/gsim/data/EF13f/ef_2013_phis_ss_embeded.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd10_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd120_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd20_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd30_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd50_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd60_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd75_table.csv
  openquake/hazardlib/tests/gsim/data/EF13f/for_sd90_table.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96MblgAB1987_MEAN.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96MblgAB1987_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96MblgJ1996_MEAN.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96MblgJ1996_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96Mw_MEAN.csv
  openquake/hazardlib/tests/gsim/data/FRANKEL1996/FRANKEL96Mw_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/edwards_faeh_2013_alpine_test.py
  openquake/hazardlib/tests/gsim/edwards_faeh_2013_foreland_test.py
  openquake/hazardlib/tests/gsim/eshm20_craton_test.py
  openquake/hazardlib/tests/gsim/faccioli_cauzzi_2006_ipe_test.py
  openquake/hazardlib/tests/gsim/frankel_1996_test.py
  openquake/hazardlib/tests/gsim/fukushima_tanaka_1990_test.py
  openquake/hazardlib/tests/gsim/garcia_2005_test.py
  openquake/hazardlib/tests/gsim/geomatrix_1993_test.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
  openquake/hazardlib/tests/gsim/ghofrani_atkinson_test.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/gulerce_2017_test.py
  openquake/hazardlib/tests/gsim/gulerce_abrahamson_2011_test.py
  openquake/hazardlib/tests/gsim/gupta_2010_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance, internal

#7086 Fast tests/9
  openquake/hazardlib/tests/gsim/data/IDRISS14/IDRISS_2014_MEAN.csv
  openquake/hazardlib/tests/gsim/data/IDRISS14/IDRISS_2014_TOTAL_STD.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/ASK14_NSHMP_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/ASK14_NSHMP_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/BSSA14_NSHMP_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/BSSA14_NSHMP_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/CB14_NSHMP_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/CB14_NSHMP_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/CY14_NSHMP_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/CY14_NSHMP_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/IDRISS14_NSHMP_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/NSHMP2014/IDRISS14_NSHMP_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_ESHM_CENTRAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_ESHM_STDDEV_INTER_EVENT.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_ESHM_STDDEV_INTRA_EVENT.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_ESHM_STDDEV_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_GEOLOGY_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_SLOPE_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_STDDEV_INTER_EVENT.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_STDDEV_INTRA_EVENT.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_STDDEV_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/kotha20/KOTHA_2020_VS30_MEAN.csv
  openquake/hazardlib/tests/gsim/hassani_atkinson_2020_test.py
  openquake/hazardlib/tests/gsim/hong_goda_2007_test.py
  openquake/hazardlib/tests/gsim/idini_2017_test.py
  openquake/hazardlib/tests/gsim/idriss_2014_test.py
  openquake/hazardlib/tests/gsim/kale_2015_test.py
  openquake/hazardlib/tests/gsim/kanno_2006_test.py
  openquake/hazardlib/tests/gsim/kotha_2016_test.py
  openquake/hazardlib/tests/gsim/kotha_2020_test.py
  openquake/hazardlib/tests/gsim/lanzano_2016_test.py
  openquake/hazardlib/tests/gsim/lanzano_2019_test.py
  openquake/hazardlib/tests/gsim/lanzano_2020_test.py
  openquake/hazardlib/tests/gsim/lanzano_luzi_2019_test.py
  openquake/hazardlib/tests/gsim/lin_2009_test.py
  openquake/hazardlib/tests/gsim/lin_lee_2008_test.py
  openquake/hazardlib/tests/gsim/mcverry_2006_test.py
  openquake/hazardlib/tests/gsim/montalva_2016_test.py
  openquake/hazardlib/tests/gsim/montalva_2017_test.py
  openquake/hazardlib/tests/gsim/morikawa_fujiwara_2013_test.py
  openquake/hazardlib/tests/gsim/munson_thurber_1997_test.py
  openquake/hazardlib/tests/gsim/nath_2012_test.py
  openquake/hazardlib/tests/gsim/nga_east_full_uncertainty_test.py
  openquake/hazardlib/tests/gsim/nga_east_median_test.py
  openquake/hazardlib/tests/gsim/nga_east_total_sigma_test.py
  openquake/hazardlib/tests/gsim/nshmp_2014_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance, internal

#7014 LT adding more epistemic uncertainties
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/simple_fault.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_58/sscLT.xml
  openquake/qa_tests_data/classical/case_58/sscLTcase01.xml
  openquake/qa_tests_data/classical/case_73/__init__.py
  openquake/qa_tests_data/classical/case_73/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_73/gmcLT.xml
  openquake/qa_tests_data/classical/case_73/job.ini
  openquake/qa_tests_data/classical/case_73/source_model.xml
  openquake/qa_tests_data/classical/case_73/sscLT.xml
  openquake/qa_tests_data/classical/case_73/ssm.xml
Labels: enhancement

#7089 Fast tests/11
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_NEHRPBC_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_NEHRPBC_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/parker_2020_test.py
  openquake/hazardlib/tests/gsim/pezeshk_2011_test.py
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
  openquake/hazardlib/tests/gsim/sgobba_2020_test.py
  openquake/hazardlib/tests/gsim/sharma_2009_test.py
  openquake/hazardlib/tests/gsim/somerville_2009_test.py
  openquake/hazardlib/tests/gsim/tem20/lin_2011_foot_test.py
  openquake/hazardlib/tests/gsim/tem20/lin_2011_hanging_test.py
  openquake/hazardlib/tests/gsim/toro_2002_test.py
  openquake/hazardlib/tests/gsim/tusa_langer_2016_test.py
  openquake/hazardlib/tests/gsim/usgs_ceus_2019_test.py
Labels: performance, internal

#7090 Fast tests/12
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/raghukanth_iyengar_2007.py
  openquake/hazardlib/tests/gsim/kuehn_2020_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance, internal

#7091 Fast tests/13
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/tests/gsim/data/generic_avgsa/GENERIC_GMPE_AVGSA_AKKAR_MEAN.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/GENERIC_GMPE_AVGSA_AKKAR_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/GENERIC_GMPE_AVGSA_BAKER_JAYARAM_MEAN.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/GENERIC_GMPE_AVGSA_BAKER_JAYARAM_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/ecos09_test.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/hazardlib/tests/gsim/pankow_pechmann_2004_test.py
  openquake/hazardlib/tests/gsim/sera_site_amplification_test.py
  openquake/hazardlib/tests/gsim/shahjouei_pezeshk_2016_test.py
  openquake/hazardlib/tests/gsim/silva_2002_test.py
  openquake/hazardlib/tests/gsim/skarlatoudis_2013_test.py
  openquake/hazardlib/tests/gsim/somerville_2001_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/vanhoutte_2018_test.py
  openquake/hazardlib/tests/gsim/yenier_atkinson_2015_test.py
Labels: performance, internal

#7093 Fast tests/14
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterNECorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SInterSWCorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabNECorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/SM99/SM99SSlabSWCorr_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/megawati_2003.py
  openquake/hazardlib/tests/gsim/megawati_pan_2010_test.py
  openquake/hazardlib/tests/gsim/si_midorikawa_1999_test.py
Labels: performance, internal

#7092 Fast tests/15
  debian/changelog
  openquake/hazardlib/gsim/dowrickrhoades_2005.py
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Asc.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Asc_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Asc_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Asc_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Asc_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SInter.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SInter_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SInter_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SInter_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SSlab.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SSlab_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SSlab_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005SSlab_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Volc.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Volc_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Volc_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Volc_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/DOWRICKRHOADES2005/DowrickRhoades2005Volc_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/dowrickrhoades_2005_test.py
  utils/build_vtable
Labels: performance, internal

#7098 Fixed MultiFaultSources
  debian/changelog
  doc/adv-manual/index.rst
  doc/adv-manual/multifault.rst
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/source_model/kite-fault-source.xml
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: bug

#7100 Fixed another bug of MultiFaultSources
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/classical/case_65/job.ini
Labels: bug

#7103 Fixed eshm20_craton GMPE
  openquake/hazardlib/gsim/eshm20_craton.py
Labels: bug

#7104 Fixed the documentation on `gmvs_to_poes`
  doc/adv-manual/pandas.rst
  openquake/commonlib/calc.py
Labels: documentation

#7106 Removed mag-dependent pointsource_distance
  debian/changelog
  doc/adv-manual/common-mistakes.rst
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/classical/case_19/expected/hazard_curve-mean_SA(0.15).csv
Labels: internal

#7105 Changed GmfComputer.compute_all
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/getters.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
Labels: internal

#7101 Installation of WebUI with new Django
  debian/systemd/openquake-webui.service
  doc/installing/examples/nginx.md
  helpers/zipdemos.sh
  openquake/server/local_settings.py.pam
  openquake/server/tests/views_test.py
  openquake/server/urls.py
  openquake/server/v1/calc_urls.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
  setup.py
Labels: enhancement

#7110 Added utility hazardlib.read_input
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/__init__.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/data/rup.xml
  openquake/hazardlib/tests/calc/scenario_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
Labels: documentation

#7112 Changed the API of stochastic.sample_ruptures
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: internal

#7114 Simplified GMF calculator
  demos/hazard/EventBasedPSHA/job.ini
  demos/hazard/EventBasedPSHA/job.py
  demos/hazard/EventBasedPSHA/site_model.csv
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/stochastic.py
Labels: enhancement, documentation

#7107 Zipping the demos better
  openquake/commands/zip.py
  openquake/commonlib/oqzip.py
Labels: packaging

#7116 Fixed oq check_input in multi-user situations
  openquake/calculators/base.py
  openquake/calculators/reportwriter.py
  openquake/commands/check_input.py
  openquake/commonlib/logs.py
  openquake/hazardlib/calc/hazard_curve.py
Labels: bug

#7117 Extended the multi-rupture scenario calculator to multiple TRTs
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/__init__.py
Labels: internal

#7119 Fix `oq --version` for branch-based user installations
  install.py
Labels: packaging

#7120 Regenerated the verification table for BooreEtAl2020
  openquake/hazardlib/tests/gsim/boore_2020_test.py
  openquake/hazardlib/tests/gsim/data/BOORE20/BooreEtAl2020.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_inter_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_intra_std.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_mean.csv
  openquake/hazardlib/tests/gsim/data/BOORE20/Boore_2020_total_std.csv
  utils/build_vtable
Labels: bug, internal

#7121 Fixed an import issue affecting Python 3.6
  openquake/hazardlib/lt.py
Labels: bug

#7131 Fixed slow tasks due to wrong weight of CollapsedFaultSources
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/base.py
Labels: performance

#7133 Better parallelization of the preclassical calculator
  openquake/calculators/classical.py
  openquake/hazardlib/source/base.py
Labels: performance

#7138 Use higher def vulnerability functions for the BCR demo
  demos/risk/ClassicalBCR/job_hazard.ini
  demos/risk/ClassicalBCR/job_risk.ini
  demos/risk/ClassicalBCR/structural_vulnerability_model.xml
  demos/risk/ClassicalBCR/vulnerability_model_original.xml
  demos/risk/ClassicalBCR/vulnerability_model_retrofitted.xml
Labels: documentation

#7139 Printing a warning in case of extreme GMVs
  openquake/calculators/event_based.py
  openquake/calculators/views.py
Labels: enhancement
