Repository gem/oq-engine, pull requests merged in 2022-03, with the labels that each got.

#7618 Made preclassical for UCERF faster
  openquake/hazardlib/source/multi_fault.py
Labels: performance

#7617 Made amplification compatible with vectorization
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: performance

#7621 Disable the distance cache by default
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_75/job.ini
Labels: performance

#7620 Reducing the preclassical for UCERF to <1 seconds
  openquake/calculators/preclassical.py
  openquake/hazardlib/source/multi_fault.py
Labels: performance

#7624 Split get_probability_no_exceedance in two functions
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tom.py
Labels: internal

#7623 Turn cluster workers into standalone workers
  openquake/baselib/parallel.py
Labels: enhancement

#7622 Raised a helpful error message when ensurepip is missing
  debian/changelog
  doc/installing/universal.md
  install.py
Labels: dependencies

#7625 Fixing the MultiFaultSources weight
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
Labels: performance

#7628 Improved the preclassical calculator
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
Labels: performance

#7627 update Django to rel. 3.2.12
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos.txt
  requirements-py39-win64.txt
Labels: dependencies

#7631 Fixed bug with discard_trts
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
Labels: bug

#7632 Changed the default amplification method to "convolution"
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_49/job.ini
Labels: enhancement

#7633 Changed /extract/events to return events sorted by ID to make the QGIS plugin happy
  debian/changelog
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
Labels: bug, backport

#7630 updating to geometric mean
  openquake/hazardlib/gsim/atkinson_boore_2006.py
Labels: internal

#7635 Added a test using another user oqdata
  openquake/commands/tests/commands_test.py
Labels: internal

#7636 Unskipped a test for acme
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: internal

#7637 Changed the signature of get_poes
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/nshmp_2014.py
Labels: bug, internal

#7638 Added a method ContextMaker.convert
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/contexts_test.py
Labels: internal

#7639 Added missing [directory] in the openquake.cfg generate by install.py
  install.py
Labels: bug

#7640 Collapsing the contexts/15
  openquake/calculators/preclassical.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: internal

#7641 Added test for CanadaSHM6
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_76/__init__.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.csv
  openquake/qa_tests_data/classical/case_76/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_76/job.ini
  openquake/qa_tests_data/classical/case_76/source_model.xml
  openquake/qa_tests_data/classical/case_76/source_model_logic_tree.xml
Labels: internal

#7642 Reserving case_76 for CanadaSHM6
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_76/__init__.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.csv
  openquake/qa_tests_data/classical/case_76/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_76/job.ini
  openquake/qa_tests_data/classical/case_76/source_model.xml
  openquake/qa_tests_data/classical/case_76/source_model_logic_tree.xml
Labels: internal

#7644 Fixed frequency<->period mismatch in EAS, FAS, DRTV
  openquake/hazardlib/contexts.py
  openquake/hazardlib/imt.py
Labels: internal

#7645 Collapsing the contexts/16
  openquake/baselib/general.py
  openquake/baselib/tests/general_test.py
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/classical/README.md
Labels: internal

#7646 Fix a typo in Kuehn et al. (2020) model
  debian/changelog
  openquake/hazardlib/gsim/kuehn_2020.py
Labels: bug

#7647 Collapsing the contexts/17
  openquake/calculators/tests/classical_test.py
  openquake/commands/compare.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7648 Raised an error when the total standard deviation is zero
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/yenier_atkinson_2015_test.py
Labels: enhancement

#7650 Storing the correct occurrence rate in the ruptures dataset
  openquake/commonlib/source_reader.py
  openquake/hazardlib/source/base.py
Labels: bug, internal

#7651 Refactored `extract_mfd`
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/stochastic.py
  openquake/server/tests/views_test.py
Labels: internal

#7652 Moved the PolygonPlotter in hazardlib
  openquake/commands/plot.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/utils.py
Labels: internal

#7653 Special case for the the datadir of the user openquake
  openquake/commonlib/logs.py
Labels: bug

#7657 Fixed a bug in preclassical case_50
  openquake/calculators/base.py
  openquake/calculators/preclassical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/views.py
  openquake/commonlib/source_reader.py
Labels: bug, internal

#7659 change install.py to have different ExecStart for dbserver and webui
  install.py
Labels: bug

#7656 Added method ModifiableGMPE.set_tables
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_77/__init__.py
  openquake/qa_tests_data/classical/case_77/expected/uhs-mean.csv
  openquake/qa_tests_data/classical/case_77/gmmLT_tab.xml
  openquake/qa_tests_data/classical/case_77/job.ini
  openquake/qa_tests_data/classical/case_77/source_model.xml
  openquake/qa_tests_data/classical/case_77/source_model_logic_tree.xml
Labels: bug

#7662 Rounded the magnitudes in multiFaultSources to two digits
  debian/changelog
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#7664 Introduced function valid.namelists
  openquake/hazardlib/valid.py
Labels: enhancement

#7666 Not storing the aggregation keys
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/risklib/asset.py
Labels: internal

#7667 Stored agg_keys as an array of variable-length strings
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_17/agg_keys.org
Labels: internal

#7668 More refactoring
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/risklib/asset.py
Labels: internal

#7654 Kuehn model bug fix
  debian/changelog
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_ALASKA_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_CAM_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_CASCADIA_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_GLOBAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_GLOBAL_Mb7.7_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_GLOBAL_Mb8.1_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_GLOBAL_epsilon-1_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_GLOBAL_epsilon1_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_JAPAN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_NEWZEALAND_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_SOUTHAMERICA_MEAN.csv
  openquake/hazardlib/tests/gsim/data/kuehn2020/KUEHN2020_INTERFACE_TAIWAN_MEAN.csv
Labels: bug

#7669 Implemented num_rlzs_disagg=0
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_4/job.ini
Labels: enhancement

#7670 Refactored the aggrisk/aggcurves exporters
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
Labels: internal

#7661 change git protocol for packager.sh
  packager.sh
Labels: internal

#7671 Using agg_values less
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
Labels: internal

#7674 Updated the FAQ about clusters
  doc/faq-cluster.md
Labels: documentation

#7672 Removed dependency from shapefile module
  .github/workflows/engine_test.yml
  debian/changelog
  doc/adv-manual/oq-commands.rst
  doc/sphinx/openquake.commands.rst
  openquake/commands/from_shapefile.py
  openquake/commands/tests/commands_test.py
  openquake/commands/to_shapefile.py
  openquake/commonlib/shapefileparser.py
  openquake/hazardlib/shakemap/parsers.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos.txt
  requirements-py39-win64.txt
  setup.py
Labels: dependencies

#7676 Fixed missing occurrence_rate
  openquake/hazardlib/contexts.py
Labels: bug

#7680 Fixed aggcurves-stats and aggrisk-stats
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
Labels: bug

#7681 Fixed small bug in by_country
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
Labels: bug

#7682 Fixed source ID recognition
  openquake/commonlib/logictree.py
Labels: bug

#7683 Fixed the check on unique section IDs
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/nrml.py
  openquake/qa_tests_data/classical/case_75/extra_section.xml
  openquake/qa_tests_data/classical/case_75/wrong_ssmLT.xml
Labels: bug

#7684 Extended `oq reduce_sm` to multiFaultSources
  debian/changelog
  openquake/commonlib/readinput.py
Labels: bug, enhancement

#7685 Changed zip_all to generate a single archive for the entire mosaic
  openquake/commands/zip.py
  openquake/commonlib/oqzip.py
Labels: internal

#7688 Reduced tolerance in kuehn2020_test
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/tests/gsim/kuehn_2020_test.py
Labels: internal

#7687 Documented collect_rlzs
  doc/adv-manual/risk.rst
Labels: documentation

#7689 Update risk-profiles page in advanced manual
  doc/adv-manual/risk-profiles.rst
Labels: documentation

#7686 Removing support for Python 3.6
  doc/faq-cluster.md
  doc/faq.md
  openquake/commands/__main__.py
  openquake/commands/tests/commands_test.py
  requirements-py36-linux64.txt
  requirements-py36-macos.txt
  requirements-py36-win64.txt
Labels: dependencies

#7692 Delete stray file sources.gpkg
  sources.gpkg
Labels: internal

#7694 From gpkg to nrml
  openquake/hazardlib/geo/packager.py
  openquake/hazardlib/sourceconverter.py
Labels: internal
