Repository gem/oq-engine, pull requests merged in 2022-02, with the labels that each got.

#7528 Speeding up `MultiFaultSource.get_bounding_box`
  .github/workflows/engine_test.yml
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source/non_parametric.py
Labels: performance

#7530 Vectorized chiou_youngs_2008_swiss
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
Labels: performance

#7531 Using numpy.clip more
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/tests/geo/point_test.py
Labels: internal

#7532 Vectorizing the US NSHM model
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/armenia_2016.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/idriss_2014.py
  openquake/hazardlib/gsim/mgmpe/cy14_site_term.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance

#7533 Made it possible to set the default pointsource_distance in openquake.cfg
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
Labels: performance

#7536 Refactore the nrcan15_site_term_test
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
Labels: internal

#7537 Vectorized many more GMPEs for the US model
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/can15/utils.py
  openquake/hazardlib/gsim/can15/western.py
Labels: performance

#7534 Gc2kitenew
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/qa_tests_data/classical/case_61/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_62/expected/hcurve-mean.csv
Labels: enhancement

#7539 Fixed an AttributeError
  openquake/hazardlib/contexts.py
Labels: bug

#7540 Vectorized the last GMPEs for the US model
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/frankel_1996.py
  openquake/hazardlib/gsim/silva_2002.py
  openquake/hazardlib/gsim/somerville_2001.py
  openquake/hazardlib/gsim/tavakoli_pezeshk_2005.py
Labels: performance

#7542 Vectorized children of Cauzzi2014
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
Labels: performance

#7543 Fixed vectorization of abrahamson_2015
  openquake/hazardlib/gsim/abrahamson_2015.py
Labels: bug

#7544 Added a parameter receiver_host in openquake.cfg
  openquake/baselib/parallel.py
  openquake/engine/openquake.cfg
Labels: internal

#7545 Typo fix
  doc/installing/rhel-nightly.md
Labels: documentation

#7546 Vectorized a lot more GMPEs
  openquake/hazardlib/gsim/abrahamson_silva_1997.py
  openquake/hazardlib/gsim/akkar_2014.py
  openquake/hazardlib/gsim/allen_2012.py
  openquake/hazardlib/gsim/boore_1997.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2003.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/geomatrix_1993.py
  openquake/hazardlib/gsim/kanno_2006.py
  openquake/hazardlib/gsim/munson_thurber_1997.py
  openquake/hazardlib/gsim/sharma_2009.py
  openquake/hazardlib/gsim/somerville_2009.py
Labels: performance

#7547 Vectorized many more GMPEs
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/akkar_cagnan_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/bindi_2011.py
  openquake/hazardlib/gsim/bindi_2011_ipe.py
  openquake/hazardlib/gsim/bindi_2014.py
  openquake/hazardlib/gsim/bindi_2017.py
  openquake/hazardlib/gsim/lanzano_2016.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/lin_2009.py
  openquake/hazardlib/gsim/munson_thurber_1997.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/travasarou_2003.py
  openquake/hazardlib/gsim/tromans_2019.py
  openquake/hazardlib/gsim/utils.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
Labels: performance

#7538 Updating changelog [ci skip]
  debian/changelog
Labels: documentation

#7548 Vectorized Sadigh1997
  openquake/hazardlib/gsim/sadigh_1997.py
Labels: performance

#7551 Vectorized more GMPEs
  openquake/hazardlib/gsim/campbell_1997.py
  openquake/hazardlib/gsim/nath_2012.py
  openquake/hazardlib/gsim/raghukanth_iyengar_2007.py
  openquake/hazardlib/gsim/si_midorikawa_1999.py
Labels: performance

#7550 Adding test for multi-fault source
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_75/__init__.py
  openquake/qa_tests_data/classical/case_75/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_75/gmmLT.xml
  openquake/qa_tests_data/classical/case_75/job.ini
  openquake/qa_tests_data/classical/case_75/ruptures_0.xml
  openquake/qa_tests_data/classical/case_75/ruptures_0_sections.xml
  openquake/qa_tests_data/classical/case_75/ssmLT.xml
Labels: internal

#7553 Small fix to the RecordBuilder defaults for string fields
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/kotha_2020.py
Labels: internal

#7554 Introduced computed rupture parameters
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/site.py
  openquake/hazardlib/valid.py
Labels: enhancement, internal

#7552 Vectorized the entire mosaic (nearly)
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/climent_1994.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/gsim/zhao_2016.py
Labels: performance

#7558 Removed circular import
  openquake/calculators/tests/__init__.py
  openquake/commands/run.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/engine/engine.py
Labels: internal

#7559 Refactoring GMPETable/1
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/tests/gsim/data/gsimtables/good_dummy_table_multi_stddev.hdf5
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
Labels: internal

#7562 Sponsors logo
  README.md
Labels: documentation

#7565 Optimized NBCC_AA13 GMPEs
  debian/changelog
  openquake/calculators/event_based.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/tests/gsim/can15/eastern_test.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
  openquake/hazardlib/tests/gsim/nga_east_full_uncertainty_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance

#7568 Reordering the contexts by magnitude
  openquake/hazardlib/contexts.py
Labels: performance, internal

#7569 Optimizing gmpe_table._get_mean
  openquake/hazardlib/gsim/gmpe_table.py
Labels: performance

#7572 Vectorized derras_2014
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
Labels: performance

#7535 Documentation on server installation with group authentication with django
  doc/installing/server.md
Labels: documentation

#7574 Raised the limit to 94 GMPEs per tectonic region type and 94 branches per source model logic tree
  debian/changelog
  openquake/baselib/general.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/lt.py
Labels: enhancement, backport

#7576 Small refactoring of get_poes
  doc/tutorials/the-datastore/datastore.org
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/contexts_test.py
Labels: internal

#7577 Vectorized a lot more GMPEs
  openquake/hazardlib/gsim/allen_2012_ipe.py
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/gsim/armenia_2016.py
  openquake/hazardlib/gsim/arroyo_2010.py
  openquake/hazardlib/gsim/atkinson_2015.py
  openquake/hazardlib/gsim/bahrampouri_2021.py
  openquake/hazardlib/gsim/bahrampouri_2021_duration.py
  openquake/hazardlib/gsim/baumont_2018.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can15/sinter.py
  openquake/hazardlib/gsim/can15/sslab.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/douglas_stochastic_2013.py
  openquake/hazardlib/gsim/dowrickrhoades_2005.py
  openquake/hazardlib/gsim/drouet_2015_brazil.py
  openquake/hazardlib/gsim/drouet_alpes_2015.py
  openquake/hazardlib/gsim/kale_2015.py
  openquake/hazardlib/gsim/kotha_2016.py
  openquake/hazardlib/gsim/lanzano_luzi_2019.py
  openquake/hazardlib/gsim/manea_2021.py
  openquake/hazardlib/gsim/megawati_pan_2010.py
  openquake/hazardlib/gsim/toro_1997.py
  openquake/hazardlib/gsim/toro_2002.py
  openquake/hazardlib/tests/gsim/bahrampouri_2021_duration_test.py
  openquake/hazardlib/tests/gsim/data/AR10/AR10_SINTER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AR10/AR10_SINTER_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/AR10/AR10_SINTER_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/AR10/AR10_SINTER_STD_TOTAL.csv
Labels: performance

#7578 Vectorized more GMPEs
  openquake/hazardlib/gsim/afshari_stewart_2016.py
  openquake/hazardlib/gsim/berge_thierry_2003.py
  openquake/hazardlib/gsim/dost_2004.py
  openquake/hazardlib/gsim/edwards_fah_2013a.py
  openquake/hazardlib/gsim/edwards_fah_2013f.py
  openquake/hazardlib/gsim/idini_2017.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/rietbrock_edwards_2019.py
  openquake/hazardlib/gsim/si_2020.py
  openquake/hazardlib/gsim/tusa_langer_azzaro_2019.py
  openquake/hazardlib/gsim/vanhoutte_2018.py
  openquake/hazardlib/gsim/zhao_2006_swiss.py
Labels: performance

#7579 Vectorized more GMPEs
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/fukushima_tanaka_1990.py
  openquake/hazardlib/gsim/ghofrani_atkinson_2014.py
  openquake/hazardlib/gsim/jaimes_2020.py
  openquake/hazardlib/gsim/lanzano_2020.py
  openquake/hazardlib/gsim/pankow_pechmann_2004.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/rietbrock_2013.py
  openquake/hazardlib/gsim/sgobba_2020.py
  openquake/hazardlib/gsim/shahjouei_pezeshk_2016.py
  openquake/hazardlib/gsim/yu_2013.py
Labels: performance

#7580 Vectorized more GMPEs
  openquake/hazardlib/gsim/atkinson_boore_1995.py
  openquake/hazardlib/gsim/boore_1993.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016_vh.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008_swiss.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/megawati_2003.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCBest_MEAN.csv
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCBest_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCLowerLimit_MEAN.csv
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCLowerLimit_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCUpperLimit_MEAN.csv
  openquake/hazardlib/tests/gsim/data/B93GSC/B93GSCUpperLimit_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/CF08Swiss/CF08_MEAN_VsK_1.csv
  openquake/hazardlib/tests/gsim/data/CF08Swiss/CF08_MEAN_VsK_4.csv
  openquake/hazardlib/tests/gsim/data/CF08Swiss/CF08_MEAN_VsK_8.csv
  openquake/hazardlib/tests/gsim/data/CF08Swiss/cf_2008_phis_ss_embeded.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlabV_MEAN.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlabV_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlabV_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlabV_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlab_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlab_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/GA05/GA05SSlab_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/GarciaEtAl2005SSlab.csv
  openquake/hazardlib/tests/gsim/data/GarciaEtAl2005SSlabVert.csv
  openquake/hazardlib/tests/gsim/garcia_2005_test.py
Labels: performance

#7581 Vectorizes the last GMPEs
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_2018.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bommer_2009.py
  openquake/hazardlib/gsim/boore_2020.py
  openquake/hazardlib/gsim/convertito_2012.py
  openquake/hazardlib/gsim/ecos_2009.py
  openquake/hazardlib/gsim/garcia_2005.py
  openquake/hazardlib/gsim/gulerce_2017.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/hong_goda_2007.py
  openquake/hazardlib/gsim/mgmpe/avg_gmpe.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/silva_2002.py
Labels: performance

#7583 Forbidding non-vectorized GMPEs
  debian/changelog
  openquake/hazardlib/gsim/base.py
Labels: performance

#7586 Creation of symlink for openquake manual
  .github/workflows/demos.yml
Labels: documentation

#7584 Fixed the exporter `aggrisk-stats` in the case of zero losses
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats.csv
Labels: bug, backport

#7585 Vectorize the contexts
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/lt_test.py
Labels: performance

#7512 Youd et Al 2002 GMPE
  CONTRIBUTORS.txt
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/youd_etal_2002.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/data/YOUD04/Youd2004_MEAN.csv
  openquake/hazardlib/tests/gsim/data/YOUD04/Youd2004_STDDEV.csv
  openquake/hazardlib/tests/gsim/youd_etal_2002_test.py
Labels: enhancement

#7588 Refactored tests for ameri_2017
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Repi_Homoscedastic_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_INTER_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_INTRA_EVENT_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_MEAN.csv
  openquake/hazardlib/tests/gsim/data/AMERI2017/A17_Rjb_Homoscedastic_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/AmeriEtAl2017RepiStressDrop.csv
  openquake/hazardlib/tests/gsim/data/AmeriEtAl2017RjbStressDrop.csv
Labels: internal

#7587 Collapsing the contexts
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/frankel_1996_test.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/hazardlib/tests/gsim/mgmpe/nrcan15_site_term_test.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
  openquake/hazardlib/tests/gsim/sgobba_2020_test.py
  openquake/hazardlib/tests/gsim/sharma_2009_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
Labels: performance

#7589 Collapsing the contexts/2
  openquake/baselib/performance.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/data/context/job.ini
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_24/job.ini
Labels: performance

#7591 Collapsing the contexts/3
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/data/context/job.ini
  openquake/hazardlib/tests/lt_test.py
Labels: performance

#7592 Collapsing the contexts/4
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/contexts_test.py
Labels: internal

#7593 Collapsing the contexts/5
  openquake/baselib/hdf5.py
  openquake/baselib/performance.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/data/context/job.ini
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_24/job.ini
Labels: performance

#7594 Collapsing the contexts/6
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
Labels: performance

#7595 Limited unique rupture IDs
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_damage_test.py
  openquake/commands/compare.py
  openquake/hazardlib/contexts.py
Labels: internal

#7597 Collapsing the contexts/7
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
Labels: internal

#7564 Buffer
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/__init__.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/multi_old.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/data/context02/ruptures_0.xml
  openquake/hazardlib/tests/data/context02/ruptures_0_sections.xml
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/data/multi_cache_01/ruptures_26.xml
  openquake/hazardlib/tests/geo/surface/data/multi_cache_01/ruptures_26_sections.xml
  openquake/hazardlib/tests/geo/surface/data/multi_cache_01/sites.csv
  openquake/hazardlib/tests/geo/surface/data/nzl/s1493/pro01.txt
  openquake/hazardlib/tests/geo/surface/data/nzl/s1493/pro02.txt
  openquake/hazardlib/tests/geo/surface/data/sections_rupture200_sections.xml
  openquake/hazardlib/tests/geo/surface/gc2_test.py
  openquake/hazardlib/tests/geo/surface/multi_cache_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_simple.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
  openquake/hazardlib/tests/geo/surface/results/results_msf_nan_rx.npz
  openquake/hazardlib/tests/geo/surface/results/results_msf_nan_ry0.npz
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0a.npz
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0b.npz
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0c.npz
  openquake/hazardlib/tests/geo/surface/results/results_nzl_1_rx.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh_back.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh_lons.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_ref_idx.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rprof_0.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rprof_2.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rx.txt
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/source/non_parametric_test.py
  openquake/qa_tests_data/classical/case_65/expected/gmf_data.csv
  openquake/qa_tests_data/classical/case_65/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_75/expected/hcurve-mean.csv
  openquake/qa_tests_data/ucerf/expected/hazard_map-mean.csv
Labels: performance

#7598 Fixed sorting bug in the `/v1/calc/run` web API
  debian/changelog
  openquake/server/views.py
Labels: bug, backport

#7599 Collapsing the contexts/8
  openquake/baselib/general.py
  openquake/baselib/performance.py
  openquake/baselib/tests/general_test.py
  openquake/baselib/tests/performance_test.py
  openquake/hazardlib/contexts.py
Labels: performance

#7600 Fixed passing of the parent_dir in event_based_damage
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/commonlib/datastore.py
Labels: bug, backport

#7601 Add to the modifiable GMPE the NRCan15 site term
  debian/changelog
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/qa_tests_data/classical/case_12/gsim_logic_tree.xml
Labels: enhancement

#7602 Accepted ps_grid_spacing=0
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_43/job.ini
Labels: internal

#7603 Avoid some ugly deepcopy
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
Labels: internal

#7605 Additional collapse test
  openquake/hazardlib/__init__.py
  openquake/hazardlib/tests/contexts_test.py
Labels: internal

#7608 Collapsing the contexts/10
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_3/job.ini
  openquake/qa_tests_data/classical/case_69/__init__.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_69/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_69/job.ini
  openquake/qa_tests_data/classical/case_69/source_model.xml
  openquake/qa_tests_data/classical/case_69/source_model_logic_tree.xml
Labels: internal

#7609 Collapsing the contexts/11
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_69/job.ini
Labels: performance

#7607 Added CanadaSHM6 GMMs
  openquake/hazardlib/gsim/CanadaSHM6_ActiveCrust.py
  openquake/hazardlib/gsim/CanadaSHM6_InSlab.py
  openquake/hazardlib/gsim/CanadaSHM6_Interface.py
  openquake/hazardlib/gsim/CanadaSHM6_StableCrust.py
  openquake/hazardlib/gsim/CanadaSHM6_tables/AA13/ENA_central_cl450.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/AA13/ENA_high_cl450.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/AA13/ENA_low_cl450.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_01_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_02_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_03_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_04_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_05_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_06_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_07_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_08_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_09_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_10_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_11_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_12_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/CanadaSHM6_tables/NGA-East-13/CanadaSHM6-trial_NGA-East_Model_13_AA13_sigma.vs3000.hdf5
Labels: enhancement

#7610 Fix reproducibility bug with OQ_SAMPLE_SOURCES
  openquake/calculators/preclassical.py
Labels: internal

#7611 Add note about Monterey to install script doc
  doc/installing/universal.md
Labels: documentation

#7612 Collapsing the contexts/12
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
Labels: internal
