Repository gem/oq-engine, pull requests merged in 2022-09, with the labels that each got.

#8038 Make `check_disagg_by_src` mandatory
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
Labels: enhancement

#8037 Add installation of tools in install.py
  install.py
Labels: dependencies

#8039 Worked around a numpy.concatenate bug
  openquake/hazardlib/contexts.py
Labels: bug

#8040 Round coordinates to 4 digits in the sourcewriter
  openquake/baselib/general.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/expected_sources.toml
  openquake/hazardlib/tests/source_model/alternative-mfds_4test.xml
  openquake/hazardlib/tests/source_model/complex-fault-source.xml
  openquake/hazardlib/tests/source_model/kite-fault-source.xml
  openquake/hazardlib/tests/source_model/mixed.xml
Labels: outputs, inputs

#8041 Improve error messages for missing taxonomy string cases
  openquake/calculators/base.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/readinput.py
Labels: documentation

#8043 Update universal installer instructions for devel
  doc/installing/universal.md
Labels: documentation

#8042 Fix multifault disagg
  debian/changelog
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: bug

#8044 Fixed disaggregation with mutex sources
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
Labels: bug

#8047 Minor edits to whats-new for engine-3.15 [skip CI]
  doc/whats-new.md
Labels: documentation

#8048 Optimized storing disagg_by_src
  openquake/calculators/classical.py
Labels: performance

#8049 Added a check on `sum(srcs_weights) == 1` for mutex sources
  debian/changelog
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/sourcewriter_test.py
  openquake/qa_tests_data/event_based/case_15/Hazard/Japan/ssm/ssm01.xml
Labels: enhancement

#8050 Disagg by src doc
  doc/adv-manual/classical_PSHA.rst
Labels: documentation

#8051 Adding part on epsilon *
  doc/manual/oq-manual.rst
Labels: documentation

#8052 Added command oq compare risk_by_event
  openquake/commands/compare.py
Labels: internal

#8053 first release of requirement for python3.10
  requirements-py310-linux64.txt
Labels: dependencies

#8045 Whats New for engine-3.15
  doc/whats-new.md
Labels: documentation

#8057 Change view 'totlosses'
  openquake/calculators/views.py
  openquake/qa_tests_data/scenario_risk/case_6a/expected/totlosses.txt
Labels: internal

#8056 Disabling DBHandler in "calc" mode
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logs.py
Labels: internal

#8060 Managed the case with CoVs = 0 for the beta distribution
  debian/changelog
  openquake/risklib/scientific.py
Labels: bug

#8061 Reduced precision in the header of the UHS csv files
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-max.csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_15/expected/hazard_uhs-std.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-000.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-001.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-002.csv
  openquake/qa_tests_data/classical/case_28/expected/hazard_uhs-rlz-003.csv
  openquake/qa_tests_data/classical/case_38/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
  openquake/qa_tests_data/classical/case_56/expected/uhs.csv
  openquake/qa_tests_data/classical/case_77/expected/uhs-mean.csv
Labels: outputs

#8063 Doing reinsurance calculations at the aggregate event loss table level
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/reinsurance_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/qa_tests_data/event_based_risk/case_1/job_re.ini
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/case_1/treaty.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8064 Implementing quota share
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8065 Supported absolute values for deductible and insurance_limit
  debian/changelog
  openquake/calculators/base.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/case_1/treaty.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
Labels: enhancement

#8066 Changed management of deductible/liability (absolute/relative)
  openquake/calculators/base.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/job2.ini
  openquake/qa_tests_data/event_based_risk/case_1/job_ins.ini
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/case_1/policy_ins.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8068 Removed reinsurance calculator
  openquake/calculators/reinsurance.py
  openquake/calculators/tests/reinsurance_test.py
  openquake/qa_tests_data/reinsurance/case_1/__init__.py
  openquake/qa_tests_data/reinsurance/case_1/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_1/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_1/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_1/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_1/job.ini
  openquake/qa_tests_data/reinsurance/case_1/policy.csv
  openquake/qa_tests_data/reinsurance/case_1/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_2/__init__.py
  openquake/qa_tests_data/reinsurance/case_2/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_2/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_2/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_2/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_2/job.ini
  openquake/qa_tests_data/reinsurance/case_2/policy.csv
  openquake/qa_tests_data/reinsurance/case_2/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_3/__init__.py
  openquake/qa_tests_data/reinsurance/case_3/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_3/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_3/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_3/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_3/job.ini
  openquake/qa_tests_data/reinsurance/case_3/policy.csv
  openquake/qa_tests_data/reinsurance/case_3/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_4/__init__.py
  openquake/qa_tests_data/reinsurance/case_4/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_4/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_4/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_4/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_4/job.ini
  openquake/qa_tests_data/reinsurance/case_4/policy.csv
  openquake/qa_tests_data/reinsurance/case_4/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_5/__init__.py
  openquake/qa_tests_data/reinsurance/case_5/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_5/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_5/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_5/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_5/job.ini
  openquake/qa_tests_data/reinsurance/case_5/policy.csv
  openquake/qa_tests_data/reinsurance/case_5/reinsurance.csv
Labels: internal

#8069 Implemented part of the new reinsurance logic
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/qa_tests_data/event_based_risk/case_1/job_re.ini
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/case_1/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/case_1/treaty.csv
  openquake/risklib/read_nrml.py
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/policies.csv
  openquake/risklib/tests/reinsurance.xml
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8070 Added max_cession_event
  openquake/qa_tests_data/event_based_risk/case_1/reinsurance.xml
  openquake/risklib/read_nrml.py
  openquake/risklib/reinsurance.py
Labels: enhancement

#8071 Implemented reinsurance_by_event and associated exporter
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/insurance_by_event.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/reinsurance.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance.xml
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, outputs

#8072 Implemented reinsurance_curves
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/reinsurance_curves.csv
  openquake/server/db/actions.py
Labels: enhancement, outputs

#8073 Implemented relative deductible and liability
  openquake/calculators/base.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/risklib/reinsurance.py
  openquake/server/db/actions.py
Labels: enhancement, inputs

#8075 Moved reinsurance tests
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/exposure.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/exposure1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/gmfs.hdf5
  openquake/qa_tests_data/event_based_risk/reinsurance/job.ini
  openquake/qa_tests_data/event_based_risk/reinsurance/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance_np.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance_prop.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/report.rst
  openquake/qa_tests_data/event_based_risk/reinsurance/vulnerability_model_nonstco.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/vulnerability_model_stco.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8076 Improved view `risk_by_event`
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/scientific.py
Labels: enhancement

#8077 Remove leftovers in contributors.py
  debian/changelog
  helpers/contributors.py
Labels: internal

#8079 Fixed off by one error in the association policy <-> agg_id
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/no_reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/no_reinsurance.xml
  openquake/risklib/reinsurance.py
Labels: bug

#8080 Made max_cession_event optional
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/risklib/reinsurance.py
Labels: enhancement

#8081 Changed management of nonproportional treaties
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance_np.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/policies.csv
  openquake/risklib/tests/reinsurance.xml
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, inputs

#8082 Removed all zero overspill columns
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_prop.csv
  openquake/risklib/reinsurance.py
Labels: enhancement, outputs

#8083 Fixed the logic of the reinsurance calculation
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8084 Supporting nonproportional reinsurance flags
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/job2.ini
  openquake/qa_tests_data/event_based_risk/reinsurance/policy2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance2.xml
  openquake/risklib/reinsurance.py
Labels: enhancement

#8085 Validate the proportional reinsurance fractions
  openquake/calculators/event_based_risk.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/policies.csv
  openquake/risklib/tests/reinsurance.xml
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8086 HDF5_USE_FILE_LOCKING=FALSE on windows
  debian/changelog
  openquake/baselib/hdf5.py
Labels: dependencies

#8087 Implementing CatXL
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_prop.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8088 Refactored reinsurance.by_event
  openquake/calculators/event_based_risk.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8089 Refactored management of policy indices
  openquake/calculators/base.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8078 Adding strike and dip methods for gridded surface
  debian/changelog
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/mutex/expected/ruptures.csv
Labels: enhancement

#8092 Storing reinsurance_by_policy
  openquake/calculators/event_based_risk.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8093 Added a test_max_cession
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8094 Changed the risk calculators to reuse the hazard exposure
  debian/changelog
  openquake/calculators/base.py
  openquake/engine/engine.py
Labels: enhancement

#8095 Refactored management of treaties
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8097 Add parameter max_aggregations
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/risklib/asset.py
Labels: enhancement

#8096 Added exporter aggrisk_reinsurance (first version)
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/aggrisk_reinsurance.csv
  openquake/risklib/tests/reinsurance_test.py
Labels: outputs

#8099 Added ProportionalTestCase
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8100 Implementing multiple levels of CatXL
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/aggrisk_reinsurance.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves2.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8102 Added clever algorithm for multi-level treaties
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8103 Vectorized clever_agg
  openquake/baselib/general.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement

#8105 Adding the `treaty_key` to the by_policy dataframe
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8106 Extended clever_agg to proportional treaties
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: internal

#8108 Integrated the general algorithm for multi-level treaties
  openquake/calculators/base.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/aggrisk_reinsurance.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/no_reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves_prop.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement
