Repository gem/oq-engine, pull requests merged in 2022-07, with the labels that each got.

#7948 Replaced policy_dict with policy_df
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/risklib/scientific.py
Labels: internal

#7949 Added treaty concept to the engine
  openquake/calculators/base.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/job_eb.ini
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/case_1/treaty.csv
Labels: enhancement

#7950 Partial implementation of reinsured losses
  openquake/calculators/base.py
  openquake/calculators/classical_risk.py
  openquake/calculators/reinsurance.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/reinsurance_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical_risk/case_5/job_r.ini
  openquake/qa_tests_data/reinsurance/case_1/__init__.py
  openquake/qa_tests_data/reinsurance/case_1/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_1/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_1/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_1/job.ini
  openquake/qa_tests_data/reinsurance/case_1/policy.csv
  openquake/qa_tests_data/reinsurance/case_1/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_2/__init__.py
  openquake/qa_tests_data/reinsurance/case_3/__init__.py
  openquake/qa_tests_data/reinsurance/case_4/__init__.py
  openquake/qa_tests_data/reinsurance/case_5/__init__.py
  openquake/qa_tests_data/scenario_risk/case_4/job.ini
  openquake/qa_tests_data/scenario_risk/case_6a/job_risk.ini
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
  openquake/server/tests/data/end-to-end-hazard-risk/job_risk_classical.ini
  openquake/server/tests/data/end-to-end-hazard-risk/job_risk_event_based.ini
  openquake/server/tests/data/event_based_risk/job.ini
Labels: enhancement

#7951 Added test cases for reinsurance 2-5
  openquake/calculators/tests/reinsurance_test.py
  openquake/qa_tests_data/reinsurance/case_2/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_2/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_2/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_2/job.ini
  openquake/qa_tests_data/reinsurance/case_2/policy.csv
  openquake/qa_tests_data/reinsurance/case_2/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_3/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_3/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_3/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_3/job.ini
  openquake/qa_tests_data/reinsurance/case_3/policy.csv
  openquake/qa_tests_data/reinsurance/case_3/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_4/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_4/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_4/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_4/job.ini
  openquake/qa_tests_data/reinsurance/case_4/policy.csv
  openquake/qa_tests_data/reinsurance/case_4/reinsurance.csv
  openquake/qa_tests_data/reinsurance/case_5/avg_losses.csv
  openquake/qa_tests_data/reinsurance/case_5/exposure_model.csv
  openquake/qa_tests_data/reinsurance/case_5/exposure_model.xml
  openquake/qa_tests_data/reinsurance/case_5/job.ini
  openquake/qa_tests_data/reinsurance/case_5/policy.csv
  openquake/qa_tests_data/reinsurance/case_5/reinsurance.csv
Labels: internal

#7952 Added the expected files for the reinsurance tests
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/tests/reinsurance_test.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/event_based_risk/case_1/job_eb.ini
  openquake/qa_tests_data/event_based_risk/case_1/treaty.csv
  openquake/qa_tests_data/reinsurance/case_1/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_1/job.ini
  openquake/qa_tests_data/reinsurance/case_2/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_2/job.ini
  openquake/qa_tests_data/reinsurance/case_3/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_3/job.ini
  openquake/qa_tests_data/reinsurance/case_4/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_4/job.ini
  openquake/qa_tests_data/reinsurance/case_5/expected/reinsurance_losses.csv
  openquake/qa_tests_data/reinsurance/case_5/job.ini
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
Labels: enhancement

#7953 Added missing CSV files to the manual
  doc/manual/input_exposure_wa.csv
  doc/manual/input_scenario_gmfs.csv
  doc/manual/input_scenario_sites.csv
  doc/manual/oq-manual.rst
  doc/manual/output_scenario_gmfs.csv
  doc/manual/output_scenario_sites.csv
Labels: documentation

#7954 Added dynamic version to the manual
  doc/manual/conf.py
  doc/manual/oq-manual.rst
Labels: documentation

#7899 Bahrampouri Arias Intensity GMPE
  openquake/hazardlib/gsim/bahrampouri_2021.py
  openquake/hazardlib/tests/gsim/bahrampouri_2021_ai_test.py
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_ASC_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_ASC_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_ASC_mean.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SInter_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SInter_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SInter_mean.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SSlab_INTRA.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SSlab_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/BMG20/BMG20_AI_SSlab_mean.csv
Labels: enhancement

#7955 Cleanup for reinsurance losses
  openquake/risklib/reinsurance.py
  openquake/risklib/riskmodels.py
Labels: enhancement

#7959 Changed case_57 to use the Kotha GMPEs
  openquake/qa_tests_data/classical/case_57/expected/hcurve_PGA.csv
  openquake/qa_tests_data/classical/case_57/expected/hcurve_SA.csv
  openquake/qa_tests_data/classical/case_57/gmcLT.xml
Labels: documentation

#7964 Fixed source_info.num_ruptures
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: internal

#7965 Fixed rup_id split-dependence
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
Labels: bug

#7966 Fixed NegativeBinomialTOM with ps_grid_spacing
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/non_parametric.py
  openquake/qa_tests_data/classical/case_78/expected/hazard_curve-mean-PGA_NegBinomTest.csv
  openquake/qa_tests_data/classical/case_78/job.ini
  openquake/qa_tests_data/classical/case_78/source_negbinom.xml
Labels: bug

#7969 Changed the avg_losses storage to make it easier to manage secondary loss types
  debian/changelog
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/views.py
  openquake/hazardlib/stats.py
  openquake/risklib/riskmodels.py
Labels: internal

#7971 Changed the storage of the src_loss_table
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_nonstructural.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_structural.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_table.csv
  openquake/risklib/riskmodels.py
Labels: outputs

#7970 Temporarily removing insured losses
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
Labels: internal

#7975 Removed unused exporter
  openquake/calculators/export/risk.py
  openquake/server/db/actions.py
Labels: internal

#7976 Changed the storage of agg_curves-stats
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
Labels: internal, outputs

#7977 Restoring insured losses
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_damage/case_12/expected/a_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/d_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk_sampling.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_6c/expected/aggcurves_eb.csv
  openquake/qa_tests_data/event_based_risk/case_7a/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-OCCUPANCY.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
  openquake/qa_tests_data/event_based_risk/occupants/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/scenario_risk/case_8/expected/agglosses.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: outputs

#7979 Changed the algorithm for the magnitude bins
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-1.csv
Labels: bug

#7980 Optimized event_based_risk
  openquake/calculators/event_based_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: performance

#7981 Moved some constants from riskmodels->scientific
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#7982 Implementing total losses
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
  openquake/risklib/scientific.py
Labels: enhancement, outputs

#7984 Extended total losses to avg_losses
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
Labels: enhancement, outputs

#7983 fixing the precision problem in setting up the mag bins
  openquake/hazardlib/calc/disagg.py
Labels: bug

#7985 Added test for total_losses + taxonomy mapping
  openquake/qa_tests_data/event_based_risk/case_5/contents_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_5/job_eb.ini
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map_contents.csv
  openquake/risklib/scientific.py
Labels: outputs

#7987 Extended case_5 to a nontrivial taxonomy mapping
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/structural_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map_structural.csv
Labels: internal

#7986 Refactoring AvgRiskModel
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#7988 Update installation notes for M1 CPU
  doc/installing/universal.md
Labels: documentation

#7990 Changed AvgRiskModel->LossComputer
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_5/job.ini
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#7991 From LossComputer to RiskComputer
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#7992 Refactored the risk functions
  openquake/calculators/tests/scenario_damage_test.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#7993 Fixed HDF5 BlockingIOError in the China model
  openquake/calculators/base.py
  openquake/commonlib/source_reader.py
Labels: bug

#7994 Extended insurances losses to totals
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/job2.ini
  openquake/qa_tests_data/event_based_risk/case_1/job_ins.ini
  openquake/risklib/scientific.py
Labels: enhancement

#7996 Disabling the DbServer on demand
  debian/changelog
  openquake/baselib/__init__.py
  openquake/commands/__main__.py
  openquake/commands/dbserver.py
  openquake/commands/run.py
Labels: enhancement

#7997 Add mag dist trt
  CONTRIBUTORS.txt
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-1.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_TRT_Eps-0.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist_TRT-1.csv
Labels: enhancement

#7998 Removed the tempname hack
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/source_reader.py
Labels: internal

#7999 Added test of disagg_by_src with sampling
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_45/expected/hazard_curve-mean-MMI.csv
  openquake/qa_tests_data/classical/case_45/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_45/job.ini
  openquake/qa_tests_data/classical/case_45/source_model_logic_tree.xml
Labels: internal

#8000 Implemented disagg_by_src for mutex sources
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/tests/nrml_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source_model/source_group_collection.xml
  openquake/qa_tests_data/classical/case_27/expected/hazard_curve.csv
  openquake/qa_tests_data/classical/case_27/job.ini
  openquake/qa_tests_data/classical/case_27/source_model.xml
  openquake/qa_tests_data/disagg/case_5/slab_buc0/6.05.nrml
  openquake/qa_tests_data/disagg/case_5/slab_buc1/6.75.nrml
  openquake/qa_tests_data/disagg/case_6/ssm/shallow/shallow_faults.xml
  openquake/qa_tests_data/disagg/case_7/int_col0_40km.xml
  openquake/qa_tests_data/disagg/case_7/int_col_50km.xml
  openquake/qa_tests_data/disagg/case_9/ssm/source_model.xml
Labels: internal

#8001 Added a sanity check on source fragments
  openquake/commonlib/source_reader.py
Labels: enhancement

#8002 Added some restrictions on risk IDs
  debian/changelog
  openquake/hazardlib/valid.py
  openquake/risklib/read_nrml.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: inputs

#8003 Refactored the risk_functions dictionary
  openquake/calculators/export/risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#8004 Improved RiskComputer serialization
  openquake/baselib/tests/hdf5_test.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal
