Repository gem/oq-engine, pull requests merged in 2022-11, with the labels that each got.

#8201 Fixed `oqparam.mags_by_trt` when the --hc option is used
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
Labels: bug

#8203 Fighting memory leaks with `maxtasksperchild`
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/calculators/classical.py
  openquake/calculators/tests/__init__.py
Labels: performance

#8158 Adding the possibility to define the edges of bins used in the disaggregation
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/disagg/README.md
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_8/job_a.ini
Labels: enhancement

#8206 Added `spawn` distribution mechanism
  debian/changelog
  openquake/baselib/parallel.py
  openquake/commonlib/source_reader.py
Labels: internal

#8207 Spawn
  openquake/baselib/parallel.py
Labels: performance

#8208 Fixed OQ_REDUCE
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim_lt.py
Labels: bug, performance, internal

#8181 Check the order of treaties in xml and csv input files...
  demos/risk/Reinsurance/policy.csv
  doc/adv-manual/event_based.rst
  openquake/commonlib/tests/reinsurance_test.py
  openquake/risklib/reinsurance.py
Labels: inputs

#8210 Do not use scientific notation inside example reinsurance outputs in the advanced manual
  doc/adv-manual/event_based.rst
Labels: documentation

#8213 Reduced memory consumption when using the ps_grid_spacing approximation
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
Labels: performance

#8214 Fixed min_mag, max_mag filtering
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_13/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_13/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_13/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_13/job.ini
Labels: bug

#8216 Forced the usage of collect_rlzs with large exposures
  debian/changelog
  openquake/calculators/event_based_risk.py
Labels: inputs

#8215 Reduced the bounding box of point sources
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/aftershock/case_1/expected/hcurves.csv
  openquake/qa_tests_data/classical/case_67/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_77/expected/uhs-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.15.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.85.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-sid-1-mean.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b1.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b2.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-mean.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-0.csv
Labels: performance

#8219 Optimized the collapsing of PointSources
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_map-mean-PGA.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-0.csv
Labels: performance

#8218 Passed the zworkers dictionary to the DbServer
  openquake/baselib/parallel.py
  openquake/baselib/tests/workerpool_test.py
  openquake/baselib/workerpool.py
  openquake/engine/engine.py
  openquake/server/dbserver.py
Labels: bug

#8217 Change requirements to use same path for pure python
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos_x86_64.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#8220 Sending one multiFaultSource per task
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/contexts.py
Labels: performance

#8222 Fixed a doctest broken in python 3.8
  openquake/baselib/sap.py
Labels: documentation

#8221 Fixed the exporter of `avg_losses-stats`
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/commonlib/util.py
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/job_haz.ini
  openquake/qa_tests_data/gmf_ebrisk/case_4/job_risk.ini
Labels: bug

#8223 Fixing typo
  openquake/commonlib/oqvalidation.py
Labels: bug

#8224 Fixed `oq show worst_sources`
  openquake/hazardlib/contexts.py
Labels: internal

#8225 Disaggregation test
  openquake/qa_tests_data/disagg/case_8/job_a.ini
Labels: bug, outputs

#8227 Add clarifications to the doc page for collect_rlzs
  doc/adv-manual/event_based.rst
Labels: documentation

#8228 Unskipped the breaking reinsurance_test
  openquake/commonlib/tests/reinsurance_test.py
Labels: bug

#8229 Put together the evil global risk parameters
  openquake/calculators/base.py
  openquake/calculators/reportwriter.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/datastore_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/commonlib/tests/reinsurance_test.py
Labels: internal

#8230 Update docstring for the GmfComputer class
  openquake/hazardlib/calc/gmf.py
Labels: documentation

#8211 WIP - Change web path
  debian/changelog
  doc/installing/server.md
  docker/README.md
  openquake/server/local_settings.py.pam
  openquake/server/settings.py
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/base.html
  openquake/server/templates/engine/get_outputs.html
  openquake/server/urls.py
  openquake/server/utils.py
Labels: enhancement

#8233 update 'settings.py' to fix wrong config variable interpolation
  openquake/server/settings.py
Labels: bug

#8234 Refactored ModifiableGMPE
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
Labels: internal

#8232 First example of postprocessing script
  openquake/baselib/general.py
  openquake/engine/postproc/rupture_histogram.py
  openquake/engine/postproc/tests.py
Labels: proposal, documentation

#8236 Moved the zstreamer in `oq workers start`
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/server/dbserver.py
Labels: internal

#8237 Refactored ModifiableGMPE/2
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: internal

#8240 Removing the memory leak in the global hazard model/2
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: bug

#8107 Add a to_nrml command to convert gpkg to xml
  openquake/baselib/node.py
  openquake/baselib/tests/node_test.py
  openquake/commands/nrml_from.py
  openquake/commands/tests/commands_test.py
  openquake/commands/tests/data/expected_converted_nrml.xml
  openquake/hazardlib/geo/packager.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/expected_sources.toml
  openquake/hazardlib/valid.py
Labels: enhancement

#8244 Added parameter `pmap_max_gb`
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
Labels: performance, inputs

#8245 Do not use ray pool
  openquake/baselib/parallel.py
Labels: internal

#8247 Added an experimental calculator splitting by GSIM
  openquake/calculators/classical.py
  openquake/engine/postproc/classical_by_gsim.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#8250 MAJOR: added `save_memory` flag for classical calculations
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
Labels: performance

#8251 Fixed task_input_url
  openquake/baselib/parallel.py
Labels: bug

#8253 Improved task distribution when using keep_source_groups=true
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/postproc/classical_by_gsim.py
  openquake/hazardlib/site.py
Labels: performance

#8255 Introduced parallel tiling
  openquake/calculators/classical.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_25/job.ini
Labels: performance

#8246 Fixed ModifiableGMPE when GMPETables are involved
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: internal

#8252 Generalizing weichert
  openquake/hmtk/seismicity/occurrence/utils.py
  openquake/hmtk/seismicity/occurrence/weichert.py
  openquake/hmtk/tests/seismicity/occurrence/utils_test.py
Labels: enhancement

#8259 Add missing change
  openquake/hmtk/seismicity/occurrence/weichert.py
Labels: bug

#8257 Mean Rate Distribution calculator
  .gitignore
  debian/changelog
  openquake/engine/postproc/compute_mrd.py
  openquake/engine/postproc/data/calc_001.hdf5
  openquake/engine/postproc/data/mrd.toml
  openquake/engine/postproc/postproc_test.py
  openquake/hazardlib/calc/mrd.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/data/mrd/calc_934.hdf5
  openquake/hazardlib/tests/calc/mrd_test.py
Labels: enhancement

#8263 Speeding up the reading of the source models
  openquake/baselib/node.py
Labels: performance

#8262 Moved horiz_comp_to_geom_mean to the job.ini
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/mrd.py
  openquake/hazardlib/const.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/qa_tests_data/classical/case_77/gmmLT_tab.xml
  openquake/qa_tests_data/classical/case_77/job.ini
  openquake/qa_tests_data/classical/case_79/gmmLT.xml
  openquake/qa_tests_data/classical/case_79/job.ini
  openquake/qa_tests_data/disagg/case_10/gmmLT.xml
  openquake/qa_tests_data/disagg/case_10/job.ini
  openquake/qa_tests_data/disagg/case_12/gmmLT.xml
  openquake/qa_tests_data/disagg/case_12/job.ini
Labels: inputs

#8248 Obtain a xml with the original namespaces after converting nrml -> gpkg -> nrml
  openquake/baselib/node.py
  openquake/commands/tests/data/expected_converted_nrml.xml
  openquake/hazardlib/geo/packager.py
  openquake/hazardlib/nrml_to.py
Labels: enhancement, inputs

#8265 Sending the heavy tasks first
  openquake/calculators/classical.py
  openquake/calculators/views.py
Labels: performance

#8266 Made preclassical faster in presence of big sources
  openquake/calculators/preclassical.py
Labels: performance

#8267 Fixed avg_losses-rlzs output
  debian/changelog
  openquake/calculators/classical_risk.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/qa_tests_data/classical_risk/case_5/expected/avg_losses-000.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/avg_losses-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/loss_curves_avg.txt
Labels: bug

#8268 Fixed the weight of non-point sources
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: performance

#8269 Removed parameter max_sites_per_tile
  doc/adv-manual/classical_PSHA.rst
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_14/job.ini
  openquake/qa_tests_data/classical/case_22/job.ini
Labels: internal

#8272 Fixed New Madrid cluster calculation
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_80/expected/hazard_curve-mean-PGA.csv
Labels: bug

#8273 Fixed issue with investigation_time with scenario_risk reinsurance
  openquake/calculators/post_risk.py
Labels: bug

#8274 Store the CompositeSourceModel by source group
  openquake/calculators/classical.py
  openquake/commonlib/source_reader.py
Labels: performance, internal
