Repository gem/oq-engine, pull requests merged in 2022-10, with the labels that each got.

#8110 Storing the policy_grp
  openquake/calculators/base.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, internal

#8111 Restored overspill functionality
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, internal

#8113 Fixed overspill exporter
  openquake/calculators/export/risk.py
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance/reinsurance2.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, outputs

#8114 Moved reinsurance fully into the PostRiskCalculator
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/reaggregate.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/aggrisk_reinsurance.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/no_reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/exposure.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/exposure1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/gmfs.hdf5
  openquake/qa_tests_data/event_based_risk/reinsurance_1/job.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_1/job2.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_1/no_reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/policy2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance2.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance_np.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance_prop.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/report.rst
  openquake/qa_tests_data/event_based_risk/reinsurance_1/vulnerability_model_nonstco.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/vulnerability_model_stco.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance_2/contents_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/job.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_2/nonstructural_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/reinsurance2.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/source_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/structural_vulnerability_model.xml
Labels: enhancement

#8115 Fixed to the reinsurance outputs
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/aggrisk_reinsurance.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/no_reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance_curves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/gsim_logic_tree.xml
Labels: outputs

#8116 Added columns for CatXL overspill
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_avg2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance_curves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance_avg.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance_curves.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: outputs

#8117 Fixed gmf limits
  openquake/baselib/parallel.py
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#8104 Add reinsurance documentation
  doc/adv-manual/event_based.rst
Labels: documentation

#8118 Renamed max_retention->deductible
  openquake/qa_tests_data/event_based_risk/case_1/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance2.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_1/reinsurance_np.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_2/reinsurance2.xml
  openquake/risklib/read_nrml.py
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: inputs

#8120 Rename reinsurance outputs
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/no_reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggrisk.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_losses.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_losses2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-avg_losses.csv
  openquake/server/db/actions.py
Labels: outputs

#8121 Raised the recursion limit
  debian/changelog
  openquake/baselib/parallel.py
Labels: enhancement

#8123 Add reinsurance demo
  demos/risk/Reinsurance/README.md
  demos/risk/Reinsurance/exposure_model.csv
  demos/risk/Reinsurance/exposure_model.xml
  demos/risk/Reinsurance/gmpe_logic_tree.xml
  demos/risk/Reinsurance/job.ini
  demos/risk/Reinsurance/nonstructural_vulnerability_model.xml
  demos/risk/Reinsurance/policy.csv
  demos/risk/Reinsurance/reinsurance.xml
  demos/risk/Reinsurance/site_model.csv
  demos/risk/Reinsurance/source_model.xml
  demos/risk/Reinsurance/source_model_logic_tree.xml
  demos/risk/Reinsurance/structural_vulnerability_model.xml
Labels: documentation

#8125 Fixes to the reinsurance docs
  doc/adv-manual/event_based.rst
  doc/adv-manual/index.rst
Labels: documentation

#8133 Increased the recursion limit again
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/preclassical.py
Labels: bug

#8132 Reduced slow tasks in event_based_risk
  debian/changelog
  openquake/baselib/performance.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/calc.py
Labels: performance

#8134 Storing gmf_data/slices for use in event_based_risk
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/qa_tests_data/event_based_risk/case_8/gmf-data.hdf5
  openquake/qa_tests_data/event_based_risk/reinsurance_1/gmfs.hdf5
Labels: performance

#8137 Parallelized build_gmfslices
  debian/changelog
  openquake/calculators/__init__.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/calc.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
Labels: performance

#8139 Do not install manually fiona in the engine workflow
  .github/workflows/engine_test.yml
Labels: dependencies, internal

#8141 Fixing scenario_damage case_12
  openquake/commonlib/calc.py
Labels: bug

#8058 Fixing the calculation of cs
  debian/changelog
  openquake/calculators/conditional_spectrum.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/expected/spectra2.csv
  openquake/hazardlib/tests/calc/expected/spectra6.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/conditional-spectrum-1.csv
Labels: bug

#8142 Warned when splitting in policy groups
  openquake/risklib/reinsurance.py
Labels: internal

#8144 Fixed wrong event_id in reinsurance_by_policy
  openquake/calculators/post_risk.py
  openquake/risklib/reinsurance.py
Labels: bug

#8149 Refactored conditional spectrum/3
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/cond_spectra.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_1/expected/cond-spectrum-1.csv
Labels: internal

#8151 Docs openquake org refact
  .github/workflows/demos.yml
  .github/workflows/docs.yml
Labels: documentation

#8152 Reducing memory consumption in classical calculations
  debian/changelog
  openquake/baselib/performance.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/geo/surface/multi_cache_test.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: performance

#8153 Fixed export bug caused by policy IDs magically promoted from ints to floats
  openquake/risklib/reinsurance.py
Labels: bug

#8154 Make sure the fullreport works for NGAEast GMPEs
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
Labels: bug, backport

#8155 Mitigated the slow tasks in event_based_risk
  openquake/calculators/event_based_risk.py
  openquake/commonlib/calc.py
Labels: performance

#8157 Saving memory in event_based_risk
  openquake/calculators/event_based_risk.py
Labels: performance

#8159 Fast and simple event_based_risk
  openquake/baselib/performance.py
  openquake/baselib/zeromq.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/calc.py
  openquake/commonlib/logs.py
Labels: performance

#8160 Removed warning flooding stderr
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: outputs

#8162 Removed relative deductibles/limits in reinsurance calculation
  openquake/qa_tests_data/event_based_risk/case_1/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/no_reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-aggcurves_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_portfolio.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_portfolio2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event_np.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-risk_by_event_prop.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/policy2.csv
  openquake/risklib/reinsurance.py
Labels: internal

#8163 Added parameter `max_gmvs per task`
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_5/job.ini
Labels: internal

#8164 Ignoring non-catXL treaties when building portfolio groups
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance_3/contents_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/job.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_3/nonstructural_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/reinsurance1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/source_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_3/structural_vulnerability_model.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: enhancement, internal

#7766 Minor modifications to GSIM YoudEtAl2002 and Adding new GSIM Zhang and Zhao. (2005)
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/youd_etal_2002.py
  openquake/hazardlib/gsim/zhang_zhao_2005.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/data/YOUD04/Youd2004_MEAN.csv
  openquake/hazardlib/tests/gsim/data/YOUD04/Youd2004_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005Crust_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005Crust_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005SInter_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ZHANG05/Zhang2005SSlab_STDDEV.csv
  openquake/hazardlib/tests/gsim/zhang_zhao_2005_test.py
Labels: enhancement

#8167 Added conditional spectrum calculator in hazardlib
  debian/changelog
  openquake/hazardlib/calc/cond_spectra.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
Labels: enhancement

#8166 Removed support for Python < 3.8
  debian/changelog
  install.py
  openquake/baselib/python3compat.py
  openquake/commands/__main__.py
  openquake/hazardlib/sourceconverter.py
Labels: dependencies

#8135 Wong2022
  debian/changelog
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/wong2022.py
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_MEAN_PGA.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_MEAN_SA02.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_MEAN_SA1.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_SIGMA_PGA.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_SIGMA_SA02.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGDeep2022_SIGMA_SA1.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGShallow2022_MEAN.csv
  openquake/hazardlib/tests/gsim/data/Wong2022/WONGShallow2022_SIGMA.csv
  openquake/hazardlib/tests/gsim/wong_2022_test.py
Labels: enhancement

#8127 minor fixes in functions implementing Stepp (1972) completeness analysis
  openquake/hmtk/plotting/seismicity/completeness/plot_stepp_1972.py
  openquake/hmtk/seismicity/completeness/comp_stepp_1971.py
Labels: bug

#8170 Reduced the number of warnings when the horizontal component is not convertible
  debian/changelog
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
Labels: enhancement, internal

#8171 Extended the AbrahamsonEtAl2014 GMPE to extrapolate the vs30
  debian/changelog
  openquake/hazardlib/gsim/abrahamson_2014.py
Labels: enhancement

#8161 Add tests checking reinsurance input files
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_3/policy.csv
  openquake/risklib/reinsurance.py
  openquake/risklib/tests/reinsurance_test.py
Labels: inputs

#8175 Fixed AtkinsonBoore2006 with stress drop adjustment
  debian/changelog
  openquake/hazardlib/gsim/atkinson_boore_2006.py
Labels: bug

#8176 Worked aroun the memory leak in the tiling calculator
  debian/changelog
  openquake/calculators/classical.py
Labels: bug

#8178 Split `ContextMaker.get_pmap` in two methods
  openquake/hazardlib/contexts.py
Labels: internal

#8180 In shakemap2gmfs the truncation_level must be a float, not an int
  openquake/commands/shakemap2gmfs.py
Labels: bug

#8183 Added some support for SharedMemory in the Starmap
  openquake/baselib/parallel.py
  openquake/baselib/tests/parallel_test.py
  openquake/commonlib/logs.py
Labels: internal

#8101 add fiona wheel on requirements files but not for arm64 macos
  .github/workflows/macos_intel_install.yml
  .github/workflows/macos_m1_install.yml
  .github/workflows/rocky_install.yml
  .github/workflows/ubuntu_install.yml
  .github/workflows/windows_install.yml
  openquake/hazardlib/tests/geo/mesh_test.py
  openquake/sep/utils.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py37-linux64.txt
  requirements-py37-macos_x86_64.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#8186 Fixes for the new libraries?
  .github/workflows/engine_test.yml
  doc/adv-manual/event_based.rst
  doc/adv-manual/general.rst
  openquake/baselib/sap.py
  openquake/calculators/export/hazard.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/geo/mesh_test.py
Labels: internal

#8184 Added an array-based Pmap concept
  .github/workflows/engine_test.yml
  doc/tutorials/the-datastore/ex5.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/lt_test.py
  openquake/hazardlib/tests/probability_map_test.py
  openquake/qa_tests_data/classical/README.md
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
Labels: performance

#8187 Using install.py in the hazardlib tests
  openquake/hmtk/tests/comparison/rate_grid_test.py
  openquake/hmtk/tests/seismicity/smoothing/test_smoothed_seismicity.py
Labels: internal

#8188 Added methods to ProbabilityMap
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/probability_map.py
Labels: internal

#8189 Added test for the New Madrid cluster
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_80/__init__.py
  openquake/qa_tests_data/classical/case_80/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_80/gmmLT.xml
  openquake/qa_tests_data/classical/case_80/job.ini
  openquake/qa_tests_data/classical/case_80/ssm/NMFZfaults/newmad2014_500_cluster.xml
  openquake/qa_tests_data/classical/case_80/ssmLT.xml
Labels: internal

#8190 Some minor refactoring
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: internal

#8191 More refactoring of the ProbabilityMaps
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: internal

#8192 Returning probabilities of no exceedence
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/probability_map.py
Labels: performance

#8193 Fixed ProbabilityMap.update with tiling and using numba
  openquake/calculators/classical.py
  openquake/hazardlib/probability_map.py
Labels: performance

#8194 Avoiding building intermediate pmaps
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: performance

#8195 add python 3.10 support on github action for M1
  .github/workflows/macos_intel_install.yml
  .github/workflows/macos_m1_install.yml
  requirements-py310-macos_arm64.txt
Labels: dependencies

#8197 Add a command `oq purge failed`
  debian/changelog
  openquake/commands/purge.py
Labels: enhancement

#8199 Sending the sitecol around
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
Labels: internal

#8200 Saving a bit of memory in classical calculations
  openquake/calculators/classical.py
Labels: performance
