Repository gem/oq-engine, pull requests merged in 2022-04, with the labels that each got.

#7695 add missing .service for After section on systemd
  install.py
Labels: bug

#7696 Removed split_task in classical calculations
  openquake/calculators/classical.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7698 Fixed equivalent distance approximation
  debian/changelog
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
Labels: performance

#7700 Disabled save_disk_space by default
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
Labels: outputs

#7704 Removed wrong logging calls in hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: internal, backport

#7703 Removed save_disk_space
  debian/changelog
  doc/performance/SAM.org
  openquake/calculators/base.py
  openquake/commands/run.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
Labels: outputs

#7705 Optimized "computing pnes"
  openquake/hazardlib/tom.py
Labels: performance

#7706 Optimized "computing pnes"/3
  openquake/hazardlib/tom.py
Labels: performance

#7707 Restored composing_pnes
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tom.py
Labels: performance

#7708 Changed the definition of aggrisk: dividing by investigation_time
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk_sampling.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-site_id.csv
Labels: outputs

#7709 Optimized "composing pnes"/4
  openquake/hazardlib/contexts.py
Labels: performance

#7710 Removed the old UCERF calculator
  openquake/calculators/event_based.py
  openquake/calculators/tests/ucerf_test.py
  openquake/calculators/ucerf_base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/source_reader.py
Labels: internal

#7711 What's new for engine 3.14
  doc/whats-new.md
  openquake/hazardlib/geo/mesh.py
Labels: documentation

#7712 Refactored DictArray
  openquake/baselib/general.py
  openquake/calculators/classical.py
  openquake/hazardlib/gsim/base.py
Labels: performance, internal

#7715 Remove truncation_level = None
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/cross_correlation.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/stats.py
  openquake/hazardlib/tests/calc/hazard_curve_cluster_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/results/results_msf_nan_rx.npz
  openquake/hazardlib/tests/geo/surface/results/results_msf_nan_ry0.npz
  openquake/hazardlib/tests/geo/surface/results/results_nzl_1_rx.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh_back.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh_lons.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_ref_idx.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rprof_0.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rprof_2.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rx.txt
  openquake/hazardlib/tests/geo/surface/results/results_t01.npz
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowCrust.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowFault.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowOffshore.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_StableShallowCrust.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionInterface.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionIntraSlab30.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionIntraSlab50.csv
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/hazardlib/tests/gsim/nshmp_2014_test.py
  openquake/hazardlib/tests/gsim/projects/acme_2019_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/yenier_atkinson_2015_test.py
  openquake/qa_tests_data/classical/case_47/job.ini
  openquake/qa_tests_data/classical/case_53/job.ini
  openquake/qa_tests_data/classical/case_54/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_1/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_2/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/agglosses.csv
Labels: inputs

#7717 Converted _truncnorm_sf into a numba function
  openquake/hazardlib/stats.py
Labels: performance

#7720 Reducing the memory stress on the CPU
  debian/changelog
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/stats.py
  openquake/hazardlib/tom.py
Labels: performance

#7721 Reducing the memory stress on the CPU/2
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: performance

#7722 Fixed a wrong formula in `modifiable_gmpe.add_between_within_stds`
  debian/changelog
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/qa_tests_data/event_based/case_28/expected/gmf-data.csv
Labels: bug, backport

#7718 add refactored CONTRIBUTORS with github account
  CONTRIBUTORS.txt
  helpers/contributors.py
Labels: internal

#7723 Optimized "composing pnes"/5
  openquake/hazardlib/contexts.py
Labels: performance

#7724 Avoided double counting with `ps_grid_spacing`
  openquake/calculators/preclassical.py
Labels: bug, backport

#7725 Reducing the memory stress on the CPU/3
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
Labels: performance

#7727 Improved the error message when using an out-of-the-range maximum_distance
  debian/changelog
  doc/faq-hazard.md
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/commands/engine.py
Labels: enhancement

#7730 Added debugging parameter source_nodes
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_1/job.ini
Labels: internal

#7731 Supporting h5py >=3.4
  openquake/calculators/base.py
Labels: dependencies

#7729 Changed the magnitude-dependent `maximum_distance` feature to discard ruptures below `minmag` and above `maxmax`
  debian/changelog
  openquake/calculators/base.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/classical/case_13/expected/extreme_sites.rst
  openquake/qa_tests_data/classical/case_13/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_13/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_13/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_13/job.ini
Labels: enhancement

#7734 Setting `ps_grid_spacing` now sets the `pointsource_distance` too
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/expected/hazard_map-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/job.ini
Labels: performance

#7735 Optimized "composing pnes"/6
  debian/changelog
  openquake/hazardlib/contexts.py
Labels: performance

#7736 Implemented CScalingMSR
  debian/changelog
  openquake/hazardlib/lt.py
  openquake/hazardlib/scalerel/base.py
  openquake/hazardlib/scalerel/cscaling.py
  openquake/hazardlib/source/multi_point.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/scalerel/asr_test.py
  openquake/hazardlib/tests/scalerel/msr_test.py
  openquake/hazardlib/valid.py
  openquake/hmtk/parsers/source_model/nrml04_parser.py
  openquake/qa_tests_data/classical/case_1/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_1/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_1/source_model.xml
Labels: enhancement

#7737 Not storing far away ruptures
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/stochastic.py
Labels: bug

#7740 Fixed NaNs in disaggregation
  debian/changelog
  openquake/hazardlib/contexts.py
Labels: bug, backport

#7742 Better vectorization of get_poes
  openquake/hazardlib/gsim/base.py
Labels: performance

#7743 Fixed bug for empty probs_occur
  openquake/hazardlib/contexts.py
Labels: bug, internal, backport

#7739 Adding the possibility of disaggregating hazard using epsilon star
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_8/__init__.py
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_8/gmcLt.xml
  openquake/qa_tests_data/disagg/case_8/job.ini
  openquake/qa_tests_data/disagg/case_8/sscLt.xml
  openquake/qa_tests_data/disagg/case_8/ssm/source_model.xml
Labels: enhancement

#7741 Adds a method to compute the cross correlation matrix in the CrossCorrelation abstract class
  debian/changelog
  openquake/hazardlib/cross_correlation.py
  openquake/hazardlib/tests/cross_correlation_test.py
Labels: enhancement

#7746 make_contexts/1
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/expected/hazard_map-mean-PGA.csv
Labels: performance

#7748 make_contexts/2
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
Labels: performance

#7751 Huge speedup of the classical calculator for few sites
  openquake/hazardlib/contexts.py
Labels: performance

#7750 make_contexts/3
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/source/area_test.py
Labels: performance

#7754 make_contexts/6
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: performance

#7755 make_contexts/7
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/acceptance/disagg_test.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
  openquake/hazardlib/tests/source/point_test.py
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/damages.csv
Labels: performance

#7762 Fixed error in sample_ruptures_poissonian
  openquake/hazardlib/source/base.py
Labels: bug

#7763 Removed useless term from PlanarSurface._project
  openquake/hazardlib/geo/surface/planar.py
Labels: performance

#7749 numba-0.55.1-1 for linux requirements files
  openquake/hazardlib/stats.py
  requirements-py37-linux64.txt
  requirements-py38-linux64.txt
  requirements-py39-linux64.txt
Labels: dependencies

#7768 Fixed a logging statement that could run out of memory in large calculations
  debian/changelog
  openquake/calculators/classical.py
Labels: internal

#7767 Changed split_sources
  doc/adv-manual/developing.rst
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/qa_tests_data/disagg/case_1/expected_output/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag_Dist-0.csv
Labels: internal

#7770 Fixed the counting of the logic tree paths
  openquake/commonlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/tests/lt_test.py
Labels: bug

#7771 Workaround for `count_paths` slowness
  openquake/commonlib/logictree.py
  openquake/hazardlib/lt.py
Labels: bug, performance
