Repository gem/oq-engine, pull requests merged in 2022-05, with the labels that each got.

#7775 Made test_shapefile skippable
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
  setup.py
Labels: dependencies

#7774 make_contexts/10
  doc/performance/ALS.org
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/characteristic.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/kite_fault.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source/multi_point.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/tests/contexts_test.py
  utils/csm2rup
Labels: performance

#7776 make_contexts/11
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
Labels: performance

#7777 Back to using unique branch ID abbreviations
  openquake/baselib/general.py
  openquake/calculators/extract.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/tests/lt_test.py
Labels: internal

#7778 Added a check for inconsistent IDs between fragility and consequence functions
  debian/changelog
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_14/__init__.py
  openquake/qa_tests_data/scenario_damage/case_14/consequence_model.xml
  openquake/qa_tests_data/scenario_damage/case_14/earthquake_rupture_model_21_2.xml
  openquake/qa_tests_data/scenario_damage/case_14/exp.csv
  openquake/qa_tests_data/scenario_damage/case_14/exposure_model.xml
  openquake/qa_tests_data/scenario_damage/case_14/exposure_model.zip
  openquake/qa_tests_data/scenario_damage/case_14/fragility_model.xml
  openquake/qa_tests_data/scenario_damage/case_14/gmpe.xml
  openquake/qa_tests_data/scenario_damage/case_14/job.ini
  openquake/risklib/riskmodels.py
Labels: internal

#7780 Fixed source_info.trti
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/source_reader.py
Labels: internal

#7782 make_contexts/12: simplified the distance cache
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_cache_test.py
Labels: internal

#7781 Fixed the test scenario case_14
  openquake/calculators/tests/scenario_damage_test.py
  openquake/hazardlib/contexts.py
  openquake/risklib/riskmodels.py
Labels: bug, internal

#7738 Fixed disaggregation with --hc
  openquake/calculators/disaggregation.py
Labels: bug, backport

#7786 make_ctxs/12
  openquake/hazardlib/contexts.py
Labels: internal

#7789 Some fixes to the logic tree
  doc/adv-manual/logic-trees.rst
  openquake/baselib/general.py
  openquake/calculators/disaggregation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/lt.py
Labels: bug

#7787 Simple performance improvement of Kuehn et al. 2020 model
  debian/changelog
  openquake/hazardlib/gsim/kuehn_2020.py
Labels: performance

#7790 make_ctxs/13
  openquake/calculators/base.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
Labels: performance

#7792 Numbified cartesian_to_spherical
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/point_test.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: performance

#7793 make_contexts/14
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
Labels: performance

#7795 Rewritten disaggregation in terms of context arrays
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
Labels: performance, internal

#7794 Simplified AreaSource.iter_ruptures
  doc/adv-manual/developing.rst
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/area.py
Labels: internal

#7796 make_ctxs/15
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/point.py
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
  openquake/hazardlib/tests/source/point_test.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(0.2).csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(2.0).csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data-bis.csv
  openquake/qa_tests_data/event_based/case_2/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_2/expected/minimum-intensity-gmf-data.csv
  openquake/qa_tests_data/event_based/case_23/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf1.csv
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf2.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/aggcurves.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/damages.csv
Labels: performance

#7797 Added a test with CampbellBozorgnia2014 in the engine
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_72/expected/hcurve-002.csv
  openquake/qa_tests_data/classical/case_72/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_72/job.ini
Labels: internal

#7798 make_ctxs/16
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
  openquake/hazardlib/tests/site_test.py
Labels: performance

#7799 make_ctxs/17
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/base.py
Labels: performance

#7801 Fixed bug introduced in https://github.com/gem/oq-engine/pull/7795
  openquake/calculators/disaggregation.py
  openquake/hazardlib/contexts.py
Labels: bug, internal

#7802 Numbified get_rx and get_ry0
  debian/changelog
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
Labels: performance

#7806 Fixed check on the logic tree values for empty values
  openquake/commonlib/logictree.py
Labels: enhancement

#7803 Storing the context arrays directly
  doc/adv-manual/developing.rst
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7808 Fixed `oq compare rups` after the change in the rupture storage
  openquake/calculators/classical.py
  openquake/commands/compare.py
Labels: internal

#7811 Killing the zmq workers in case of exceptions
  openquake/engine/engine.py
Labels: enhancement

#7812 Avoid logging the generic name split_task
  openquake/baselib/parallel.py
Labels: enhancement

#7804 remove remove_old_venv from install server and devel_server
  install.py
Labels: bug

#7813 Reduced classical/case_18 to a single point source
  openquake/calculators/tests/classical_test.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(1.0).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.csv
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.xml
  openquake/qa_tests_data/classical/case_18/job.ini
  openquake/qa_tests_data/classical/case_18/point_source.xml
  openquake/qa_tests_data/classical/case_18/source_model_logic_tree.xml
  openquake/qa_tests_data/classical/case_18/vancouver_area_source.xml
Labels: internal

#7814 make_ctxs/20
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
Labels: internal

#7815 make_contexts/21
  openquake/hazardlib/contexts.py
Labels: internal

#7816 make_ctxs/22
  openquake/hazardlib/source/point.py
Labels: internal

#7817 make_contexts/23
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/geo/surface/planar_test.py
  openquake/hazardlib/tests/source/point_test.py
Labels: internal

#7818 make_contexts/24
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_curve-mean_SA(1.0).csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_18/expected/hazard_uhs-mean.csv
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.csv
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.xml
Labels: internal

#7819 make_ctxs/25
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
Labels: internal

#7820 make_ctxs/26
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
Labels: internal

#7823 make_contexts/27
  openquake/hazardlib/source/point.py
Labels: performance

#7824 Discarded source_id="1" in disagg/case_1
  openquake/qa_tests_data/disagg/case_1/expected_output/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_1/gmpe_logic_tree.xml
  openquake/qa_tests_data/disagg/case_1/job.ini
  openquake/qa_tests_data/disagg/case_1/source_model.xml
Labels: internal

#7827 make_contexts/29
  openquake/hazardlib/contexts.py
Labels: performance

#7826 Fixed the SMTK
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/gsim/base.py
Labels: bug

#7828 make_contexts/30
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/point.py
Labels: performance

#7829 make_contexts/31
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-PGV.csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.025).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.05).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.2).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(0.5).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_curve-SA(2.0).csv
  openquake/qa_tests_data/classical/case_24/expected/hazard_uhs.csv
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7822 Epsilon star fix
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_8/job.ini
  openquake/qa_tests_data/disagg/case_8/ssm/source_model.xml
Labels: bug

#7830 Spectacular speedup in iter_ruptures
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
Labels: performance

#7832 make_contexts/32
  openquake/hazardlib/contexts.py
Labels: internal

#7833 make_contexts/33
  openquake/hazardlib/contexts.py
Labels: performance

#7834 Removed REQUIRES_COMPUTED_PARAMETERS
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/tests/gsim/nshmp_2014_test.py
  openquake/hazardlib/valid.py
Labels: internal

#7835 Added ztor estimation to Campbell and Bozorgnia (2014)
  debian/changelog
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/qa_tests_data/classical/case_71/expected/hcurves.csv
  openquake/qa_tests_data/classical/case_71/gmpe_logic_tree.xml
Labels: enhancement

#7836 make_contexts/34
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7837 Implemented infrastructure risk
  .github/workflows/engine_test.yml
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_15/__init__.py
  openquake/qa_tests_data/scenario_damage/case_15/exposure.xml
  openquake/qa_tests_data/scenario_damage/case_15/exposure_demo_edges.csv
  openquake/qa_tests_data/scenario_damage/case_15/exposure_demo_nodes.csv
  openquake/qa_tests_data/scenario_damage/case_15/fragility_model.xml
  openquake/qa_tests_data/scenario_damage/case_15/job.ini
  openquake/qa_tests_data/scenario_damage/case_15/nonfunctional.csv
  openquake/qa_tests_data/scenario_damage/case_15/rupture_model.xml
  openquake/qa_tests_data/scenario_damage/case_15/site_model_measured.xml
  openquake/risklib/connectivity.py
Labels: enhancement

#7838 Better monitoring of make_contexts
  openquake/hazardlib/contexts.py
Labels: internal

#7840 make_contexts/35
  openquake/hazardlib/contexts.py
Labels: performance

#7844 Doubled the speed in `iter_ruptures`
  openquake/hazardlib/scalerel/point.py
  openquake/hazardlib/source/point.py
Labels: performance

#7845 Doubling the speed of iter_ruptures again
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_24/job.ini
  openquake/qa_tests_data/classical/case_70/expected/hcurve-mean.csv
Labels: performance

#7843 Automatically set discard_trts in disaggregation calculations
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
  openquake/qa_tests_data/disagg/case_1/job.ini
Labels: enhancement

#7847 RPM package using install.py
  .github/workflows/rpm_stable.yml
  rpm/python3-oq-engine.spec.inc
Labels: dependencies

#7848 Upgrade pandas to 1.3.5
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos.txt
  requirements-py39-win64.txt
Labels: dependencies

#7850 Fixed risk infrastructure test
  openquake/calculators/tests/scenario_damage_test.py
Labels: dependencies

#7852 Removed the special case for PointMSR
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_2/expected/hcurve.csv
  openquake/qa_tests_data/classical/case_59/expected/hcurve-mean.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
Labels: performance

#7849 Fixed upgrade_nrml
  debian/changelog
  openquake/hazardlib/source/multi_point.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source_model/points.xml
  openquake/hazardlib/tests/sourceconverter_test.py
Labels: bug

#7854 Temporarily restore rvolc=0
  openquake/hazardlib/geo/surface/planar.py
Labels: internal

#7855 Fixed the time information stored in source_data
  openquake/commands/shell.py
  openquake/hazardlib/contexts.py
Labels: internal

#7846 Introduced the concept of split sources at the XML level
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: enhancement

#7857 NetworkX requirements
  requirements-py37-linux64.txt
  requirements-py37-macos.txt
  requirements-py37-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos.txt
  requirements-py39-win64.txt
Labels: dependencies

#7860 Fixed type error in get_mean_and_stddevs
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
Labels: bug

#7861 Check missing mags in GMPETable
  debian/changelog
  openquake/hazardlib/__init__.py
  openquake/hazardlib/contexts.py
Labels: enhancement

#7864 Improved the precision of the `ps_grid_spacing` approximation
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/point.py
  openquake/qa_tests_data/classical/case_43/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_43/expected/hazard_map-mean-PGA.csv
Labels: performance

#7869 Reduced slow tasks in EHSM20
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
Labels: performance

#7872 Improved slow tasks more
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/contexts_test.py
Labels: performance

#7874 Solved slow tasks in EUR
  openquake/commonlib/source_reader.py
  openquake/hazardlib/contexts.py
Labels: performance
