Repository gem/oq-engine, pull requests merged in 2023-05, with the labels that each got.

#8689 Added check for missing site parameters
  debian/changelog
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based/case_26/job_land.ini
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/qa_tests_data/logictree/case_28/job_wrong.ini
Labels: enhancement

#8690 Replaced `sites_csv` with `site_model_csv`
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_64/GRID_Mascandola.csv
  openquake/qa_tests_data/classical/case_64/job.ini
Labels: internal, inputs

#8695 Fully fixed `import_gmvs_csv`
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_22/gmfdata.csv
  openquake/qa_tests_data/scenario/case_22/job_bis.ini
  openquake/qa_tests_data/scenario/case_22/sitemodel.csv
Labels: bug

#8694 Improved `view_extreme_gmvs` and some cleanup
  openquake/calculators/views.py
  openquake/commands/mosaic.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/cross_correlation.py
Labels: internal

#8698 Added ses_seed information to extract/ruptures
  openquake/calculators/extract.py
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
Labels: enhancement

#8699 Added function get_ebrupture
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/source/rupture.py
  utils/max_gmv0
Labels: enhancement

#8704 Fixed extract/rupture_info
  openquake/calculators/tests/event_based_risk_test.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_23/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/src_mutex/expected/ruptures.csv
Labels: bug, outputs

#8705 Added source ID information when extracting a single rupture
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
Labels: enhancement, outputs

#8706 Removed the EBRupture.scenario attribute
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
Labels: internal

#8709 Huge helper for debugging GMPEs
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/med_gmv.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/commands/compare.py
  openquake/commands/tests/commands_test.py
  openquake/qa_tests_data/logictree/case_04/job.ini
  openquake/qa_tests_data/logictree/case_13/job_gmv.ini
Labels: internal

#8710 Refactored can_shm6_inslab.py
  openquake/hazardlib/gsim/can20/can_shm6_inslab.py
  openquake/hazardlib/gsim/can20/can_shm6_interface.py
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
Labels: internal

#8711 Added view `risk_by_rup`
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
Labels: enhancement

#8707 Changed the disaggregation by poe algorithm
  debian/changelog
  doc/manual/hazard.rst
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/commonlib/tests/calc_test.py
  openquake/hazardlib/probability_map.py
  openquake/qa_tests_data/disagg/case_1/expected_output/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_1/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_10/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_11/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
  openquake/qa_tests_data/disagg/case_5/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_6/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_6/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-traditional-0.csv
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-1.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/TRT_Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/TRT_Mag_Dist-1.csv
Labels: enhancement

#8714 Added rrup information to event based calculations
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
  utils/max_gmv0
Labels: enhancement

#8716 Fixed terrible bug in the Canadian GMPEs
  openquake/hazardlib/gsim/can20/can_shm6_inslab.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.csv
Labels: bug

#8721 Moved expected files for the CanadaSHM6 test to .org format
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.csv
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
Labels: internal

#8723 Copying contexts before updating
  openquake/hazardlib/gsim/cauzzi_faccioli_2008_swiss.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss.py
  openquake/hazardlib/gsim/zhao_2006_swiss.py
Labels: bug, backport

#8726 Making the contexts immutable in get_mean_stds
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/bindi_2011_ipe.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/can20/can_shm6_inslab.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/youd_etal_2002.py
  openquake/hazardlib/gsim/zhang_zhao_2005.py
  openquake/hazardlib/gsim/zhao_2006_swiss.py
  openquake/qa_tests_data/logictree/case_71/expected/hcurves.csv
Labels: bug, backport

#8727 Fixed rupture sampling for same source in multiple branches
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/source_reader.py
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_25/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
Labels: bug

#8729 Fixed CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55 with `sigma_mu_epsilon`
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/can20/can_shm6_inslab.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/gmpe_logic_tree.xml
Labels: bug

#8720 Shorter `gsims` column in full report
  debian/changelog
  openquake/calculators/views.py
Labels: enhancement

#8717 Rename outputs `rates_by_src` to `mean_rates_by_src` and `mean_disagg_bysrc` to `mean_disagg_by_src`
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/classical/case_82/expected/mean_rates_by_src.csv
  openquake/qa_tests_data/logictree/case_05/expected/mean_disagg_by_src.csv
  openquake/server/db/actions.py
Labels: enhancement

#8732 New loss types: area and number
  debian/changelog
  openquake/calculators/tests/multi_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Com_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Ind_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Res_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/area_vulnerability.xml
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-OCCUPANCY.csv
  openquake/qa_tests_data/event_based_risk/case_8/job.ini
  openquake/qa_tests_data/event_based_risk/case_8/number_vulnerability.xml
  openquake/qa_tests_data/scenario_risk/case_10/job.ini
  openquake/qa_tests_data/scenario_risk/case_10/rupture_model.xml
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: enhancement, outputs

#8700 Dsg mf several sites
  debian/changelog
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: bug, backport

#8735 Deprecated the <area> conversion in the exposure
  debian/changelog
  openquake/risklib/asset.py
Labels: documentation

#8736 Fixed another mutability bug
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/qa_tests_data/logictree/case_79/gmmLT.xml
Labels: bug

#8737 Restored `sites_csv = site_model.csv`
  openquake/calculators/base.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_34/job.ini
Labels: bug

#8739 Backported fixes for the mutability bug
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/akkar_bommer_2010.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/bindi_2011_ipe.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/cauzzi_faccioli_2008_swiss.py
  openquake/hazardlib/gsim/chiou_youngs_2008_swiss.py
  openquake/hazardlib/gsim/youd_etal_2002.py
  openquake/hazardlib/gsim/zhang_zhao_2005.py
  openquake/qa_tests_data/classical/case_71/expected/hcurves.csv
Labels: bug, critical

#8741 third fix to disaggregation with multifaults
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: bug

#8728 Added a flake8 test for serious violations
  .github/workflows/engine_test.yml
  openquake/baselib/tests/flake8_test.py
  openquake/hmtk/plotting/beachball.py
  openquake/hmtk/seismicity/occurrence/utils.py
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
Labels: bug

#8743 Fixed IMT-ordering in the expected files for case_76
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/imt.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
Labels: internal

#8744 Sort by IMT correctly
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/imt.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
Labels: internal

#8746 Changed the order of the IMT to be by period and not lexicographic
  debian/changelog
  openquake/baselib/general.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
  openquake/qa_tests_data/postproc/case_mrd/expected/hazard_curve-mean-SA(0.2).csv
  openquake/qa_tests_data/postproc/case_mrd/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/postproc/case_mrd/job.ini
Labels: inputs

#8745 AELO: catch all exceptions raised by 'get_params_from', including OsError for ini file not found
  openquake/commonlib/mosaic.py
  openquake/server/views.py
Labels: bug

#8748 Fixed the damage state header in the aggrisk outputs
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_12/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_damage/case_12/expected/aggrisk-taxonomy-policy.csv
Labels: outputs, backport

#8749 Speeding up rupture sampling
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/sourceconverter.py
Labels: performance

#8751 Forbid OBJECT_REPLACEMENT_CHARACTER
  openquake/baselib/sap.py
  openquake/baselib/tests/flake8_test.py
  openquake/hazardlib/scalerel/cscaling.py
Labels: internal

#8718 AELO: enable/disable urls and buttons depending from the application mode
  .github/workflows/engine_test.yml
  openquake/server/settings.py
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aelo_mode.py
  openquake/server/tests/test_public_mode.py
  openquake/server/tests/views_test.py
  openquake/server/v1/calc_urls.py
Labels: enhancement

#8753 Removed ugly SkipTest in views_test.py
  openquake/server/tests/views_test.py
Labels: internal

#8740 AELO: changes to the GUI
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aelo_mode.py
  openquake/server/views.py
Labels: enhancement

#8757 Splitting multiFaultSources before rupture sampling
  openquake/calculators/event_based.py
  openquake/hazardlib/sourceconverter.py
Labels: performance

#8758 Made `truncation_level` mandatory
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/aftershock/case_1/pre_job.ini
  openquake/qa_tests_data/classical/case_27/job.ini
  openquake/qa_tests_data/classical/case_47/job.ini
  openquake/qa_tests_data/classical/case_53/job.ini
  openquake/qa_tests_data/classical/case_54/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_1/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_2/job.ini
  openquake/qa_tests_data/event_based/spatial_correlation/case_3/job.ini
  openquake/qa_tests_data/event_based_risk/case_miriam/job2.ini
  openquake/qa_tests_data/logictree/case_12/job.ini
  openquake/qa_tests_data/logictree/case_12/job_bis.ini
  openquake/qa_tests_data/logictree/case_36/job.ini
  openquake/qa_tests_data/scenario/case_5/job.ini
  openquake/qa_tests_data/scenario/case_6/job.ini
  openquake/qa_tests_data/scenario/case_8/job.ini
  openquake/qa_tests_data/scenario_damage/case_4/job_risk.ini
  openquake/qa_tests_data/scenario_risk/case_1g/job_risk.ini
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
  openquake/qa_tests_data/scenario_risk/case_shapefile/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shapefile/job.ini
  openquake/qa_tests_data/scenario_risk/case_shapefile/job_zipped.ini
Labels: bug

#8759 Improved multiFault sampling more
  debian/changelog
  doc/adv-manual/general.rst
  openquake/hazardlib/source/base.py
Labels: performance

#8760 Fixed task distribution in the USA model (100x speedup)
  openquake/hazardlib/sourceconverter.py
Labels: performance

#8763 Syntax error of anchor
  doc/installing/README.md
Labels: documentation

#8765 Replace url for menu help button
  openquake/server/templates/engine/base.html
Labels: enhancement

#8764 Document the syntax like 'aggregate_by = NAME_1; taxonomy'
  doc/adv-manual/event_based.rst
Labels: documentation

#8769 Fixed event based with area,number loss types
  openquake/qa_tests_data/scenario/case_21/earthquake_rupture_model_USGS.xml
  openquake/risklib/asset.py
Labels: bug

#8771 Saved 20% of the memory when reading the exposure
  debian/changelog
  openquake/risklib/asset.py
Labels: performance

#8770 Storing the assets directly as a DataFrame
  openquake/baselib/performance.py
  openquake/risklib/asset.py
  openquake/risklib/connectivity.py
  openquake/risklib/scientific.py
Labels: bug

#8762 Add a clearer error message when a single percent is found in the ini
  openquake/baselib/__init__.py
  openquake/baselib/node.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/__init__.py
Labels: bug

#8766 Replace help_url to point to the latest engine manual
  openquake/server/templates/engine/base.html
Labels: enhancement

#8773 Added OQ_SAMPLE_ASSETS
  openquake/risklib/asset.py
Labels: internal

#8775 Saving memory in event_based_risk
  openquake/calculators/event_based_risk.py
Labels: performance

#8772 Improve advanced manual about aggregation by multiple keys for reinsurance
  doc/adv-manual/event_based.rst
Labels: documentation

#8776 Saving memory in event_based_risk/2
  openquake/baselib/performance.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: performance

#8779 Speeding up reading the assets (35x)
  openquake/calculators/classical.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
Labels: performance

#8781 Saving memory in event_based_risk/3
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-001.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-sid-1-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/loss_curves-mean.csv
  openquake/risklib/asset.py
  openquake/risklib/scientific.py
Labels: performance

#8782 Refactoring the exposure processor/1
  openquake/calculators/tests/multi_risk_test.py
  openquake/risklib/asset.py
Labels: internal

#8783 Refactoring the exposure processor/2
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/geo/utils.py
  openquake/risklib/asset.py
  utils/expo2csv
Labels: internal

#8785 Introduced avg_occupants
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/multi_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_risk/case_3/expected/asset-loss.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/agg_loss.csv
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#8786 Recognized `occupants_avg` field in the exposure
  debian/changelog
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Com_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Ind_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Res_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Singapore.xml
  openquake/risklib/asset.py
Labels: enhancement, inputs

#8787 Refactoring the exposure processor/3
  openquake/baselib/general.py
  openquake/risklib/asset.py
Labels: performance

#8794 Storing site_id in the assets
  openquake/commonlib/readinput.py
  openquake/risklib/asset.py
Labels: internal

#8796 Refactoring the exposure processor/7
  openquake/risklib/asset.py
Labels: performance

#8799 Speeding up processing the AssetCollection
  openquake/risklib/asset.py
Labels: performance

#8800 Speeding up processing the AssetCollection/2
  openquake/calculators/tests/multi_risk_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/multi_risk/case_1/expected/agg_risk.csv
  openquake/risklib/asset.py
Labels: performance

#8801 Using numpy.unique to build the tag collection
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_damage/case_11/expected/aggcurves-county-taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_12/expected/aggrisk-taxonomy-policy.csv
  openquake/qa_tests_data/event_based_damage/case_12/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_12/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/b_damages.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damage_table.txt
  openquake/qa_tests_data/event_based_damage/case_13/expected/c_damages.txt
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_tag.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/losses_by_taxo.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-OCCUPANCY.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
  openquake/qa_tests_data/event_based_risk/recompute/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/recompute/expected/recomputed_losses.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_1/expected/reinsurance-avg_policy.csv
  openquake/qa_tests_data/scenario_damage/case_12/expected/aggrisk2.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_7/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_8/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/reinsurance/expected/reinsurance-avg_portfolio.csv
  openquake/risklib/asset.py
Labels: performance

#8805 Fixed disagg-stats exporter
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-mean-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-mean-1.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/TRT_Mag_Dist-mean-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/TRT_Mag_Dist-mean-1.csv
  openquake/qa_tests_data/disagg/case_master/job.ini
Labels: bug, backport

#8806 Fixed the case of multiple exposure.xml files
  openquake/risklib/asset.py
Labels: bug

#8807 Computing the geohash with numba
  debian/changelog
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
Labels: performance

#8808 Using 2 digits for the magnitude
  debian/changelog
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/qa_tests_data/disagg/case_14/CEUSFaultSources.xml
  openquake/qa_tests_data/disagg/case_14/__init__.py
  openquake/qa_tests_data/disagg/case_14/job.ini
  openquake/qa_tests_data/disagg/case_14/reduced.xml
  openquake/qa_tests_data/disagg/case_14/sites_dsg.csv
  openquake/qa_tests_data/disagg/case_14/ssmLT_denver.xml
Labels: internal

#8809 Optimized check on duplicate assets
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/scenario/case_23/__init__.py
  openquake/qa_tests_data/scenario/case_23/exp1.csv
  openquake/qa_tests_data/scenario/case_23/exp2.csv
  openquake/qa_tests_data/scenario/case_23/exposure_model.xml
  openquake/qa_tests_data/scenario/case_23/fault_rupture.xml
  openquake/qa_tests_data/scenario/case_23/job.ini
  openquake/qa_tests_data/scenario/case_23/sitemesh.csv
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
Labels: performance

#8811 Optimized the region check
  openquake/risklib/asset.py
Labels: performance

#8815 Vectorized the association assets <-> sites
  debian/changelog
  openquake/commands/prepare_site_model.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
Labels: performance

#8814 Refactoring the exposure processor/9
  openquake/calculators/multi_risk.py
  openquake/calculators/views.py
  openquake/commands/prepare_site_model.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
  openquake/risklib/asset.py
Labels: internal

#8816 Refactoring the exposure processor/10
  openquake/commands/prepare_site_model.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/risklib/asset.py
Labels: performance

#8803 Document how to configure multiple engine installations to run on a same computer
  doc/adv-manual/general.rst
  doc/faq.md
  openquake/commands/mosaic.py
Labels: documentation

#8817 Better monitoring of the exposure processor
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/risklib/asset.py
Labels: internal

#8818 Optimized reading the exposure more
  openquake/calculators/tests/multi_risk_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/event_based_damage/case_13/expected/d_damages.txt
  openquake/qa_tests_data/multi_risk/case_1/expected/agg_risk.csv
  openquake/risklib/asset.py
Labels: performance

#8819 Fixed oq-risk-tests/case_global_eb
  openquake/risklib/asset.py
Labels: bug, internal

#8823 Fixed a terrible bug in the tiling calculator
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_22/job.ini
Labels: bug, critical, backport

#8825 Backported tiling bug
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_22/job.ini
Labels: bug, critical
