Repository gem/oq-engine, pull requests merged in 2023-12, with the labels that each got.

#9265 small fixes to aelo plotting
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
Labels: bug

#9267 Initial work for event based in-a-box
  openquake/calculators/event_based.py
  openquake/commonlib/global_model_getter.py
Labels: enhancement

#9268 Added parameter mosaic_model
  openquake/calculators/event_based.py
  openquake/commands/mosaic.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
  openquake/server/tests/test_aelo_mode.py
Labels: enhancement

#9272 AELO: better handle cases with low or zero hazard
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/aelo.py
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/views.py
Labels: enhancement

#9277 AELO: when presenting ASCE tables, format numbers to display 2 significant figures
  openquake/server/views.py
Labels: enhancement

#9271 Hcurve documentation
  doc23/user-guide/outputs/classical-psha-outputs.rst
Labels: documentation

#9279 Doc23 home readme plus other minors adjustments
  README.md
  doc23/api-reference/index.rst
  doc23/contributing/development-guidelines.md
  doc23/contributing/index.rst
  doc23/contributing/testing.md
  doc23/getting-started/installation-instructions/index.rst
  doc23/release-notes/whats-new-1.2.md
  doc23/release-notes/whats-new-1.3.md
  doc23/release-notes/whats-new-1.4.md
  doc23/release-notes/whats-new-1.5.md
  doc23/release-notes/whats-new-1.6.md
  doc23/release-notes/whats-new-1.7.md
  doc23/release-notes/whats-new-1.8.md
  doc23/release-notes/whats-new-1.9.md
  doc23/release-notes/whats-new-2.0.md
  doc23/release-notes/whats-new-2.1.md
  doc23/release-notes/whats-new-2.2.md
  doc23/release-notes/whats-new-2.3.md
  doc23/release-notes/whats-new-2.4.md
  doc23/release-notes/whats-new-2.5.md
  doc23/release-notes/whats-new-2.6.md
  doc23/release-notes/whats-new-2.7.md
  doc23/release-notes/whats-new-2.8.md
  doc23/release-notes/whats-new-2.9.md
  doc23/release-notes/whats-new-3.0.md
  doc23/release-notes/whats-new-3.1.md
  doc23/release-notes/whats-new-3.10.md
  doc23/release-notes/whats-new-3.11.md
  doc23/release-notes/whats-new-3.12.md
  doc23/release-notes/whats-new-3.13.md
  doc23/release-notes/whats-new-3.14.md
  doc23/release-notes/whats-new-3.15.md
  doc23/release-notes/whats-new-3.16.md
  doc23/release-notes/whats-new-3.17.md
  doc23/release-notes/whats-new-3.2.md
  doc23/release-notes/whats-new-3.3.md
  doc23/release-notes/whats-new-3.4.md
  doc23/release-notes/whats-new-3.5.md
  doc23/release-notes/whats-new-3.6.md
  doc23/release-notes/whats-new-3.7.md
  doc23/release-notes/whats-new-3.8.md
  doc23/release-notes/whats-new-3.9.md
  doc23/user-guide/faq.rst
  doc23/user-guide/index.rst
  doc23/user-guide/working-with-the-dstore.rst
Labels: documentation

#9281 Fixed `extract_from_zip` when managing zip files coming from MACOSX
  debian/changelog
  openquake/commonlib/readinput.py
Labels: bug

#9282 Removed dbserver.user
  debian/changelog
  openquake/commands/dbserver.py
  openquake/engine/openquake.cfg
Labels: internal

#9284 Added a check for missing fields in the CSV files for the exposure
  debian/changelog
  openquake/risklib/asset.py
Labels: enhancement, inputs

#9285 Some PEP8 fixes
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/bahrampouri_2021.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/gsim/zhao_2016_volc_perg/volc_perg.py
Labels: internal

#9286 Simplified Exposure class
  openquake/calculators/base.py
  openquake/calculators/post_risk.py
  openquake/commonlib/tests/readinput_test.py
  openquake/risklib/asset.py
Labels: internal

#9287 Additional refactoring of the Exposure class
  openquake/risklib/asset.py
  utils/build_global_exposure
Labels: internal

#9288 More refactoring of the exposure
  openquake/risklib/asset.py
  utils/build_global_exposure
Labels: internal

#9291 Updated RaghukanthIyengar2007TestCase to use `contexts.get_mean_stds`
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
Labels: internal

#9290 Fixing expected files for Python 3.11 newer libraries
  .github/workflows/engine_pr_test.yml
  openquake/hazardlib/gsim/base.py
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.15.csv
  openquake/server/tests/test_public_mode.py
Labels: dependencies, internal

#9292 Fixed old-fashioned tests using a scalar magnitude
  openquake/hazardlib/gsim/base.py
Labels: internal

#9293 Added a test reading the global exposure generated by `build_global_exposure`
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/mosaic/case_01/expected/avg_gmf.csv
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/qa_tests_data/mosaic/exposure.hdf5
  openquake/risklib/asset.py
  openquake/server/tests/test_public_mode.py
  utils/build_global_exposure
  utils/build_global_sites
Labels: enhancement, inputs

#9295 Simplified classical_risk/case_master
  openquake/calculators/tests/classical_risk_test.py
  openquake/qa_tests_data/classical_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-mean.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.15.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.5.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.85.csv
  openquake/qa_tests_data/classical_risk/case_master/exposure_model.xml
  openquake/qa_tests_data/classical_risk/case_master/job.ini
Labels: internal

#9297 Avoided some numpy 1.26 warnings
  openquake/baselib/general.py
  openquake/calculators/tests/__init__.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.15.csv
  openquake/qa_tests_data/classical_bcr/case_2/job.ini
  openquake/qa_tests_data/classical_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.15.csv
Labels: internal

#9298 Changed the weighted quantile algorithm to not depend on `numpy.argsort`
  debian/changelog
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/classical_risk/case_master/expected/avg_losses-quantile-0.15.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.15.csv
Labels: dependencies, outputs

#9209 Improvement of the algorithm used to generate kite surfaces
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_00.txt
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_01.txt
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_02.txt
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_03.txt
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_04.txt
  openquake/hazardlib/tests/geo/surface/data/profiles10/cs_05.txt
  openquake/hazardlib/tests/geo/surface/data/profiles11/cs_00.txt
  openquake/hazardlib/tests/geo/surface/data/profiles11/cs_01.txt
  openquake/hazardlib/tests/geo/surface/data/profiles11/cs_02.txt
  openquake/hazardlib/tests/geo/surface/data/profiles11/cs_03.txt
  openquake/hazardlib/tests/geo/surface/data/profiles11/cs_04.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_00.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_01.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_02.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_03.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_04.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_05.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_06.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_07.txt
  openquake/hazardlib/tests/geo/surface/data/profiles_benchmark/cs_08.txt
  openquake/hazardlib/tests/geo/surface/kite_fault_auxilliary_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_bechmark_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
  openquake/hazardlib/tests/geo/surface/results/results_msf_nan_ry0.npz
  openquake/hazardlib/tests/geo/surface/results/results_nzl_1_rx.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_mesh_lons.txt
  openquake/hazardlib/tests/geo/surface/results/results_nzl_2_rx.txt
  openquake/hazardlib/tests/geo/surface/results/results_t01.npz
  openquake/hazardlib/tests/source/kite_fault_test.py
  openquake/qa_tests_data/classical/case_65/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_75/expected/hcurve-mean.csv
  openquake/qa_tests_data/event_based/case_29/expected/full_ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/gmf_data.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures2.csv
Labels: enhancement

#9087 Fixed mesh creation in surface/kite_fault.py
  debian/changelog
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
Labels: bug, backport

#9299 AELO: do not raise an error if no sources are close to the site
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
Labels: enhancement

#9300 Fixed check_mean_rates for Japan
  openquake/calculators/classical.py
  openquake/calculators/postproc/aelo_plots.py
Labels: bug

#9301 Fixed a few Python 3.11/numpy 1.26 warnings
  openquake/calculators/multi_risk.py
  openquake/commonlib/datastore.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim/bayless_abrahamson_2018.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/source_reader.py
Labels: internal

#9275 Log warning if all stations are beyond maximum_distance_stations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_29/__init__.py
  openquake/qa_tests_data/scenario/case_29/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_29/job.ini
  openquake/qa_tests_data/scenario/case_29/rupture_model.xml
  openquake/qa_tests_data/scenario/case_29/site_model.csv
  openquake/qa_tests_data/scenario/case_29/site_model_stations.csv
  openquake/qa_tests_data/scenario/case_29/stationlist_seismic.csv
Labels: enhancement

#9302 Fixing zmq without DbServer
  openquake/commonlib/logs.py
  openquake/server/dbserver.py
Labels: bug

#9303 Simplified the exposure and removed expo2csv
  openquake/commands/purge.py
  openquake/commands/run.py
  openquake/commands/show.py
  openquake/risklib/asset.py
  utils/expo2csv
Labels: internal, inputs

#9266 Using shapely spatial index to perform geospatial searches
  openquake/calculators/event_based.py
  openquake/commonlib/global_model_getter.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/global_model_getter_test.py
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
Labels: enhancement

#9304 PEP 8 fixes to the New Zealand GMPEs
  install.py
  openquake/hazardlib/gsim/nz22/atkinson_2022.py
  openquake/hazardlib/gsim/nz22/const.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/tests/valid_test.py
  pyproject.toml
Labels: internal

#9305 Using ruff as linter/1
  .github/workflows/engine_pr_test.yml
  openquake/baselib/node.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/__init__.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/datastore_test.py
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/engine/__init__.py
  openquake/engine/engine.py
  pyproject.toml
Labels: internal

#9307 Fixed the GlobalModelGetter
  debian/changelog
  openquake/commonlib/global_model_getter.py
Labels: bug
