Repository gem/oq-engine, pull requests merged in 2023-07, with the labels that each got.

#8877 Solved hanging of classical calculations due to large packets
  debian/changelog
  openquake/baselib/__init__.py
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/commands/engine.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
  openquake/qa_tests_data/classical/case_22/job.ini
  openquake/qa_tests_data/logictree/case_14/job.ini
Labels: bug, critical

#8879 Added dbserver.user in openquake.cfg
  debian/changelog
  openquake/commands/dbserver.py
  openquake/engine/openquake.cfg
Labels: enhancement

#8884 Minor edits to what's new for engine-3.17
  doc/whats-new.md
Labels: documentation

#8883 Managed the case of disabling the stats correctly
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_47/job.ini
  openquake/qa_tests_data/classical/case_53/job.ini
  openquake/qa_tests_data/classical/case_54/job.ini
Labels: bug

#8885 Adding disappeared test for mrd calculation
  openquake/hazardlib/tests/calc/expected/mrd/calc_2130.hdf5
  openquake/hazardlib/tests/calc/expected/mrd/gmclt.xml
  openquake/hazardlib/tests/calc/expected/mrd/job.ini
  openquake/hazardlib/tests/calc/expected/mrd/source_model.xml
  openquake/hazardlib/tests/calc/expected/mrd/ssclt.xml
  openquake/hazardlib/tests/calc/figs/mrd_direct_test.png
  openquake/hazardlib/tests/calc/figs/mrd_indirect_test.png
  openquake/hazardlib/tests/calc/figs/mrd_test_mrd_comparison.png
  openquake/hazardlib/tests/calc/mrd_test.py
Labels: enhancement

#8887 Removed all incorrect references to celery
  doc/adv-manual/general.rst
  doc/glossary.md
  doc/hardware-suggestions.md
  doc/installing/ubuntu.md
  doc/sphinx/baselib.rst
  openquake/baselib/tests/parallel_test.py
  openquake/engine/celeryconfig.py
  utils/reset-db
Labels: documentation

#8880 Whats New for engine-3.17
  doc/whats-new.md
Labels: documentation

#8888 Removed dependence from calc_XXX.hdf5 in mrd_test
  openquake/hazardlib/tests/calc/expected/mrd/calc_2130.hdf5
  openquake/hazardlib/tests/calc/mrd_test.py
Labels: internal

#8889 updating changelog
  debian/changelog
Labels: bug

#8892 Refactored event_based/1
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/case_1/job_ins.ini
Labels: internal

#8894 Refactored event_based/2
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/job_ins.ini
Labels: performance

#8886 Implemented parallel tiling
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
  openquake/qa_tests_data/classical/case_22/job.ini
  openquake/qa_tests_data/logictree/case_14/job.ini
Labels: performance

#8898 Fixed the error "You must supply a list of magnitudes as 2-digit strings
  openquake/calculators/event_based.py
Labels: bug

#8899 Making sure the GMVs are 32 bit
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#8902 Changed the eid <-> rlz associations again
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_29/expected/full_ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_nonstructural.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_structural.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: bug, backport

#8903 Moved the generation of the hazard curves from the GMFs in post_execute
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/qa_tests_data/event_based/case_17/job.ini
Labels: internal

#8906 Removed redundant argument
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
Labels: performance

#8904 Backported critical fix https://github.com/gem/oq-engine/pull/8902
  debian/changelog
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based/case_1/expected/events.csv
  openquake/qa_tests_data/event_based/case_14/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_29/expected/full_ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures_full.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/eb_aggcurves-policy-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_nonstructural.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/src_loss_structural.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: bug

#8909 Transferring the GMFs are dictionaries instead of DataFrames
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
Labels: performance

#8916 Reduced slow tasks in event_based
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
Labels: performance

#8921 Reduced slow tasks in the ebrisk calculator
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
Labels: performance
