Repository gem/oq-engine, pull requests merged in 2023-01, with the labels that each got.

#8323 Parallelized the main reinsurance calculation
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/commonlib/datastore.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/risklib/reinsurance.py
Labels: performance

#8324 Removed empty see page references
  doc/manual/hazard.rst
Labels: documentation

#8328 Splitting the multiFaultSources first
  openquake/calculators/preclassical.py
Labels: performance

#8330 Removed slow `np.isin(all_policies, exp_policies)` in the reinsurance calculator
  openquake/risklib/reinsurance.py
Labels: performance

#8329 Added command `oq workers debug`
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/workerpool.py
  openquake/baselib/zeromq.py
  openquake/commands/workers.py
Labels: internal

#8331 Raised the tolerance on `srcs_weights`
  openquake/hazardlib/sourceconverter.py
Labels: enhancement

#8336 Basic infrastructure for AELO
  doc/tutorials/aelo.org
  openquake/engine/aelo.py
  openquake/engine/openquake.cfg
  openquake/server/tests/views_test.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#8338 Renamed rup_id -> seed in event_based calculations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#8334 Fixed OqParam.get_input_size for in-memory params
  openquake/commonlib/oqvalidation.py
Labels: bug

#8337 RPM for python3.9
  .github/workflows/rpm_stable.yml
  doc/installing/rhel.md
  docker/Dockerfile.base
  docker/Dockerfile.dev
  docker/Dockerfile.engine
Labels: dependencies

#8318 Conditioned ground motion calculator
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commands/run.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/shakemap/conditioned_gmfs.py
  openquake/qa_tests_data/scenario_risk/case_11/__init__.py
  openquake/qa_tests_data/scenario_risk/case_11/earthquake_rupture_model_USGS.xml
  openquake/qa_tests_data/scenario_risk/case_11/gmf-data.csv
  openquake/qa_tests_data/scenario_risk/case_11/job.ini
  openquake/qa_tests_data/scenario_risk/case_11/site_model.csv
  openquake/qa_tests_data/scenario_risk/case_11/site_model_stations.csv
  openquake/qa_tests_data/scenario_risk/case_11/stationlist_seismic.csv
Labels: enhancement

#8344 Removed celery from openquake.cfg
  openquake/engine/openquake.cfg
Labels: dependencies

#8347 Ignominiously defeated scipy: 100x speedup with our own truncnorm_sf
  debian/changelog
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8350 Committed fake EUR files
  openquake/qa_tests_data/mosaic/EUR/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/EUR/in/job.ini
  openquake/qa_tests_data/mosaic/EUR/in/sites_eur_res6.csv
  openquake/qa_tests_data/mosaic/EUR/in/ssm/main_region/asm/asm_ver12e_winGT_fs017_lo_abgrs_maxmag_low.xml
  openquake/qa_tests_data/mosaic/EUR/in/ssmLT.xml
Labels: internal

#8351 Fixed log in disaggregation calculations with num_disagg_rlzs=0
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/hazardlib/calc/disagg.py
Labels: bug

#8349 Warning for point sources containing magnitudes >= 8
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/calculators/tests/disagg_test.py
Labels: enhancement

#8354 Make sure fiona is optional
  openquake/commonlib/mosaic.py
Labels: dependencies

#8355 Fixed readinput._checksum for <in-memory> files
  openquake/commonlib/readinput.py
Labels: bug

#8356 Fixed disaggregation bug with GMPETables
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/disagg/case_13/__init__.py
  openquake/qa_tests_data/disagg/case_13/gmpe_logic_tree_sample.xml
  openquake/qa_tests_data/disagg/case_13/job.ini
  openquake/qa_tests_data/disagg/case_13/source_model.xml
  openquake/qa_tests_data/disagg/case_13/source_model_logic_tree.xml
Labels: bug

#8358 Running a real calculation with aelo.py
  openquake/engine/aelo.py
  openquake/engine/engine.py
Labels: enhancement

#8357 Improve Advanced Manual versioning.
  .github/workflows/docs.yml
  doc/adv-manual/conf.py
  doc/adv-manual/index.rst
Labels: documentation

#8363 Minor edits to whats-new for engine-3.16
  doc/whats-new.md
Labels: documentation

#8046 Passed investigation times to the classical risk and bcr calculators
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical_bcr/case_1/expected/bcr-structural.csv
  openquake/qa_tests_data/classical_bcr/case_1/hazard_curve-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-mean.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.15.csv
  openquake/qa_tests_data/classical_bcr/case_2/expected/bcr-quantile-0.85.csv
  openquake/qa_tests_data/classical_risk/case_2/expected/loss_curves.csv
  openquake/qa_tests_data/classical_risk/case_2/expected/loss_maps.csv
  openquake/qa_tests_data/classical_risk/case_3/expected/loss_curves-ref-a8-000.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_curves-sid-1-mean.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b1.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-b1,b2.csv
  openquake/qa_tests_data/classical_risk/case_4/expected/loss_maps-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/avg_losses-000.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/avg_losses-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/expected/loss_curves-mean.csv
  openquake/qa_tests_data/classical_risk/case_5/job_h.ini
  openquake/qa_tests_data/classical_risk/case_5/job_r.ini
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-mean.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.15.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.5.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.85.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/classical_test.py
Labels: enhancement

#8366 Fixed 0 weight assertion
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/contexts_test.py
Labels: bug

#8368 Reducing the stress on the ZMQ receiver socket
  openquake/baselib/parallel.py
Labels: internal

#8370 Multi versions for 'user' and 'advanced' manuals
  .github/workflows/docs.yml
  doc/adv-manual/_static/css/custom.css
  doc/adv-manual/conf.py
  doc/manual/_static/css/custom.css
  doc/manual/conf.py
Labels: enhancement

#8371 Logging hidden exceptions in the process pool
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/baselib/zeromq.py
Labels: internal

#8372 Increased the number of disaggregation tasks
  debian/changelog
  openquake/calculators/disaggregation.py
Labels: performance

#8373 Added debugging features to safely_call
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/commonlib/logs.py
  openquake/server/db/actions.py
Labels: internal

#8374 Fixed number of oq-workers on oq1
  openquake/baselib/parallel.py
  openquake/commonlib/source_reader.py
  openquake/engine/engine.py
Labels: internal

#8375 Sending small zmq messages in classical calculations
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/hazardlib/probability_map.py
Labels: performance

#8289 Add to Lanzano et al. 2019 the adjustment proposed by Lanzano et al. (2022)
  debian/changelog
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_MOD22_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_MOD22_RJB_STD.csv
  openquake/hazardlib/tests/gsim/lanzano_2019_mod2022_test.py
Labels: enhancement
