Repository gem/oq-engine, pull requests merged in 2023-03, with the labels that each got.

#8474 Fixed event based running out of memory
  debian/changelog
  openquake/calculators/event_based.py
Labels: bug, backport

#8475 Add oversampling parameter
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_71/job.ini
Labels: enhancement, inputs

#8476 AELO project: refined disaggregation by source
  openquake/commonlib/readinput.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/logictree.py
Labels: enhancement

#8478 Implemented preclassical cache
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/commands/engine.py
  openquake/commonlib/readinput.py
  openquake/engine/aelo.py
  openquake/engine/postproc/postproc_test.py
  openquake/hazardlib/source_reader.py
Labels: performance

#8479 Added command `oq runpsha`
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/commands/runpsha.py
  openquake/commonlib/readinput.py
  openquake/engine/aelo.py
  openquake/engine/postproc/disagg_by_rel_sources.py
Labels: performance

#8480 Fixed mosaic tests
  openquake/calculators/preclassical.py
  openquake/commonlib/readinput.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/hazardlib/logictree.py
Labels: internal

#8481 Fixed JPN disaggregation
  openquake/hazardlib/calc/disagg.py
Labels: bug

#8482 Added test with reduction to one source
  openquake/calculators/base.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/export/risk.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/classical/case_68/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_68/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_68/expected/hazard_curve-rlz-001-PGA.csv
  openquake/qa_tests_data/classical/case_68/job1.ini
Labels: enhancement, internal

#8484 Printing relevant sources when disagg_by_src=true and there is a single site
  openquake/calculators/classical.py
  openquake/commands/runpsha.py
  openquake/engine/aelo.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/engine/postproc/postproc_test.py
Labels: enhancement

#8485 Fixed Kendra fix for extendModel
  openquake/hazardlib/source_reader.py
Labels: bug, backport

#8486 Renamed oq runpsha => oq onsite
  openquake/calculators/base.py
  openquake/commands/onsite.py
  openquake/commonlib/readinput.py
  openquake/engine/postproc/__init__.py
Labels: internal

#8492 Simplified the construction of the index trt_smr
  doc/tutorials/the-datastore/datastore.org
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#8420 GMM for Canada SHM6
  openquake/hazardlib/gsim/can20/AA13/ENA_central_cl450.hdf5
  openquake/hazardlib/gsim/can20/AA13/ENA_high_cl450.hdf5
  openquake/hazardlib/gsim/can20/AA13/ENA_low_cl450.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_01_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_02_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_03_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_04_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_05_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_06_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_07_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_08_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_09_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_10_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_11_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_12_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/NGA-EAST-13/SHM6-trial_NGA-East_Model_13_AA13_sigma.vs3000.hdf5
  openquake/hazardlib/gsim/can20/__init__.py
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/can20/can_shm6_inslab.py
  openquake/hazardlib/gsim/can20/can_shm6_interface.py
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
Labels: enhancement

#8495 Changed `disagg_by_src` to store rates
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/logictree/case_07/job.ini
Labels: outputs

#8497 Added flag `use_rates`
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/logictree/case_06/__init__.py
  openquake/qa_tests_data/logictree/case_06/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_06/expected/curve-rlz0.csv
  openquake/qa_tests_data/logictree/case_06/expected/curve-rlz1.csv
  openquake/qa_tests_data/logictree/case_06/gsim_logic_tree.xml
  openquake/qa_tests_data/logictree/case_06/job.ini
  openquake/qa_tests_data/logictree/case_06/source_model_1.xml
  openquake/qa_tests_data/logictree/case_06/source_model_2.xml
  openquake/qa_tests_data/logictree/case_06/source_model_logic_tree.xml
Labels: internal

#8489 Adding the option to set kappa0 while initialising the model
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_MOD22_RJB_MEAN_kappa0.csv
  openquake/hazardlib/tests/gsim/lanzano_2019_mod2022_test.py
Labels: enhancement

#8498 Removed the R-dimension from the `disagg_by_src` array
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/tests/logictree_test.py
Labels: internal

#8499 Enhanced disaggregation by source
  openquake/calculators/classical.py
  openquake/calculators/tests/logictree_test.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/logictree/case_07/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/logictree/case_07/job.ini
  openquake/qa_tests_data/logictree/case_07/sampling.ini
Labels: internal

#8501 Fixes the index of a matrix in the plot of the MRD
  openquake/hazardlib/tests/calc/mrd_test.py
Labels: bug

#8502 Fixed `logictree.get_trt_by_src`
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/logictree.py
Labels: bug, inputs

#8507 Lan19 fix
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_MOD22_RJB_MEAN_kappa0.csv
  openquake/hazardlib/tests/gsim/data/LAN2019/ITA18_MOD22_RJB_STD_kappa0.csv
  openquake/hazardlib/tests/gsim/lanzano_2019_mod2022_test.py
Labels: bug

#8506 try two for reqv solution: job param with list of sources to skip
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_84/__init__.py
  openquake/qa_tests_data/classical/case_84/expected/dbs.csv
  openquake/qa_tests_data/classical/case_84/gmmLT.xml
  openquake/qa_tests_data/classical/case_84/job.ini
  openquake/qa_tests_data/classical/case_84/lookup_reqv_asc.hdf5
  openquake/qa_tests_data/classical/case_84/ssm/WUSActiveShallowSources_no-reqv.xml
  openquake/qa_tests_data/classical/case_84/ssm/WUSActiveShallowSources_no-reqv2.xml
  openquake/qa_tests_data/classical/case_84/ssm/WUSActiveShallowSources_reqv.xml
  openquake/qa_tests_data/classical/case_84/ssmLT.xml
Labels: enhancement

#8509 Avoid storing some datasets twice
  openquake/calculators/base.py
Labels: internal

#8500 Implementing insurance deductibles at asset level
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/multi_risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_risk/case_master/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance_4/contents_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves-policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggrisk-policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggrisk.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/reinsurance-avg_portfolio.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/job.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_4/nonstructural_vulnerability_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/reinsurance1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/source_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_4/structural_vulnerability_model.xml
  openquake/risklib/asset.py
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
Labels: enhancement

#8508 Stored source_data information in full_lt
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/logictree/case_13/expected/source_branches.org
Labels: enhancement

#8511 Docs ideductible
  doc/adv-manual/event_based.rst
  openquake/qa_tests_data/event_based_risk/reinsurance_3/policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/policy.csv
Labels: documentation

#8512 Replaced hard-coded limit in the MRD postprocessor
  debian/changelog
  openquake/engine/postproc/compute_mrd.py
Labels: enhancement

#8513 Discriminate tricky source IDs earlier
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
Labels: internal

#8514 Changed the _poes storage and rlzs_by_g
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/classical/case_12/expected/disagg_by_grp.rst
  openquake/qa_tests_data/logictree/case_01/job.ini
  openquake/qa_tests_data/logictree/case_45/expected/hazard_curve-mean-MMI.csv
Labels: enhancement, internal

#8517 Fix a leftover variable name change
  openquake/commonlib/readinput.py
Labels: bug

#8516 Moving around logic tree tests and docs
  doc/adv-manual/event_based.rst
  doc/adv-manual/logic_trees.rst
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/qa_tests_data/logictree/case_02/__init__.py
  openquake/qa_tests_data/logictree/case_02/expected/hcurve.csv
  openquake/qa_tests_data/logictree/case_02/expected_hazard_curves.xml
  openquake/qa_tests_data/logictree/case_02/gsim_logic_tree.xml
  openquake/qa_tests_data/logictree/case_02/job.ini
  openquake/qa_tests_data/logictree/case_02/lookup_asc.hdf5
  openquake/qa_tests_data/logictree/case_02/lookup_sta.hdf5
  openquake/qa_tests_data/logictree/case_02/source_model.xml
  openquake/qa_tests_data/logictree/case_02/source_model_logic_tree.xml
  openquake/qa_tests_data/logictree/case_14/AS2008_expected_curves.dat
  openquake/qa_tests_data/logictree/case_14/CB2008_expected_curves.dat
  openquake/qa_tests_data/logictree/case_14/__init__.py
  openquake/qa_tests_data/logictree/case_14/expected/hazard_curve-rlz-000_PGA.csv
  openquake/qa_tests_data/logictree/case_14/gmpe_logic_tree.xml
  openquake/qa_tests_data/logictree/case_14/job.ini
  openquake/qa_tests_data/logictree/case_14/qa_sites.csv
  openquake/qa_tests_data/logictree/case_14/simple_fault.xml
  openquake/qa_tests_data/logictree/case_14/source_model_logic_tree.xml
  openquake/qa_tests_data/logictree/case_30/__init__.py
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/logictree/case_30/expected/hcurve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hcurve-SA(1.0).csv
  openquake/qa_tests_data/logictree/case_30/gmmLT_3.xml
  openquake/qa_tests_data/logictree/case_30/job.ini
  openquake/qa_tests_data/logictree/case_30/ssm/shallow/gridded_seismicity_source_4.xml
  openquake/qa_tests_data/logictree/case_30/ssm/shallow/int_kt.xml
  openquake/qa_tests_data/logictree/case_30/ssm/shallow/shallow_faults.xml
  openquake/qa_tests_data/logictree/case_30/ssmLT.xml
  openquake/qa_tests_data/logictree/case_52/__init__.py
  openquake/qa_tests_data/logictree/case_52/gsim_logic_tree.xml
  openquake/qa_tests_data/logictree/case_52/job.ini
  openquake/qa_tests_data/logictree/case_52/source_model.xml
  openquake/qa_tests_data/logictree/case_52/source_model_logic_tree.xml
Labels: documentation

#8518 Improved scenario/test_case_21
  openquake/qa_tests_data/scenario/case_21/stationlist_seismic.csv
Labels: internal

#8520 Moved case_39 in qa_tests_data/logictree
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/logictree/case_39/__init__.py
  openquake/qa_tests_data/logictree/case_39/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/logictree/case_39/expected/hazard_curve-mean-SA(0.1).csv
  openquake/qa_tests_data/logictree/case_39/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/logictree/case_39/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/logictree/case_39/expected/hazard_map-mean.csv
  openquake/qa_tests_data/logictree/case_39/expected/realizations.org
  openquake/qa_tests_data/logictree/case_39/gmmLT.xml
  openquake/qa_tests_data/logictree/case_39/job.ini
  openquake/qa_tests_data/logictree/case_39/ssm/Area_65m/area_source_gp_HLE.xml
  openquake/qa_tests_data/logictree/case_39/ssm/Area_65p/HLEKAOSFL_area.xml
  openquake/qa_tests_data/logictree/case_39/ssm/gridded_seismicity/point.xml
  openquake/qa_tests_data/logictree/case_39/ssmLT.xml
Labels: internal

#8521 Fixed KeyError in calculations using the EasternCan15Mid with PGA
  debian/changelog
  openquake/hazardlib/gsim/can15/eastern.py
Labels: bug, backport

#8519 Finished work on single source disaggregation
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: enhancement

#8522 Better logging for AELO
  openquake/commonlib/logs.py
Labels: enhancement

#8523 Parallelized disaggregation by source
  openquake/calculators/classical.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: performance

#8524 Fixed IndexError in disagg.by_source
  openquake/commands/onsite.py
  openquake/engine/aelo.py
  openquake/hazardlib/calc/disagg.py
Labels: bug

#8526 Better logging for mosaic models
  openquake/commonlib/logs.py
  openquake/commonlib/mosaic.py
Labels: enhancement, internal

#8527 Fixed the error message for wrong weights in the gsim logic tree file
  debian/changelog
  openquake/hazardlib/gsim_lt.py
Labels: bug

#8528 Fixed the source ID generation for CollapsedPointSources
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: bug

#8529 Fixed bug with iml_disagg
  openquake/calculators/disaggregation.py
  openquake/qa_tests_data/disagg/case_10/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_10/job.ini
Labels: bug

#8530 Moved case_19 in qa_tests_data/logictree
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/logictree/README.md
  openquake/qa_tests_data/logictree/case_19/__init__.py
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/logictree/case_19/gmpe_logic_tree.xml
  openquake/qa_tests_data/logictree/case_19/job.ini
  openquake/qa_tests_data/logictree/case_19/simple_area_source_model.xml
  openquake/qa_tests_data/logictree/case_19/simple_source_model_logic_tree.xml
Labels: internal

#8531 Enabling the sanity check on the rates
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/logictree_test.py
  openquake/engine/aelo.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/logictree/case_06/job.ini
  openquake/qa_tests_data/logictree/case_07/job.ini
  openquake/qa_tests_data/logictree/case_07/sampling.ini
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_SA(0.1).csv
  openquake/qa_tests_data/logictree/case_19/expected/hazard_curve-mean_SA(0.15).csv
  openquake/qa_tests_data/logictree/case_19/job.ini
Labels: internal

#8534 Fixed hanging of the AUS model
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source_reader.py
Labels: bug

#8536 Fixed AUS hanging again
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
Labels: bug, performance

#8539 Fix a broken import
  utils/strip_dupl_sites
Labels: bug

#8538 Changed the ArrayWrapper storage to a Datagroup
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/tests/calc/data/mrd/calc_934.hdf5
Labels: internal

#8541 Storing `disagg_source` results
  openquake/calculators/classical.py
  openquake/engine/postproc/disagg_by_rel_sources.py
Labels: enhancement

#8543 Fixed conditional spectrum with multiple sites
  debian/changelog
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/hazardlib/calc/cond_spectra.py
  openquake/qa_tests_data/conditional_spectrum/case_2/__init__.py
  openquake/qa_tests_data/conditional_spectrum/case_2/expected/cs-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_2/expected/cs-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_2/gmpe_logic_tree.xml
  openquake/qa_tests_data/conditional_spectrum/case_2/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_2/source_model1.xml
  openquake/qa_tests_data/conditional_spectrum/case_2/source_model2.xml
  openquake/qa_tests_data/conditional_spectrum/case_2/source_model_logic_tree.xml
Labels: bug, backport

#8544 Improved case_28 and fixed the full_lt view
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim_lt.py
  openquake/qa_tests_data/logictree/README.md
  openquake/qa_tests_data/logictree/case_28/expected/realizations.org
Labels: internal

#8545 Another fix on the conditional spectrum
  openquake/hazardlib/calc/cond_spectra.py
Labels: bug

#8546 Parallelized conditional spectrum
  debian/changelog
  openquake/calculators/conditional_spectrum.py
Labels: performance, enhancement

#8547 Rejecting duplicated mutex sources
  openquake/calculators/classical.py
  openquake/hazardlib/source_reader.py
Labels: enhancement

#8550 Reduced a bit the noise in case of critical exceptions
  openquake/calculators/base.py
  openquake/commonlib/logs.py
Labels: enhancement

#8551 Added two nontrivial logic tree tests
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/logictree/case_05/__init__.py
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_05/gmpe_logic_tree.xml
  openquake/qa_tests_data/logictree/case_05/job.ini
  openquake/qa_tests_data/logictree/case_05/job_bis.ini
  openquake/qa_tests_data/logictree/case_05/source_model.xml
  openquake/qa_tests_data/logictree/case_05/source_model_logic_tree.xml
Labels: internal

#8556 Avoid printing the tracebacks twice
  debian/changelog
  openquake/commands/__main__.py
  openquake/commonlib/logs.py
Labels: internal

#8557 Changed the source seed generating method
  debian/changelog
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_6/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_6/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
Labels: enhancement

#8555 Added a `mean_rates` calculator in hazardlib
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean-bis.csv
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_05/job.ini
  openquake/qa_tests_data/logictree/case_05/job_bis.ini
Labels: internal

#8559 Changed disagg_source to use full enumeration
  openquake/calculators/classical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean-bis.csv
  openquake/qa_tests_data/logictree/case_05/job_bis.ini
Labels: internal

#8560 Added check on the mean rates in logictree_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/qa_tests_data/logictree/case_07/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/logictree/case_07/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/logictree/case_07/expected/hazard_curve-rlz-001-PGA.csv
  openquake/qa_tests_data/logictree/case_07/sampling.ini
Labels: internal

#8553 Subtract the insurance deductible correctly when total_losses is missing
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/qa_tests_data/event_based_risk/reinsurance_5/__init__.py
  openquake/qa_tests_data/event_based_risk/reinsurance_5/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_5/exposure_model_1.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_5/exposure_model_1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/exposure_model_2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_5/exposure_model_2.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/job_1.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_5/job_2.ini
  openquake/qa_tests_data/event_based_risk/reinsurance_5/policy_1.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_5/policy_2.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_5/reinsurance_1.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/reinsurance_2.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/source_model.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/reinsurance_5/structural_vulnerability_model.xml
  openquake/risklib/reinsurance.py
  openquake/risklib/scientific.py
Labels: bug

#8562 adding icm to nshmp2014
  openquake/hazardlib/gsim/nshmp_2014.py
Labels: bug

#8563 Changed default to multi=True in create_jobs
  openquake/commands/run.py
  openquake/commands/tests/commands_test.py
  openquake/engine/engine.py
  openquake/engine/multirun.py
Labels: internal

#8564 Extended `oq runsite` to accept a file of sites
  openquake/commands/runsite.py
  openquake/commonlib/mosaic.py
Labels: enhancement, internal

#8565 Use `get_params_from` also in `aelo_run` Django view
  openquake/server/views.py
Labels: internal

#8566 Fixed command `oq reduce_smlt`
  debian/changelog
  openquake/commands/reduce_smlt.py
  openquake/hazardlib/logictree.py
Labels: internal

#8567 Added test akin to the KOR model
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/logictree/README.md
  openquake/qa_tests_data/logictree/case_04/__init__.py
  openquake/qa_tests_data/logictree/case_04/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_04/gmmLT.xml
  openquake/qa_tests_data/logictree/case_04/job.ini
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_1/KOR_c1_M1_1.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_2/KOR_c1_M1_2.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_3/KOR_c1_M1_3.xml
  openquake/qa_tests_data/logictree/case_04/ssmLT.xml
Labels: internal

#8568 Added an exporter for mean_disagg_bysrc
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/qa_tests_data/logictree/case_05/expected/mean_disagg_bysrc.csv
Labels: enhancement, outputs

#8569 Using the colon convention in the breaking tests
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_1/KOR_c1_M1_1.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_2/KOR_c1_M1_2.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_3/KOR_c1_M1_3.xml
  openquake/qa_tests_data/logictree/case_79/ssm01-asc.xml
  openquake/qa_tests_data/logictree/case_79/ssm01-interface.xml
  openquake/qa_tests_data/logictree/case_79/ssm02-interface.xml
Labels: internal

#8572 AELO project: collecting together false duplicates
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_1/KOR_c1_M1_1.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_2/KOR_c1_M1_2.xml
  openquake/qa_tests_data/logictree/case_04/ssm/areas/KOR_c1_M1_3/KOR_c1_M1_3.xml
Labels: internal

#8577 Managed the case of empty branches in the source model logic tree
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-001-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-002-PGA.csv
Labels: performance

#8578 Renamed disagg_by_src -> rates_by_src
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/classical/case_82/expected/disagg_by_src.csv
  openquake/qa_tests_data/classical/case_82/expected/rates_by_src.csv
  openquake/qa_tests_data/classical/case_84/expected/rbs.csv
  openquake/server/db/actions.py
Labels: outputs

#8574 Improve `oq runsites` command
  openquake/commands/runsite.py
Labels: enhancement

#8579 Fixed extract_rates_by_src
  openquake/calculators/extract.py
  openquake/calculators/preclassical.py
Labels: bug

#8581 Fix management of max_sites_per_model
  openquake/commands/runsite.py
Labels: bug

#8584 Enhanced `oq sample` to sample MultiPointSources too
  openquake/commands/sample.py
Labels: enhancement, inputs

#8583 Fixed reduction of the logic tree for NAF
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/logictree/case_12/__init__.py
  openquake/qa_tests_data/logictree/case_12/expected/mean_rates.csv
  openquake/qa_tests_data/logictree/case_12/gmmLT.xml
  openquake/qa_tests_data/logictree/case_12/job.ini
  openquake/qa_tests_data/logictree/case_12/ssm/GridMultiSources_C.xml
  openquake/qa_tests_data/logictree/case_12/ssm/GridMultiSources_C_L50_BG.xml
  openquake/qa_tests_data/logictree/case_12/ssmLT.xml
Labels: bug

#8585 Added class `compute_mrd.Input`
  openquake/engine/postproc/compute_mrd.py
Labels: internal

#8588 Add the possibility to execute oq runsite only picking or excluding a subset of specific siteids or models
  openquake/commands/runsite.py
Labels: enhancement

#8590 Initial work on postprocessing
  openquake/calculators/postproc/__init__.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/postproc/data/calc_001.hdf5
  openquake/calculators/postproc/data/mrd.toml
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/postproc/postproc_test.py
  openquake/calculators/tests/postproc_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/postproc/rupture_histogram.py
  openquake/hazardlib/tests/calc/data/mrd/calc_934.hdf5
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/qa_tests_data/postproc/case_mrd/__init__.py
  openquake/qa_tests_data/postproc/case_mrd/gmmLT.xml
  openquake/qa_tests_data/postproc/case_mrd/job.ini
  openquake/qa_tests_data/postproc/case_mrd/sites.csv
  openquake/qa_tests_data/postproc/case_mrd/sscLT.xml
  openquake/qa_tests_data/postproc/case_mrd/ssm/ssm_uh_set1_mmax1/src_TSZ074.xml
Labels: enhancement

#8586 Removed dataset `trt_smrs`
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/postproc_test.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
Labels: internal

#8592 Update changelog
  debian/changelog
Labels: documentation

#8593 AELO project: fixed reduction of logic tree for EUR and ARB
  openquake/hazardlib/logictree.py
Labels: bug

#8594 Fixed compute_mrd
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/postproc/compute_mrd.py
Labels: bug

#8595 Improved test case_12
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/base.py
  openquake/qa_tests_data/logictree/case_12/expected/realizations.org
  openquake/qa_tests_data/logictree/case_12/job_bis.ini
  openquake/qa_tests_data/logictree/case_12/ssm/GridMultiSources_C_L50_BG.xml
Labels: internal

#8597 Honored `minimum_magnitude` for MultiFaultSources
  debian/changelog
  doc/adv-manual/general.rst
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/qa_tests_data/classical/case_65/expected/disagg_by_mag_true.org
  openquake/qa_tests_data/classical/case_65/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_65/job.ini
Labels: bug, documentation, backport

#8598 Fixed oq zip
  debian/changelog
  openquake/hazardlib/logictree.py
Labels: bug, backport

#8599 adding intensity measure component to nga east
  openquake/hazardlib/gsim/nga_east.py
Labels: bug
