Repository gem/oq-engine, pull requests merged in 2023-11, with the labels that each got.

#9174 Small refactoring for insurances losses
  openquake/calculators/event_based_risk.py
  openquake/calculators/views.py
Labels: internal

#9176 Improve style of password reset form
  openquake/server/templates/password_reset_form.html
Labels: enhancement

#9177 Give a clearer error message when attempting to create a new normal user assigning a username that is already taken
  openquake/server/management/commands/createnormaluser.py
Labels: enhancement

#9179 Fixed insured losses larger than ground losses
  debian/changelog
  openquake/risklib/scientific.py
  openquake/sep/classes.py
Labels: bug

#9182 Introduced a cached_property for `sec_imts`
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/commonlib/oqvalidation.py
Labels: performance, internal

#9181 Importing/exporting gmfs in HDF5
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/hazardlib/tests/calc/expected/mrd/job.ini
Labels: outputs

#9186 Customize messages in password reset workflows
  openquake/server/management/commands/createnormaluser.py
  openquake/server/templates/registration/normal_user_creation_email.txt
  openquake/server/templates/registration/normal_user_creation_email_aelo.txt
  openquake/server/templates/registration/normal_user_creation_email_subject.txt
  openquake/server/templates/registration/normal_user_creation_email_subject_aelo.txt
  openquake/server/templates/registration/password_reset_done.html
  openquake/server/templates/registration/password_reset_email.txt
  openquake/server/templates/registration/password_reset_email_aelo.txt
  openquake/server/templates/registration/password_reset_form.html
  openquake/server/templates/registration/password_reset_sent.html
  openquake/server/templates/registration/password_reset_subject.txt
  openquake/server/templates/registration/password_reset_subject_aelo.txt
  openquake/server/templates/registration/reset_password.html
  openquake/server/urls.py
Labels: enhancement

#9192 Fixed the HDF5 exporter
  openquake/calculators/base.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/qa_tests_data/gmf_ebrisk/case_1/gmf-data.hdf5
Labels: bug

#9193 Fixed extract relevant_gmfs
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
Labels: bug

#9194 Raised the limit on number of assets and realizations
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#9195 Fix some docstrings and pep8 in AELO code
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
Labels: enhancement

#9196 Add measurement units to ASCE variable only if possible
  openquake/server/views.py
Labels: bug

#9191 Doc23 basaryucell
  doc23/api-reference/index.rst
  doc23/conf.py
  doc23/contributing/how-to-add-a-new-gsim.rst
  doc23/contributing/implementing-new-gsim.md
  doc23/contributing/index.rst
  doc23/getting-started/demos-and-tutorials.rst
  doc23/getting-started/demos-tutorials/index.rst
  doc23/getting-started/index.rst
  doc23/getting-started/installation-instructions.rst
  doc23/getting-started/installation-instructions/tools.md
  doc23/getting-started/installation-instructions/ubuntu.md
  doc23/getting-started/installation-instructions/windows.md
  doc23/index.rst
  doc23/release-notes/index.rst
  doc23/release-notes/whats-new-1.5.md
  doc23/release-notes/whats-new-1.6.md
  doc23/release-notes/whats-new-1.7.md
  doc23/release-notes/whats-new-1.8.md
  doc23/release-notes/whats-new-2.0.md
  doc23/release-notes/whats-new-2.2.md
  doc23/release-notes/whats-new-2.3.md
  doc23/release-notes/whats-new-2.4.md
  doc23/release-notes/whats-new-3.3.md
  doc23/underlying-science/index.rst
  doc23/user-guide/configuration-file/risk-calculations.rst
  doc23/user-guide/extras/index.rst
  doc23/user-guide/index.rst
  doc23/user-guide/inputs/liquefaction.rst
  doc23/user-guide/outputs/classical-psha-outputs.rst
  doc23/user-guide/outputs/scenario-analysis-outputs.rst
Labels: documentation

#9203 Refactored risk from relevant GMFs
  openquake/calculators/aftershock.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/loss_curves.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/risklib/scientific.py
Labels: enhancement

#9204 Removed unused imports
  openquake/sep/calculators.py
Labels: internal

#9205 Fixed average losses when reading from GMFs
  openquake/calculators/event_based_risk.py
  openquake/calculators/post_risk.py
Labels: bug

#9206 Disabling the DbServer for single user installations
  .github/workflows/engine_pr_test.yml
  install.py
  openquake/commands/dbserver.py
  openquake/commonlib/logs.py
  openquake/engine/openquake.cfg
  openquake/server/tests/test_aelo_mode.py
  openquake/server/tests/test_public_mode.py
  openquake/server/tests/test_read_only_mode.py
Labels: enhancement

#9208 Make it possible to make AELO plots using the `oq plot` command
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/commands/plot.py
Labels: enhancement

#9210 Removing ugly plot code
  debian/changelog
  openquake/calculators/postproc/aelo_plots.py
Labels: internal

#9211 Do not refresh the outputs page automatically
  openquake/server/static/js/engine_get_outputs.js
Labels: enhancement

#9199 Add USE_REVERSE_PROXY variable to local settings and set request server port depending from it
  doc/installing/server.md
  openquake/server/local_settings.py.aelo
  openquake/server/management/commands/createnormaluser.py
  openquake/server/settings.py
Labels: bug

#9207 Set upper limit for the Goda & Atkinson cross-correlation coeffient
  debian/changelog
  openquake/hazardlib/cross_correlation.py
Labels: bug

#9215 Minor simplification in read_csv
  openquake/baselib/hdf5.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/event_based_risk/recompute/ruptures.csv
  openquake/qa_tests_data/scenario/case_13/ruptures.csv
  openquake/qa_tests_data/scenario/case_20/ruptures.csv
  openquake/risklib/asset.py
Labels: internal

#9212 Update Dockerfile file for dev and stable docker
  doc/docker/advanced.md
  doc/docker/single.md
  docker/Dockerfile.dev
  docker/Dockerfile.engine
  openquake/server/dbserver.py
Labels: internal

#9138 recipe for Singularity container
  docker/Singularity.def
  docker/scripts/oq-db_start.sh
  docker/scripts/oq-start.sh
Labels: documentation

#9217 Removed revmap
  openquake/calculators/tests/scenario_test.py
  openquake/risklib/asset.py
Labels: internal

#9142 Check duplicate fields
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_18/__init__.py
  openquake/qa_tests_data/scenario_damage/case_18/consequence_displaced.csv
  openquake/qa_tests_data/scenario_damage/case_18/consequence_fatalities.csv
  openquake/qa_tests_data/scenario_damage/case_18/exposure.csv
  openquake/qa_tests_data/scenario_damage/case_18/exposure_model.xml
  openquake/qa_tests_data/scenario_damage/case_18/fragility.xml
  openquake/qa_tests_data/scenario_damage/case_18/gmf.csv
  openquake/qa_tests_data/scenario_damage/case_18/job.ini
  openquake/qa_tests_data/scenario_damage/case_18/sitemesh.csv
Labels: enhancement

#9218 Allowing multiple oq fields in the exposure fieldmap
  debian/changelog
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario_damage/case_18/expected/aggrisk.csv
  openquake/risklib/asset.py
Labels: enhancement, inputs

#9219 Added another test with --hc
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based/case_31/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_31/job_rup.ini
  openquake/qa_tests_data/event_based/case_31/sites.csv
Labels: internal

#9222 Do not raise an error for zero hazard in case of a single site
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/postproc/compute_rtgm.py
Labels: enhancement

#9223 Fixed wrong `mean_rates_by_src` in presence of the colon convention
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/logictree/case_12/job.ini
Labels: bug

#9221 AELO: add a warning to the outputs page if ASCE outputs are missing since the hazard is too low
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/views.py
Labels: enhancement

#9225 Update CONTRIBUTORS.txt
  CONTRIBUTORS.txt
Labels: documentation

#9226 Create the database directory automatically
  openquake/commands/dbserver.py
  openquake/commonlib/dbapi.py
Labels: bug, internal

#9230 The TodorovicSilva test was not running
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_27/expected/avg_gmf.csv
Labels: bug, internal

#9231 Added rupture_dict parameter
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/scenario/case_28/__init__.py
  openquake/qa_tests_data/scenario/case_28/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_28/job.ini
Labels: enhancement, inputs

#9190 Use Fiona wheel that include also GDAL
  .github/workflows/macos_m1_install.yml
  .github/workflows/ubuntu_install.yml
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/sep/utils.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
Labels: dependencies

#9233 Change tolerances in aelo_test.py test_CCA
  openquake/engine/tests/aelo_test.py
Labels: internal

#9247 Fixed `oq sample`
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/commands/sample.py
Labels: internal

#9232 This fixes a bug in the calculation of Rjb for gridded surfaces
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/tests/geo/surface/data/fault_n_bora.csv
  openquake/hazardlib/tests/geo/surface/gridded_test.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: bug, dependencies

#9249 Added a script `utils/build_global_exposure`
  openquake/baselib/general.py
  openquake/baselib/hdf5.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
  utils/build_global_exposure
Labels: internal

#9235 epistemic sigma for Abrahamson2014
  openquake/hazardlib/gsim/abrahamson_2014.py
Labels: enhancement

#9240 NZ NSHM 2022 modification of Parker2020
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_INTERFACE_GLO_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_INTERFACE_GLO_GNS_TOTAL_STDDEV_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_INTERFACE_GLO_GNS_TOTAL_STDDEV_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_SLAB_GLO_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_SLAB_GLO_GNS_TOTAL_STDDEV_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/NZNSH2022_PARKER20/PARKER2021_SLAB_GLO_GNS_TOTAL_STDDEV_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/nz22/nznshm2022_parker2020_test.py
Labels: enhancement

#9244 Atkinson2022 gsim
  doc/sphinx/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/nz22/Atkinson22_coeffs_mod_v8b_sanjay_v2.csv
  openquake/hazardlib/gsim/nz22/__init__.py
  openquake/hazardlib/gsim/nz22/atkinson_2022.py
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/.~lock.ATKINSON22_CRUST_CENTRAL_MEAN.csv#
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_CRUST_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_CRUST_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_INTERFACE_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_INTERFACE_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_SLAB_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON2022_SLAB_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_CRUST_CENTRAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_CRUST_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_CRUST_LOWER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_CRUST_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_CRUST_UPPER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_INTER_CENTRAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_INTER_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_INTER_LOWER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_INTER_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_INTER_UPPER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_SLAB_CENTRAL_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_SLAB_LOWER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_SLAB_LOWER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_SLAB_UPPER_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ATKINSON2022/ATKINSON22_SLAB_UPPER_MEAN_EPI_SCALE_CORRECTED.csv
  openquake/hazardlib/tests/gsim/nz22/atkinson_2022_test.py
Labels: enhancement

#9242 NZ NSHM 2022 modification of Kuehn2020
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INSLAB_NZL_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INSLAB_NZL_GNS_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INSLAB_NZL_GNS_TOTAL_STDDEV_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INSLAB_NZL_GNS_TOTAL_STDDEV_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INTERFACE_NZL_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INTERFACE_NZL_GNS_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INTERFACE_NZL_GNS_TOTAL_STDDEV_MODIFIED_SIGMA.csv
  openquake/hazardlib/tests/gsim/data/nz22/kuehn2020/KUEHN20_INTERFACE_NZL_GNS_TOTAL_STDDEV_ORIGINAL_SIGMA.csv
  openquake/hazardlib/tests/gsim/nz22/nz_nshm2022_kuehn_2020_test.py
Labels: enhancement

#9243 Stafford2022 gsim
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_MEAN_CENTRAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_MEAN_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_MEAN_LOWER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_MEAN_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_MEAN_UPPER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_SIGMA_CENTRAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_SIGMA_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_NM_SIGMA_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_MEAN_CENTERAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_MEAN_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_MEAN_LOWER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_MEAN_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_MEAN_UPPER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_SIGMA_CENTRAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_SIGMA_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_REV_SIGMA_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_MEAN_CENTRAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_MEAN_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_MEAN_LOWER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_MEAN_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_MEAN_UPPER_v2_EPI_SCALED.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_SIGMA_CENTRAL_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_SIGMA_LOWER_v2.csv
  openquake/hazardlib/tests/gsim/data/nz22/STAFFORD2022/STAFFORD_NZ_SS_SIGMA_UPPER_v2.csv
  openquake/hazardlib/tests/gsim/nz22/stafford_2022_test.py
Labels: enhancement

#9241 NZ NSHM 2022 modification of AbrahamsonGulerce2020
  openquake/hazardlib/gsim/nz22/nz_nshm2022_abrahamson_gulerce_2020.py
  openquake/hazardlib/tests/gsim/data/nz22/ag2020/AG20_INTERFACE_GLO_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ag2020/AG20_INTERFACE_GLO_GNS_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/nz22/ag2020/AG20_SLAB_GLO_GNS_MEAN.csv
  openquake/hazardlib/tests/gsim/data/nz22/ag2020/AG20_SLAB_GLO_GNS_TOTAL_STDDEV.csv
  openquake/hazardlib/tests/gsim/nz22/nz_nshm2022_abrahamson_gulerce_2020_test.py
Labels: enhancement

#9236 epistemic sigma for Boore2014
  openquake/hazardlib/gsim/boore_2014.py
Labels: enhancement

#9237 epistemic sigma for Bradley2013
  openquake/hazardlib/gsim/bradley_2013.py
Labels: enhancement

#9238 epistemic sigma for CampbellBozorgnia2014
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
Labels: enhancement

#9239 epistemic sigma for ChiouYoungs2014
  openquake/hazardlib/gsim/chiou_youngs_2014.py
Labels: enhancement

#9252 Improved `build_global_exposure`
  openquake/baselib/hdf5.py
  utils/build_global_exposure
Labels: internal

#9253 Improved `build_global_exposure`/2
  utils/build_global_exposure
Labels: performance, internal

#9254 Improved build_global_exposure/3
  utils/build_global_exposure
Labels: performance, internal

#9255 Improved build_global_exposure/4
  openquake/baselib/hdf5.py
  utils/build_global_exposure
Labels: performance, internal

#9251 Fix formatting in universal.md
  doc/installing/universal.md
Labels: documentation

#9256 Improved build_global_exposure/5
  utils/build_global_exposure
Labels: bug, performance, internal

#9259 Added function `readinput.get_site_model_around`
  openquake/calculators/tests/mosaic_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/mosaic/case_01/__init__.py
  openquake/qa_tests_data/mosaic/case_01/expected/avg_gmf.csv
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/qa_tests_data/mosaic/scenarios/sitecol.hdf5
  openquake/qa_tests_data/mosaic/site_model.hdf5
Labels: enhancement, inputs

#9228 AELO: changes requested in the editorial_to-do_list
  openquake/calculators/classical.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/classical/case_27/expected/mean_rates_by_src.csv
  openquake/qa_tests_data/classical/case_82/expected/mean_rates_by_src.csv
  openquake/qa_tests_data/classical/case_84/expected/rbs.csv
  openquake/qa_tests_data/logictree/case_05/expected/mean_disagg_by_src.csv
  openquake/server/static/js/engine_get_outputs.js
  openquake/server/templates/engine/get_outputs.html
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/views.py
Labels: enhancement

#9261 Removed the obsolete `by_country` hack
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/risklib/asset.py
Labels: inputs

#9262 Fixed the installer broken by https://github.com/gem/oq-engine/pull/9260/
  install.py
Labels: critical
