Repository gem/oq-engine, pull requests merged in 2023-06, with the labels that each got.

#8812 Fix documentation
  doc/adv-manual/Makefile
  doc/adv-manual/conf.py
  doc/adv-manual/secondary_perils.rst.bak
  doc/manual/Makefile
  doc/manual/conf.py
  doc/manual/hazard.rst
  doc/manual/risk.rst
  doc/samples/README.md
  doc/samples/dot_ddown_adv.json.sample
  doc/samples/dot_ddown_man.json.sample
  doc/sphinx/Makefile
  doc/sphinx/openquake.hazardlib.gsim.rst
  doc/sphinx/openquake.hazardlib.rst
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/wong2022.py
  openquake/hazardlib/gsim/zhang_zhao_2005.py
Labels: documentation

#8827 Added test sensitive to the sampling bug
  openquake/calculators/tests/logictree_test.py
  openquake/qa_tests_data/logictree/case_18/__init__.py
  openquake/qa_tests_data/logictree/case_18/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/logictree/case_18/gmpe_logic_tree.xml
  openquake/qa_tests_data/logictree/case_18/job.ini
  openquake/qa_tests_data/logictree/case_18/source_model.xml
  openquake/qa_tests_data/logictree/case_18/source_model_logic_tree.xml
Labels: bug

#8828 Fixed the sampling bug
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/probability_map.py
  openquake/qa_tests_data/logictree/case_18/expected/hazard_curve-mean.csv
Labels: bug, critical

#8829 Fixed the rupture exporter in presence of GMPETables
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_18/expected/gmf.csv
  openquake/qa_tests_data/event_based/case_30/Wcrust_low_rhypo.hdf5
  openquake/qa_tests_data/event_based/case_30/__init__.py
  openquake/qa_tests_data/event_based/case_30/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_30/job.ini
  openquake/qa_tests_data/event_based/case_30/nbc_asc_logic_tree.xml
  openquake/qa_tests_data/event_based/case_30/point_source.xml
  openquake/qa_tests_data/event_based/case_30/source_model_logic_tree.xml
Labels: bug, outputs, backport

#8831 Renamed rlzs_by_g -> trt_smrs
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/calc/cond_spectra.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/probability_map.py
Labels: internal

#8830 Fixing bug in code that creates profiles from simple fault
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/qa_tests_data/classical/case_61/expected/hcurve-mean.csv
Labels: bug

#8834 Not storing trt_rlzs anymore
  openquake/calculators/classical.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
Labels: internal

#8832 Introduced new loss type `residents`
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Com_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Ind_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Res_Singapore.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Singapore.xml
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_8/expected/aggrisk-OCCUPANCY.csv
  openquake/qa_tests_data/event_based_risk/case_8/job.ini
  openquake/qa_tests_data/event_based_risk/case_8/structural_vulnerability.xml
  openquake/qa_tests_data/event_based_risk/case_8/taxonomy_map.csv
  openquake/qa_tests_data/event_based_risk/case_8/vulnerability_fatalities.xml
  openquake/qa_tests_data/event_based_risk/case_8/vulnerability_residents.xml
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement, outputs, inputs

#8836 Added prefix to rupture_idxs
  openquake/hazardlib/sourcewriter.py
Labels: enhancement, inputs

#8835 Refactored a bit `get_conditioned_mean_and_covariance`
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#8837 Refactored get_conditioned_mean_and_covariance more
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: internal

#8839 Fixed clusterize function and plot
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: internal

#8841 Extended sensitivity_analysis to file parameters
  debian/changelog
  doc/adv-manual/event_based.rst
  openquake/commonlib/readinput.py
  openquake/engine/engine.py
Labels: enhancement

#8778 Fixes Errors in ESHM20 GMM Aliases and Minor Bug in Lanzano et al. (2019)
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/tests/gsim/eshm20_aliases_test.py
Labels: bug, backport

#8842 Added test for Lanzano2019 for vs30>1500
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/qa_tests_data/classical/case_02/__init__.py
  openquake/qa_tests_data/classical/case_02/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_02/job.ini
  openquake/qa_tests_data/classical/case_02/source_model.xml
  openquake/qa_tests_data/classical/case_02/source_model_logic_tree.xml
Labels: bug

#8843 Added test for failing conditioned GMFs
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_24/__init__.py
  openquake/qa_tests_data/scenario/case_24/earthquake_rupture_model_USGS.xml
  openquake/qa_tests_data/scenario/case_24/job.ini
  openquake/qa_tests_data/scenario/case_24/site_model.csv
  openquake/qa_tests_data/scenario/case_24/site_model_stations.csv
  openquake/qa_tests_data/scenario/case_24/stationlist_seismic.csv
Labels: internal

#8844 Rounded lon-lat (and refactoring the station_data)
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/classical/case_40/expected/hazard_curve-mean-PGV.csv
  openquake/qa_tests_data/classical/case_40/expected/hazard_map-mean.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(0.2).csv
  openquake/qa_tests_data/classical/case_51/expected/hcurves-SA(2.0).csv
  openquake/qa_tests_data/classical/case_51/expected/uhs.csv
  openquake/qa_tests_data/event_based/case_22/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_28/expected/gmf-data.csv
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses.txt
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
Labels: internal

#8845 Solved usual HDF5 bug
  openquake/calculators/post_risk.py
  openquake/commonlib/calc.py
Labels: bug, internal

#8846 Ugly workaround for area unit of measure
  openquake/risklib/asset.py
Labels: bug

#8848 Fixed bug in `get_ry0_distance` breaking conditioned GMFs
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/qa_tests_data/scenario/case_24/expected/avg_gmf.csv
Labels: bug, backport

#8850 Added context manager perf_stat
  openquake/baselib/performance.py
Labels: performance, internal

#8851 Django 3.2.19
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#8852 Saving memory in store_poes
  openquake/calculators/classical.py
Labels: performance

#8857 GMFs too small to produce losses now give a warning rather than an error
  debian/changelog
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/qa_tests_data/gmf_ebrisk/case_5/__init__.py
  openquake/qa_tests_data/gmf_ebrisk/case_5/exposure_model.xml
  openquake/qa_tests_data/gmf_ebrisk/case_5/gmf_scenario.csv
  openquake/qa_tests_data/gmf_ebrisk/case_5/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_5/sites.csv
  openquake/qa_tests_data/gmf_ebrisk/case_5/vulnerability.xml
Labels: bug, backport

#8858 Removed section ordering in in the multiFaultSource reader
  debian/changelog
  openquake/hazardlib/source_reader.py
Labels: bug, backport

#8855 Add a `READ_ONLY` application mode, that disables all engine server editing actions on calculations
  .github/workflows/engine_test.yml
  openquake/server/settings.py
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_read_only_mode.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#8860 Hide the `Continue` button while running the webui in aelo mode
  openquake/server/templates/engine/index.html
Labels: enhancement

#8859 Use the vs30 from the site collection in shakemap2gmfs
  debian/changelog
  openquake/calculators/base.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
Labels: enhancement

#8863 Added test for shakemap2gmfs
  openquake/calculators/tests/scenario_test.py
  openquake/commands/shakemap2gmfs.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/shakemap/maps.py
  openquake/qa_tests_data/scenario/case_25/__init__.py
  openquake/qa_tests_data/scenario/case_25/site_model_uniform_grid_rock.csv
  openquake/qa_tests_data/scenario/case_25/usp0006dv8.npy
Labels: internal

#8864 Fixed risk_imtls
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap/maps.py
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
Labels: bug

#8865 PEP8 fixes
  openquake/hazardlib/tests/calc/_conditioned_gmfs_test_data.py
  openquake/hazardlib/tests/calc/conditioned_gmfs_test.py
Labels: internal

#8866 Computing the GMFs on the sites and not on the stations
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_24/expected/avg_gmf.csv
Labels: outputs

#8867 Fixed a subtle filtering bug in conditioned GMFs
  debian/changelog
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/tests/calc/conditioned_gmfs_test.py
  openquake/qa_tests_data/scenario/case_24/expected/avg_gmf.csv
Labels: bug, backport

#8861 Kuehn model bug fix
  debian/changelog
  openquake/hazardlib/gsim/kuehn_2020.py
Labels: bug

#8870 Fixed another bug with conditioned GMFs
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario/case_26/__init__.py
  openquake/qa_tests_data/scenario/case_26/earthquake_rupture_model_GCMT.xml
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_26/job.ini
  openquake/qa_tests_data/scenario/case_26/site_model_europe.csv
  openquake/qa_tests_data/scenario/case_26/site_model_stations_europe.csv
  openquake/qa_tests_data/scenario/case_26/stationlist_seismic.csv
Labels: bug

#8869 Fixed tau<->phi in LanzanoLuzi2019
  debian/changelog
  openquake/hazardlib/gsim/lanzano_luzi_2019.py
Labels: bug, backport

#8871 Raise an error when the same parameter is set in different sections
  debian/changelog
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/classical_risk/case_master/job.ini
  openquake/qa_tests_data/event_based/case_29/job.ini
  openquake/qa_tests_data/event_based_risk/case_1f/job.ini
  openquake/qa_tests_data/logictree/case_28/job.ini
  openquake/qa_tests_data/scenario_risk/case_3/job.ini
Labels: enhancement

#8874 Fixed `dstore[oqparam].maximum_distance`
  openquake/commonlib/oqvalidation.py
Labels: bug

#8873 Replaced the conditional_spectrum calculator with a postprocessor
  debian/changelog
  doc/adv-manual/classical_PSHA.rst
  doc/sphinx/openquake.calculators.rst
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/postproc/conditional_spectrum.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/tests/calc/data/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_1/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_2/job.ini
Labels: enhancement

#8525 Adding support for the direct VPSHA method
  debian/changelog
  openquake/calculators/postproc/compute_mrd.py
  openquake/hazardlib/calc/mrd.py
Labels: enhancement

#8875 Documented the postprocessing framework
  doc/adv-manual/classical_PSHA.rst
  openquake/calculators/base.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/tests/postproc_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/aelo.py
  openquake/hazardlib/tests/calc/data/job.ini
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/conditional_spectrum/case_1/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_2/job.ini
  openquake/qa_tests_data/logictree/case_01/job.ini
  openquake/qa_tests_data/logictree/case_05/job.ini
  openquake/qa_tests_data/logictree/case_05/job_bis.ini
  openquake/qa_tests_data/logictree/case_06/job.ini
  openquake/qa_tests_data/logictree/case_07/job.ini
  openquake/qa_tests_data/logictree/case_07/sampling.ini
  openquake/qa_tests_data/logictree/case_12/job.ini
  openquake/qa_tests_data/logictree/case_13/job_gmv.ini
  openquake/qa_tests_data/logictree/case_19/job.ini
  openquake/qa_tests_data/postproc/case_mrd/job.ini
Labels: documentation
