Repository gem/oq-engine, pull requests merged in 2023-02, with the labels that each got.

#8361 Whats New for engine 3.16
  doc/whats-new.md
Labels: documentation

#8379 Changed extract_disagg_by_src for use in AELO
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/qa_tests_data/classical/case_20/job_bis.ini
Labels: enhancement

#8381 Optimized the rupture sampling for MultiFaultSources
  debian/changelog
  openquake/hazardlib/source/multi_fault.py
Labels: performance

#8382 Implemented output slowdown
  openquake/baselib/__init__.py
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/commands/engine.py
  openquake/engine/openquake.cfg
Labels: internal

#8383 Simplified a bit parallel.py
  openquake/baselib/general.py
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
Labels: internal

#8376 Adjusting READMEs and doc/installation
  README.md
  debian/docs
  doc/docker/advanced.md
  doc/docker/single.md
  doc/faq-cluster.md
  doc/faq.md
  doc/hardware-suggestions.md
  doc/img/win-installer-1.png
  doc/img/win-installer-2.png
  doc/img/win-installer-3.png
  doc/installing/README.md
  doc/installing/development.md
  doc/installing/docker.md
  doc/installing/fedora-nightly.md
  doc/installing/fedora.md
  doc/installing/linux-generic.md
  doc/installing/rhel.md
  doc/installing/server.md
  doc/installing/tools.md
  doc/installing/ubuntu-nightly.md
  doc/installing/ubuntu.md
  doc/installing/universal.md
  doc/installing/windows.md
  doc/running/server.md
  doc/running/unix.md
  doc/running/windows.md
  doc/testing.md
  doc/upgrading/rhel.md
  doc/upgrading/ubuntu.md
Labels: documentation

#8384 Changed the tiling mechanism to send task outputs incrementally
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
Labels: performance, internal

#8388 Saving memory on the master node
  openquake/calculators/classical.py
  openquake/commonlib/oqvalidation.py
Labels: performance

#8387 upgrade Django to 3.2.17
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#8386 Update README.md
  README.md
Labels: documentation

#8389 Using `combine_probs` in `disagg_by_src`
  openquake/calculators/classical.py
Labels: internal

#8390 Making it possible to extract the individual loss curves per tag combination
  debian/changelog
  demos/risk/EventBasedRisk/job.ini
  demos/risk/EventBasedRisk/job_eb.ini
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
Labels: bug

#8391 Moved the Puebla test from scenario_risk to scenario
  openquake/calculators/tests/scenario_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_21/__init__.py
  openquake/qa_tests_data/scenario/case_21/earthquake_rupture_model_USGS.xml
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_21/job.ini
  openquake/qa_tests_data/scenario/case_21/site_model.csv
  openquake/qa_tests_data/scenario/case_21/site_model_stations.csv
  openquake/qa_tests_data/scenario/case_21/stationlist_seismic.csv
Labels: internal

#8394 Add consequences to composite risk model attrs; include consequences when doing extract_agg_damages
  openquake/calculators/extract.py
  openquake/risklib/riskmodels.py
Labels: bug

#8397 Fix realization repr (stray quote)
  openquake/calculators/extract.py
Labels: bug

#8399 Add documentation for the conditioning of gmfs in scenario calculations
  doc/manual/hazard.rst
  doc/manual/risk.rst
Labels: documentation

#8396 Added a SourceSiteDisaggregator class/1
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/source_reader.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: enhancement

#8400 Added SiteDisaggregator class
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tom.py
Labels: performance

#8401 Cleaning up the disaggregation calculator
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: internal

#8402 Refactored the disaggregation calculator
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8403 More work on the disaggregation calculator
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
Labels: internal

#8404 Optimized disaggregation for poissonian contexts
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8405 Disaggregation refactoring/1
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: internal

#8406 Disaggregation refactoring/2
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/acceptance/disagg_test.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: internal

#8407 Disaggregation refactoring/3
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
Labels: internal

#8408 Added disagg_mag_eps_dist method
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: enhancement

#8411 Moved logictree.py and source_reader.py into hazardlib
  demos/hazard/EventBasedPSHA/job.py
  doc/sphinx/openquake.commonlib.rst
  doc/sphinx/openquake.hazardlib.rst
  openquake/commands/ltcsv.py
  openquake/commonlib/__init__.py
  openquake/commonlib/logictree.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/source_test.py
  openquake/engine/postproc/data/calc_001.hdf5
  openquake/hazardlib/__init__.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/data/mrd/calc_934.hdf5
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/hazardlib/tests/calc/scenario_test.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
  utils/plot_lt
Labels: enhancement

#8412 Reducing slow tasks in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: performance

#8413 Reducing data transfer in disaggregation (14x)
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8414 Fixed install.py: it must not set the shared_dir
  debian/changelog
  install.py
Labels: bug

#8410 Implemented a mean_disagg extractor
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-1.csv
Labels: enhancement, outputs

#8417 Reducing the outbound data transfer in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8416 Fix reqv collapse
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_82/__init__.py
  openquake/qa_tests_data/classical/case_82/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_82/job.ini
  openquake/qa_tests_data/classical/case_82/lookup_reqv_asc.hdf5
  openquake/qa_tests_data/classical/case_82/multipoint.xml
  openquake/qa_tests_data/classical/case_82/multipoint2.xml
  openquake/qa_tests_data/classical/case_82/source_model_logic_tree.xml
Labels: bug, backport

#8418 Statistical disaggregation outputs
  debian/changelog
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/hazardlib/stats.py
  openquake/qa_tests_data/disagg/case_1/job.ini
  openquake/qa_tests_data/disagg/case_10/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_11/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist_TRT-1.csv
  openquake/qa_tests_data/disagg/case_4/job.ini
  openquake/qa_tests_data/disagg/case_5/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat_TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_TRT_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_8/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-1.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist_TRT-0.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist_TRT-1.csv
  openquake/server/db/actions.py
Labels: enhancement, outputs

#8419 Added exporter for disagg_by_src
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/classical_test.py
  openquake/qa_tests_data/classical/case_82/expected/disagg_by_src.csv
  openquake/qa_tests_data/classical/case_82/job.ini
  openquake/server/db/actions.py
Labels: enhancement, outputs

#8423 Reduced the number of tasks generated in disaggregation calculations/1
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: performance

#8424 Reduced the number of tasks generated in disaggregation calculations/2
  openquake/calculators/disaggregation.py
Labels: performance

#8428 Fix extend model
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/classical/case_83/__init__.py
  openquake/qa_tests_data/classical/case_83/common1.xml
  openquake/qa_tests_data/classical/case_83/common2.xml
  openquake/qa_tests_data/classical/case_83/extra1.xml
  openquake/qa_tests_data/classical/case_83/extra2.xml
  openquake/qa_tests_data/classical/case_83/extra3.xml
  openquake/qa_tests_data/classical/case_83/extra4.xml
  openquake/qa_tests_data/classical/case_83/extra5.xml
  openquake/qa_tests_data/classical/case_83/gsim_logic_tree.xml
  openquake/qa_tests_data/classical/case_83/job_expanded_LT.ini
  openquake/qa_tests_data/classical/case_83/job_extendModel.ini
  openquake/qa_tests_data/classical/case_83/source_model_logic_tree_expanded.xml
  openquake/qa_tests_data/classical/case_83/source_model_logic_tree_extendModel.xml
Labels: bug

#8430 Changed read_ctxs->read_ctxt
  doc/tutorials/the-datastore/ex4.py
  doc/tutorials/the-datastore/ex5.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/engine/postproc/compute_mrd.py
  openquake/engine/postproc/rupture_histogram.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/mrd_test.py
Labels: internal

#8431 update changelog
  debian/changelog
Labels: documentation

#8432 Managed the src_mutex case better in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
Labels: internal

#8434 Storing rup_mutex and removing ctxt.weight
  openquake/hazardlib/contexts.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/source_reader.py
Labels: internal

#8435 Improved the task distribution in disaggregation
  openquake/calculators/base.py
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8436 Doing the disaggregation in terms of rates instead of probabilities
  openquake/calculators/disaggregation.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8437 Optimized disagg-outputs composition and saving
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_7/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-traditional-0.csv
Labels: performance

#8438 Computing the mean disaggregation on the workers
  debian/changelog
  openquake/calculators/disaggregation.py
Labels: performance, enhancement

#8439 Optimized disaggregation (320x speedup)
  doc/tutorials/the-datastore/ex4.py
  doc/tutorials/the-datastore/ex5.py
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/views.py
  openquake/engine/postproc/compute_mrd.py
  openquake/engine/postproc/data/calc_001.hdf5
  openquake/engine/postproc/rupture_histogram.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/hazardlib/tests/gsim/utils.py
Labels: performance

#8440 Added output TRT_Mag
  openquake/hazardlib/calc/disagg.py
Labels: enhancement, outputs

#8441 Fixed the performance monitoring in disaggregation
  openquake/calculators/disaggregation.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag-0.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
Labels: performance

#8442 Smart task distribution in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/calc/disagg.py
Labels: performance

#8443 Removed obsolete commanda `oq celery`
  openquake/commands/celery.py
Labels: dependencies, backport

#8447 Reduced slow tasks in disaggregation
  openquake/calculators/disaggregation.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
Labels: performance

#8449 Fixed BlockingIOError
  debian/changelog
  openquake/calculators/event_based.py
Labels: bug, backport

#8450 Enhanced hazardlib.read_input to manage the full logic tree
  demos/hazard/EventBasedPSHA/job.py
  doc/adv-manual/event_based.rst
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/expected/spectra2.csv
  openquake/hazardlib/tests/calc/scenario_test.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
  utils/profile_ctxs.py
Labels: enhancement, internal

#8451 Added a test doing the disaggregation fully in hazardlib
  openquake/calculators/conditional_spectrum.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/commonlib/tests/calc_test.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/data/disagg/job.ini
  openquake/hazardlib/tests/calc/data/disagg/job_sampling.ini
  openquake/hazardlib/tests/calc/disagg_test.py
Labels: documentation

#8452 Fixed error with disagg_bin_edges
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_8/job_a.ini
Labels: bug

#8455 Added disaggregation test with a NegativeBinomialTOM
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/classical/case_78/expected/disagg_by_dist.org
Labels: enhancement, internal

#8453 Added feature `infer_occur_rates` for multiFault sources
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/classical/case_65/expected/disagg_by_mag_false.org
  openquake/qa_tests_data/classical/case_65/expected/disagg_by_mag_true.org
  openquake/qa_tests_data/classical/case_65/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_65/job.ini
  openquake/qa_tests_data/event_based/case_29/__init__.py
  openquake/qa_tests_data/event_based/case_29/expected/full_ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/gmf_data.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures2.csv
  openquake/qa_tests_data/event_based/case_29/gmmLT.xml
  openquake/qa_tests_data/event_based/case_29/job.ini
  openquake/qa_tests_data/event_based/case_29/report.rst
  openquake/qa_tests_data/event_based/case_29/sections.xml
  openquake/qa_tests_data/event_based/case_29/ssm.hdf5
  openquake/qa_tests_data/event_based/case_29/ssm.xml
  openquake/qa_tests_data/event_based/case_29/ssmLT.xml
Labels: performance

#8364 AELO: let the user provide input data and receive feedback on field validation and job completion
  .github/workflows/engine_test.yml
  debian/changelog
  openquake/commonlib/mosaic.py
  openquake/engine/aelo.py
  openquake/qa_tests_data/mosaic/CCA/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/EUR/in/job_vs30.ini
  openquake/server/admin.py
  openquake/server/db/actions.py
  openquake/server/local_settings.py.aelo
  openquake/server/settings.py
  openquake/server/templates/engine/index.html
  openquake/server/tests/data/openquake.cfg
  openquake/server/tests/views_test.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#8456 Changed disaggregation to consider all realizations by default
  debian/changelog
  doc/manual/hazard.rst
  openquake/calculators/disaggregation.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/disagg/case_13/job.ini
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-0.csv
  openquake/qa_tests_data/disagg/case_2/expected_output/Mag-1.csv
  openquake/qa_tests_data/disagg/case_2/job.ini
  openquake/qa_tests_data/disagg/case_4/expected_output/Mag_Dist-mean-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/TRT_Mag_Dist-mean-0.csv
  openquake/qa_tests_data/disagg/case_4/expected_output/TRT_Mag_Dist-mean-1.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-traditional-0.csv
  openquake/qa_tests_data/disagg/case_master/job.ini
Labels: outputs

#8359 Add a very simplified version of the JPN model for testing purposes
  openquake/qa_tests_data/mosaic/JPN/in/gmmLTrisk.xml
  openquake/qa_tests_data/mosaic/JPN/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/JPN/in/sites_jpn_res6.csv
  openquake/qa_tests_data/mosaic/JPN/in/ssm/source_model_noEQTHR_2021.xml
  openquake/qa_tests_data/mosaic/JPN/in/ssmLT.xml
Labels: inputs

#8457 Fixed check on required site parameters
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/site.py
Labels: bug

#8458 Refactored get_cmakers
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/gsim/base_site_test.py
  openquake/qa_tests_data/classical/case_15/calc_by_rlz.py
  utils/profile_ctxs.py
Labels: internal

#8459 AELO: disaggregation by relevant sources/1
  openquake/calculators/extract.py
  openquake/engine/postproc/disagg_by_rel_sources.py
  openquake/engine/postproc/postproc_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/probability_map.py
  openquake/qa_tests_data/mosaic/__init__.py
Labels: enhancement

#8460 Setting the right parameters for AELO jobs
  openquake/engine/aelo.py
  openquake/qa_tests_data/mosaic/EUR/in/sites_eur_res6.csv
  openquake/server/tests/data/openquake.cfg
  openquake/server/tests/views_test.py
Labels: enhancement

#8461 Re-sample CCA site model to keep ~125 sites
  openquake/commonlib/mosaic.py
  openquake/engine/postproc/postproc_test.py
  openquake/qa_tests_data/mosaic/CCA/in/sites_cca_res6.csv
  openquake/qa_tests_data/mosaic/test_sites.csv
Labels: enhancement

#8464 Removed `get_rlzs_by_gsim_list`
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
Labels: internal

#8465 Some work on reducing logic trees
  doc/adv-manual/logic_trees.rst
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_36/expected/branchsets.org
  openquake/qa_tests_data/classical/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/classical/case_7/expected/hazard_curve-smltp_b3-gsimltp_b1.csv
  openquake/qa_tests_data/classical/case_7/job.ini
  openquake/qa_tests_data/classical/case_7/source_model_3.xml
  openquake/qa_tests_data/classical/case_7/source_model_logic_tree.xml
Labels: internal

#8466 Let the webui tests use sites tested to belong to corresponding mosaic models
  openquake/qa_tests_data/mosaic/test_sites.csv
  openquake/server/tests/views_test.py
Labels: enhancement

#8468 Do not use get_realizations if not needed
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
Labels: internal

#8471 Added command `oq reduce_smlt`
  openquake/commands/reduce_smlt.py
  openquake/hazardlib/logictree.py
Labels: inputs

#8472 Removed ._gsims_by_trt
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/hazardlib/logictree.py
Labels: internal

#8473 Make sure we can run calculations on cole
  openquake/server/settings.py
Labels: critical
