Repository gem/oq-engine, pull requests merged in 2023-10, with the labels that each got.

#9058 Make the calculator tests parallelizable
  openquake/calculators/base.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commands/prepare_site_model.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/datastore.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/datastore_test.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/server/db/actions.py
Labels: performance, internal

#9060 Fixed another pandas warning
  openquake/hazardlib/site_amplification.py
Labels: internal

#9062 Stored _rates instead of _poes
  openquake/baselib/performance.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_damage_test.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/calc.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-SA(1.0).csv
Labels: internal

#9063 Optimized the calculation of quantile hazard maps
  debian/changelog
  openquake/hazardlib/stats.py
Labels: performance

#9034 Fixed resampling bug in simple fault sources
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/expected/spectra2.csv
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/surface/data/atf_haiyuan_data.py
  openquake/hazardlib/tests/geo/surface/gc2_test.py
  openquake/hazardlib/tests/geo/surface/simple_fault_test.py
  openquake/hazardlib/tests/source/simple_fault_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
  openquake/qa_tests_data/classical/case_32/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_35/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_61/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical/case_74/expected/hcurve-mean.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-007.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-mean.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.5.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-quantile-0.85.csv
  openquake/qa_tests_data/disagg/case_6/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_6/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/disagg/case_master/expected_output/Mag_Dist-mean-1.csv
  openquake/qa_tests_data/disagg/case_master/expected_output/TRT_Mag_Dist-mean-1.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_map-mean.csv
  openquake/qa_tests_data/logictree/case_14/expected/hazard_curve-rlz-000_PGA.csv
  openquake/qa_tests_data/logictree/case_21/expected/hazard_curve-smltp_b1_mfd1_low_dip_dip45-gsimltp_Sad1997.csv
  openquake/qa_tests_data/logictree/case_21/expected/hazard_curve-smltp_b1_mfd1_mid_dip_dip45-gsimltp_Sad1997.csv
  openquake/qa_tests_data/logictree/case_21/expected/hazard_curve-smltp_b1_mfd2_mid_dip_dip30-gsimltp_Sad1997.csv
  openquake/qa_tests_data/logictree/case_21/expected/hazard_curve-smltp_b1_mfd2_mid_dip_dip45-gsimltp_Sad1997.csv
  openquake/qa_tests_data/logictree/case_21/expected/hazard_curve-smltp_b1_mfd2_mid_dip_dip60-gsimltp_Sad1997.csv
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/logictree/case_71/expected/hcurves.csv
  openquake/qa_tests_data/logictree/case_73/expected/hcurve-mean.csv
  openquake/qa_tests_data/scenario/case_22/gmf-data.csv
  openquake/qa_tests_data/scenario/case_22/gmfdata.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/agg_loss.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/asset-loss.csv
  openquake/qa_tests_data/scenario_risk/case_4/expected/totlosses.txt
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/occupants/expected/asset-loss.csv
Labels: bug

#9065 In engine_nightly_test.yml pass --version only if GITHUB_HEAD_REF is not empty
  .github/workflows/engine_nightly_test.yml
Labels: bug

#9067 Speeding up count_ruptures in event_based
  debian/changelog
  openquake/calculators/event_based.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/source/kite_fault.py
  openquake/hazardlib/source/simple_fault.py
Labels: performance

#9070 Restored ds_calc_dir as it was
  openquake/commonlib/datastore.py
  openquake/server/db/actions.py
Labels: bug, outputs

#9071 Fixed event based calculations with same ID sources
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: bug

#9069 Remove Travis leftovers
  .travis.yml
  .travis/common.sh
  .travis/packaging.sh
  .travis/py_executables.sh
  .travis/py_shebangs.sh
Labels: enhancement

#9074 Do not run useless tests in Monterey
  .github/workflows/macos_m1_monterey_install.yml
Labels: internal

#9075 Tried to round the mesh for simple fault sources
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/simple_fault.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
Labels: internal

#9076 Added sanity check on mean_rates_by_src and mean_rates_ss
  openquake/calculators/classical.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/qa_tests_data/disagg/case_12/job.ini
Labels: internal

#9077 Finally fixed the AELO tests
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
Labels: bug

#9078 Fixed misprint making counting the ruptures ultra-slow in event_based
  openquake/calculators/event_based.py
Labels: bug, performance

#9079 Disabled SLOW MODE on macOS
  debian/changelog
  openquake/calculators/base.py
Labels: internal

#9080 Caching the KiteFault surface
  openquake/hazardlib/source/kite_fault.py
Labels: performance

#9082 Refactored many long functions
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/near_fault.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/tests/geo/surface/gc2_test.py
  openquake/hazardlib/tests/near_fault_test.py
  openquake/hazardlib/tests/source/simple_fault_test.py
Labels: internal

#9083 Refactored geo/line.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/polygon_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: internal

#9085 Refactore KiteFaultSurface
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: internal

#9088 Not losing GMFs in conditioned_gmfs scenarios with number_of_ground_motion_fields > 1
  debian/changelog
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_21/job.ini
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_26/job.ini
Labels: enhancement

#9090 Implemented `maximum_distance_stations`
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_21/job.ini
Labels: enhancement

#9091 Implemented maximum_distance_stations correctly
  openquake/calculators/event_based.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
Labels: enhancement

#9092 Extended the conditioned test to multiple gsims
  debian/changelog
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_risk/conditioned/gmpe_logic_tree_GEM_best_all_filtered_50_cataldi.xml
  openquake/qa_tests_data/scenario_risk/conditioned/job.ini
Labels: internal

#9093 Refactored conditioned gmfs
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/tests/calc/conditioned_gmfs_test.py
Labels: internal

#9095 Using rrup when filtering the stations with maximum_distance_stations
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
Labels: enhancement

#9096 Refactored conditioned GMFs a bit more
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: internal

#9097 Refactored the GMF generation
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#9099 Removed duplication in the ConditionedGmfComputer
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: internal

#9100 Made the GmfComputer a bit faster
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9101 Fixed HDF5 bug with event based starting from ruptures (--hc)
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: bug

#9102 Renamed get_ms_and_sids -> get_mean_covs
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/tests/calc/conditioned_gmfs_test.py
Labels: internal

#9103 Optimized even more the calculation of the GMFs
  openquake/calculators/event_based.py
  openquake/calculators/postproc/med_gmv.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9104 Fixed conditioned_gmfs
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
Labels: bug

#9105 Calling strip_zeros for each rupture
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: internal

#9106 Refactored the GmfComputer more
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
Labels: internal

#9107 Optimized the GmfComputer more
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9108 Skipping useless calculations
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9111 Optimized the GmfComputer a bit more
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9112 Add some logging to the infrastructure risk analysis
  openquake/risklib/connectivity.py
Labels: enhancement

#8713 Zhao perg implementation and mgmpe modifications for functionality in oq-mbtk's SMT module
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/zhao_2016.py
  openquake/hazardlib/gsim/zhao_2016_volc_perg/volc_perg.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/tests/gsim/data/ZHAO16PERG/unit_test_volc.geojson
  openquake/hazardlib/tests/gsim/zhao_2016_perg_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_83/__init__.py
  openquake/qa_tests_data/classical/case_83/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/classical/case_83/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_83/job.ini
  openquake/qa_tests_data/classical/case_83/sites.csv
  openquake/qa_tests_data/classical/case_83/source_model.xml
  openquake/qa_tests_data/classical/case_83/source_model_logic_tree.xml
  openquake/qa_tests_data/classical/case_83/test_volc.geojson
Labels: enhancement

#9113 Raised clear error message
  debian/changelog
  openquake/hazardlib/source_reader.py
Labels: enhancement

#9115 Using sphinx 6.2
  .github/workflows/docs.yml
  setup.py
Labels: dependencies

#9119 Minor edits to whats-new.md
  doc/whats-new.md
Labels: documentation

#9048 Trying to fix the HM2018 model
  debian/changelog
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/correlation.py
  openquake/qa_tests_data/event_based/case_31/__init__.py
  openquake/qa_tests_data/event_based/case_31/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_31/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based/case_31/job.ini
  openquake/qa_tests_data/event_based/case_31/source_model.xml
  openquake/qa_tests_data/event_based/case_31/source_model_logic_tree.xml
Labels: bug

#8862 Modification to Kuehn sigma_mu_adjustment calculation
  openquake/hazardlib/gsim/kuehn_2020.py
Labels: bug

#9121 Required at least Python 3.10.6 on mac and windows
  debian/changelog
  install.py
Labels: dependencies

#9120 Several corrections to secondary perils module
  openquake/sep/classes.py
  openquake/sep/liquefaction/liquefaction.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: bug

#9122 More refactoring of the GmfComputer
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
Labels: internal

#9124 Updated the installation docs
  doc/installing/README.md
  doc/installing/cluster.md
  doc/installing/development.md
  doc/installing/docker.md
  doc/installing/universal.md
Labels: documentation

#9126 Change the approach to identify if an action is running from a fork and get requirements from master
  .github/workflows/engine_pr_test.yml
  install.py
Labels: bug

#9127 Fixed the nightly build destroyed by Paolo
  .github/workflows/engine_nightly_test.yml
Labels: internal

#9128 Minor speedup when computing the GMFs
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/gmf.py
Labels: performance

#9125 New sponsors logo
  README.md
Labels: documentation

#9131 Fix event based damage extract and change corresponding demo
  demos/risk/EventBasedDamage/job.ini
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
Labels: enhancement

#9130 Fix manual and turn on documentation build for new Pull Requests
  .github/workflows/docs.yml
  doc/manual/conf.py
  doc/manual/index_toc.rst_part
  doc/manual/secondary_perils.rst
  doc/manual/sep/liquefaction_data_prep.md
  doc/manual/sep/sep_models.rst
  doc/manual/sep/sep_tutorials.rst
Labels: documentation

#9110 Replaced hazard XML outputs with CSV outputs in the manual
  doc/manual/hazard.rst
Labels: documentation

#9118 Work on the What's New
  doc/whats-new.md
Labels: documentation

#9132 Fix case with empty aggregate_by
  openquake/calculators/extract.py
Labels: bug

#9123 Fixed get_mean_stddevs_cy14
  debian/changelog
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
Labels: bug

#9134 Fixed `oq extract ruptures` on Windows
  debian/changelog
  doc/whats-new.md
  openquake/commands/extract.py
Labels: bug, outputs

#9135 Updated the documentation for installating the engine on Windows
  doc/faq.md
  doc/installing/universal.md
  doc/installing/windows.md
Labels: documentation

#9136 Add a test checking newlines in extracted ruptures
  openquake/baselib/tests/flake8_test.py
  openquake/commands/tests/commands_test.py
Labels: enhancement

#9140 Add links to liquefaction tutorial notebooks
  doc/manual/sep/sep_tutorials.rst
Labels: documentation

#9144 Added view` check_disagg_by_src`
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/views.py
Labels: internal

#9148 Reduced disagg/case_09
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_9/job.ini
Labels: internal

#9147 Removed `dbserver.ensure_on` in most places
  openquake/commands/db.py
  openquake/commands/engine.py
  openquake/commands/importcalc.py
  openquake/commands/mosaic.py
  openquake/commands/run.py
  openquake/engine/aelo.py
  openquake/engine/engine.py
  openquake/engine/multirun.py
  openquake/server/dbserver.py
Labels: internal

#9149 Fixed a bug in the disaggregation with mutex sources
  debian/changelog
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
Labels: bug

#9150 Fixed a bug in disagg_sources for mutex sources
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/mosaic/JPN/in/ssm/ssm01.hdf5
  openquake/qa_tests_data/mosaic/JPN/in/ssm/ssm01.xml
  openquake/qa_tests_data/mosaic/JPN/in/ssmLT.xml
Labels: bug

#9151 Fixed sanity check on the disagg_rates
  debian/changelog
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/disagg.py
Labels: bug

#9152 Added AELO test for KOR
  openquake/calculators/disaggregation.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/mosaic/KOR/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/KOR/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/KOR/in/sites_kor_res6.csv
  openquake/qa_tests_data/mosaic/KOR/in/ssm/areas/KOR_c1_M1_1/KOR_c1_M1_1.xml
  openquake/qa_tests_data/mosaic/KOR/in/ssm/areas/KOR_c1_M1_2/KOR_c1_M1_2.xml
  openquake/qa_tests_data/mosaic/KOR/in/ssmLT.xml
Labels: bug

#9153 Fixed disagg_by_src when there are same ID sources
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/probability_map.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data-from-ruptures.csv
  openquake/qa_tests_data/event_based/case_20/expected/gmf-data.csv
  openquake/qa_tests_data/event_based/case_6/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_6/expected/quantile_curve-0.1.csv
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/aggcurves-id.csv
  openquake/qa_tests_data/event_based_risk/case_3/expected/avg_losses-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggrisk-stats-id.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/losses_by_occupancy.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/portfolio_losses.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/ruptures_events.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/stddevs.txt
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggrisk-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/avg_losses-mean.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
Labels: bug

#9154 Fixing the KOR model
  debian/changelog
  openquake/commands/mosaic.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/logictree.py
Labels: bug

#9155 Write in bold text the asce7 and asce41 outputs in aelo mode
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/get_outputs.html
Labels: enhancement

#9129 solving error for low hazard sites
  openquake/calculators/postproc/compute_rtgm.py
Labels: enhancement

#9157 Disabling the DbServer
  debian/changelog
  openquake/commands/engine.py
  openquake/commands/reset.py
  openquake/engine/engine.py
Labels: internal

#9159 Risk by rupture
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/engine/engine.py
Labels: enhancement

#9160 AELO plots
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/qa_tests_data/mosaic/CCA/in/job_vs30.ini
  openquake/server/templates/engine/get_outputs.html
  openquake/server/templatetags/servertags.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#9162 Fixed site model parameters in the demo
  demos/hazard/EventBasedPSHA/site_model.csv
Labels: documentation

#9164 Minor cleanup to the AELO plots code
  openquake/calculators/postproc/compute_rtgm.py
Labels: internal

#9165 Added extract/relevant_gmfs
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
Labels: outputs

#9167 Added command `oq info executing`
  debian/changelog
  openquake/commands/info.py
Labels: enhancement

#9163 Simplified aelo outputs page
  openquake/calculators/postproc/compute_rtgm.py
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/get_outputs.html
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/templates/engine/index.html
  openquake/server/urls.py
  openquake/server/views.py
Labels: enhancement

#9171 Added a view `calc_risk`
  openquake/calculators/views.py
Labels: internal

#9170 Fixed an interpolation bug
  openquake/calculators/postproc/compute_rtgm.py
Labels: bug

#9169 Update slurm.md with few updates
  doc/installing/slurm.md
Labels: documentation

#9173 Restored dbserver.ensure_on()
  openquake/commands/engine.py
Labels: bug
