Repository gem/oq-engine, pull requests merged in 2024-06, with the labels that each got.

#9737 minor formatting improvements
  doc/user-guide/advanced/special-features.rst
  doc/user-guide/configuration-file/classical-psha-config.rst
  doc/user-guide/configuration-file/event-based-risk-config.rst
  doc/user-guide/index.rst
  doc/user-guide/inputs/exposure-models-inputs.rst
  doc/user-guide/inputs/rupture-model-inputs.rst
  doc/user-guide/inputs/seismic-source-model-inputs.rst
  doc/user-guide/inputs/site-model-inputs.rst
  doc/user-guide/workflows/event-based-psha.rst
  doc/user-guide/workflows/scenario-hazard.rst
Labels: documentation

#9738 Restored `.set_sections` so that the multifaultsource converter can work again
  openquake/hazardlib/source/multi_fault.py
Labels: bug

#9736 Filtering the site collection depending on the rupture when possible
  openquake/commonlib/readinput.py
  openquake/hazardlib/site.py
Labels: enhancement

#9740 Added numba to setup.py
  setup.py
Labels: dependencies, backport

#9739 add wheel for django_cookie_consent
  openquake/baselib/general.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#9742 Reduced a few tests
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/classical/case_50/job.ini
  openquake/qa_tests_data/event_based_damage/case_14/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_damage/case_14/exposure_model.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_damage/case_15/job.ini
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggcurves-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-NAME.csv
  openquake/qa_tests_data/event_based_risk/case_5/expected/aggrisk-stats-taxonomy.csv
  openquake/qa_tests_data/event_based_risk/case_5/job.ini
  openquake/qa_tests_data/logictree/case_73/expected/hcurve-mean.csv
  openquake/qa_tests_data/logictree/case_73/job.ini
  openquake/qa_tests_data/scenario_damage/case_12/Exposure_Cal_Colombia.csv
  openquake/qa_tests_data/scenario_damage/case_12/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_12/expected/aggrisk2.csv
Labels: performance

#9743 Moved OQ_DEBUG_SITE in get_site_collection
  openquake/calculators/views.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_65/expected/disagg_by_mag_false.org
  openquake/qa_tests_data/classical/case_65/expected/disagg_by_mag_true.org
  openquake/qa_tests_data/classical/case_75/expected/context.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
  openquake/qa_tests_data/classical/case_78/expected/disagg_by_dist.org
  openquake/qa_tests_data/classical/case_80/expected/rups.org
  openquake/qa_tests_data/disagg/case_master/expected/mean_disagg.rst
  openquake/qa_tests_data/event_based/case_16/expected/global_gmfs.txt
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves3.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves5.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_curves7.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/risk_by_rup.org
  openquake/qa_tests_data/logictree/case_12/expected/realizations.org
  openquake/qa_tests_data/logictree/case_28/expected/realizations.org
  openquake/qa_tests_data/logictree/case_39/expected/realizations.org
  openquake/qa_tests_data/scenario_damage/case_11/expected/mean_perils.rst
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
Labels: internal

#9744 Changed the script to build the global site model
  utils/build_global_sites
Labels: critical

#9701 Right hand
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: inputs

#9745 Made the calculators tests faster
  openquake/qa_tests_data/classical/case_50/expected/hcurves-PGA.csv
  openquake/qa_tests_data/classical/case_50/expected/hcurves-SA(1.0).csv
  openquake/qa_tests_data/classical/case_50/expected/uhs.csv
  openquake/qa_tests_data/classical/case_50/job.ini
  openquake/qa_tests_data/classical/case_82/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_2/expected/cs-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_2/expected/cs-1.csv
  openquake/qa_tests_data/conditional_spectrum/case_2/job.ini
  openquake/qa_tests_data/disagg/case_15/job_1yr.ini
  openquake/qa_tests_data/disagg/case_15/job_50yr.ini
  openquake/qa_tests_data/event_based/case_7/expected/hazard_curve-mean.csv
  openquake/qa_tests_data/event_based/case_7/job.ini
  openquake/qa_tests_data/event_based_damage/case_15/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_damage/case_15/job.ini
  openquake/qa_tests_data/event_based_risk/case_9/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_9/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_9/job.ini
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean-bis.csv
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_05/expected/mean_disagg_by_src.csv
  openquake/qa_tests_data/logictree/case_05/job.ini
  openquake/qa_tests_data/logictree/case_05/job_bis.ini
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hazard_curve-SA(1.0).csv
  openquake/qa_tests_data/logictree/case_30/expected/hcurve-PGA.csv
  openquake/qa_tests_data/logictree/case_30/expected/hcurve-SA(1.0).csv
  openquake/qa_tests_data/logictree/case_30/job.ini
  openquake/qa_tests_data/logictree/case_79/job.ini
Labels: performance

#9648 AELO year 3 updates to run all IMTs
  CONTRIBUTORS.txt
  debian/changelog
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/postproc_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/disagg/case_15/gmmLT.xml
  openquake/qa_tests_data/disagg/case_15/job_1yr.ini
  openquake/qa_tests_data/disagg/case_15/job_50yr.ini
  openquake/qa_tests_data/mosaic/CCA/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/CCA/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/JPN/in/expected/uhs.csv
  openquake/qa_tests_data/mosaic/JPN/in/gmmLTrisk.xml
  openquake/qa_tests_data/mosaic/JPN/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/KOR/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/KOR/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/PAC/in/gmmLT_1.xml
  openquake/qa_tests_data/mosaic/PAC/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/WAF/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/WAF/in/job_vs30.ini
  openquake/qa_tests_data/postproc/case_rtgm/gmmLT_SC.xml
  openquake/qa_tests_data/postproc/case_rtgm/job_vs30.ini
Labels: enhancement

#9749 Cached get_realizations
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/disagg_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: performance

#9750 Optimized get_realizations a bit more
  openquake/hazardlib/logictree.py
Labels: performance

#9752 Small refactoring of get_rlzs_by_gsim
  openquake/hazardlib/logictree.py
Labels: internal

#9755 Improved compare sitecol
  openquake/commands/compare.py
Labels: internal

#9756 Changed the scenario calculators to discard the sites far away from the rupture
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/mosaic_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/mosaic/case_01/expected/avg_gmf.csv
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/qa_tests_data/scenario/case_22/gmfdata.csv
  openquake/qa_tests_data/scenario/case_22/sitemodel.csv
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
Labels: enhancement, outputs

#9760 Remove all warnings and errors and improve 'docs' workflow
  .github/workflows/docs.yml
  doc/user-guide/configuration-file/classical-psha-config.rst
  doc/user-guide/inputs/exposure-models-inputs.rst
  doc/user-guide/inputs/rupture-model-inputs.rst
Labels: bug, enhancement

#9757 Rewritten `oq compare assetcol`
  openquake/calculators/views.py
  openquake/commands/compare.py
Labels: internal

#9762 Added more debugging utilities
  debian/changelog
  openquake/calculators/views.py
  openquake/commands/info.py
  openquake/commonlib/readinput.py
  openquake/risklib/asset.py
Labels: internal

#9763 `Refactored build_global_exposure`
  openquake/commands/plot_assets.py
  openquake/commonlib/expo_to_hdf5.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/data/grm_exposure.csv
  openquake/commonlib/tests/data/grm_exposure.xml
  openquake/commonlib/tests/expo_to_hdf5_test.py
  utils/build_global_exposure
Labels: internal

#9764 Fine-filtered the sites around the rupture and improved plot_assets
  openquake/commands/plot_assets.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
Labels: enhancement

#9766 Added `oq compare rates` and a view `oq show gids`
  openquake/calculators/views.py
  openquake/commands/compare.py
Labels: internal

#9769 Using 32 bits for the realization weights
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/calculators/views.py
  openquake/qa_tests_data/event_based/case_31/expected/avg_gmf.csv
Labels: performance

#9770 Reverting https://github.com/gem/oq-engine/pull/9701/
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: bug

#9761 Change footer css: bigger and dark-grey font, plus some additional vertical padding
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/includes/footer.html
Labels: enhancement

#9772 Added view_fastmean
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/event_based.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/commands/compare.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/logictree.py
Labels: internal

#9773 Use Django commands instead of webui alias for server installation
  .github/workflows/rocky_install.yml
  .github/workflows/webui_rh_test.yml
  doc/getting-started/installation-instructions/server.md
  docker/scripts/oq-start.sh
  install.py
  openquake/commands/webui.py
  utils/reset-db
Labels: enhancement, documentation

#9767 Fix doc
  debian/changelog
  doc/underlying-science/index.rst
  doc/underlying-science/secondary-perils.rst
  doc/user-guide/inputs/index.rst
  doc/user-guide/inputs/liquefaction-inputs.rst
  doc/user-guide/inputs/secondary-perils-inputs.rst
  doc/user-guide/outputs/_images/hazus-displacements.png
  doc/user-guide/outputs/_images/hazus-probabilities.png
  doc/user-guide/outputs/_images/zhu15-probabilities.png
  doc/user-guide/outputs/index.rst
  doc/user-guide/outputs/liquefaction-analysis-outputs.rst
  doc/user-guide/outputs/secondary-perils-outputs.rst
  doc/user-guide/workflows/index.rst
  doc/user-guide/workflows/liquefaction.rst
  doc/user-guide/workflows/secondary-perils.rst
Labels: documentation

#9779 Fixed export avg gmf
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_risk/conditioned/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_risk/conditioned/job.ini
Labels: bug, outputs

#9780 ARISTOTLE: doing everything with a single exposure.hdf5 file
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/mosaic_test.py
  openquake/commands/mosaic.py
  openquake/commonlib/expo_to_hdf5.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/qa_tests_data/mosaic/case_01/__init__.py
  openquake/qa_tests_data/mosaic/case_01/expected/avg_gmf.csv
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/qa_tests_data/mosaic/exposure.hdf5
  openquake/qa_tests_data/mosaic/site_model.hdf5
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/server/views.py
  utils/build_global_exposure
  utils/build_global_sites
Labels: enhancement

#9781 Passing the `asset_hazard_distance` in `oq mosaic aristotle`
  openquake/commands/mosaic.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
Labels: internal

#9759 Add AELO release information
  openquake/calculators/base.py
  openquake/commonlib/datastore.py
  openquake/qa_tests_data/mosaic/aelo_changelog.ini
  openquake/server/apps.py
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/aelo_changelog.html
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/templates/engine/includes/footer.html
  openquake/server/urls.py
  openquake/server/utils.py
  openquake/server/views.py
Labels: proposal, enhancement, backport

#9778 Run demos automatically also on push to branches engine-3.20 and engine-3.21
  .github/workflows/demos_ltr_latest.yml
Labels: internal

#9782 Extended Starmap.apply to split DataFrames
  debian/changelog
  openquake/baselib/general.py
  openquake/baselib/tests/parallel_test.py
Labels: enhancement

#9784 Fixed the issue of small negative eigenvalues in conditioned GMFs
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
Labels: critical

#9776 Keeping the stations in conditioned GMFs
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_24/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_damage/case_13/expected/aggrisk-stats.csv
  openquake/qa_tests_data/scenario_damage/case_13/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_19/Exposure_model_N3.xml
  openquake/qa_tests_data/scenario_damage/case_19/Fragility_model_N3.xml
  openquake/qa_tests_data/scenario_damage/case_19/__init__.py
  openquake/qa_tests_data/scenario_damage/case_19/earthquake_rupture_model_USGS.xml
  openquake/qa_tests_data/scenario_damage/case_19/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_19/gmpe.xml
  openquake/qa_tests_data/scenario_damage/case_19/job.ini
  openquake/qa_tests_data/scenario_damage/case_19/site_model.csv
  openquake/qa_tests_data/scenario_damage/case_19/site_model_stations.csv
  openquake/qa_tests_data/scenario_damage/case_19/stationlist_seismic.csv
  openquake/qa_tests_data/scenario_risk/conditioned/Site_model_variable_Albania.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_risk/conditioned/gmpe_logic_tree_GEM_best_all_filtered_50_cataldi.xml
  openquake/qa_tests_data/scenario_risk/reinsurance/expected/reinsurance-avg_portfolio.csv
Labels: bug

#9786 Fixed exporting the ruptures when imported from a CSV
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: outputs

#9788 Extended `oq info` to .csv files
  openquake/baselib/hdf5.py
  openquake/commands/info.py
Labels: internal

#9789 Removed exporter for `disagg-stats-traditional`
  doc/user-guide/outputs/disaggregation-outputs.rst
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
Labels: bug

#9787 Added a demo with post loss amplification and reinsurance
  demos/risk/Reinsurance/job_pla.ini
  demos/risk/Reinsurance/pla_model.csv
Labels: documentation

#9790 Added command `oq compare oqparam`
  debian/changelog
  openquake/commands/compare.py
  openquake/commands/tests/commands_test.py
Labels: enhancement, internal

#9791 Added `oq plot_sites csvfiles`
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/event_based.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/plots.py
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
  openquake/commands/plot_sites.py
Labels: internal

#9792 Added an `around` function
  openquake/baselib/general.py
Labels: internal

#9794 Fixed wrong comment [ci skip]
  openquake/hazardlib/gsim/afshari_stewart_2016.py
Labels: documentation

#9796 Reduce GsimLogicTree._ltnode when filtering by TRT
  openquake/hazardlib/gsim_lt.py
Labels: internal

#9799 Added tests for OqParam.to_ini
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
Labels: internal

#9800 Supporting the stations in ARISTOTLE
  openquake/baselib/hdf5.py
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commands/mosaic.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/hazardlib/site.py
Labels: enhancement

#9801 Extended geolocate to multiple polygons with the same code
  openquake/hazardlib/geo/utils.py
Labels: enhancement

#9802 Remove `engine_version` from AELO changelog
  openquake/calculators/base.py
  openquake/qa_tests_data/mosaic/aelo_changelog.ini
  openquake/server/static/css/engine.css
Labels: AELO

#9798 Adding vs30
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
Labels: enhancement

#9803 Added method `GsimLogicTree.to_node`
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim_lt.py
Labels: internal

#9804 ARISTOTLE: add to the WebUI the possibility to upload a station_data_file
  openquake/calculators/base.py
  openquake/engine/aristotle.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9805 Restored custom_site_id in risk calculations
  openquake/calculators/tests/classical_damage_test.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical_damage/case_master/expected/uhs-mean.csv
  openquake/qa_tests_data/classical_damage/case_master/job_haz.ini
  openquake/qa_tests_data/classical_risk/case_master/expected/loss_maps-mean.csv
  openquake/qa_tests_data/classical_risk/case_master/expected/uhs-mean.csv
  openquake/qa_tests_data/classical_risk/case_master/job.ini
Labels: outputs

#9806 Added function `valid.modifiable_gmpe`
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: enhancement, internal

#9807 Fixed `plot_avg_gmf` to work remotely
  openquake/calculators/event_based.py
  openquake/calculators/postproc/plots.py
  openquake/commands/plot.py
Labels: internal

#9808 Filter sites array
  debian/changelog
  openquake/commonlib/readinput.py
Labels: enhancement

#9810 Added a view `long_ruptures`
  openquake/calculators/views.py
  openquake/hazardlib/source/point.py
Labels: internal

#9811 Fixed `modified_gsim` when the underlying GMPE has arguments
  openquake/hazardlib/valid.py
Labels: bug

#9809 ARISTOTLE: fix handling temporary uploaded files
  openquake/server/tests/data/fault_rupture.xml
  openquake/server/tests/data/stationlist_seismic.csv
  openquake/server/views.py
Labels: bug

#9813 Saving a bit more memory in classical calculations
  openquake/hazardlib/contexts.py
Labels: performance
