Repository gem/oq-engine, pull requests merged in 2024-12, with the labels that each got.

#10184 Fixed the filtering of the site collection in event_based with --hc
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/hazard.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/lt.py
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf1.csv
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf2.csv
  openquake/qa_tests_data/event_based/case_31/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_31/job.ini
  openquake/qa_tests_data/event_based/case_31/sites.csv
Labels: bug

#10183 ARISTOTLE: fix using rupture and station data and managing corresponding download/conversion issues
  openquake/commonlib/readinput.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/data/us20002926-grid.xml
  openquake/hazardlib/tests/shakemap/data/us20002926-rup.json
  openquake/hazardlib/tests/shakemap/data/us20002926.json
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: bug

#10187 Moving logic from Django view into shakemap.validate
  .github/workflows/engine_pr_test.yml
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal

#10188 Refactored download_station_data
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal

#10189 ARISTOTLE: Avoided downloading shakemap_url twice
  .github/workflows/engine_pr_test.yml
  openquake/commands/sample.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/data/us20002926-stations.json
  openquake/hazardlib/tests/shakemap/data/us6000jllz-stations.json
  openquake/hazardlib/tests/shakemap/data/us7000n7n8-stations.json
  openquake/hazardlib/tests/shakemap/data/usp0001ccb-stations.json
  openquake/hazardlib/tests/shakemap/validate_test.py
Labels: performance

#10190 Fix management of station_data_issue
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: bug

#10191 Made `get_rup_dic` shorter
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/data/us6000f65h-grid.xml
Labels: internal

#10157 ARISTOTLE: differentiate interfaces for level 0, 1 and 2
  openquake/calculators/postproc/plots.py
  openquake/commands/plot_assets.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/aelo_form.html
  openquake/server/templates/engine/includes/aristotle_form_level_0.html
  openquake/server/templates/engine/includes/aristotle_form_level_1.html
  openquake/server/templates/engine/includes/aristotle_form_level_2.html
  openquake/server/templates/engine/includes/aristotle_run_form.html
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#10192 Aristotle: refactoring AristotleParam
  openquake/commands/mosaic.py
  openquake/commonlib/calc.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/data/us20002926-stations.json
  openquake/hazardlib/tests/shakemap/data/us6000f65h-stations.json
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal

#10193 ARISTOTLE: Monitoring downloads
  bin/arist
  openquake/baselib/performance.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
Labels: performance

#10196 Moved another slow WebUI test into the fast `validation_test.py`
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/data/us7000n05d-grid.xml
  openquake/hazardlib/tests/shakemap/data/us7000n05d-rup.json
  openquake/hazardlib/tests/shakemap/data/us7000n05d-stations.json
  openquake/hazardlib/tests/shakemap/data/us7000n05d.json
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/tests/test_aristotle_mode.py
Labels: internal

#10198 Aristotle: introduced user concept
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/views.py
Labels: enhancement

#10186 Added build_global_ses
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/scenario/case_33/__init__.py
  openquake/qa_tests_data/scenario/case_33/job1.ini
  openquake/qa_tests_data/scenario/case_33/job2.ini
  utils/build_global_ses
Labels: enhancement

#10199 ARISTOTLE: render a different interface depending from the level of the current user
  openquake/server/admin.py
  openquake/server/migrations/0001_create_user_profiles.py
  openquake/server/migrations/__init__.py
  openquake/server/models.py
  openquake/server/settings.py
  openquake/server/signals.py
  openquake/server/templates/engine/includes/aristotle_run_form.html
  openquake/server/templates/engine/index.html
  openquake/server/templatetags/servertags.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/utils.py
  openquake/server/views.py
Labels: enhancement

#10200 Storing event based ruptures in `import_gmfs_hdf5`
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
Labels: enhancement, outputs

#10202 Extended `build_global_ses` to store the ruptures
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
Labels: enhancement, outputs

#10204 Fixed get_joyner_boore_distance
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/geo/mesh.py
  openquake/qa_tests_data/event_based/case_33/__init__.py
  openquake/qa_tests_data/event_based/case_33/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_33/gmmLT_1TRT.xml
  openquake/qa_tests_data/event_based/case_33/job.ini
  openquake/qa_tests_data/event_based/case_33/one_cf_gr_src.xml
  openquake/qa_tests_data/event_based/case_33/sites.csv
  openquake/qa_tests_data/event_based/case_33/ssmLT_1TRT_1src.xml
Labels: bug

#10203 set minimun RAM to 16 GB
  doc/getting-started/installation-instructions/index.rst
Labels: documentation

#10205 Improvements to `build_global_ses`
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
  utils/build_global_ses
Labels: enhancement

#10206 Added commands `oq plot ebruptures` and `oq filter_around`
  debian/changelog
  openquake/calculators/extract.py
  openquake/commands/filter_around.py
  openquake/commands/plot.py
  utils/build_global_ses
Labels: internal

#10210 Added `model` field to `rupture_dt`
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/stochastic.py
  openquake/hazardlib/source/rupture.py
  utils/build_global_ses
Labels: enhancement, outputs

#10211 Saving the rupture geometries as 32 bit floats
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/event_based_damage/case_16/dmgdist.txt
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/aggrisk.csv
Labels: performance, outputs

#10213 Reverted breaking change
  openquake/calculators/base.py
Labels: bug

#10201 ARISTOTLE: add the possibility to share/unshare a job
  openquake/server/db/actions.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/utils.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#10208 ARISTOTLE: add a checkbox to interface level 2 choosing if using the ShakeMap or not
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/aristotle_form_level_2.html
  openquake/server/views.py
  setup.cfg
Labels: bug

#10214 Improved importing of sites, ruptures, events and gmfs
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_test.py
Labels: internal, outputs

#10216 Simplified the RuptureGetter
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
Labels: internal

#10217 Simplified RuptureGetter/2
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
Labels: internal

#10218 Simplified RuptureGetter/3
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
  openquake/commonlib/calc.py
  openquake/hazardlib/source/rupture.py
Labels: internal

#10195 Add Seattle Basin class of KuehnEtAl2020 for US 2023 Conterminous Seattle Basin subduction GMCs + Adding USGS basin scaling and cybershake basin adjustments for NGAWest2 GMMs
  debian/changelog
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/gsim/utils_usgs_basin_scaling.py
  openquake/hazardlib/gsim/zalachoris_rathje_2019.py
  openquake/hazardlib/tests/gsim/utils_us23_basin_adj_test.py
Labels: enhancement

#10221 Storing `trt_smrt_start_stop`
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
Labels: internal

#10222 Replaced the `RuptureGetter` with `calc.get_proxies`
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/filters.py
Labels: internal

#10223 Starting from ruptures.hdf5
  openquake/calculators/event_based.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  utils/build_global_exposure
  utils/build_global_ses
Labels: enhancement

#10224 Fixed oq-risk-tests
  openquake/calculators/event_based.py
Labels: bug

#10226 Starting from ruptures.hdf5/2
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/readinput.py
  utils/build_global_ses
Labels: enhancement

#10228 ARISTOTLE: disable conditioning for users with level below 2
  openquake/hazardlib/shakemap/parsers.py
Labels: internal

#10230 Minor refactoring of `get_mean_covs`
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: internal

#10229 Starting from ruptures.hdf5/4
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commonlib/readinput.py
  openquake/engine/global_ses.py
  openquake/engine/tests/global_ses_test.py
  openquake/qa_tests_data/mosaic_for_ses/job_sites.ini
Labels: enhancement

#10231 Parallelized `get_mean_covs` when conditioning the GMFs
  bin/arist
  debian/changelog
  openquake/baselib/tests/parallel_test.py
  openquake/calculators/event_based.py
  openquake/engine/engine.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/shakemap/validate.py
Labels: performance

#10232 Fix the behavior of the calc log visualization
  openquake/server/views.py
Labels: bug

#10235 Using mosaic.geojson
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/mosaic/mosaic.geojson
Labels: inputs

#10236 Using ModelBoundaries.shp for AELO and mosaic.geojson for the rest
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/aelo.py
  openquake/engine/tests/global_ses_test.py
  openquake/hazardlib/geolocate.py
  openquake/qa_tests_data/mosaic_for_ses/mosaic.geojson
Labels: internal

#10237 Added a watchdog killing slow calculations
  debian/changelog
  openquake/commonlib/logs.py
  openquake/engine/engine.py
  openquake/engine/openquake.cfg
  openquake/server/views.py
Labels: enhancement

#10234 DEBUG variable in tools installation mode.
  openquake/server/local_settings.py.tools
  openquake/server/settings.py
Labels: internal

#10238 Fixed a bug while exporting realizations.csv for scenario calculations
  debian/changelog
  openquake/calculators/extract.py
Labels: bug

#10233 Fix K20 site param bug
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/tests/gsim/utils_us23_basin_adj_test.py
Labels: bug
