Repository gem/oq-engine, pull requests merged in 2024-07, with the labels that each got.

#9814 Disabled data compression
  openquake/engine/openquake.cfg
Labels: performance

#9815 Refined multifault rupture filtering
  openquake/hazardlib/geo/surface/multi.py
Labels: internal

#9812 AELO: Display the asce_version in the outputs page and rename ASCE 7-16 and ASCE 41-17 to ASCE 16 and ASCE 41
  openquake/calculators/export/__init__.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/server/templates/engine/get_outputs_aelo.html
  openquake/server/views.py
Labels: enhancement

#9816 Disaggregation by section
  openquake/baselib/general.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_75/expected/context.org
Labels: enhancement

#9817 Disabled check on too many branches if `smlt_branch` is given
  debian/changelog
  openquake/hazardlib/logictree.py
Labels: bug

#9818 (Not) extended the maximum number of source model branches to 33,489
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/tests/data/drouet_smtlt.xml
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: enhancement

#9820 Fixed self.sitecol
  openquake/calculators/base.py
  openquake/calculators/preclassical.py
Labels: internal

#9821 Replace `sites_slice` with `tile_spec`
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_40/job.ini
  openquake/qa_tests_data/classical/case_66/expected/hmap1.csv
  openquake/qa_tests_data/classical/case_66/expected/hmap2.csv
  openquake/qa_tests_data/classical/case_66/job.ini
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf1.csv
  openquake/qa_tests_data/event_based/case_27/expected/avg_gmf2.csv
Labels: internal

#9822 Reimplemented the sensitivity_analysis
  debian/changelog
  demos/hazard/MultiPointClassicalPSHA/job.ini
  demos/risk/EventBasedDamage/README.md
  demos/risk/EventBasedDamage/job.ini
  doc/user-guide/advanced/special-features.rst
  openquake/commands/collect_jobs.py
  openquake/commands/create_jobs.py
  openquake/commands/run.py
  openquake/commands/sensitivity_analysis.py
  openquake/commands/submit.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
  openquake/engine/openquake.cfg
  openquake/qa_tests_data/classical/case_40/job.ini
  openquake/qa_tests_data/classical/case_43/job.ini
  openquake/qa_tests_data/classical/case_69/job.ini
  openquake/qa_tests_data/logictree/case_56/job.ini
  openquake/server/views.py
Labels: enhancement

#9823 Avoided over-allocating cores
  .github/workflows/engine_pr_test.yml
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/reportwriter.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/views.py
  openquake/commands/collect_jobs.py
  openquake/commands/submit.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/dbapi.py
  openquake/engine/aristotle.py
  openquake/engine/export/core.py
  openquake/engine/tools/make_html_report.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/risklib/tests/scientific_test.py
  openquake/sep/tests/test_utils.py
  openquake/sep/utils.py
  openquake/server/tests/test_public_mode.py
  openquake/server/views.py
Labels: internal

#9826 Fixed collect_jobs
  openquake/commands/collect_jobs.py
  openquake/commands/submit.py
Labels: internal

#9765 Cookie consent
  doc/getting-started/installation-instructions/server.md
  docker/Singularity.def
  docker/scripts/oq-db_start.sh
  docker/scripts/oq-start.sh
  openquake/commands/webui.py
  openquake/server/fixtures/0001_cookie_consent_required_plus_hide_cookie_bar.json
  openquake/server/fixtures/0002_cookie_consent_analytics.json
  openquake/server/local_settings.py.aelo_aristotle
  openquake/server/local_settings.py.pam
  openquake/server/local_settings.py.server
  openquake/server/settings.py
  openquake/server/static/css/cookie_consent.css
  openquake/server/templates/cookie_consent/cookiegroup_list.html
  openquake/server/templates/engine/base.html
  openquake/server/templates/engine/includes/cookie_analytics.html
  openquake/server/templates/engine/includes/cookie_bar.html
  openquake/server/templatetags/servertags.py
  openquake/server/urls.py
  openquake/server/utils.py
  setup.py
Labels: dependencies

#9827 Removed `dbserver.listen`
  doc/getting-started/installation-instructions/cluster.md
  openquake/engine/openquake.cfg
  openquake/server/dbserver.py
Labels: internal

#9829 Managing the DbServer correctly
  openquake/calculators/tests/__init__.py
  openquake/commands/dbserver.py
  openquake/commands/engine.py
  openquake/commands/reset.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/logs.py
  openquake/engine/openquake.cfg
  openquake/server/dbserver.py
Labels: internal

#9830 Make sure CONTEXT_PROCESSORS is defined for all application modes
  .github/workflows/engine_pr_test.yml
  openquake/server/local_settings.py.aelo_aristotle
  openquake/server/local_settings.py.pam
  openquake/server/local_settings.py.server
  openquake/server/local_settings.py.tools
  openquake/server/settings.py
Labels: bug

#9831 Added uniqueness check for the station coordinates
  debian/changelog
  openquake/baselib/tests/general_test.py
  openquake/calculators/event_based.py
  openquake/commands/rerun.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/data/Stations_NIED.csv
  openquake/commonlib/tests/data/job.ini
  openquake/commonlib/tests/data/sites.csv
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/aristotle.py
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: enhancement, inputs

#9828 seismicity classes aelo
  openquake/calculators/postproc/compute_rtgm.py
Labels: enhancement

#9832 Implemented a smarter SLURM algorithm
  openquake/baselib/parallel.py
  openquake/baselib/slurm.py
  openquake/calculators/classical.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_22/job.ini
Labels: performance, enhancement

#9833 Fix in doc
  doc/user-guide/inputs/secondary-perils-inputs.rst
Labels: documentation

#9835 Refined SLURM algorithm
  .github/workflows/demos.yml
  debian/changelog
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/commands/submit.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
Labels: performance

#9834 Add the possibility to plot surfaces
  openquake/commands/plot.py
Labels: internal

#9837 Fix dev-tools installation
  openquake/server/local_settings.py.tools
  openquake/server/templates/engine/includes/cookie_bar.html
Labels: bug

#9836 Made sure the tiles have at least 100 sites
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
Labels: performance

#9838 Returning a composite array instead of a dictionary of arrays
  openquake/calculators/classical.py
  openquake/hazardlib/map_array.py
Labels: internal

#9839 Removed `pmap_max_mb` and avoided gzipping the _rates
  openquake/calculators/classical.py
  openquake/engine/openquake.cfg
Labels: performance

#9841 Saving the rates on temporary files in tiling calculations/2
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/commonlib/calc.py
  openquake/engine/openquake.cfg
Labels: performance

#9774 New cav/ia gsim from Sandikkaya and Akkar 2017
  CONTRIBUTORS.txt
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/sandikkaya_akkar_2017.py
  openquake/hazardlib/tests/gsim/data/SA17/SA17_REPI_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SA17/SA17_RHYPO_MEAN.csv
  openquake/hazardlib/tests/gsim/data/SA17/SA17_RJB_MEAN.csv
  openquake/hazardlib/tests/gsim/sandikkaya_akkar_2017_test.py
Labels: enhancement

#9704 Add New Attenuation Model of Ambraseys2005
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/ambraseys_2005.py
  openquake/hazardlib/tests/gsim/ambraseys_2005_test.py
  openquake/hazardlib/tests/gsim/data/Am05/Am05_MEAN_ROCK_H.csv
  openquake/hazardlib/tests/gsim/data/Am05/Am05_MEAN_SOFT_H.csv
  openquake/hazardlib/tests/gsim/data/Am05/Am05_MEAN_STIF_H.csv
  openquake/hazardlib/tests/gsim/data/Am05/Am05_MEAN_STIF_V.csv
  openquake/hazardlib/tests/gsim/data/Am05/Am05_STD_TOT_STIF_H.csv
  openquake/hazardlib/tests/gsim/data/Am05/Am05_STD_TOT_STIF_V.csv
Labels: enhancement

#9842 Reduce the memory consumption in tiling calculations
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
Labels: performance

#9843 Refined the tiling calculator
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
Labels: performance

#9844 Completely rewritten the SLURM approach to use zmq
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/workerpool.py
  openquake/calculators/classical.py
  openquake/commands/run.py
  openquake/commonlib/readinput.py
  openquake/server/views.py
Labels: enhancement

#9845 Storing the rates as a single dataset again
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/classical_test.py
Labels: performance

#9848 Removed kwargs signature from SandikkayaAkkar2017
  openquake/hazardlib/gsim/sandikkaya_akkar_2017.py
Labels: internal

#9847 Removed `oq plot sources`
  openquake/calculators/classical.py
  openquake/calculators/extract.py
  openquake/commands/plot.py
  openquake/commands/show.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/source_reader.py
  openquake/server/tests/test_public_mode.py
Labels: internal

#9846 Add command to plot non-parametric sources
  openquake/commands/plot.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/non_parametric.py
Labels: internal

#9852 ARISTOTLE: add the possibility to specify maximum_distance_stations, either from command line or from the webui
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9854 Fix a couple of details in ARISTOTLE mode
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
Labels: bug

#9857 Change ARISTOTLE form placeholders to indicate the expected formats
  openquake/server/views.py
Labels: enhancement

#9858 ARISTOTLE: change `maximum_distance` default to 100 km; change label of `ses_seed` to `'Random seed'`
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9860 Reduced the memory consumption in tiling calculations
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
Labels: performance

#9862 Fixed bug with the conditional spectrum with non-contributing TRTs
  debian/changelog
  openquake/calculators/postproc/conditional_spectrum.py
  openquake/calculators/tests/conditional_spectrum_test.py
  openquake/qa_tests_data/conditional_spectrum/case_3/__init__.py
  openquake/qa_tests_data/conditional_spectrum/case_3/expected/cs-0.csv
  openquake/qa_tests_data/conditional_spectrum/case_3/gmpe_logic_tree.xml
  openquake/qa_tests_data/conditional_spectrum/case_3/job.ini
  openquake/qa_tests_data/conditional_spectrum/case_3/source_model1.xml
  openquake/qa_tests_data/conditional_spectrum/case_3/source_model2.xml
  openquake/qa_tests_data/conditional_spectrum/case_3/source_model_logic_tree.xml
Labels: bug

#9865 Improved test of `mean_rates_by_src`
  openquake/calculators/classical.py
  openquake/calculators/tests/disagg_test.py
Labels: internal

#9867 Using half the memory on Windows
  openquake/baselib/parallel.py
Labels: performance

#9866 Using half the memory in postclassical
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/map_array.py
Labels: performance

#9869 Avoided computing twice `max_weight`
  openquake/calculators/classical.py
Labels: internal

#9870 Refined the tiling calculator
  openquake/calculators/classical.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
Labels: performance

#9871 Reduced the memory consumption in event_based calculations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/oqvalidation.py
Labels: performance, enhancement

#9872 Made `minimum_magnitude` and `minimum_intensity` mandatory except in toy calculations
  debian/changelog
  doc/user-guide/advanced/advanced-calculations.rst
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/qa_tests_data/event_based/case_26/job_land.ini
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/qa_tests_data/event_based/case_7/job.ini
Labels: performance, inputs

#9863 ARISTOTLE: improve format of losses table, plus other improvements
  openquake/calculators/views.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/templatetags/servertags.py
  openquake/server/views.py
Labels: enhancement

#9873 Added `oq compare asce` functionality
  openquake/calculators/views.py
  openquake/commands/compare.py
  openquake/commands/mosaic.py
Labels: enhancement, internal

#9874 Improve documentation of server installation and fix a corner case in using temporary directory
  doc/getting-started/installation-instructions/server.md
  openquake/server/views.py
Labels: bug, documentation

#9876 In server/views.py always use config.directory.custom_tmp if present, when creating temp files or directories
  openquake/server/views.py
Labels: bug

#9875 Fixed a critical memory bug in event based calculations
  debian/changelog
  openquake/hazardlib/geo/mesh.py
Labels: bug, performance

#9877 Fixed "object has no attribute msparams"
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source/multi_fault.py
  openquake/qa_tests_data/classical/case_67/__init__.py
  openquake/qa_tests_data/classical/case_67/gmmLT.xml
  openquake/qa_tests_data/classical/case_67/job.ini
  openquake/qa_tests_data/classical/case_67/ssm/test_source.hdf5
  openquake/qa_tests_data/classical/case_67/ssm/test_source.xml
  openquake/qa_tests_data/classical/case_67/ssm/test_source_sections.xml
  openquake/qa_tests_data/classical/case_67/ssmLT.xml
Labels: bug

#9878 Fixed encoding error in extract realizations
  debian/changelog
  openquake/calculators/extract.py
Labels: bug

#9850 use extrapolation in order to handle floating point edge cases
  openquake/hazardlib/gsim/kuehn_2020.py
Labels: bug

#9851 Add a generic command to plot all kinds of sources
  openquake/commands/plot.py
Labels: internal

#9880 Improved error message when the exposure is missing
  openquake/calculators/base.py
Labels: enhancement, inputs
