Repository gem/oq-engine, pull requests merged in 2024-10, with the labels that each got.

#10002 Fixed the tiling test
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source_reader.py
Labels: internal

#10003 Forbidden `hazard_curves_from_gmfs=true` in ebrisk
  openquake/baselib/parallel.py
  openquake/commonlib/oqvalidation.py
Labels: bug

#9990 Whats New for engine-3.21
  debian/changelog
  doc/release-notes/whats-new.md
Labels: documentation

#10004 Minor refactoring of `get_job_id`
  openquake/commands/engine.py
Labels: internal

#10006 Formatting of the What's New
  doc/release-notes/whats-new-3.21.md
Labels: bug, documentation

#10007 Fixed the `assert(losses)` error in the view delta_loss
  debian/changelog
  openquake/calculators/views.py
Labels: bug

#9994 Update tusa_langer_azzaro_2019.py
  CONTRIBUTORS.txt
  openquake/hazardlib/gsim/tusa_langer_azzaro_2019.py
  openquake/hazardlib/tests/gsim/data/TLA19/TusaLangerAzzaro2019_100b_MEAN.csv
  openquake/hazardlib/tests/gsim/data/TLA19/TusaLangerAzzaro2019_100b_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/TLA19/TusaLangerAzzaro2019_60b_MEAN.csv
  openquake/hazardlib/tests/gsim/data/TLA19/TusaLangerAzzaro2019_60b_STD_TOTAL.csv
Labels: bug

#10005 Removed the Collapser class and some refactoring
  openquake/calculators/classical.py
  openquake/calculators/postproc/median_spectrum.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/qa_tests_data/classical/case_69/expected/hcurve-mean.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_map-mean.csv
Labels: internal

#10008 Added `whats-new.md` to `index.rst`
  doc/conf.py
  doc/release-notes/index.rst
  doc/release-notes/whats-new.md
Labels: documentation

#10013 User-dependent `scratch_dir`
  openquake/baselib/parallel.py
Labels: bug, backport

#10012 Work around unicode error when exporting strings
  debian/changelog
  openquake/baselib/node.py
Labels: bug

#10016 Fixed WorkerPool.start to use the .scratch
  openquake/baselib/workerpool.py
Labels: bug, backport

#10015 Refined cleaning custom_tmp in `oq reset`
  openquake/commands/purge.py
Labels: bug

#10017 Towards a TOML representation of the CoeffsTable
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/tests/gsim/coeffs_table_test.py
Labels: enhancement

#10020 Fixed the progress with `disagg_by_src`
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
Labels: bug, backport

#10021 Added a memory check in disaggregation calculations
  debian/changelog
  openquake/calculators/disaggregation.py
Labels: enhancement

#10019 Replace some of `oq dbserver upgrade` with `oq engine --upgrade-db`
  doc/contributing/testing.md
  docker/scripts/oq-start.sh
  install.py
Labels: documentation

#10022 Added `CoeffsTable.fromtoml`
  debian/changelog
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/tests/gsim/coeffs_table_test.py
Labels: enhancement

#10024 Removing CampbellBozorgnia classes by updating the CoeffsTable instead
  openquake/hazardlib/gsim/bozorgnia_campbell_2016_vh.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2014_test.py
  openquake/hazardlib/tests/gsim/coeffs_table_test.py
Labels: internal

#10025 Modernized the regionalization of Chiou Youngs (2014)
  debian/changelog
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
Labels: enhancement

#10026 Simplifying the taxonomy mapping/1
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#10027 Simplifying the taxonomy mapping/2
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
Labels: internal

#10028 Simplifying the taxonomy mapping/3
  openquake/calculators/base.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10029 Simplifying the taxonomy mapping/4
  openquake/calculators/base.py
  openquake/calculators/multi_risk.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/qa_tests_data/event_based_risk/case_5/job.ini
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map.csv
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map_contents.csv
  openquake/qa_tests_data/event_based_risk/case_5/taxonomy_map_structural.csv
  openquake/qa_tests_data/event_based_risk/case_8/Exposure_Vulnerability_Mapping.csv
  openquake/qa_tests_data/event_based_risk/case_8/job.ini
  openquake/qa_tests_data/event_based_risk/case_8/taxonomy_map.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10030 Simplifying the taxonomy mapping/5
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/risklib/riskmodels.py
Labels: internal

#10032 Simplifying the taxonomy mapping/6
  openquake/calculators/event_based_risk.py
  openquake/risklib/riskmodels.py
Labels: internal

#10031 Changed ARISTOTLE to work with a single calculation for multiple countries
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/engine/aristotle.py
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#10033 Add the possibility to export the asset collection via the command line, keeping it hidden from the webui
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/qa_tests_data/scenario_risk/case_11/expected/assetcol.csv
  openquake/qa_tests_data/scenario_risk/case_9/expected/assetcol.csv
  openquake/server/views.py
Labels: enhancement

#10036 Moved the Aristotle test in the engine repository
  .github/workflows/engine_pr_test.yml
  openquake/calculators/checkers.py
  openquake/engine/tests/aristotle1/aggrisk.txt
  openquake/engine/tests/aristotle1/job.ini
  openquake/engine/tests/aristotle2/aggrisk.txt
  openquake/engine/tests/aristotle2/job.ini
  openquake/engine/tests/aristotle_test.py
Labels: internal

#10037 Added command `oq info loss_types`
  debian/changelog
  openquake/commands/info.py
Labels: documentation, internal

#10038 Fixed the stored calculation_mode in `oq sensitivity_analysis`
  debian/changelog
  openquake/commands/run.py
Labels: bug

#10039 Removed support for XML consequences
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/multi_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_11/job.ini
  openquake/qa_tests_data/event_based_damage/case_11/structural_consequence_model.csv
  openquake/qa_tests_data/event_based_damage/case_11/structural_consequence_model.xml
  openquake/qa_tests_data/event_based_damage/case_13/job_a.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_b.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_c.ini
  openquake/qa_tests_data/event_based_damage/case_13/job_d.ini
  openquake/qa_tests_data/event_based_damage/case_13/structural_consequence_model.csv
  openquake/qa_tests_data/event_based_damage/case_13/structural_consequence_model.xml
  openquake/qa_tests_data/multi_risk/case_1/consequence_model.csv
  openquake/qa_tests_data/multi_risk/case_1/consequence_model.xml
  openquake/qa_tests_data/multi_risk/case_1/consequence_model_2.csv
  openquake/qa_tests_data/multi_risk/case_1/consequence_model_2.xml
  openquake/qa_tests_data/multi_risk/case_1/job.ini
  openquake/qa_tests_data/multi_risk/case_1/job_2.ini
  openquake/qa_tests_data/scenario_damage/case_14/consequence_model.csv
  openquake/qa_tests_data/scenario_damage/case_14/consequence_model.xml
  openquake/qa_tests_data/scenario_damage/case_14/job.ini
  openquake/qa_tests_data/scenario_damage/case_4b/consequence_model.csv
  openquake/qa_tests_data/scenario_damage/case_4b/contents_consequence_model.xml
  openquake/qa_tests_data/scenario_damage/case_4b/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_4b/nonstructural_consequence_model.xml
  openquake/qa_tests_data/scenario_damage/case_4b/structural_consequence_model.xml
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/riskmodels_test.py
Labels: inputs

#10040 Tested csm2rup in run-demos.sh
  bin/run-demos.sh
  utils/csm2rup
Labels: internal

#10041 Checking `oqparam.to_ini()` with the demos
  bin/run-demos.sh
  demos/hazard/ComplexFaultSourceClassicalPSHA/job.ini
  demos/hazard/LogicTreeCase2ClassicalPSHA/job.ini
  demos/hazard/ScenarioLiquefaction/job.ini
  openquake/calculators/checkers.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/valid.py
Labels: internal, inputs

#10043 Fixed oqparam.to_ini()
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/valid.py
Labels: internal

#10047 Added median_spectrum_disagg output
  openquake/baselib/general.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/postproc_test.py
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum1.csv
Labels: outputs

#10048 More work on the median spectrum outputs
  openquake/baselib/general.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/median_spectrum.py
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum1.csv
Labels: outputs

#10049 Saving median_spectrum_disagg
  openquake/calculators/classical.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/median_spectrum.py
Labels: outputs

#10050 Added clear error message for missing fiona
  openquake/calculators/event_based.py
  openquake/commands/info.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/geo/packager.py
  openquake/hazardlib/gsim/zhao_2016.py
Labels: dependencies

#10051 Added loss type liquefaction
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_21/__init__.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_21/exposure.xml
  openquake/qa_tests_data/scenario_damage/case_21/exposure_demo_edges.csv
  openquake/qa_tests_data/scenario_damage/case_21/exposure_demo_nodes.csv
  openquake/qa_tests_data/scenario_damage/case_21/fragility_model_liq.xml
  openquake/qa_tests_data/scenario_damage/case_21/fragility_model_shaking.xml
  openquake/qa_tests_data/scenario_damage/case_21/gmpe_logic_tree_ascr.xml
  openquake/qa_tests_data/scenario_damage/case_21/job.ini
  openquake/qa_tests_data/scenario_damage/case_21/non_operational.csv
  openquake/qa_tests_data/scenario_damage/case_21/rupture.xml
  openquake/qa_tests_data/scenario_damage/case_21/site_model.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#10052 Added loss type landslide
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_21/fragility_model_landslide.xml
  openquake/qa_tests_data/scenario_damage/case_21/job.ini
  openquake/qa_tests_data/scenario_damage/case_21/non_operational.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement, inputs

#10046 support for python3.12
  .github/workflows/engine_pr_test.yml
  .github/workflows/macos_intel_install.yml
  .github/workflows/macos_m1_install.yml
  .github/workflows/ubuntu_install.yml
  .github/workflows/windows_test.yml
  requirements-py312-linux64.txt
  requirements-py312-macos_arm64.txt
  requirements-py312-macos_x86_64.txt
  requirements-py312-win64.txt
Labels: dependencies

#10056 Sorting the indices in `filter_site_array_around`
  openquake/commonlib/readinput.py
  openquake/engine/tests/aristotle1/aggrisk.txt
  openquake/engine/tests/aristotle2/aggrisk.txt
  openquake/hazardlib/calc/filters.py
Labels: bug

#10055 Add pytest 8.3.3 to our requirements #10053
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py312-linux64.txt
  requirements-py312-macos_arm64.txt
  requirements-py312-macos_x86_64.txt
  requirements-py312-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#10054 Tried to run the tests with Python 3.12
  .github/workflows/engine_pr_test.yml
  openquake/commonlib/readinput.py
  openquake/hazardlib/tests/pmf_test.py
Labels: dependencies, internal

#10057 Added missing DISPLAY_NAMEs
  openquake/calculators/export/__init__.py
  openquake/calculators/postproc/median_spectrum.py
Labels: outputs

#10060 Reduced the maximum number of functions parameters to 15
  openquake/baselib/tests/flake8_test.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/kite_fault.py
  openquake/hazardlib/source/simple_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source/kite_fault_test.py
  openquake/hazardlib/tests/source/simple_fault_test.py
Labels: internal

#10061 Small refactoring of the source classes
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source/non_parametric.py
Labels: internal

#10059 ARISTOTLE: if the hypocenter is close to the boundaries of many mosaic models, allow to select one of them...
  openquake/calculators/checkers.py
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/engine/tests/aristotle3/aggrisk.txt
  openquake/engine/tests/aristotle3/job.ini
  openquake/engine/tests/aristotle_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#10062 Fixed extract_dependencies for appconf
  openquake/baselib/general.py
Labels: bug, dependencies

#10067 Added a check for missing secondary perils
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/imt.py
Labels: inputs

#10066 Fixing the key of dictionary in readinput
  openquake/commonlib/readinput.py
Labels: bug

#10068 Moved `area` inside the `cost_types` in the exposure
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/scenario/case_16/Example_Exposure.xml
  openquake/risklib/asset.py
  openquake/risklib/read_nrml.py
Labels: internal, inputs

#10069 Export job zip/1
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/hazard.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/aristotle_test.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/event_based_risk/case_1/job.ini
  openquake/qa_tests_data/scenario/case_16/job.ini
  openquake/risklib/asset.py
  openquake/server/views.py
Labels: outputs

#10070 ARISTOTLE: change the way a hypocenter is considered close to any mosaic models
  openquake/calculators/event_based.py
  openquake/engine/aristotle.py
  openquake/engine/tests/aristotle4/aggrisk.txt
  openquake/engine/tests/aristotle4/job.ini
  openquake/engine/tests/aristotle_test.py
  openquake/hazardlib/geo/utils.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: bug

#10072 Investigating median spectrum weights
  openquake/calculators/postproc/median_spectrum.py
  openquake/commands/plot.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/job2.ini
Labels: investigation

#10073 Added test for consequence=losses for liquefaction and landslide
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_21/job.ini
  openquake/qa_tests_data/scenario_damage/case_22/__init__.py
  openquake/qa_tests_data/scenario_damage/case_22/consequences.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/exposure_model.csv
  openquake/qa_tests_data/scenario_damage/case_22/exposure_model.xml
  openquake/qa_tests_data/scenario_damage/case_22/fault_rupture.xml
  openquake/qa_tests_data/scenario_damage/case_22/fragility_model_landslide.xml
  openquake/qa_tests_data/scenario_damage/case_22/fragility_model_liquefaction.xml
  openquake/qa_tests_data/scenario_damage/case_22/fragility_model_structural.xml
  openquake/qa_tests_data/scenario_damage/case_22/job.ini
  openquake/qa_tests_data/scenario_damage/case_22/mapping_multiple_loss_types.csv
  openquake/qa_tests_data/scenario_damage/case_22/site_model.csv
  openquake/risklib/scientific.py
Labels: enhancement

#10075 Vectorized `compute_csq` by asset
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/multi_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: performance

#10076 Added test for risk_by_event from event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_15/expected/risk_by_event.csv
Labels: outputs

#10077 Added total_losses
  openquake/calculators/event_based_damage.py
  openquake/calculators/multi_risk.py
  openquake/qa_tests_data/scenario_damage/case_4b/job_risk.ini
  openquake/qa_tests_data/scenario_damage/case_7/job_r.ini
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10074 ARISTOTLE: fix circular imports
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/post_risk.py
  openquake/commands/importcalc.py
  openquake/commands/tests/independence_test.py
  openquake/commonlib/calc.py
  openquake/engine/aristotle.py
  openquake/engine/engine.py
  openquake/server/views.py
  utils/csm2rup
Labels: bug

#10079 Changed the damage outputs
  debian/changelog
  openquake/calculators/classical_damage.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_continuous.csv
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_discrete.csv
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_interpolation.csv
  openquake/qa_tests_data/classical_damage/case_1a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_1b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_1c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_continuous.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_discrete.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_interpolation.csv
  openquake/qa_tests_data/classical_damage/case_2a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_2b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_3a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_5a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_6a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_6b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-rlzs-AkkarBommer2010().csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-rlzs-SadighEtAl1997().csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-stats.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-007.csv
  openquake/qa_tests_data/classical_damage/case_master/job_haz.ini
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_risk-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/scenario_damage/case_1/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages1.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages2.csv
  openquake/qa_tests_data/scenario_damage/case_17/expected/avg_damages-rlz-000_no_time_event.csv
  openquake/qa_tests_data/scenario_damage/case_17/expected/avg_damages-rlz-000_time_event_day.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/avg_damages-rlz-000.csv
  openquake/qa_tests_data/scenario_damage/case_2/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_3/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_6/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/damages.csv
Labels: outputs

#10080 Honoring `total_losses` in damage calculations too
  openquake/calculators/event_based_damage.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement

#10081 Make sure that no_damage is positive
  openquake/calculators/post_risk.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
Labels: bug, outputs

#10082 Changed the ruptures.csv exporter to also export the source IDs
  debian/changelog
  openquake/calculators/extract.py
  openquake/qa_tests_data/event_based/case_15/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_23/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_25/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures2.csv
  openquake/qa_tests_data/event_based/case_3/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_30/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_32/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_5/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_8/expected/rup_data.csv
  openquake/qa_tests_data/event_based/src_mutex/expected/ruptures.csv
Labels: outputs

#10083 Fixed median_spectrum.set_imls
  openquake/calculators/postproc/median_spectrum.py
Labels: bug, internal

#10084 Raised an error in case of non-invertible hazard curves
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/map_array.py
  openquake/qa_tests_data/disagg/case_14/job.ini
Labels: bug

#10085 Avoided RuntimeWarning: divide by zero encountered in buffer
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/postproc_test.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/geo/mesh_test.py
  openquake/hazardlib/tests/geo/surface/complex_fault_test.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
  openquake/hazardlib/tests/geo/surface/simple_fault_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/uhs-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-avg_portfolio.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves-policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggrisk-policy.csv
Labels: internal

#10087 Restored DIST_TOLERANCE as it was
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/postproc_test.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/geo/mesh_test.py
  openquake/hazardlib/tests/geo/surface/complex_fault_test.py
  openquake/hazardlib/tests/geo/surface/gridded_test.py
  openquake/hazardlib/tests/geo/surface/simple_fault_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/uhs-mean.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/aggregate_by_avg_losses_tag-taxonomy_tag-occupancy_kind-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/avg_losses-quantile-0.5.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-avg_portfolio.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves-policy.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_4/expected/aggrisk-policy.csv
Labels: internal

#10088 Renamed from_lons_lats -> from_
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/source/complex_fault.py
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: internal

#10092 Improved the validations in OqParam
  openquake/commonlib/oqvalidation.py
Labels: internal

#10093 Added functionality to read multi fault sources
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
Labels: inputs

#10095 Composing probabilities in event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
Labels: bug

#10096 Temporarily using the mean damage distribution
  openquake/calculators/event_based_damage.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
Labels: enhancement

#10097 Moved event_based_damage/case_16 from the oq-risk-tests
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/event_based_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_16/__init__.py
  openquake/qa_tests_data/event_based_damage/case_16/assets.csv
  openquake/qa_tests_data/event_based_damage/case_16/consequences.csv
  openquake/qa_tests_data/event_based_damage/case_16/contents_fragility_model.xml
  openquake/qa_tests_data/event_based_damage/case_16/dmgdist.txt
  openquake/qa_tests_data/event_based_damage/case_16/exposure_model.xml
  openquake/qa_tests_data/event_based_damage/case_16/gsim_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_16/job.ini
  openquake/qa_tests_data/event_based_damage/case_16/nonstructural_fragility_model.xml
  openquake/qa_tests_data/event_based_damage/case_16/portfolio_dmgdist.txt
  openquake/qa_tests_data/event_based_damage/case_16/sites.csv
  openquake/qa_tests_data/event_based_damage/case_16/source_model_1.xml
  openquake/qa_tests_data/event_based_damage/case_16/source_model_2.xml
  openquake/qa_tests_data/event_based_damage/case_16/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_damage/case_16/structural_fragility_model.xml
Labels: bug

#10098 Add set -x and remove unused installation of sphinx theme
  .github/workflows/demos_ltr_latest.yml
Labels: internal

#10101 Added a function `compose_dds`
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/risklib/scientific.py
Labels: enhancement

#10102 Added an exporter for `trt_gsim`
  debian/changelog
  demos/hazard/MedianSpectrum/CanadaSHM6-GMM-LT.xml
  demos/hazard/MedianSpectrum/CanadaSHM6_NBCC2020_WesternCanada-LT.xml
  demos/hazard/MedianSpectrum/CanadaSHM6_NBCC2020_WesternCanada.xml
  demos/hazard/MedianSpectrum/README.txt
  demos/hazard/MedianSpectrum/job.ini
  demos/hazard/MedianSpectrum/sites.csv
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/logictree_test.py
  openquake/commands/plot.py
  openquake/qa_tests_data/logictree/case_84/expected/trt_gsim.csv
Labels: outputs

#10103 Small refactoring of the consequences
  openquake/calculators/event_based_damage.py
  openquake/calculators/multi_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10104 Refactoring of get_risk_functions
  openquake/risklib/riskmodels.py
Labels: internal

#10105 Improved test scenario_risk/case_master and some refactoring
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/aggrisk.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10106 Fixed RiskComputerTestCase
  openquake/calculators/event_based_damage.py
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#10108 Changed ordering to (riskid, loss_type)
  debian/changelog
  openquake/engine/tests/aristotle1/aggrisk.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss.txt
  openquake/qa_tests_data/scenario_risk/case_master/expected/portfolio_loss2.txt
  openquake/risklib/scientific.py
Labels: internal

#10109 Computing all loss types together
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10110 Introduced "peril" in the risk functions
  openquake/calculators/multi_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10111 Honoring `custom_tmp` in gettemp
  openquake/baselib/general.py
Labels: internal
