Repository gem/oq-engine, pull requests merged in 2024-03, with the labels that each got.

#9499 Minor edits to whats-new
  doc/release-notes/whats-new.md
Labels: documentation

#9496 What's new for engine-3.19
  doc/release-notes/whats-new.md
Labels: documentation

#9500 Extended build_global_exposure
  utils/build_global_exposure
Labels: internal

#9502 Reading the gsim_lt from site_model.hdf5
  openquake/calculators/event_based.py
  openquake/commands/mosaic.py
  openquake/hazardlib/gsim_lt.py
  openquake/qa_tests_data/mosaic/case_01/expected/avg_gmf.csv
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/qa_tests_data/mosaic/site_model.hdf5
Labels: enhancement

#9503 Gzipping the _rates
  openquake/calculators/classical.py
Labels: performance

#9504 Made `store_rates` faster by not splitting by IMT
  openquake/calculators/classical.py
Labels: performance

#9505 Made `storing rates` faster in tiling calculations
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/hazardlib/probability_map.py
Labels: performance

#9506 Removed Python version check in install.py
  install.py
Labels: dependencies

#9507 Reduced data transfer in classical calculations by gzipping the rates
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/probability_map.py
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-SA(0.1)
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-SA(0.2).csv
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-SA(0.5).csv
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_22/expected/hazard_curve-mean-SA(2.0).csv
Labels: performance

#9508 Reducing memory consumption in postclassical
  openquake/baselib/hdf5.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: performance

#9510 Compressing the sources with zlib and not gzip
  openquake/calculators/classical.py
  openquake/hazardlib/source_reader.py
Labels: performance

#9509 Added optional flag `config.distribution.compress`
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
  openquake/engine/openquake.cfg
Labels: performance

#9514 Instrumenting the pickle/unpickle time
  openquake/baselib/parallel.py
  openquake/calculators/classical.py
Labels: performance, internal

#9512 Changelog2ghrel
  .github/workflows/docs.yml
  CONTRIBUTORS.txt
  debian/changelog
  helpers/changelog2ghrel.sh
Labels: enhancement

#9515 Produce 4x less tiles if `config.distribution.compress` is set
  openquake/calculators/classical.py
  openquake/hazardlib/site.py
Labels: performance

#9518 Added a demo ScenarioCase3
  demos/hazard/ScenarioCase3/README.txt
  demos/hazard/ScenarioCase3/job.ini
  openquake/calculators/event_based.py
Labels: documentation

#9516 Small refinement of tiling
  openquake/calculators/classical.py
Labels: performance

#9519 Removed parameter `rupture_usgs_id`
  debian/changelog
  demos/hazard/ScenarioCase3/job.ini
  openquake/calculators/event_based.py
  openquake/calculators/views.py
  openquake/commands/plot.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source/rupture.py
Labels: internal, inputs

#9521 Complete the action used to run demos of selected engine versions and upload corresponding artifacts
  .github/workflows/demos_ltr_latest.yml
Labels: enhancement

#9522 Removed the ExternalLink feature
  openquake/calculators/base.py
  openquake/calculators/tests/event_based_risk_test.py
Labels: enhancement, inputs, backport

#9523 Fixed `oq zip`
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/commonlib/readinput.py
Labels: bug

#9501 Add ARISTOTLE mode
  openquake/server/settings.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#9525 Reduced by half the data transfer in classical by using 32 bit rates
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/probability_map.py
Labels: performance

#9526 Add oq parameter tectonic_region_type and use it in Aristotle mode
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim_lt.py
  openquake/qa_tests_data/mosaic/case_01/job.ini
Labels: enhancement

#9511 Worked on the command `oq mosaic aristotle`
  openquake/calculators/views.py
  openquake/commands/mosaic.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/site.py
  openquake/risklib/riskmodels.py
  utils/build_global_exposure
  utils/build_global_sites
Labels: enhancement, internal

#9528 Add maximum_distance form field; run aristotle calculation on submit
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9532 Small changes to build_global_exposure
  utils/build_global_exposure
Labels: internal, inputs

#9527 Fix the release notes index
  doc/release-notes/index.rst
  doc/release-notes/whats-new-3.18.md
Labels: documentation, backport

#9530 Building one calculation per country in Aristotle mode
  openquake/baselib/hdf5.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/qa_tests_data/mosaic/case_01/job.ini
  openquake/risklib/asset.py
  openquake/server/views.py
Labels: enhancement

#9536 Reading the taxonomy mapping in aristotle-mode
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  utils/build_global_exposure
Labels: enhancement

#9539 Rounding lon, lat with numpy always
  debian/changelog
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/event_based/case_14/Site_model_South_Africa.xml
  openquake/qa_tests_data/scenario/case_27/expected/avg_gmf.csv
Labels: bug

#9540 Raise an error for GMF-conditioned calculations with too many sites
  debian/changelog
  openquake/calculators/event_based.py
Labels: enhancement

#9541 Do not plot stations in avg_gmf
  openquake/calculators/extract.py
Labels: enhancement

#9538 Add to the webui outputs page buttons to display avg_gmf plots for all the available imts
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/commands/plot.py
  openquake/server/templates/engine/get_outputs.html
  openquake/server/templatetags/servertags.py
  openquake/server/views.py
Labels: enhancement

#9529 Visualize losses produced by an aristotle calculation
  openquake/commands/plot_assets.py
  openquake/commonlib/readinput.py
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/templates/engine/index.html
  openquake/server/urls.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#9531 Webui tools_only mode
  openquake/server/local_settings.py.tools
  openquake/server/urls.py
  openquake/server/utils.py
Labels: internal

#9543 Fixed Aristotle calculations in the case of a single taxonomy mapping
  debian/changelog
  openquake/calculators/base.py
  openquake/commands/mosaic.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/engine/aristotle.py
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
Labels: enhancement

#9544 Exporting the complete site mesh
  openquake/calculators/export/hazard.py
Labels: outputs

#9546 Splitting multiple taxonomy mappings in multiple calculations
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/hazardlib/geo/utils.py
  openquake/risklib/asset.py
  openquake/server/views.py
Labels: enhancement

#9545 Fix creation and visualization of avg_gmf plots, also displaying country borders
  openquake/calculators/event_based.py
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/views.py
Labels: enhancement

#9549 Removed GlobalModelGetter
  openquake/commonlib/global_model_getter.py
  openquake/commonlib/tests/global_model_getter_test.py
Labels: internal

#9550 Added view_aggrisk
  openquake/calculators/views.py
Labels: enhancement, outputs

#9551 Add plot of assets and make plots only if OQ_APPLICATION_MODE is defined
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
  openquake/server/settings.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs.html
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9552 Call _plot_assets only once
  openquake/calculators/base.py
Labels: enhancement

#9553 Improved the view aggrisk
  openquake/calculators/views.py
  openquake/server/views.py
Labels: outputs

#9554 Change text of aristotle 'Submit' button to 'Processing...' while creating job
  openquake/server/static/js/engine.js
Labels: enhancement

#9557 Add shakemap_id to job description and display job description on top of the outputs page
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/views.py
Labels: enhancement
