Repository gem/oq-engine, pull requests merged in 2024-11, with the labels that each got.

#10116 Refactored PointRupture
  openquake/hazardlib/source/point.py
  openquake/hazardlib/source/rupture.py
  openquake/hazardlib/tests/calc/_conditioned_gmfs_test_data.py
Labels: internal

#10115 Documented the GmfComputer
  .github/workflows/engine_pr_test.yml
  doc/contributing/developing-with-the-engine.rst
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
  openquake/risklib/scientific.py
Labels: documentation

#10117 Introduced perils in the CompositeRiskModel
  openquake/commonlib/oqvalidation.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
Labels: internal

#10122 Using the max(coeffs) strategy in the consequences
  openquake/calculators/event_based_damage.py
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk-parent.csv
  openquake/qa_tests_data/scenario_damage/case_21/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: internal

#10123 Removed secondary simulations
  debian/changelog
  openquake/calculators/event_based_damage.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commands/info.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_damage/case_11/job.ini
  openquake/qa_tests_data/scenario_damage/case_12/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_12/expected/aggrisk2.csv
  openquake/qa_tests_data/scenario_damage/case_12/job.ini
  openquake/qa_tests_data/scenario_damage/case_22/job_r.ini
Labels: internal

#10120 ARISTOTLE: use the `preferred` shakemap version if more than one is available
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10125 Moved case_21 in the infrastructure_risk tests
  openquake/calculators/tests/infrastructure_risk_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/infrastructure_risk/case_1/__init__.py
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-avg_loss.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-dem_cl.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-event_ccl.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-event_efl.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-event_pcl.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-event_wcl.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/expected/infra-node_el.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/exposure.xml
  openquake/qa_tests_data/infrastructure_risk/case_1/exposure_demo_edges.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/exposure_demo_nodes.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/fragility_model.xml
  openquake/qa_tests_data/infrastructure_risk/case_1/job.ini
  openquake/qa_tests_data/infrastructure_risk/case_1/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/rupture_model.xml
  openquake/qa_tests_data/infrastructure_risk/case_1/site_model_measured.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/__init__.py
  openquake/qa_tests_data/infrastructure_risk/case_2/consequence_multiple_loss_types.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/expected/aggrisk-parent.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/expected/aggrisk.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/exposure.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/exposure_demo_edges.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/exposure_demo_nodes.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/fragility_model_landslide.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/fragility_model_liquefaction.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/fragility_model_structural.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/gmpe_logic_tree_ascr.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/job.ini
  openquake/qa_tests_data/infrastructure_risk/case_2/rupture.xml
  openquake/qa_tests_data/infrastructure_risk/case_2/site_model.csv
Labels: internal

#10127 Adding `with_betw_ratio` in Aristotle mode
  openquake/calculators/event_based.py
Labels: enhancement

#10128 Adding with_betw_ratio in Aristotle mode/2
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/event_based.py
  openquake/commands/plot.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/calc/conditioned_gmfs_test.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/scenario_risk/conditioned/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_risk/conditioned/gmpe_logic_tree_GEM_best_all_filtered_50_cataldi.xml
  openquake/qa_tests_data/scenario_risk/conditioned/job.ini
Labels: bug

#10131 Adding epistemic scaling factors for ParkerEtAl2020 GMM
  debian/changelog
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/parker_2020_epi_adj_table.csv
Labels: enhancement

#10132 add mgmpe changes to changelog
  debian/changelog
Labels: documentation

#10135 Refactored event_based_damage
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/riskmodels_test.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#10136 Added a test for multi-peril scenario_damage
  openquake/calculators/event_based_damage.py
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#10138 Making the multi_risk calculator closer to a scenario_damage
  openquake/calculators/base.py
  openquake/calculators/multi_risk.py
Labels: internal

#10130 Add a duplicates_strategy argument to read_df…
  debian/changelog
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: enhancement

#10139 add timezonefinder wheel and deps ad requirements on linux OS
  requirements-py310-linux64.txt
  requirements-py311-linux64.txt
  requirements-py312-linux64.txt
Labels: dependencies

#10144 Fixing formatting errors.
  doc/underlying-science/secondary-perils.rst
Labels: documentation

#10141 Change `check_dependencies` to retrieve versions from packages that expose it differently
  openquake/baselib/general.py
Labels: bug

#10145 Moved the test on check_dependencies
  bin/run-demos.sh
  openquake/baselib/tests/general_test.py
  openquake/commands/webui.py
Labels: internal

#10146 Enhanced gmfs_file to multiple .hdf5 files
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/oqvalidation_test.py
  openquake/hazardlib/site.py
Labels: enhancement, inputs

#10147 Fixed extract gmf_data
  openquake/calculators/extract.py
  openquake/calculators/tests/multi_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/abrahamson_2014.py
Labels: bug

#10148 Refactoring to homogenise GMM basin terms
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/afshari_stewart_2016.py
  openquake/hazardlib/gsim/aristeidou_2023.py
  openquake/hazardlib/gsim/bahrampouri_2021_duration.py
  openquake/hazardlib/gsim/bayless_abrahamson_2018.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/boore_2020.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/can20/can_shm6_interface.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/si_2020.py
Labels: internal

#10143 [WIP] Adding USGS basin scaling factors to required GMMs
  openquake/hazardlib/gsim/parker_2020.py
Labels: enhancement

#10149 Fixed demo broken by the basing term refactoring
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/can20/can_shm6_interface.py
Labels: internal

#10153 Forcing the signature (C, ctx, region) for _get_basin_term
  debian/changelog
  openquake/baselib/tests/flake8_test.py
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/aristeidou_2023.py
  openquake/hazardlib/gsim/bahrampouri_2021_duration.py
  openquake/hazardlib/gsim/bayless_abrahamson_2018.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/can20/can_shm6_interface.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/morikawa_fujiwara_2013.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/si_2020.py
Labels: internal

#10158 Extended damages-rlzs to multiple perils
  openquake/baselib/general.py
  openquake/calculators/classical_damage.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/views.py
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_continuous.csv
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_discrete.csv
  openquake/qa_tests_data/classical_damage/case_1/expected/damage_interpolation.csv
  openquake/qa_tests_data/classical_damage/case_1a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_1b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_1c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_continuous.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_discrete.csv
  openquake/qa_tests_data/classical_damage/case_2/expected/damage_interpolation.csv
  openquake/qa_tests_data/classical_damage/case_2a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_2b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_3a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_4c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_5a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_6a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_6b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7a/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7b/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_7c/expected/damages.csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-rlzs-AkkarBommer2010().csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-rlzs-SadighEtAl1997().csv
  openquake/qa_tests_data/classical_damage/case_8a/expected/damages-stats.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-007.csv
  openquake/qa_tests_data/event_based_damage/case_11/expected/avg_risk-rlz-000.csv
  openquake/qa_tests_data/event_based_damage/case_15/expected/avg_risk-mean.csv
  openquake/qa_tests_data/event_based_damage/case_16/dmgdist.txt
  openquake/qa_tests_data/scenario_damage/case_11/expected/avg_damages1.csv
  openquake/qa_tests_data/scenario_damage/case_17/expected/avg_damages-rlz-000_no_time_event.csv
  openquake/qa_tests_data/scenario_damage/case_17/expected/avg_damages-rlz-000_time_event_day.csv
  openquake/qa_tests_data/scenario_damage/case_2/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_3/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_4/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_5a/expected/damages-mean.csv
  openquake/qa_tests_data/scenario_damage/case_6/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_6/expected/dmg_by_taxon.csv
  openquake/qa_tests_data/scenario_damage/case_7/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_damage/case_9/expected/damages.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: outputs

#10161 Minor refactoring of multi_risk
  openquake/calculators/multi_risk.py
Labels: internal

#10112 ARISTOTLE: plot shakemap
  openquake/calculators/getters.py
  openquake/calculators/postproc/plots.py
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
  openquake/commands/tests/independence_test.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: enhancement

#10164 Added worldcities.csv
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/mosaic/worldcities.csv
Labels: enhancement

#10165 Added script `bin/arist`
  bin/arist
Labels: internal

#10168 ARISTOTLE: parsing tests
  openquake/calculators/postproc/plots.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/jsondata/us6000jllz-grid.xml
  openquake/hazardlib/tests/shakemap/jsondata/us6000jllz-rup.json
  openquake/hazardlib/tests/shakemap/jsondata/us6000jllz.json
  openquake/hazardlib/tests/shakemap/jsondata/usp0001ccb-grid.xml
  openquake/hazardlib/tests/shakemap/jsondata/usp0001ccb-rup.json
  openquake/hazardlib/tests/shakemap/jsondata/usp0001ccb.json
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal

#10171 Decoupling `aristotle.main_cmd` from the plots
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/views.py
Labels: bug

#10173 Moved `print_usgs_rupture` in oq info
  debian/changelog
  openquake/calculators/views.py
  openquake/commands/info.py
Labels: internal, inputs

#10175 Refactored `aristotle_validate`
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/jsondata/us6000jllz-stations.json
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/views.py
Labels: internal

#10177 Not storing non-interesting errors in convert_to_oq_rupture
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/source/rupture.py
  openquake/server/tests/test_aristotle_mode.py
Labels: internal

#10166 ARISTOTLE: handle corner case completing a job without producing aggrisk
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/views.py
Labels: bug

#10178 Removed useless code
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/tests/test_aristotle_mode.py
Labels: inputs

#10179 Added writeability check for `datadir` and `scratch_dir`
  debian/changelog
  openquake/engine/engine.py
Labels: enhancement

#10180 Aristotle: replaced slow tests with fast tests
  openquake/commands/info.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/data/fault_rupture.xml
  openquake/hazardlib/tests/shakemap/data/stationlist_seismic.csv
  openquake/hazardlib/tests/shakemap/data/us6000f65h.json
  openquake/hazardlib/tests/shakemap/data/us6000jllz-grid.xml
  openquake/hazardlib/tests/shakemap/data/us6000jllz-rup.json
  openquake/hazardlib/tests/shakemap/data/us6000jllz-stations.json
  openquake/hazardlib/tests/shakemap/data/us6000jllz.json
  openquake/hazardlib/tests/shakemap/data/usp0001ccb-grid.xml
  openquake/hazardlib/tests/shakemap/data/usp0001ccb-rup.json
  openquake/hazardlib/tests/shakemap/data/usp0001ccb.json
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal

#10181 ARISTOTLE: Do not call `plot_assets` 3 times
  openquake/calculators/base.py
  openquake/calculators/post_risk.py
Labels: performance

#10182 Added AristotleValidateTestCase.test_4
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/data/us7000n7n8-grid.xml
  openquake/hazardlib/tests/shakemap/data/us7000n7n8-rup.json
  openquake/hazardlib/tests/shakemap/data/us7000n7n8-stations.json
  openquake/hazardlib/tests/shakemap/data/us7000n7n8.json
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: internal
