Repository gem/oq-engine, pull requests merged in 2024-08, with the labels that each got.

#9882 G-times speedup and G-times memory reduction in event_based calculations
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
  openquake/hazardlib/tests/site_test.py
Labels: performance

#9881 Fix broken reference link
  openquake/hazardlib/calc/cond_spectra.py
Labels: documentation

#9884 Refined SLURM mode
  openquake/baselib/parallel.py
  openquake/baselib/workerpool.py
  openquake/commands/run.py
  openquake/commands/workers.py
  openquake/engine/openquake.cfg
Labels: enhancement

#9889 Add to taxonomy_mapping.csv the mappings for Canada and USA
  openquake/qa_tests_data/mosaic/taxonomy_mapping.csv
Labels: internal

#9891 Splitting in groups with homogeneous temporal occurrence model
  debian/changelog
  openquake/calculators/classical.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
Labels: internal

#9886 Splitting by blocks of gsims to avoid excessive tiling
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/source_reader.py
Labels: performance

#9893 Fixing problem with aliases
  debian/changelog
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
Labels: bug

#9890 fix: convert expectation of lognormal distribution to mean of normal
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
Labels: bug

#9895 Various refactoring
  openquake/baselib/performance.py
  openquake/calculators/classical.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/lt_test.py
Labels: internal

#9896 Optimized "computing pnes" in classical calculations (3x in the common case)
  debian/changelog
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/tests/lt_test.py
Labels: performance

#9898 Saving memory by using 32 bit rates
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
Labels: performance

#9900 Using 32 bit MapArrays
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/tests/lt_test.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/disagg/case_5/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist_Eps-0.csv
Labels: performance

#9901 Refactored `set_poes`
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/mgmpe/avg_poe_gmpe.py
  openquake/hazardlib/tests/gsim/base_site_test.py
Labels: internal

#9908 Added maximum_distance=magdist feature
  doc/user-guide/extras/faq.rst
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/compare.py
  openquake/commands/plot.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/calc/filters.py
Labels: performance

#9909 Implemented partial tiling
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
Labels: performance

#9911 Refactored storing the rates a bit
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
Labels: internal

#9912 Saving memory in the classical calculator by reducing the size of the .rmap
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/map_array.py
Labels: performance

#9914 Unified tiling
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/source/data/ctxt-got.csv
Labels: internal

#9915 When exporting gmfs, include secondary perils (if available)
  debian/changelog
  openquake/calculators/extract.py
Labels: enhancement
