Repository gem/oq-engine, pull requests merged in 2024-05, with the labels that each got.

#9626 Improved the check for missing site parameters
  debian/changelog
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_03/job_wrong.ini
Labels: enhancement

#9628 Checking consequences with residents
  debian/changelog
  openquake/calculators/base.py
Labels: enhancement, inputs

#9624 Check dependencies with the requirements
  openquake/baselib/general.py
  openquake/commands/webui.py
Labels: dependencies

#9630 Making SA(0) equivalent to PGA in hazardlib
  openquake/hazardlib/gsim/abrahamson_silva_1997.py
  openquake/hazardlib/gsim/boore_atkinson_2008.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/can15/eastern.py
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
Labels: internal

#9631 Discard stations from the avg_gmf plot
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_test.py
Labels: outputs

#9632 Fixed the check for development installations
  openquake/baselib/general.py
Labels: bug, dependencies

#9635 Fix in create_gmf_data when importing a CSV
  openquake/calculators/base.py
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_test.py
Labels: bug

#9621 Updating the existing CY14 backbone PR by Marco to work with 3.20.0 and recently refactored CY14 class
  openquake/hazardlib/gsim/can20/can_shm6_active_crust.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/chiou_youngs_2014/path_adjustment_table_target_region_idaho.txt
  openquake/hazardlib/gsim/chiou_youngs_2014/source_function_table.txt
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/tests/gsim/chiou_youngs_2014_test.py
Labels: enhancement

#9636 Added function pla_factor
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement

#9638 updating changelog for CY14 refactoring PR
  debian/changelog
Labels: documentation

#9640 Initial implementation of Post Loss Amplification
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/tests/event_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/gmf_ebrisk/case_6/__init__.py
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggcurves-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggcurves.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/exposure.xml
  openquake/qa_tests_data/gmf_ebrisk/case_6/gmfs.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/job.ini
  openquake/qa_tests_data/gmf_ebrisk/case_6/pla_model.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/sites.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/structural.xml
  openquake/risklib/scientific.py
Labels: enhancement

#9642 Some refactoring for PLA
  openquake/calculators/post_risk.py
  openquake/risklib/scientific.py
Labels: internal

#9645 Fixed a bug in `oq extract "ruptures?rup_id=XXX`
  debian/changelog
  openquake/calculators/getters.py
Labels: bug, outputs, backport

#9647 Added a check to forbid `individual_rlzs=true` and `collect_rlzs=true`
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/logictree/case_17/job.ini
Labels: inputs

#9649 Removed the XML exporters deprecated years ago
  doc/api-reference/openquake.commonlib.rst
  openquake/calculators/export/hazard.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/tests/expected_hazard_curves.xml
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/qa_tests_data/classical/case_12/expected_hazard_curves.xml
  openquake/qa_tests_data/classical/case_18/expected/uhs-rlz-1.xml
  openquake/qa_tests_data/classical_bcr/case_1/hazard_curve-mean.xml
  openquake/qa_tests_data/classical_damage/case_master/expected/hazard_curve-mean-PGA.xml
  openquake/qa_tests_data/classical_damage/case_master/expected/hazard_curve-mean-SA(0.1).xml
  openquake/qa_tests_data/classical_damage/case_master/expected/hazard_curve-mean-SA(0.3).xml
  openquake/qa_tests_data/event_based/case_1/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/qa_tests_data/event_based/case_21/expected/hazard_curve-smltp_b1-gsimltp_b1-PGA.xml
  openquake/qa_tests_data/logictree/case_02/expected_hazard_curves.xml
  openquake/qa_tests_data/logictree/case_15/expected/hazard_uhs-mean-0.01.xml
  openquake/qa_tests_data/logictree/case_15/expected/hazard_uhs-mean-0.1.xml
  openquake/qa_tests_data/logictree/case_15/expected/hazard_uhs-mean-0.2.xml
  openquake/risklib/nrml_examples/uhs-mean.xml
  openquake/risklib/nrml_examples/uhs-quantile.xml
  openquake/risklib/nrml_examples/uhs.xml
Labels: internal, outputs

#9651 Fixed post loss amplification for aggrisk
  openquake/calculators/post_risk.py
  openquake/calculators/tests/event_risk_test.py
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-id-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk_bis.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/job2.ini
  openquake/risklib/scientific.py
Labels: enhancement, outputs

#9652 Renamed event_risk_test -> gmf_ebrisk_test
  openquake/calculators/tests/gmf_ebrisk_test.py
Labels: internal

#9653 Mmax relative uncertainty without moment balancing
  debian/changelog
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/qa_tests_data/logictree/README.md
  openquake/qa_tests_data/logictree/case_84/__init__.py
  openquake/qa_tests_data/logictree/case_84/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/logictree/case_84/gmclt.xml
  openquake/qa_tests_data/logictree/case_84/job.ini
  openquake/qa_tests_data/logictree/case_84/job_test.ini
  openquake/qa_tests_data/logictree/case_84/ssclt.xml
  openquake/qa_tests_data/logictree/case_84/ssclt_test.xml
  openquake/qa_tests_data/logictree/case_84/ssm.xml
  openquake/qa_tests_data/logictree/case_84/ssmA.xml
  openquake/qa_tests_data/logictree/case_84/ssmB.xml
Labels: enhancement

#9592 [WIP] changing comparison point of tolerance for the kite fault meshes
  openquake/hazardlib/geo/surface/kite_fault.py
Labels: internal

#9655 Add Attenuation Model of Ghasemi2009
  CONTRIBUTORS.txt
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/ghasemi_2009.py
  openquake/hazardlib/tests/gsim/data/Ghasemi09.csv
  openquake/hazardlib/tests/gsim/ghasemi_2009_test.py
Labels: enhancement

#9641 Using custom `hcurves` and `uhs` exporters in AELO mode
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/engine/tests/aelo_test.py
Labels: outputs

#9656 Overhauled a bit the FAQ
  doc/user-guide/extras/faq.rst
Labels: documentation

#9657 Added another check for missing gsim in scenario calculations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario/case_2/job_wrong.ini
Labels: enhancement, inputs

#9660 set pyzmq to 26.0.3
  debian/changelog
  requirements-py310-win64.txt
  requirements-py311-win64.txt
  requirements-py39-win64.txt
Labels: dependencies

#9661 update pyzmq to 26.0.3
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#9659 Documenting oq show delta_loss
  doc/user-guide/extras/faq.rst
  openquake/calculators/views.py
Labels: documentation

#9662 Changed the UHS exporter in AELO mode
  openquake/calculators/export/hazard.py
  openquake/engine/tests/aelo_test.py
Labels: outputs

#9664 Documented griddedRupture
  doc/user-guide/inputs/rupture-model.rst
  doc/user-guide/inputs/seismic-source-model.rst
Labels: documentation

#9663 Updated docs for the event based outputs
  doc/getting-started/demos-tutorials/index.rst
  doc/user-guide/outputs/event-based-psha-outputs.rst
  doc/user-guide/special-features.rst
Labels: documentation

#9665 Improved `oq info mfd` and added `oq info msr`
  doc/user-guide/index.rst
  doc/user-guide/workflows/index.rst
  openquake/commands/info.py
Labels: documentation

#9666 Documenting the site parameters
  doc/user-guide/configuration-file/hazard-calculations.rst
  openquake/commands/info.py
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_MEAN.csv
  openquake/hazardlib/tests/gsim/data/PEZE11/PZ11_STD_TOTAL.csv
Labels: documentation

#9667 Restored check on the Python version in install.py
  install.py
Labels: dependencies

#9668 Improved `oq info imt` and `oq info gsim`
  doc/user-guide/useful-oq-commands.rst
  openquake/commands/info.py
Labels: documentation

#9669 Fixed the passing of parameters in `NRCan15SiteTerm`
  debian/changelog
  doc/user-guide/inputs/ground-motion-models.rst
  openquake/hazardlib/gsim/mgmpe/nrcan15_site_term.py
Labels: bug, documentation

#9671 Saving disk space in conditioned GMFs calculations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: performance

#9672 Saving memory in conditioned scenarios
  openquake/baselib/performance.py
  openquake/baselib/tests/performance_test.py
  openquake/calculators/event_based.py
Labels: performance

#9670 Adding asce_version parameter
  openquake/commands/mosaic.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/aelo.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: inputs

#9673 Add to the webui the possibility to disable the warning about the existence of a newer engine release
  openquake/server/local_settings.py.aelo
  openquake/server/settings.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/base.html
  openquake/server/utils.py
Labels: enhancement

#9675 Saving between 25% and 33% of the memory in conditioned scenarios
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: performance

#9676 Explicit unlink of the shared memory
  openquake/baselib/performance.py
  openquake/calculators/event_based.py
Labels: internal

#9678 Improve form layouts
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9680 Improved shared memory management
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/baselib/tests/parallel_test.py
  openquake/baselib/tests/performance_test.py
  openquake/calculators/event_based.py
Labels: internal

#9679 Fixed "slow lane" for the New Zealand model
  debian/changelog
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/source/multi_fault.py
Labels: bug

#9683 Extended the `delta_loss` warning to scenario_risk
  debian/changelog
  doc/user-guide/extras/faq.rst
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
Labels: enhancement

#9684 Removed delta_loss warnings in the demos
  demos/risk/EventBasedRisk/job.ini
  demos/risk/EventBasedRisk/job_eb.ini
  demos/risk/Reinsurance/job.ini
  openquake/calculators/views.py
Labels: documentation

#9658 Add Vertical Component to Abrahamson_Silva 1997
  CONTRIBUTORS.txt
  debian/changelog
  openquake/hazardlib/gsim/abrahamson_silva_1997.py
  openquake/hazardlib/tests/gsim/abrahamson_silva_1997_test.py
  openquake/hazardlib/tests/gsim/data/AS97/AS97_MEAN_DS_V.csv
  openquake/hazardlib/tests/gsim/data/AS97/AS97_MEAN_ROCK_V.csv
  openquake/hazardlib/tests/gsim/data/AS97/AS97_STD_TOTAL_V.csv
Labels: enhancement

#9689 Reduced the memory consumption and improved the performance in postclassical
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/getters.py
Labels: performance

#9691 Solved New Zealand model ultra-slow on "Applying uncertainties"
  openquake/hazardlib/logictree.py
  openquake/hazardlib/tests/gsim/data/AS97/AS97_MEAN_DS_V.csv
  openquake/hazardlib/tests/gsim/data/AS97/AS97_MEAN_ROCK_V.csv
  openquake/hazardlib/tests/gsim/data/AS97/AS97_STD_TOTAL_V.csv
Labels: performance

#9692 Added utilities dumpa/loada
  openquake/baselib/general.py
Labels: internal

#9693 Refined `delta_loss` to work by gsim
  doc/user-guide/extras/faq.rst
  openquake/calculators/views.py
Labels: internal

#9694 Added method PmapGetter.get_mean_rates
  openquake/calculators/getters.py
Labels: internal

#9695 Renamed ProbabilityMap->MapArray
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/probability_map.py
Labels: internal

#9696 Finally removed the ProbabilityCurve
  doc/contributing/developing-with-the-engine.rst
  openquake/calculators/classical.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/conditional_spectrum.py
  openquake/commonlib/calc.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/calc_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/calc/hazard_curve_test.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/risklib/scientific.py
Labels: internal

#9682 Add a command to plot gmf values per site for each event id/2
  debian/changelog
  openquake/calculators/extract.py
  openquake/commands/plot.py
Labels: internal

#9697 Moving webui tests for ARISTOTLE to the mosaic repo
  .github/workflows/engine_pr_test.yml
  openquake/server/tests/test_aelo_mode.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/tests/views_test.py
  openquake/server/views.py
Labels: internal

#9690 Installation instruction for python3.11and oq-engine on macos
  doc/getting-started/installation-instructions/_images/macos/download_python.png
  doc/getting-started/installation-instructions/_images/macos/install_certifi_1.png
  doc/getting-started/installation-instructions/_images/macos/install_certifi_2.png
  doc/getting-started/installation-instructions/_images/macos/install_certifi_3.png
  doc/getting-started/installation-instructions/_images/macos/openssl.png
  doc/getting-started/installation-instructions/_images/macos/run_installer.png
  doc/getting-started/installation-instructions/index.rst
  doc/getting-started/installation-instructions/macos.rst
  doc/getting-started/installation-instructions/universal.md
  doc/getting-started/running-calculations/web-ui.rst
Labels: documentation

#9700 Optimized the calculation of mean hazard curves when `use_rates=true`
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_bcr.py
  openquake/calculators/classical_damage.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/getters.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  utils/combine_mean_curves.py
  utils/compare_mean_curves.py
Labels: performance

#9702 Add the arguments maximum_distance and number_of_ground_motion_fields to the oq mosaic aristotle command
  openquake/commands/mosaic.py
Labels: internal

#9703 Reduced memory consumption in the realization weights
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/classical_risk.py
  openquake/calculators/disaggregation.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: performance

#9706 More than doubled the speed of get_rlzs_by_gsim
  debian/changelog
  openquake/calculators/base.py
  openquake/hazardlib/logictree.py
Labels: performance

#9707 Removed reduce-rlzs feature
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-001-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-002-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-003-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-004-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-005-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-006-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-007-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-008-PGA.csv
  openquake/qa_tests_data/logictree/case_68/expected/hazard_curve-rlz-009-PGA.csv
Labels: internal

#9705 Improved the speed of `get_rlzs_by_gsim` again
  openquake/hazardlib/logictree.py
Labels: performance

#9711 Avoid setting the OQ_APPLICATION_MODE env variable outside the context of the webui
  openquake/server/settings.py
  openquake/server/utils.py
Labels: internal

#9699 Documentation improvements
  doc/contributing/developing-with-the-engine.rst
  doc/contributing/development-guidelines.md
  doc/contributing/testing.md
  doc/getting-started/installation-instructions/_images/windows/01_Windows_warning.png
  doc/getting-started/installation-instructions/_images/windows/02_Run_anyway.png
  doc/getting-started/installation-instructions/_images/windows/03_Installer_start.png
  doc/getting-started/installation-instructions/_images/windows/04_License.png
  doc/getting-started/installation-instructions/_images/windows/05_Uninstall.png
  doc/getting-started/installation-instructions/_images/windows/06_Stop_Processes.png
  doc/getting-started/installation-instructions/_images/windows/07_Uninstalling.png
  doc/getting-started/installation-instructions/_images/windows/08_Uninstall_Complete.png
  doc/getting-started/installation-instructions/_images/windows/09_Installer_Components.png
  doc/getting-started/installation-instructions/_images/windows/10_Install_Location.png
  doc/getting-started/installation-instructions/_images/windows/11_Installing.png
  doc/getting-started/installation-instructions/_images/windows/12_Complete.png
  doc/getting-started/installation-instructions/_images/windows/13_Desktop_Icons.png
  doc/getting-started/installation-instructions/_images/windows/14_Win11_Start_menu.png
  doc/getting-started/installation-instructions/_images/windows/15_Starting_webui_wait.png
  doc/getting-started/installation-instructions/_images/windows/16_webui_up.png
  doc/getting-started/installation-instructions/development.md
  doc/getting-started/installation-instructions/development.rst
  doc/getting-started/installation-instructions/docker.md
  doc/getting-started/installation-instructions/index.rst
  doc/getting-started/installation-instructions/macos.rst
  doc/getting-started/installation-instructions/rhel.md
  doc/getting-started/installation-instructions/server.md
  doc/getting-started/installation-instructions/ubuntu-nightly.md
  doc/getting-started/installation-instructions/ubuntu.md
  doc/getting-started/installation-instructions/universal.md
  doc/getting-started/installation-instructions/windows.md
  doc/getting-started/installation-instructions/windows.rst
  doc/getting-started/running-calculations/unix.rst
  doc/getting-started/running-calculations/web-ui.rst
  doc/user-guide/extras/faq.rst
Labels: documentation

#9712 Removed .gitattribues for CSV
  .gitattributes
Labels: internal

#9713 Added some pointers to what installation method to use
  CONTRIBUTORS.txt
  debian/changelog
  doc/getting-started/installation-instructions/index.rst
  doc/user-guide/extras/faq.rst
  openquake/baselib/tests/flake8_test.py
  openquake/hmtk/seismicity/gcmt_catalogue.py
  openquake/hmtk/tests/seismicity/gcmt_catalogue_test.py
Labels: documentation

#9714 Restored warning when setting maximum_distance for a TRT missing in the gsim_lt
  .github/workflows/engine_pr_test.yml
  openquake/commonlib/oqvalidation.py
Labels: inputs

#9715 Raised the default `max_potential_paths` to 1,000,000
  debian/changelog
  openquake/commonlib/oqvalidation.py
Labels: enhancement

#9720 Fixing the post loss amplification/1
  openquake/calculators/post_risk.py
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-id-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk_bis.csv
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: enhancement

#9721 Fixing the post loss amplification/2
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggcurves-id-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggcurves-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-id-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk-pla.csv
  openquake/qa_tests_data/gmf_ebrisk/case_6/expected/aggrisk_bis.csv
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
Labels: outputs

#9717 Minor edits to whats-new.md
  doc/release-notes/whats-new.md
Labels: documentation

#9719 Include PLA documentation
  doc/user-guide/configuration-file/risk-calculations.rst
Labels: documentation

#9722 Added test with AEP, OEP and PLA
  openquake/calculators/tests/event_based_risk_test.py
  openquake/hmtk/tests/seismicity/gcmt_catalogue_test.py
  openquake/qa_tests_data/event_based_risk/case_9/__init__.py
  openquake/qa_tests_data/event_based_risk/case_9/expected/aggcurves-.csv
  openquake/qa_tests_data/event_based_risk/case_9/expected/aggrisk-.csv
  openquake/qa_tests_data/event_based_risk/case_9/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/case_9/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_9/gmpe_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_9/job.ini
  openquake/qa_tests_data/event_based_risk/case_9/pla_model.csv
  openquake/qa_tests_data/event_based_risk/case_9/site_model.csv
  openquake/qa_tests_data/event_based_risk/case_9/source_model.xml
  openquake/qa_tests_data/event_based_risk/case_9/source_model_logic_tree.xml
  openquake/qa_tests_data/event_based_risk/case_9/structural_vulnerability_model.xml
  openquake/risklib/scientific.py
Labels: enhancement

#9724 Changed the risk_by_event exporter to sort the losses
  openquake/calculators/export/risk.py
  openquake/hmtk/tests/seismicity/gcmt_catalogue_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_2/expected/agg_losses.csv
  openquake/qa_tests_data/event_based_risk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_1.csv
  openquake/qa_tests_data/scenario_damage/case_11/expected/risk_by_event_2.csv
  openquake/qa_tests_data/scenario_damage/case_1c/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_4b/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_8/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_risk/case_1/expected/risk_by_event.csv
  openquake/risklib/tests/scientific_test.py
Labels: outputs

#9723 Avoid checking webui variables at import time
  openquake/server/apps.py
  openquake/server/settings.py
  openquake/server/tests/test_aelo_mode.py
  openquake/server/tests/test_public_mode.py
  openquake/server/tests/test_read_only_mode.py
  openquake/server/utils.py
Labels: internal

#9726 Fix templates for AELO and ARISTOTLE local settings
  openquake/server/local_settings.py.aelo_aristotle
Labels: internal

#9727 Minor Numba refactoring
  openquake/hazardlib/geo/line.py
Labels: internal

#9716 What's New for engine 3.20
  doc/release-notes/whats-new.md
Labels: documentation

#9728 Fixed the view aggrisk
  openquake/calculators/views.py
Labels: outputs

#9729 Added variable OQ_DEBUG_SITE
  openquake/calculators/extract.py
  openquake/commonlib/readinput.py
Labels: internal

#9734 Added command `oq reducexp exposure_xml site_model_csv`
  debian/changelog
  openquake/commands/reducexp.py
Labels: internal, inputs

#9735 Extended `oq mosaic aristotle` to start from a rupture_model_file
  openquake/commands/mosaic.py
Labels: internal

#9730 add django_cors_headers into requirements for application mode TOOLS
  openquake/baselib/general.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#9731 Add debug commands `oq compare assetcol` and `oq compare sitecol`
  debian/changelog
  openquake/commands/compare.py
  openquake/commands/tests/commands_test.py
Labels: internal
