Repository gem/oq-engine, pull requests merged in 2024-04, with the labels that each got.

#9559 Resetting the exposure cache in the WebUI
  openquake/commonlib/readinput.py
  openquake/server/views.py
Labels: bug

#9558 Reduce marker size in plots for assets and avg_gmf
  openquake/commands/plot.py
  openquake/commands/plot_assets.py
Labels: enhancement

#9562 Added check for missing vs30
  openquake/calculators/event_based.py
Labels: enhancement, inputs

#9566 Remove unneeded tests for the engine server in aelo mode for Windows
  .github/workflows/windows_test.yml
Labels: enhancement

#9568 Extended numba types in project_direct/project_reverse
  openquake/hazardlib/geo/utils.py
Labels: bug

#9564 Aristotle: add email notifications on calculation completed or error
  .github/workflows/engine_pr_test.yml
  openquake/engine/aristotle.py
  openquake/engine/engine.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/templates/engine/index.html
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/views.py
Labels: enhancement

#9573 Make it possible to specify the mosaic_dir in aristotle calculations
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/server/views.py
Labels: bug

#9561 Forbidden characters .:; in the branchID
  debian/changelog
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
Labels: inputs

#9574 Removed the Global cache
  openquake/calculators/base.py
  openquake/calculators/reportwriter.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/commonlib/tests/reinsurance_test.py
  openquake/engine/aristotle.py
  openquake/engine/engine.py
Labels: internal

#9575 Managed duplicated multi fault sources in event based
  debian/changelog
  openquake/hazardlib/source_reader.py
Labels: enhancement, inputs

#9576 Fixed the file famous_ruptures.csv
  openquake/commands/mosaic.py
  openquake/qa_tests_data/mosaic/famous_ruptures.csv
Labels: internal

#9577 Improved error message in oq mosaic aristotle
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/views.py
Labels: internal

#9580 Do not set minimum_intensity in Aristotle calculations
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/mosaic/famous_ruptures.csv
  openquake/risklib/riskmodels.py
Labels: performance, enhancement

#9565 Tools cookie consent
  openquake/server/local_settings.py.tools
  openquake/server/settings.py
  openquake/server/urls.py
Labels: enhancement

#9581 Downloading shakemap_polygon.txt
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/source/rupture.py
Labels: enhancement

#9582 Enlarged buffer and fixed logging
  openquake/calculators/event_based.py
  openquake/commands/mosaic.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/aelo.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
Labels: enhancement

#9584 Fixed `avg_losses-stats` exporter in the case of a single realization
  debian/changelog
  openquake/calculators/export/risk.py
  openquake/calculators/tests/classical_risk_test.py
  openquake/qa_tests_data/classical_risk/case_2/expected/avg_losses-mean.csv
Labels: bug, outputs

#9585 Some cleanup in the Canadian GMPEs
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
Labels: internal

#9586 Fixed scenario with CanadaSHM6 GMPEs and ModifiableGMPE
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/qa_tests_data/scenario/case_32/__init__.py
  openquake/qa_tests_data/scenario/case_32/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_32/gsim_lt.xml
  openquake/qa_tests_data/scenario/case_32/job.ini
  openquake/qa_tests_data/scenario/case_32/rupture.csv
  openquake/qa_tests_data/scenario/case_32/site_model.csv
Labels: bug

#9583 Aristotle: show the name of the mosaic model covering the given (lon, lat)
  openquake/engine/aristotle.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: bug, enhancement

#9588 ARISTOTLE: disable button to retrieve trts and enable it if lon or lat are changed and they are both non-empty
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
Labels: enhancement

#9589 Fixed multifault splitting
  openquake/hazardlib/source/multi_fault.py
Labels: internal

#9590 Reduced the memory consumption in classical calculations
  openquake/hazardlib/contexts.py
Labels: performance

#9591 Fixed error message for minimum_magnitude
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/filters.py
Labels: inputs

#9593 Fixed mixture_model feature
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/case_47/expected/hazard_curve-rlz-000-PGA.csv
  openquake/qa_tests_data/classical/case_47/expected/hazard_curve-rlz-001-PGA.csv
Labels: bug

#9595 Removed **kwargs from the GMPE signatures
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_2015.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/akkar_2014.py
  openquake/hazardlib/gsim/ameri_2017.py
  openquake/hazardlib/gsim/atkinson_boore_2006.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/bchydro_2016_epistemic.py
  openquake/hazardlib/gsim/bindi_2014.py
  openquake/hazardlib/gsim/bindi_2017.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/can15/nbcc2015_aa13.py
  openquake/hazardlib/gsim/can20/can_shm6_stable.py
  openquake/hazardlib/gsim/cauzzi_2014.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/derras_2014.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/gmpe_table.py
  openquake/hazardlib/gsim/gulerce_abrahamson_2011.py
  openquake/hazardlib/gsim/hassani_atkinson_2018.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/lanzano_2019.py
  openquake/hazardlib/gsim/mgmpe/cy14_site_term.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/mgmpe/split_sigma_gmpe.py
  openquake/hazardlib/gsim/multi.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/nz22/atkinson_2022.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/projects/acme_2019.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/sgobba_2020.py
  openquake/hazardlib/gsim/stewart_2016.py
  openquake/hazardlib/gsim/tromans_2019.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/gsim/yenier_atkinson_2015.py
  openquake/hazardlib/gsim/zhao_2016.py
  openquake/hazardlib/gsim/zhao_2016_volc_perg/volc_perg.py
  openquake/hazardlib/tests/gsim/mgmpe/cy14_site_term_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
  openquake/hazardlib/tests/gsim/zhao_2016_perg_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/mosaic/EUR/in/gmmLT.xml
Labels: enhancement, internal

#9597 Avoid instantiating GsimLogicTree twice
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim_lt.py
Labels: internal

#9598 Improved event_based/case_19
  openquake/calculators/tests/event_based_test.py
  openquake/qa_tests_data/event_based/case_19/expected/avg_gmf.csv
Labels: internal

#9599 Avoided reading the site model multiple times
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
Labels: internal

#9600 Avoided instantiating gsim_lt too much
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim_lt.py
Labels: internal

#9601 Splitting aristotle.main into `main_cmd` and `main_web`
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/server/views.py
Labels: internal

#9596 [WIP] Aki and Richards test fix
  openquake/hazardlib/geo/surface/complex_fault.py
Labels: inputs

#9604 Replacing round with numpy.round
  openquake/hazardlib/gsim/gmpe_table.py
Labels: internal

#9606 Clarification of USGS CEUS 2018 GMPE docstring
  openquake/hazardlib/gsim/usgs_ceus_2019.py
Labels: documentation

#9602 Adding the ability to start an Aristotle computation from a rupture_model.xml
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/server/views.py
Labels: enhancement, inputs

#9608 Extended `forbid_long_funcs` to commonlib
  openquake/baselib/tests/flake8_test.py
  openquake/commonlib/hazard_writers.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
Labels: internal

#9612 Added limit on the number of function arguments (16)
  debian/changelog
  openquake/baselib/tests/flake8_test.py
  openquake/commands/mosaic.py
  openquake/engine/aristotle.py
  openquake/server/views.py
Labels: internal

#9603 Documented some disaggregation outputs
  doc/underlying-science/PSHA-with-OQ-engine.rst
  doc/user-guide/outputs/disaggregation-outputs.rst
Labels: documentation

#9613 Limited the functions in hmtk to 100 lines
  openquake/baselib/general.py
  openquake/baselib/tests/flake8_test.py
  openquake/hmtk/plotting/beachball.py
  openquake/hmtk/seismicity/smoothing/smoothed_seismicity.py
  openquake/hmtk/tests/faults/test_active_fault_model.py
  openquake/hmtk/tests/parsers/strain/test_csv_parser.py
  openquake/hmtk/tests/seismicity/test_seismicity_utils.py
Labels: internal

#9615 Better error message when converting griddedSurfaces
  openquake/hazardlib/sourceconverter.py
Labels: enhancement, inputs

#9617 Aristotle: improve layout of the outputs page
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/get_outputs_aristotle.html
Labels: enhancement

#9619 Documentation: fix cross references and warnings
  .github/workflows/docs.yml
  doc/conf.py
  doc/contributing/development-guidelines.md
  doc/contributing/testing.md
  doc/getting-started/installation-instructions/development.md
  doc/getting-started/installation-instructions/ubuntu.md
  doc/requirements.txt
  doc/user-guide/extras/faq.rst
  doc/user-guide/extras/index.rst
  doc/user-guide/index.rst
  doc/user-guide/outputs/classical-psha-outputs.rst
  doc/user-guide/outputs/disaggregation-outputs.rst
  openquake/server/OaaS.md
  setup.py
Labels: documentation

#9616 Added a check when importing hazard_curves
  debian/changelog
  openquake/calculators/tests/classical_risk_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical_risk/case_2/hazard_curve-mean-prob_above1.csv
  openquake/qa_tests_data/classical_risk/case_2/hazard_curve-mean-prob_below0.csv
  openquake/qa_tests_data/classical_risk/case_2/job_risk-prob_above1.ini
  openquake/qa_tests_data/classical_risk/case_2/job_risk-prob_below0.ini
Labels: inputs

#9622 ARISTOTLE: fix retrieving rupture dict by usgs_id from the webui
  openquake/engine/aristotle.py
  openquake/server/views.py
Labels: bug

#9623 Fixed the serialization of the logic tree in 3 tricky cases
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/logictree_test.py
  openquake/commands/info.py
  openquake/commands/renumber_sm.py
  openquake/commands/sample.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/logictree.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
Labels: internal
