Repository gem/oq-engine, pull requests merged in 2024-02, with the labels that each got.

#9403 Using numba in line and multiline
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: performance

#9404 Restored the distance cache
  openquake/baselib/general.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9405 AELO: make outputs visualizable also for old calculations with ASCE tables stored as scalars
  openquake/server/views.py
Labels: enhancement

#9406 Refactored `closest_point` to take advantage of the MultiFault cache
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9407 Using numba in `get_spherical_bounding_box`
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/simple_fault.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: performance

#9408 Removed redundant projections in `Line.get_tu`
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/site.py
Labels: performance

#9409 Refactored the contexts and introduced a function build_ctx
  openquake/hazardlib/contexts.py
Labels: internal

#9410 Refactored a bit more the MultiLine class
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: internal

#9411 Refactored the MultiLine class some more
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/base.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
Labels: performance

#9412 Refactored `closest_point` "distance"
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/zhao_2016.py
  openquake/hazardlib/tests/contexts_test.py
Labels: performance

#9413 Minor refactoring of clon, clat
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/gsim/base_test.py
Labels: internal

#9414 Specialized multiFaultSources
  openquake/calculators/base.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal

#9415 Fixed the distance cache introduced in https://github.com/gem/oq-engine/pull/9404
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/source/data/ctxt.csv
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9416 Another fix to the distance cache
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/source/data/ctxt.csv
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: bug, internal

#9419 Storing the rupture_idxs in the file `_tmp.hdf5`
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
Labels: performance

#9420 Refined KiteSurfaces
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9421 Refactoring saving multi point sources to HDF5
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/surface/complex_fault.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/geo/surface/simple_fault.py
  openquake/hazardlib/nrml_to.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
  openquake/hazardlib/tests/sourceconverter_test.py
Labels: internal

#9422 Moving the calculation of u_max in preclassical
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9417 Fixed disaggregation for mutex sources
  debian/changelog
  openquake/calculators/disaggregation.py
  openquake/calculators/views.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/disagg/case_11/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_9/expected/Mag_Dist_Eps-0.csv
Labels: bug, backport

#9424 Optimized calculation of the MultiSurface parameters
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9425 Optimized the calculation of the bounding box for MultiFaultSources
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9428 Finally removed the dependency from the legacy contexts
  openquake/calculators/extract.py
  openquake/hazardlib/contexts.py
Labels: internal

#9429 Removed the dcache again
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/multi_fault.py
Labels: performance, internal

#9430 Optimized the distance calculations in multi fault sources/1
  openquake/calculators/preclassical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9431 Refactoring Line and Multiline a bit more
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: internal

#9432 Fixed the change in the AELO numbers for China
  openquake/hazardlib/source/multi_fault.py
Labels: critical

#9435 Refactored MultiLine to help debugging
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal

#9436 Yet another refactoring of MultiLine
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: internal

#9437 Optimized the distance calculations in multi fault sources/2
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/kite_fault.py
Labels: performance

#9438 Turned the performance test into a regular test
  openquake/hazardlib/tests/source/data/ctxt.csv
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal

#9439 Small refactoring of `get_secdists`
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: internal

#9440 Removed requirements files for Python 3.8
  requirements-py38-linux64.txt
  requirements-py38-macos_x86_64.txt
  requirements-py38-win64.txt
Labels: dependencies

#9441 Fixed flipped indices
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/multiline.py
Labels: bug

#9445 Added view `oq show rup:<source_id>`
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/qa_tests_data/classical/case_75/expected/context.org
Labels: internal

#9446 Fixed another bug in CHN for AELO
  openquake/hazardlib/contexts.py
Labels: bug

#9443 Always use annual rates for mean_rates_by_src
  openquake/calculators/classical.py
  openquake/calculators/tests/disagg_test.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/tests/postproc_test.py
  openquake/qa_tests_data/classical/case_27/expected/hazard_curve.csv
  openquake/qa_tests_data/classical/case_27/expected/mean_rates_by_src.csv
  openquake/qa_tests_data/classical/case_82/expected/mean_rates_by_src.csv
  openquake/qa_tests_data/disagg/case_15/__init__.py
  openquake/qa_tests_data/disagg/case_15/gmmLT.xml
  openquake/qa_tests_data/disagg/case_15/job_1yr.ini
  openquake/qa_tests_data/disagg/case_15/job_50yr.ini
  openquake/qa_tests_data/disagg/case_15/sites_cea_res6.csv
  openquake/qa_tests_data/disagg/case_15/ssm/src.xml
  openquake/qa_tests_data/disagg/case_15/ssmLT.xml
Labels: outputs

#9447 Removed useless and dangerous operation `to_rates(to_probs(rates))`
  debian/changelog
  openquake/calculators/getters.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
Labels: bug, outputs

#9448 Fixed `oq compare`
  debian/changelog
  openquake/commands/compare.py
Labels: bug, internal

#9450 Fixed the reading of ruptures with a multisurface with meshes of different lengths
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/source/rupture.py
  openquake/qa_tests_data/scenario/case_31/__init__.py
  openquake/qa_tests_data/scenario/case_31/job.ini
  openquake/qa_tests_data/scenario/case_31/rupture.csv
  openquake/qa_tests_data/scenario/case_31/site_model.csv
Labels: bug, inputs

#9453 Additional refactoring of multi fault sources
  openquake/calculators/preclassical.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
Labels: internal

#9426 Update aelo plots
  openquake/calculators/postproc/aelo_plots.py
Labels: outputs

#9455 Merging MSPARAMS and SECPARAMS
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/geo/utils.py
Labels: internal

#9452 removing pgv from NathEtAl2012 given provides physically unrealistic values and can't be corrected
  openquake/hazardlib/gsim/nath_2012.py
Labels: enhancement

#9456 ~Avoided computing t, u parameters twice~
  openquake/hazardlib/contexts.py
Labels: performance

#9457 Avoided computing t, u parameters twice
  openquake/hazardlib/contexts.py
Labels: performance

#9458 Turned the occurrence rates into a property
  openquake/commonlib/tests/hazard_writers_test.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source/multi_fault.py
Labels: performance

#9460 Switched `tuw` parameters to 32 bit
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
Labels: performance

#9461 Added method MultiLine.set_u_max
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
Labels: internal

#9462 Doubled the speed of single site calculations with multiFaultSources
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
Labels: performance

#9463 Doubled the speed of the preclassical calculator
  openquake/calculators/preclassical.py
  openquake/commonlib/tests/source_test.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
Labels: performance

#9464 Doubled the speed of preclassical again
  openquake/hazardlib/geo/mesh.py
  openquake/hazardlib/geo/surface/gridded.py
  openquake/hazardlib/geo/utils.py
  openquake/hazardlib/source/non_parametric.py
  openquake/hazardlib/tests/geo/geodetic_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/utils_test.py
Labels: performance

#9466 Rounded magnitudes in the SourceConverter also for multiFaultSources
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
Labels: performance

#9467 Fix instructions to install tools
  doc/getting-started/installation-instructions/tools.md
Labels: bug

#9469 Fixed check_input for MultiFaultSources
  openquake/calculators/classical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/source_reader.py
Labels: internal

#9470 Refined the secparams a bit by storing the hypocenter as a 3D array
  openquake/calculators/preclassical.py
  openquake/hazardlib/geo/surface/multi.py
Labels: internal

#9427 Source IDs are still duplicated :-(
  debian/changelog
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/classical/case_03/source_model_2.xml
Labels: bug

#9472 Discarded multifault ruptures involving only far away sections in preclassical
  openquake/calculators/preclassical.py
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9473 Fixed prefiltering of multifault sources
  openquake/calculators/preclassical.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/source/multi_fault.py
Labels: bug

#9475 Numbifying `get_ui_ti`
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/tests/geo/line_test.py
Labels: performance

#9474 Added function to download rupture.json
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap/parsers.py
Labels: enhancement, inputs

#9476 Extended `oq mosaic run_site` to compute both asce41 and asce07
  openquake/commands/mosaic.py
Labels: enhancement, internal

#9477 Using numba more in MultiLine
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
Labels: performance

#9480 Yet another refactoring of MultiLine
  openquake/calculators/preclassical.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal

#9484 Fixed exporting from calculations with a grand parent
  debian/changelog
  openquake/commonlib/datastore.py
Labels: bug, outputs, backport

#9485 Restored the old signature of the MultiFaultSource class
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal, inputs

#9487 Optimized the calculation of u_max a bit more
  .github/workflows/engine_pr_test.yml
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/contexts_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: performance

#9488 Add geometry_file to discard ruptures
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/calc/stochastic.py
  openquake/qa_tests_data/event_based/case_32/__init__.py
  openquake/qa_tests_data/event_based/case_32/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_32/gmmLT.xml
  openquake/qa_tests_data/event_based/case_32/japan.geojson
  openquake/qa_tests_data/event_based/case_32/job.ini
  openquake/qa_tests_data/event_based/case_32/source_model.xml
  openquake/qa_tests_data/event_based/case_32/ssm.xml
  openquake/qa_tests_data/event_based/case_32/ssmLT.xml
Labels: enhancement

#9483 Fix warnings aelo
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/mosaic/CCA/in/sites_cca_res6.csv
  openquake/qa_tests_data/mosaic/WAF/in/gmmLT.xml
  openquake/qa_tests_data/mosaic/WAF/in/job_vs30.ini
  openquake/qa_tests_data/mosaic/WAF/in/sites_waf_res6.csv
  openquake/qa_tests_data/mosaic/WAF/in/ssm/GridMultiSources_Collapsed.xml
  openquake/qa_tests_data/mosaic/WAF/in/ssmLT.xml
Labels: bug

#9491 Set DEFINED_FOR_INTENSITY_MEASURE_TYPES in AkkarBommer2010SWISS01
  openquake/hazardlib/gsim/akkar_bommer_2010.py
Labels: enhancement

#9468 Upgrade to Django4
  .github/workflows/webui_rh_test.yml
  openquake/server/admin.py
  pyproject.toml
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
  setup.py
Labels: dependencies

#9274 Modifications to Indirect AvgSA and implementation of European Direct AvgSA GMM
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/coeffs_table.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/mgmpe/generic_gmpe_avgsa.py
  openquake/hazardlib/gsim/weatherill_2024.py
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_mean_bj08_long.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_mean_eshm20_long.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_mean_eshm20_short.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_total_stddev_bj08_long.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_total_stddev_eshm20_long.csv
  openquake/hazardlib/tests/gsim/data/generic_avgsa/gmpe_avgsa_total_stddev_eshm20_short.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_adjustments_mean.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_homoskedastic_inter_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_homoskedastic_intra_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_homoskedastic_total_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_inter_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_intra_event_stddev_ergodic.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_intra_event_stddev_nonergodic.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_mean.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_slope_geology_inter_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_slope_geology_intra_event_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_slope_geology_mean.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_slope_geology_total_stddev.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_total_stddev_ergodic.csv
  openquake/hazardlib/tests/gsim/data/weatherill_2024/ESHM20_AvgSA_total_stddev_nonergodic.csv
  openquake/hazardlib/tests/gsim/mgmpe/generic_gmpe_avgsa_test.py
  openquake/hazardlib/tests/gsim/utils.py
  openquake/hazardlib/tests/gsim/weatherill_2024_test.py
  openquake/hazardlib/tests/imt_test.py
  openquake/qa_tests_data/classical/case_86/__init__.py
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-mean-AvgSA(0.1).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-mean-AvgSA(0.75).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-mean-AvgSA(2.0).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-000-AvgSA(0.1).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-000-AvgSA(0.75).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-000-AvgSA(2.0).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-001-AvgSA(0.1).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-001-AvgSA(0.75).csv
  openquake/qa_tests_data/classical/case_86/expected/hazard_curve-rlz-001-AvgSA(2.0).csv
  openquake/qa_tests_data/classical/case_86/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_86/job.ini
  openquake/qa_tests_data/classical/case_86/site_model.csv
  openquake/qa_tests_data/classical/case_86/source_model.xml
  openquake/qa_tests_data/classical/case_86/source_model_logic_tree.xml
Labels: enhancement

#9495 sets precision of values printed in aelo webui
  openquake/server/tests/test_aelo_mode.py
  openquake/server/views.py
Labels: enhancement

#9498 Added a view `exposure_by_country`
  openquake/calculators/views.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
Labels: enhancement, internal
