Repository gem/oq-engine, pull requests merged in 2024-01, with the labels that each got.

#9308 Using ruff as linter/3
  .github/workflows/engine_pr_test.yml
  openquake/calculators/event_based.py
  openquake/calculators/extract.py
  openquake/calculators/views.py
  openquake/commands/__init__.py
  openquake/commands/check_input.py
  openquake/commands/compare.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/calc/cond_spectra.py
  openquake/hazardlib/calc/conditioned_gmfs.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/geo/__init__.py
  openquake/hazardlib/geo/geodetic.py
  openquake/hazardlib/geo/surface/__init__.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim/kotha_2020.py
  openquake/hazardlib/gsim/mcverry_2006.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/mfd/__init__.py
  openquake/hazardlib/scalerel/__init__.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source/__init__.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/tests/acceptance/_peer_test_data.py
  openquake/hazardlib/tests/geo/mesh_test.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/point_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_bechmark_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/gsim/ameri_2017_test.py
  openquake/hazardlib/tests/gsim/atkinson_boore_2006_test.py
  openquake/hazardlib/tests/gsim/base_test.py
  openquake/hazardlib/tests/gsim/cauzzi_faccioli_2008_test.py
  openquake/hazardlib/tests/gsim/edwards_faeh_2013_alpine_test.py
  openquake/hazardlib/tests/gsim/frankel_1996_test.py
  openquake/hazardlib/tests/gsim/germany_2018_test.py
  openquake/hazardlib/tests/gsim/gmpe_table_test.py
  openquake/hazardlib/tests/gsim/raghukanth_iyengar_2007_test.py
  openquake/hazardlib/tests/gsim/sharma_2009_test.py
  openquake/hazardlib/tests/gsim/tromans_2019_test.py
  openquake/hazardlib/tests/gsim/zhao_2006_test.py
  openquake/hazardlib/tests/mfd/evenly_discretized_test.py
  openquake/hazardlib/tests/mfd/tapered_gr_test.py
  openquake/hazardlib/valid.py
  openquake/risklib/__init__.py
  openquake/server/db/upgrade_manager.py
Labels: internal

#9309 Extended oq info to shapefiles
  debian/changelog
  openquake/commands/info.py
  openquake/commands/tests/commands_test.py
Labels: internal

#9314 Refined parallelization
  openquake/engine/engine.py
  openquake/hazardlib/source_reader.py
Labels: internal

#9315 Reducing the source model logic tree to a single branch
  debian/changelog
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/valid.py
Labels: enhancement, inputs

#9316 Added geolocalization functionality `geolocate`
  openquake/calculators/event_based.py
  openquake/commonlib/global_model_getter.py
  openquake/commonlib/logs.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/aelo.py
  openquake/hazardlib/geo/utils.py
  openquake/qa_tests_data/mosaic/scenarios.csv
Labels: internal

#9311 Add example to prepare_site_model command
  doc/user-guide/_images/prepare_site_model.png
  doc/user-guide/_images/prepare_site_model_opt1.png
  doc/user-guide/_images/prepare_site_model_opt2.png
  doc/user-guide/useful-oq-commands.rst
Labels: documentation

#9318 Parallelizing the rupture filtering in `oq mosaic sample_rups`
  openquake/calculators/event_based.py
  openquake/hazardlib/calc/stochastic.py
Labels: performance

#9319 Use `lru_cache` instead of `cache` to keep compatibility with python 3.8
  openquake/commonlib/readinput.py
Labels: dependencies

#9320 Fixed bug in the Wong GMPEs
  debian/changelog
  openquake/hazardlib/gsim/wong2022.py
Labels: bug

#9321 Fixed XML exposure
  openquake/risklib/asset.py
Labels: bug

#9326 Fix branch name in demos artifact when triggering action manually
  .github/workflows/demos.yml
Labels: bug

#9327 Fixed ordering of the IMTs (i.e. two-peaks bug in the UHS)
  debian/changelog
  openquake/baselib/general.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/classical/case_04/__init__.py
  openquake/qa_tests_data/classical/case_04/expected/uhs.csv
  openquake/qa_tests_data/classical/case_04/gslt.xml
  openquake/qa_tests_data/classical/case_04/job.ini
  openquake/qa_tests_data/classical/case_04/sm.xml
  openquake/qa_tests_data/classical/case_04/smlt.xml
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
Labels: bug

#9328 Exclude USA, UCF only in AELO mode
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/geo/utils.py
Labels: bug

#9330 Fixed the sorting of the IMTs again
  openquake/baselib/general.py
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_AbrahamsonEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_BooreEtAl2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_CampbellBozorgnia2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_ActiveCrust_ChiouYoungs2014.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AbrahamsonEtAl2015SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_AtkinsonBoore2003SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_GarciaEtAl2005SSlab55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia30.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_InSlab_ZhaoEtAl2006SSlabCascadia55.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AbrahamsonEtAl2015SInter.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_AtkinsonMacias2009.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_GhofraniAtkinson2014Cascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_Interface_ZhaoEtAl2006SInterCascadia.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_central.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_high.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_AA13_low.org
  openquake/qa_tests_data/classical/case_76/expected/CanadaSHM6_StableCrust_NGAEast_01.org
Labels: bug

#9329 Merge USA and UCF in mosaic/ModelBoundaries shapefile
  openquake/commonlib/tests/readinput_test.py
  openquake/qa_tests_data/mosaic/ModelBoundaries.dbf
  openquake/qa_tests_data/mosaic/ModelBoundaries.qix
  openquake/qa_tests_data/mosaic/ModelBoundaries.shp
  openquake/qa_tests_data/mosaic/ModelBoundaries.shx
Labels: enhancement

#9322 Fix kite long running
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/data/poly_problem.xml
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
Labels: enhancement

#9333 read_ctx_by_grp returns empty dict if no values
  openquake/hazardlib/contexts.py
Labels: bug

#9334 The calculation_mode=ebrisk was not honored when starting from GMFs
  debian/changelog
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: bug, internal

#9335 Fixed another ordering issue with numpy 1.26
  openquake/calculators/event_based_risk.py
  openquake/qa_tests_data/event_based_risk/case_miriam/expected/portfolio_losses_ampl.txt
Labels: bug, dependencies

#9331 In get_params_from make mosaic_dir mandatory and add the exclude parameter
  openquake/commands/mosaic.py
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/geo/utils.py
  openquake/server/settings.py
  openquake/server/views.py
Labels: internal

#9336 Removing support for Python 3.8
  .github/workflows/docs.yml
  install.py
  openquake/commands/__main__.py
  setup.py
Labels: dependencies

#9337 Extended `oq mosaic run_site` to store the ASCE-41 parameters
  openquake/commands/mosaic.py
Labels: enhancement, internal

#9338 Storing the rupture geometries at 64 bits to solve machine-dependent numeric problems
  openquake/calculators/event_based.py
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based/src_mutex/expected/ruptures.csv
  openquake/qa_tests_data/event_based_risk/case_master/expected/risk_by_event.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-aggcurves.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_2/expected/reinsurance-avg_portfolio.csv
  openquake/qa_tests_data/event_based_risk/reinsurance_3/expected/reinsurance-risk_by_event.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/aggcurves-site_id.csv
  openquake/qa_tests_data/gmf_ebrisk/case_4/expected/risk_by_event.csv
  openquake/qa_tests_data/scenario_damage/case_5/expected/dmg_by_asset.csv
  openquake/qa_tests_data/scenario_risk/case_3/expected/asset-loss.csv
  openquake/qa_tests_data/scenario_risk/case_5/expected/losses_by_asset.csv
Labels: internal

#9340 Compatibility fixes for numpy 2.0
  .github/workflows/engine_pr_test.yml
  openquake/baselib/general.py
  openquake/calculators/base.py
  openquake/calculators/views.py
  openquake/commands/shell.py
  openquake/hazardlib/gsim/nz22/stafford_2022.py
  openquake/hazardlib/site.py
  openquake/hazardlib/source_reader.py
  openquake/risklib/asset.py
Labels: dependencies

#9341 Added test for PAC
  openquake/calculators/classical.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/mosaic/PAC/in/gmmLT_1.xml
  openquake/qa_tests_data/mosaic/PAC/in/job.ini
  openquake/qa_tests_data/mosaic/PAC/in/ssm/interface_trimmed/int_fs_z1_ah.xml
  openquake/qa_tests_data/mosaic/PAC/in/ssm/interface_trimmed/seg_int_z1_ah.xml
  openquake/qa_tests_data/mosaic/PAC/in/ssmLT_tests_mini.xml
Labels: internal

#9342 Add acknowledgements for USAID, Google Season of Docs, and EFEHR
  doc/_static/efehr-10pc-b25.png
  doc/index.rst
Labels: documentation

#9343 Simplified `logs.init` and a few other things
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/preclassical.py
  openquake/commands/run.py
  openquake/commands/shell.py
  openquake/commonlib/logs.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/engine.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/hazard_curve.py
  openquake/hazardlib/tests/calc/mrd_test.py
  openquake/qa_tests_data/mosaic/PAC/in/job.ini
  openquake/qa_tests_data/mosaic/PAC/in/ssm/interface_trimmed/int_fs_z1_ah.xml
Labels: internal

#9344 Fixed AELO calculations in the case of sources with the same name in different branches
  openquake/calculators/classical.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/mosaic/PAC/in/ssm/interface_trimmed/int_fs_z1_ah.xml
  openquake/qa_tests_data/mosaic/PAC/in/ssmLT_tests_mini.xml
Labels: bug

#9339 Added missing validation on duplicate source IDs for source models in format nrml/0.5
  debian/changelog
  openquake/hazardlib/nrml.py
Labels: enhancement, inputs

#9345 Moved around corename/basename
  openquake/calculators/classical.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/postproc/med_gmv.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/nrml.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/valid.py
Labels: internal

#9346 Improved `oq mosaic run_site file.csv`
  openquake/commands/mosaic.py
Labels: internal

#9347 Refined check on duplicate source IDs
  openquake/hazardlib/nrml.py
  openquake/hazardlib/source_reader.py
Labels: inputs

#9349 Fixed the gmf_data exporter with a filtered site collection
  debian/changelog
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/readinput.py
Labels: bug

#9350 Reducing the number of tasks used by `disagg_by_src`
  debian/changelog
  openquake/calculators/classical.py
Labels: performance

#9352 Remove windows test for advanced manual, that does not exist anymore
  .github/workflows/windows_test.yml
Labels: bug

#9353 Fixed missing `fragmentno` in source ID
  openquake/hazardlib/source_reader.py
Labels: bug

#9354 Optimized the parallelization of AELO tests
  openquake/baselib/parallel.py
  openquake/calculators/views.py
  openquake/commands/mosaic.py
Labels: performance

#9358 Fixed disagg_mag_dist_eps with mutex sources
  debian/changelog
  openquake/baselib/parallel.py
  openquake/commands/mosaic.py
  openquake/engine/engine.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/tests/calc/cond_spectra_test.py
  openquake/hazardlib/tests/calc/hazard_curve_new_test.py
  openquake/hazardlib/valid.py
Labels: bug

#9359 Changed the universal installer to recreate the venv
  debian/changelog
  install.py
Labels: dependencies

#9360 Refined config.paths
  openquake/baselib/__init__.py
Labels: internal

#9357 Adding a test for a vertical section
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/line_test.py
  openquake/hazardlib/tests/geo/surface/data/section_1680_ucf.xml
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: bug

#9362 Added a clear warning before reinstalling
  install.py
Labels: dependencies, enhancement

#9364 Strip 'AELO for XXX' -> 'XXX' in title of outputs page
  openquake/server/views.py
Labels: enhancement

#9363 After 3 years of deprecation, forbidden custom methods in GMPE classes
  debian/changelog
  openquake/hazardlib/gsim/base.py
Labels: enhancement

#9366 Disable the slow check on the sources bounding box
  openquake/calculators/preclassical.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/source_reader.py
Labels: performance

#9367 Extended `oq mosaic sample_rups` to multiple models
  debian/changelog
  openquake/commands/mosaic.py
Labels: enhancement

#9369 Fixed AELO for EUR
  openquake/calculators/tests/postproc_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/qa_tests_data/postproc/case_rtgm/__init__.py
  openquake/qa_tests_data/postproc/case_rtgm/gmmLT_SC.xml
  openquake/qa_tests_data/postproc/case_rtgm/job.ini
  openquake/qa_tests_data/postproc/case_rtgm/sites_eur_res6_rock.csv
  openquake/qa_tests_data/postproc/case_rtgm/ssm/main_region/fs/fs_ver09e_model_aGR_SRU_MU_fMthr_smaller.xml
  openquake/qa_tests_data/postproc/case_rtgm/ssm/main_region/ssm/seis_ver12b_fMthr_asm_ver12e_winGT_fs017_agbrs_point-smaller.xml
  openquake/qa_tests_data/postproc/case_rtgm/ssmLT_sigma.xml
Labels: bug

#9370 Extending AELO calculations to multiple sites
  openquake/calculators/classical.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/tests/postproc_test.py
  openquake/commands/mosaic.py
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
  openquake/qa_tests_data/mosaic/PAC/in/job.ini
  openquake/server/views.py
Labels: performance

#9371 Add __init__.py to templatetags folder
  openquake/server/templatetags/__init__.py
Labels: bug

#9373 Fixes AELO calculations for multiple points
  openquake/calculators/postproc/compute_rtgm.py
  openquake/engine/tests/aelo_test.py
Labels: bug

#9374 Renamed fpeak as f0
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020Asc_MEAN.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020Asc_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SInterProp2_MEAN.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SInter_MEAN.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SInter_STDDEV.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SSlabFpeak_MEAN.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SSlab_MEAN.csv
  openquake/hazardlib/tests/gsim/data/HA20/HassaniAtkinson2020SSlab_STDDEV.csv
  openquake/hazardlib/tests/gsim/hassani_atkinson_2020_test.py
  openquake/qa_tests_data/scenario/case_30/__init__.py
  openquake/qa_tests_data/scenario/case_30/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_30/job.ini
  openquake/qa_tests_data/scenario/case_30/rupture_model.xml
  openquake/qa_tests_data/scenario/case_30/site_model.csv
Labels: bug

#9376 Refactored disagg_by_rel_sources
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/calculators/views.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/tests/calc/disagg_test.py
  openquake/qa_tests_data/logictree/case_05/job.ini
  openquake/qa_tests_data/logictree/case_07/job.ini
  openquake/qa_tests_data/logictree/case_12/job.ini
Labels: internal

#9375 Improve performance of the non-parametric liquefaction models
  debian/changelog
  openquake/sep/classes.py
  openquake/sep/liquefaction/liquefaction.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: performance

#9379 Refactored disagg_by_rel_sources/3
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
Labels: performance

#9381 Changed `oq mosaic run_site` to run all sites by default
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/commands/mosaic.py
  openquake/engine/aelo.py
Labels: internal

#9382 Fixed AELO plots
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
Labels: bug

#9380 Disable the vs30_tolerance check on-demand
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/site_amplification.py
  openquake/hazardlib/tests/site_amplification_test.py
Labels: enhancement

#9383 Parallelized the AELO tests by site
  openquake/calculators/classical.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/postproc/disagg_by_rel_sources.py
  openquake/commands/mosaic.py
  openquake/engine/aelo.py
Labels: performance

#9386 Moved the OQ_SAMPLE_SOURCES functionality in the source_reader
  openquake/calculators/preclassical.py
  openquake/commands/tests/commands_test.py
  openquake/hazardlib/source_reader.py
Labels: performance

#9385 Add 'Start time' column to webui calculation list and improve style of that table and buttons
  openquake/server/db/actions.py
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/index.html
  openquake/server/views.py
Labels: enhancement

#9388 Better memory monitoring
  openquake/calculators/classical.py
  openquake/hazardlib/source/multi_fault.py
  utils/membomb
Labels: internal

#9392 Serializing MultiFaultSources
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/tests/source/data/ucerf.hdf5
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: internal

#9390 Move announcements functionality to a separate Django app...
  debian/changelog
  openquake/server/admin.py
  openquake/server/announcements/__init__.py
  openquake/server/announcements/migrations/0001_initial.py
  openquake/server/announcements/migrations/__init__.py
  openquake/server/announcements/models.py
  openquake/server/settings.py
  openquake/server/tests/test_aelo_mode.py
  openquake/server/utils.py
Labels: bug

#9393 Do not display an empty announcements box if no announcement has the flag show == True
  openquake/server/utils.py
Labels: bug

#9394 Return HttpResponseNotFound if the requested calc_id does not exist
  openquake/server/views.py
Labels: bug

#9396 Fixed ZalachorisRathje2019
  debian/changelog
  openquake/hazardlib/gsim/zalachoris_rathje_2019.py
Labels: bug, backport

#9395 Improved a bit the performance of MultiSurfaces
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/source/data/ctxt.csv
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9397 Removed the distance cache
  openquake/hazardlib/calc/filters.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/multi_cache_test.py
Labels: performance

#9399 Added a forgotten call to `_set_coordinate_shift`
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
Labels: internal

#9398 Refactoring of Line/Multiline
  openquake/hazardlib/geo/line.py
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/source/multi_fault_test.py
Labels: performance

#9400 Removed another useless cache in MultiLine
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/geo/surface/multi.py
  openquake/hazardlib/tests/geo/multiline_test.py
Labels: internal

#9401 Restored missing test
  openquake/hazardlib/geo/multiline.py
  openquake/hazardlib/tests/geo/multiline_test.py
  openquake/hazardlib/tests/geo/surface/multi2_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/hazardlib/tests/geo/surface/multi_test.py
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0a.npz
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0b.npz
  openquake/hazardlib/tests/geo/surface/results/results_multi_simple_ry0c.npz
Labels: internal

#9402 Removed yet another useless cache (in MultiSurface)
  openquake/hazardlib/geo/surface/multi.py
Labels: internal
