Repository gem/oq-engine, pull requests merged in 2025-01, with the labels that each got.

#10243 Fixed some warnings
  openquake/baselib/workerpool.py
  openquake/calculators/export/risk.py
  openquake/commonlib/dbapi.py
  openquake/commonlib/logs.py
  openquake/engine/engine.py
  openquake/hazardlib/gsim/zhao_2016.py
  openquake/server/db/actions.py
  openquake/server/views.py
Labels: internal

#10246 Fixed an import error with Python 3.10
  openquake/baselib/workerpool.py
  openquake/commonlib/logs.py
  openquake/engine/engine.py
  openquake/server/db/actions.py
  openquake/server/views.py
Labels: bug

#10247 Extended the ShakeMap parser to SA(0.6)
  debian/changelog
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
Labels: enhancement, inputs

#10245 Fixing the workflow for aristotle users
  bin/arist
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/aristotle.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/shakemap_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/job.ini
  openquake/server/views.py
Labels: bug

#10248 Add a SUPPRESS_PERMISSION_DENIED_WARNINGS flag to the webui settings
  openquake/server/local_settings.py.aelo_aristotle
  openquake/server/local_settings.py.pam
  openquake/server/local_settings.py.server
  openquake/server/local_settings.py.tools
  openquake/server/settings.py
Labels: internal

#10250 Minor cleanup for HDF5
  openquake/calculators/post_risk.py
  openquake/commonlib/datastore.py
Labels: internal

#10249 Removed `datastore.hdf5new`
  debian/changelog
  doc/contributing/architecture.rst
  doc/user-guide/advanced/advanced-calculations.rst
  openquake/baselib/parallel.py
  openquake/commands/collect_jobs.py
  openquake/commands/prepare_site_model.py
  openquake/commands/rerun.py
  openquake/commonlib/datastore.py
  openquake/commonlib/expo_to_hdf5.py
  openquake/commonlib/logs.py
  openquake/commonlib/tests/readinput_test.py
  utils/build_global_exposure
  utils/classical_indep
  utils/profile_ctxs.py
  utils/stress_cpu.py
  utils/vs30tohdf5
Labels: internal

#10241 NGAEast Period-Dependent Bias Adjustment and Coastal Plains Site Amplification Model for 2023 Conterminous US CEUS GMC
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/gsim/chapman_guo_2021_psa_ratios.csv
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/gsim/utils_chapman_guo_2021.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/utils_chapman_guo_2011_test.py
  openquake/hazardlib/tests/gsim/utils_us23_basin_adj_test.py
  openquake/hazardlib/tests/gsim/utils_us23_gmm_adj_test.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_87/__init__.py
  openquake/qa_tests_data/classical/case_87/expected/hazard_curve-mean-SA(0.2).csv
  openquake/qa_tests_data/classical/case_87/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_87/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_87/gmpe_logic_tree.xml
  openquake/qa_tests_data/classical/case_87/job.ini
  openquake/qa_tests_data/classical/case_87/site_model.csv
  openquake/qa_tests_data/classical/case_87/source_model.xml
  openquake/qa_tests_data/classical/case_87/source_model_logic_tree.xml
Labels: enhancement

#10251 Fix the plot_assets command in case the ShakeMap was used...
  openquake/calculators/views.py
  openquake/commands/plot_assets.py
  openquake/server/templates/engine/get_outputs_aristotle.html
Labels: bug

#10253 ARISTOTLE: notify to the user when the given rupture identifier is not found
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
Labels: bug

#10255 Fixed HDF5 error on MacOS for avg_losses
  debian/changelog
  openquake/calculators/event_based_risk.py
Labels: bug

#10257 Documenting the global_ses script
  openquake/engine/global_ses.py
Labels: documentation

#10258 Update Docker files for Copyright 2025
  demos/risk/ScenarioRisk/sensitivity.py
  doc/conf.py
  docker/Dockerfile.dev
  docker/Dockerfile.engine
  docker/Singularity.def
  docker/scripts/oq-db_start.sh
  docker/scripts/oq-start.sh
  helpers/changelog2ghrel.sh
  openquake/calculators/checkers.py
  openquake/calculators/postproc/plots.py
  openquake/commands/rerun.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/expo_to_hdf5.py
  openquake/commonlib/tests/expo_to_hdf5_test.py
  openquake/engine/aristotle.py
  openquake/engine/global_ses.py
  openquake/engine/tests/aristotle_test.py
  openquake/engine/tests/global_ses_test.py
  openquake/hazardlib/geolocate.py
  openquake/hazardlib/gsim/aristeidou_2023.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  utils/membomb
Labels: documentation

#10259 Added test for the NZ22 GMPEs
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/qa_tests_data/scenario/case_34/__init__.py
  openquake/qa_tests_data/scenario/case_34/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_34/gsim_lt.xml
  openquake/qa_tests_data/scenario/case_34/job.ini
  openquake/qa_tests_data/scenario/case_34/rupture.csv
  openquake/qa_tests_data/scenario/case_34/site_model.csv
Labels: bug

#10260 Fixed the macOS HDF5 bug also for damages
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/tests/scenario_damage_test.py
Labels: bug

#10261 Documented get_ebruptures
  doc/contributing/developing-with-the-engine.rst
Labels: documentation

#10262 Update documentation on Windows
  doc/getting-started/installation-instructions/_images/windows/00_Open.png
  doc/getting-started/installation-instructions/_images/windows/01_Run.png
  doc/getting-started/installation-instructions/_images/windows/02_License.png
  doc/getting-started/installation-instructions/_images/windows/03_Uninstall.png
  doc/getting-started/installation-instructions/_images/windows/04_Stop.png
  doc/getting-started/installation-instructions/_images/windows/05_Remove.png
  doc/getting-started/installation-instructions/_images/windows/06_Complete.png
  doc/getting-started/installation-instructions/_images/windows/06_DoneRemove.png
  doc/getting-started/installation-instructions/_images/windows/07_Choose.png
  doc/getting-started/installation-instructions/_images/windows/07_Destination.png
  doc/getting-started/installation-instructions/_images/windows/07_Installing.png
  doc/getting-started/installation-instructions/_images/windows/08_Complete.png
  doc/getting-started/installation-instructions/_images/windows/09_icons.png
  doc/getting-started/installation-instructions/_images/windows/10_webuiterm.png
  doc/getting-started/installation-instructions/windows.rst
Labels: documentation

#10263 Testing `oq info usgs_rupture`
  bin/run-demos.sh
  openquake/commands/info.py
  openquake/hazardlib/shakemap/parsers.py
Labels: inputs

#10266 In the webui, filter functionalities depending from the level of the user only if authentication is enabled
  openquake/server/models.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/index.html
  openquake/server/utils.py
  openquake/server/views.py
Labels: bug

#10264 What's New for engine 3.22
  doc/release-notes/index.rst
  doc/release-notes/whats-new.md
Labels: documentation

#10267 Move user profiles management to a separate app server.user_profile
  openquake/server/admin.py
  openquake/server/apps.py
  openquake/server/settings.py
  openquake/server/signals.py
  openquake/server/user_profile/migrations/0001_create_user_profiles.py
  openquake/server/user_profile/migrations/__init__.py
  openquake/server/user_profile/models.py
  openquake/server/user_profile/signals.py
Labels: bug

#10268 Added a new output "Aggregated Exposure Values"
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/calculators/views.py
  openquake/engine/tests/aristotle1/job.ini
  openquake/engine/tests/aristotle2/job.ini
  openquake/engine/tests/aristotle3/job.ini
  openquake/engine/tests/aristotle4/job.ini
  openquake/qa_tests_data/event_based_risk/case_1/expected/agg_keys.csv
Labels: outputs

#10269 Added `extract/aggrisk_keys` and disabled `avg_losses` in Aristotle mode
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk_keys.csv
Labels: outputs

#10270 Add aggrisk_keys rest resource to download a json
  doc/api-reference/rest-api.rst
  openquake/calculators/extract.py
  openquake/commonlib/oqvalidation.py
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement, outputs

#10274 Setting individual_rlzs = true in scenario_risk/case_master
  openquake/commonlib/oqvalidation.py
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
Labels: outputs

#10275 Removed docs about the obsolete format for the consequence files
  doc/user-guide/configuration-file/event-based-risk-config.rst
  doc/user-guide/configuration-file/scenario-risk-config.rst
Labels: documentation

#10276 Fixed the ordering in trt_gsim.csv
  openquake/calculators/export/hazard.py
  openquake/qa_tests_data/logictree/case_84/expected/trt_gsim.csv
Labels: internal

#10279 Refined multifault weight
  openquake/calculators/views.py
  openquake/hazardlib/contexts.py
Labels: performance

#10280 Renamed agg_keys -> aggexp_tags and aggrisk_keys -> aggrisk_tags
  doc/api-reference/rest-api.rst
  openquake/calculators/export/__init__.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggexp_tags.csv
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk_tags.csv
  openquake/server/tests/test_aristotle_mode.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: outputs

#10278 Changes to Preclassical to use without sites
  debian/changelog
  openquake/calculators/preclassical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/classical/case_75/pre.ini
Labels: inputs

#10281 Test the webui using pytest
  .github/workflows/engine_pr_test.yml
  .github/workflows/macos_intel_install.yml
  .github/workflows/macos_m1_install.yml
  .github/workflows/windows_test.yml
  openquake/server/settings.py
  pytest.ini
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py312-linux64.txt
  requirements-py312-macos_arm64.txt
  requirements-py312-macos_x86_64.txt
  requirements-py312-win64.txt
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: internal

#10284 Save the reduced assetcol
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
Labels: bug, outputs

#10283 set minimun python on install.py to 3.10
  install.py
  requirements-py39-linux64.txt
  requirements-py39-macos_arm64.txt
  requirements-py39-macos_x86_64.txt
  requirements-py39-win64.txt
Labels: dependencies

#10288 Override the `_dj_autoclear_mailbox` test fixture in `pytest_django` to clear the outbox only if it exists
  conftest.py
Labels: internal

#10290 Using `query_ball_tree` to determine the ruptures close to the sites in global SES calculations
  debian/changelog
  openquake/calculators/event_based.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/global_ses_test.py
  openquake/hazardlib/calc/filters.py
  openquake/qa_tests_data/mosaic_for_ses/job.ini
  openquake/qa_tests_data/mosaic_for_ses/job_sites.ini
  openquake/qa_tests_data/mosaic_for_ses/job_sm.ini
Labels: performance

#10294 Refined preclassical
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
Labels: performance

#10293 Remove dependency from pytest_django but install it in the actions that run tests for the webui
  .github/workflows/engine_pr_test.yml
  .github/workflows/macos_intel_install.yml
  .github/workflows/macos_m1_install.yml
  .github/workflows/windows_test.yml
  conftest.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py312-linux64.txt
  requirements-py312-macos_arm64.txt
  requirements-py312-macos_x86_64.txt
  requirements-py312-win64.txt
Labels: internal

#10297 Fixed gsim=<TOML> syntax
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim_lt.py
  openquake/qa_tests_data/scenario/case_35/Wcrust_med_rhypo.hdf5
  openquake/qa_tests_data/scenario/case_35/__init__.py
  openquake/qa_tests_data/scenario/case_35/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_35/job.ini
  openquake/qa_tests_data/scenario/case_35/rupture.csv
  openquake/qa_tests_data/scenario/case_35/site_model.csv
Labels: internal

#10298 Fixed the instantiation of file-dependent GMPEs from the datastore
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/hazardlib/gsim_lt.py
Labels: bug

#10299 Fixed `GsimLogicTree.__fromh5__` in the case of subdirectories
  demos/hazard/GMPETablePSHA/gsim_logic_tree.xml
  openquake/hazardlib/gsim_lt.py
Labels: bug

#10301 Extended rupture_dict to the `msr` and `aspect_ratio` parameters
  debian/changelog
  openquake/calculators/tests/scenario_test.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario/case_28/expected/avg_gmf2.csv
  openquake/qa_tests_data/scenario/case_28/job2.ini
Labels: enhancement, inputs

#10302 Aggregate by ID_1;OCCUPANCY in Aristotle calculations
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/aristotle1/job.ini
  openquake/engine/tests/aristotle2/job.ini
  openquake/engine/tests/aristotle3/job.ini
  openquake/engine/tests/aristotle4/job.ini
Labels: outputs

#10291 Add aristeidou_2024.py gsim. Add FIV3, Sa_avg2, and Sa_avg3 IMs
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/gsim/aristeidou_2024.py
  openquake/hazardlib/gsim/aristeidou_2024_assets/gmm_ann.hdf5
  openquake/hazardlib/imt.py
  openquake/hazardlib/tests/gsim/aristeidou_2023_test.py
  openquake/hazardlib/tests/gsim/aristeidou_2024_test.py
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_GEOMEAN_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_GEOMEAN_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_GEOMEAN_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_GEOMEAN_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD100_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD100_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD100_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD100_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD50_MEAN.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD50_STD_INTER.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD50_STD_INTRA.csv
  openquake/hazardlib/tests/gsim/data/ASO24/ASO24_ROTD50_STD_TOTAL.csv
  openquake/hazardlib/tests/source/data/ctxt-got.csv
Labels: enhancement

#10300 fix k20 NZL variant req site param bug
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
Labels: bug

#10304 Remove the 'Continue' button while running the WebUI in Aristotle mode
  openquake/server/templates/engine/index.html
Labels: bug
