Repository gem/oq-engine, pull requests merged in 2025-09, with the labels that each got.

#10757 add content_type to calc_results entry point
  openquake/server/views.py
Labels: bug

#10772 Fixed small negative damages due to numeric errors
  debian/changelog
  openquake/calculators/event_based_damage.py
Labels: bug

#10775 In the test checking that impact fails when SA(0.6) is missing, use a specific shakemap_id instead of usgs_preferred
  openquake/server/tests/test_impact_mode.py
Labels: internal

#10774 Changed `install.py` to exit if any of the tools is not installed
  debian/changelog
  install.py
Labels: dependencies

#10780 Removed the --reuse-input flag
  debian/changelog
  doc/getting-started/running-calculations/command-line.rst
  openquake/calculators/preclassical.py
  openquake/commands/engine.py
  openquake/commands/run.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/readinput_test.py
Labels: internal

#10758 Add douglas_et_al_2024 GMM
  CONTRIBUTORS.txt
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_162_branch_rjb.csv
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_162_branch_rrup.csv
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_3_branch_rjb.csv
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_3_branch_rrup.csv
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_5_branch_rjb.csv
  openquake/hazardlib/gsim/Douglas_et_al_2024_COEFFS/Coeffs_5_branch_rrup.csv
  openquake/hazardlib/gsim/douglas_et_al_2024.py
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b1Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b1Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b2Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b2Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b3Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_3branch_b3Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b1Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b1Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b3Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b3Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b5Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_5branch_b5Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_b162_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_b1_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rjb_b99_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b1Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b1Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b2Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b2Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b3Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_3branch_b3Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b2Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b2Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b3Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b3Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b4Original_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_5branch_b4Updated_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_b100_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_b10_MEAN.csv
  openquake/hazardlib/tests/gsim/data/DouglasEtAl24/Douglas_et_al_2024Rrup_b60_MEAN.csv
  openquake/hazardlib/tests/gsim/douglas_et_al_2024_test.py
Labels: enhancement

#10784 Make it possible to specify the link to the user manual via the local settings
  openquake/server/local_settings.py.aelo_impact
  openquake/server/settings.py
  openquake/server/templates/engine/base.html
  openquake/server/utils.py
Labels: AELO

#10788 Skipped the `MedianSpectrum` demo on mac with Python 3.11
  bin/run-demos.sh
Labels: internal

#10791 Add plot_h3 accepting a list of h3 codes and visualizing the hexagons with country borders
  openquake/commands/plot.py
Labels: internal

#10800 Fixed the case when the ShakeMap has been already downloaded
  openquake/calculators/event_based.py
Labels: bug

#10796 Added ramadan_2023 gsim
  debian/changelog
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/ramadan_2023.py
  openquake/hazardlib/tests/gsim/data/RLS23/RLS23deep_MEAN.csv
  openquake/hazardlib/tests/gsim/data/RLS23/RLS23deep_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/data/RLS23/RLS23shallow_MEAN.csv
  openquake/hazardlib/tests/gsim/data/RLS23/RLS23shallow_STD_TOTAL.csv
  openquake/hazardlib/tests/gsim/ramadan_2023_test.py
Labels: enhancement

#10798 Fixed the splitting of multifault sources with a single site
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
Labels: bug

#10803 update ilabel documentation to dictionary use
  doc/user-guide/inputs/logic-trees-inputs.rst
Labels: documentation

#10804 Added FAQ about generating a stochastic event set from a GEM model
  doc/user-guide/extras/faq.rst
Labels: documentation

#10805 IMPACT: do not restrict the site collection within the bounding box of the ShakeMap…
  openquake/calculators/tests/scenario_risk_test.py
  openquake/engine/impact.py
  openquake/hazardlib/shakemap/maps.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/qa_tests_data/scenario_risk/case_shakemap/expected/agglosses.csv
  openquake/qa_tests_data/scenario_risk/case_shakemap/pre-job.ini
  openquake/qa_tests_data/scenario_risk/case_shakemap/sites.csv
Labels: internal

#10815 Gzipping the avg_losses
  debian/changelog
  openquake/calculators/event_based_risk.py
Labels: performance

#10816 Added a check on rtgmpy in `oq mosaic run_site`
  openquake/commands/mosaic.py
Labels: internal

#10820 Saved the source model read times
  openquake/hazardlib/source_reader.py
Labels: performance

#10814 added separate get_middle_point() method for kite surfaces
  debian/changelog
  openquake/hazardlib/geo/surface/kite_fault.py
  openquake/hazardlib/tests/geo/surface/kite_fault_test.py
  openquake/hazardlib/tests/geo/surface/multi_kite_test.py
  openquake/qa_tests_data/event_based/case_29/expected/full_ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures.csv
  openquake/qa_tests_data/event_based/case_29/expected/ruptures2.csv
Labels: bug

#10825 Don't check the `export_dir` if we are not exporting
  debian/changelog
  openquake/commonlib/oqvalidation.py
Labels: bug, outputs

#10831 Removed the magdist from the AELO tests
  openquake/engine/aelo.py
  openquake/engine/tests/aelo_test.py
Labels: internal

#10828 Reduced the size of the RateMap
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/disaggregation.py
  openquake/calculators/extract.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/postproc/conditional_spectrum.py
  openquake/calculators/postproc/med_gmv.py
  openquake/calculators/postproc/median_spectrum.py
  openquake/calculators/preclassical.py
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/calc/disagg.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean-bis.csv
  openquake/qa_tests_data/logictree/case_05/expected/curve-mean.csv
  utils/classical_indep
  utils/profile_ctxs.py
Labels: performance

#10834 Aggregating the exposure
  debian/changelog
  openquake/calculators/tests/scenario_damage_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/impact.py
  openquake/qa_tests_data/scenario_damage/case_20/Exposure_Cianjur_cleaned.csv
  openquake/qa_tests_data/scenario_damage/case_20/Exposure_model_Cianjur.xml
  openquake/qa_tests_data/scenario_damage/case_20/expected/agg_values.org
  openquake/qa_tests_data/scenario_damage/case_20/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_20/expected/avg_damages.csv
  openquake/qa_tests_data/scenario_damage/case_20/job.ini
  openquake/risklib/asset.py
Labels: enhancement

#10837 Fixed `export_dir=/tmp` on Windows
  openquake/commonlib/oqvalidation.py
Labels: bug, outputs
