Repository gem/oq-engine, pull requests merged in 2025-05, with the labels that each got.

#10554 modify SS and S1 only for class BC
  openquake/calculators/postproc/compute_rtgm.py
Labels: enhancement

#10555 Fixing tags and extending functionalities
  openquake/hazardlib/lt.py
  openquake/hazardlib/tests/lt_test.py
Labels: enhancement

#10556 Add uncertainty for area source geometry
  debian/changelog
  openquake/calculators/tests/logictree_test.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/source/area.py
  openquake/hazardlib/source/base.py
  openquake/hazardlib/tests/source/area_test.py
  openquake/qa_tests_data/logictree/README.md
  openquake/qa_tests_data/logictree/case_80/__init__.py
  openquake/qa_tests_data/logictree/case_80/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/logictree/case_80/gmpe_logic_tree.xml
  openquake/qa_tests_data/logictree/case_80/job.ini
  openquake/qa_tests_data/logictree/case_80/source_model.xml
  openquake/qa_tests_data/logictree/case_80/source_model_logic_tree.xml
Labels: enhancement

#10557 Improved checks on the seismogenic depths
  openquake/hazardlib/source/point.py
  openquake/hazardlib/tests/source/point_test.py
Labels: inputs

#10558 Not saving `applyToBranches` when empty
  openquake/baselib/node.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/lt.py
  openquake/risklib/reinsurance.py
Labels: inputs

#10560 Added a check on duplicate branches in the source model logic tree
  debian/changelog
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: enhancement, inputs

#10561 Added `applyToSources` to `lt.build`
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: inputs

#10562 More work on exporting job.zip
  openquake/calculators/base.py
  openquake/calculators/export/risk.py
  openquake/commonlib/readinput.py
  openquake/engine/tests/impact_test.py
Labels: outputs

#10563 Added test for the logic tree of BCHydro
  openquake/hazardlib/tests/lt_test.py
  openquake/hazardlib/tests/lt_test.xml
Labels: inputs

#10564 Fixed AELO tests
  openquake/commonlib/readinput.py
  openquake/hazardlib/logictree.py
Labels: bug

#10565 Fixed `oq plot examples`
  bin/run-demos.sh
  debian/changelog
  openquake/calculators/checkers.py
  openquake/commands/plot.py
  openquake/engine/tests/impact_test.py
Labels: bug

#10566 IMPACT: cast some numeric values to float in order to avoid serialization issues in JsonResponse
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10568 Added route for job.zip
  debian/changelog
  doc/api-reference/rest-api.rst
  openquake/server/static/css/engine.css
  openquake/server/templates/engine/get_outputs_impact.html
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: outputs

#10569 Added seismogenic_depth uncertainties to point sources and multipoint sources
  openquake/hazardlib/lt.py
  openquake/hazardlib/source/multi_point.py
  openquake/hazardlib/source/point.py
Labels: enhancement, inputs

#10570 Improved `del_calc` and `importcalc`
  openquake/commands/engine.py
  openquake/commands/importcalc.py
  openquake/engine/engine.py
  openquake/server/db/actions.py
Labels: internal, inputs

#10571 Fixed `get_ebruptures` for scenarios
  openquake/calculators/getters.py
  openquake/calculators/tests/scenario_test.py
Labels: bug, outputs

#10574 Exporting assetcol.csv in `export_job_zip`
  openquake/calculators/export/risk.py
  openquake/engine/tests/impact_test.py
Labels: outputs

#10572 Update exposure model input documentation
  doc/user-guide/inputs/exposure-models-inputs.rst
Labels: documentation

#10575 Refined `export_job_zip`
  openquake/calculators/event_based.py
  openquake/calculators/export/risk.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/impact.py
  openquake/engine/tests/impact_test.py
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
Labels: inputs

#10576 Fixed ignoring the uncertainty in the shakemap
  debian/changelog
  openquake/hazardlib/shakemap/gmfs.py
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10577 Do not skip `occupants` when extracting `aggrisk_tags`
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
Labels: bug

#10578 Fixed downloading uncertainty.xml properly
  debian/changelog
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10580 Fixed off-by-one error in exposure_by_mmi
  openquake/risklib/asset.py
Labels: bug

#10579 Modify error message in reduce_sm.py
  openquake/commands/reduce_sm.py
Labels: proposal

#10582 update QA tests for BA08 site term
  openquake/qa_tests_data/classical/case_88/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_88/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_88/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_88/sites.csv
Labels: internal

#10586 Removed the deprecated swapaxes
  openquake/hazardlib/geo/surface/kite_fault.py
Labels: internal

#10587 Fixed one test
  openquake/hazardlib/source/point.py
Labels: bug

#10588 update CONTRIBUTORS.txt
  CONTRIBUTORS.txt
Labels: documentation

#10591 Added method `CompositeLogicTree.apply_all`
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/tests/lt_test.py
Labels: enhancement

#10589 Fix slope
  debian/changelog
  doc/underlying-science/secondary-perils.rst
  doc/user-guide/inputs/secondary-perils-inputs.rst
  openquake/sep/landslide/displacement.py
  openquake/sep/landslide/probability.py
  openquake/sep/landslide/static_safety_factor.py
  openquake/sep/tests/data/test_site_params.csv
  openquake/sep/tests/landslide/test_displacement.py
  openquake/sep/tests/landslide/test_static_safety_factor.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: inputs

#10593 Improved the error message for invalid area polygons
  debian/changelog
  openquake/hazardlib/sourceconverter.py
Labels: inputs

#10597 Refactored build_corners
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
  openquake/hazardlib/source/point.py
Labels: internal

#10601 Added a test for region-dependent GMM logic tree
  openquake/calculators/classical.py
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_06/__init__.py
  openquake/qa_tests_data/classical/case_06/expected/uhs.csv
  openquake/qa_tests_data/classical/case_06/gmmLT.xml
  openquake/qa_tests_data/classical/case_06/job.ini
  openquake/qa_tests_data/classical/case_06/sites.csv
  openquake/qa_tests_data/classical/case_06/ssm.xml
  openquake/qa_tests_data/classical/case_06/ssmLT.xml
Labels: enhancement

#10602 Added a Dummy GMPE for internal usage
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim/base.py
  openquake/hazardlib/gsim_lt.py
  openquake/qa_tests_data/classical/case_06/gmmLT.xml
  openquake/qa_tests_data/classical/case_07/__init__.py
  openquake/qa_tests_data/classical/case_07/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/classical/case_07/expected/hazard_curve-SA(0.1).csv
  openquake/qa_tests_data/classical/case_07/gsim_logic_tree.xml
  openquake/qa_tests_data/classical/case_07/job.ini
  openquake/qa_tests_data/classical/case_07/source_model.xml
  openquake/qa_tests_data/classical/case_07/source_model_logic_tree.xml
Labels: enhancement

#10599 IMPACT: ignore ShakeMap items without `version` and better identify the USGS-preferred item
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/static/js/engine.js
  openquake/server/views.py
Labels: bug

#10603 Removed dataset `gweights`
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/compute_mrd.py
  openquake/calculators/preclassical.py
  openquake/calculators/views.py
Labels: internal

#10605 Removed `.gids`
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
Labels: internal

#10607 Optimized `read_cmakers`
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/postproc/med_gmv.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/calc/mean_rates.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/tests/calc/stochastic_test.py
Labels: performance

#10608 Implemented region-dependent logic trees
  openquake/calculators/base.py
  openquake/calculators/classical.py
  openquake/calculators/getters.py
  openquake/calculators/preclassical.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/classical/case_06/expected/uhs.csv
  openquake/qa_tests_data/classical/case_06/job.ini
Labels: enhancement

#10609 Fixed the check on `number_of_logic_tree_samples`
  openquake/commonlib/oqvalidation.py
Labels: bug, inputs

#10610 Refactored lt.py
  openquake/commands/info.py
  openquake/commands/shakemap2gmfs.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/tests/lt_test.py
Labels: internal

#10612 Fixed a small bug in `oq show rlz:`
  openquake/calculators/tests/logictree_test.py
  openquake/calculators/views.py
Labels: bug

#10613 Better check on duplicate branches
  openquake/hazardlib/lt.py
Labels: inputs

#10614 Added a new uncertainty `abMaxMagAbsolute` to the logic tree
  debian/changelog
  openquake/calculators/tests/logictree_test.py
  openquake/commonlib/tests/logictree_test.py
  openquake/hazardlib/lt.py
  openquake/hazardlib/mfd/truncated_gr.py
  openquake/hazardlib/tests/lt_test.py
  openquake/qa_tests_data/logictree/case_03/__init__.py
  openquake/qa_tests_data/logictree/case_03/expected/curve-mean.csv
  openquake/qa_tests_data/logictree/case_03/gsim_logic_tree.xml
  openquake/qa_tests_data/logictree/case_03/job.ini
  openquake/qa_tests_data/logictree/case_03/source_model.xml
  openquake/qa_tests_data/logictree/case_03/source_model_logic_tree.xml
Labels: enhancement

#10615 Moved `__iter__` inside CompositeLogicTree
  openquake/commonlib/tests/readinput_test.py
  openquake/hazardlib/logictree.py
  openquake/hazardlib/lt.py
Labels: internal

#10618 Added an ordinal argument to the DummyGMPE class
  openquake/hazardlib/gsim/base.py
  openquake/qa_tests_data/classical/case_06/gmmLT.xml
  openquake/qa_tests_data/classical/case_06/gmmLT0.xml
  openquake/qa_tests_data/classical/case_06/gmmLT1.xml
  openquake/qa_tests_data/classical/case_07/gsim_logic_tree.xml
Labels: enhancement, inputs

#10621 Refined `expo_to_hdf5` to store all common fields
  openquake/calculators/extract.py
  openquake/commonlib/expo_to_hdf5.py
Labels: enhancement

#10620 In the API endpoint listing the outputs for a job, specify the export type in the url
  debian/changelog
  openquake/server/views.py
Labels: enhancement, outputs

#10624 Added a warning for missing site_labels
  openquake/calculators/classical.py
Labels: inputs

#10594 Compute missing basin params in site model from a GMM's vs30-basin param empirical relationship + Add more site param checks when building site collection
  debian/changelog
  doc/user-guide/advanced/special-features.rst
  openquake/calculators/tests/classical_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/gsim/abrahamson_2014.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/abrahamson_silva_2008.py
  openquake/hazardlib/gsim/afshari_stewart_2016.py
  openquake/hazardlib/gsim/aristeidou_2023.py
  openquake/hazardlib/gsim/aristeidou_2024.py
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/bahrampouri_2021_duration.py
  openquake/hazardlib/gsim/bayless_abrahamson_2018.py
  openquake/hazardlib/gsim/boore_2014.py
  openquake/hazardlib/gsim/bozorgnia_campbell_2016.py
  openquake/hazardlib/gsim/bradley_2013.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2008.py
  openquake/hazardlib/gsim/campbell_bozorgnia_2014.py
  openquake/hazardlib/gsim/chao_2020.py
  openquake/hazardlib/gsim/chiou_youngs_2008.py
  openquake/hazardlib/gsim/chiou_youngs_2014.py
  openquake/hazardlib/gsim/hassani_atkinson_2020.py
  openquake/hazardlib/gsim/kuehn_2020.py
  openquake/hazardlib/gsim/mgmpe/cb14_basin_term.py
  openquake/hazardlib/gsim/mgmpe/m9_basin_term.py
  openquake/hazardlib/gsim/nshmp_2014.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_abrahamson_gulerce_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
  openquake/hazardlib/gsim/parker_2020.py
  openquake/hazardlib/gsim/phung_2020.py
  openquake/hazardlib/gsim/sera_amplification_models.py
  openquake/hazardlib/gsim/si_2020.py
  openquake/hazardlib/gsim/zhao_2006.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/gsim/utils_infer_basin_params_test.py
  openquake/hazardlib/tests/gsim/utils_us23_gmm_adj_test.py
  openquake/hazardlib/tests/site_test.py
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
  openquake/qa_tests_data/classical/README.md
  openquake/qa_tests_data/classical/case_89/__init__.py
  openquake/qa_tests_data/classical/case_89/expected/hazard_curve-mean-PGA.csv
  openquake/qa_tests_data/classical/case_89/expected/hazard_curve-mean-SA(1.0).csv
  openquake/qa_tests_data/classical/case_89/expected/hazard_curve-mean-SA(2.0).csv
  openquake/qa_tests_data/classical/case_89/gmmLT.xml
  openquake/qa_tests_data/classical/case_89/job.ini
  openquake/qa_tests_data/classical/case_89/job_error.ini
  openquake/qa_tests_data/classical/case_89/job_ref.ini
  openquake/qa_tests_data/classical/case_89/site_model.csv
  openquake/qa_tests_data/classical/case_89/sites.csv
  openquake/qa_tests_data/classical/case_89/sites_error.csv
  openquake/qa_tests_data/classical/case_89/ssm.xml
  openquake/qa_tests_data/classical/case_89/ssmLT.xml
Labels: enhancement
