Repository gem/oq-engine, pull requests merged in 2025-07, with the labels that each got.

#10695 Finally fixed the multi-tag extractor
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact1/job.ini
Labels: bug

#10696 Splitting `aggexp_tags.csv`
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact5/exposure_by_mmi.org
  openquake/engine/tests/impact_test.py
  openquake/qa_tests_data/event_based_risk/case_01/expected/aggexp_tags-policy-taxonomy.csv
Labels: outputs

#10703 Fixed `multiply` logic and added function `compute_mce_max`
  openquake/calculators/base.py
  openquake/calculators/postproc/aelo_plots.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/classical/case_08/expected/hcurves.csv
Labels: enhancement

#10700 When calling the /v1/calc/CALC_ID API endpoint, return all fields except ds_calc_dir, pid or any field starting with '_'
  openquake/server/db/actions.py
Labels: enhancement

#10705 Added output `mce_default`
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/compute_rtgm.py
  openquake/calculators/tests/postproc_test.py
  openquake/qa_tests_data/postproc/case_rtgm/expected/mce_default.csv
Labels: outputs

#10706 Removed time.sleep in event_based_risk
  openquake/calculators/event_based_risk.py
  openquake/engine/openquake.cfg
Labels: internal

#10711 Refactored output splitting in event_based_risk/2
  openquake/calculators/event_based_risk.py
  openquake/engine/openquake.cfg
Labels: performance

#10712 Speeding up reading assets
  openquake/baselib/performance.py
  openquake/calculators/event_based_risk.py
Labels: performance

#10714 Refactored sparse matrices
  openquake/calculators/event_based_risk.py
Labels: performance

#10721 Added a warning when exporting missing Asset Risk Distributions
  openquake/calculators/export/risk.py
Labels: outputs

#10723 Further refactoring of event_based_risk
  openquake/baselib/parallel.py
  openquake/baselib/performance.py
  openquake/calculators/event_based_risk.py
  openquake/commonlib/calc.py
Labels: internal

#10725 Reverted check on the vs30
  debian/changelog
  openquake/calculators/base.py
Labels: inputs

#10722 Fixed extract disagg-traditional for multiple realizations
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/extract.py
  openquake/calculators/tests/disagg_test.py
  openquake/qa_tests_data/disagg/case_7/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_7/expected/TRT-traditional-0.csv
  openquake/qa_tests_data/disagg/case_7/job.ini
Labels: bug, outputs

#10726 Merging the POINT logic/1
  openquake/_unc/bins.py
  openquake/_unc/convolution.py
  openquake/_unc/tests/bins_test.py
  openquake/_unc/tests/convolution_test.py
Labels: enhancement

#10730 Storing the AFEs in disagg_by_src
  openquake/calculators/classical.py
  openquake/hazardlib/map_array.py
Labels: enhancement

#10731 Fixed the log message to print the pool size instead of num_cores
  debian/changelog
  openquake/baselib/parallel.py
  openquake/calculators/base.py
  openquake/calculators/preclassical.py
  openquake/engine/engine.py
  utils/membomb
Labels: enhancement

#10732 Merging the POINT logic/3
  openquake/_unc/dtypes/dsg_mde.py
  openquake/_unc/tests/data_calc/disaggregation/test_case01/README.md
  openquake/_unc/tests/data_calc/disaggregation/test_case01/analysis.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/gmclt_asc.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/job_a.ini
  openquake/_unc/tests/data_calc/disaggregation/test_case01/job_all.ini
  openquake/_unc/tests/data_calc/disaggregation/test_case01/job_b.ini
  openquake/_unc/tests/data_calc/disaggregation/test_case01/ssclt_a.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/ssclt_all.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/ssclt_b.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/ssm_a.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/ssm_b.xml
  openquake/_unc/tests/data_calc/disaggregation/test_case01/test_case01_convolution_m.ini
  openquake/_unc/tests/data_calc/disaggregation/test_case01/test_case01_convolution_md.ini
  openquake/_unc/tests/data_calc/disaggregation/test_case01/test_case01_convolution_mde.ini
  openquake/_unc/tests/disagg_pmf_test.py
  openquake/calculators/classical.py
Labels: internal

#10735 Removed the imts argument from global_ses.py
  openquake/calculators/base.py
  openquake/engine/global_ses.py
Labels: internal

#10736 Add `Default` Site Class option
  openquake/server/static/js/engine.js
  openquake/server/views.py
Labels: AELO

#10745 Merging POINT logic/10
  openquake/_unc/convolution.py
  openquake/_unc/hazard_pmf.py
  openquake/_unc/tests/calc_dsg_non_par_source_test.py
  openquake/_unc/tests/calc_dsg_single_source_test.py
  openquake/_unc/tests/calc_dsg_test.py
  openquake/_unc/tests/figs/dsg_test01_md_oq.png
Labels: bug

#10746 Merging POINT logic/11
  openquake/_unc/analysis.py
  openquake/_unc/calc/propagate_uncertainties.py
  openquake/_unc/processing/convolution.py
  openquake/_unc/processing/sampling.py
  openquake/_unc/tests/analysis_test.py
  openquake/_unc/tests/calc_test.py
  openquake/baselib/tests/flake8_test.py
Labels: internal

#10747 Added a tw- IMT test for extract/avg_gmf
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario/case_21/gmf-data.csv
  openquake/qa_tests_data/scenario/case_21/job.ini
Labels: internal

#10751 Removed the parameter `site_effects`
  debian/changelog
  openquake/calculators/base.py
  openquake/commands/shakemap2gmfs.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/shakemap/gmfs.py
Labels: bug

#10752 Restore the base branch path to be one-letter long
  openquake/_unc/analysis.py
  openquake/_unc/hazard_pmf.py
  openquake/_unc/tests/analysis_test.py
  openquake/hazardlib/logictree.py
Labels: outputs
