Repository gem/oq-engine, pull requests merged in 2025-03, with the labels that each got.

#10381 Adding BA08 site term to ModifiableGMPE
  debian/changelog
  openquake/hazardlib/gsim/atkinson_macias_2009.py
  openquake/hazardlib/gsim/mgmpe/ba08_site_term.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/tests/gsim/mgmpe/ba08_site_term_test.py
  openquake/hazardlib/tests/gsim/mgmpe/cb14_basin_term_test.py
  openquake/hazardlib/tests/gsim/utils_us23_gmm_adj_test.py
Labels: enhancement

#10396 Add a flag in the stations parser to keep seismic stations only
  openquake/hazardlib/shakemap/parsers.py
Labels: inputs

#10398 Added `utils/find_exposure`
  openquake/risklib/asset.py
  utils/find_exposure
Labels: internal

#10397 Extended the sourcewriter to save the multifault.fault nodes if present
  openquake/hazardlib/sourcewriter.py
  openquake/hazardlib/tests/source_model/multi-fault-source.xml
  openquake/hazardlib/tests/sourcewriter_test.py
Labels: outputs

#10400 Fixed the IMT DispProb
  openquake/hazardlib/imt.py
Labels: bug

#10394 When switching between approaches, reset the impact forms to their defaults
  openquake/hazardlib/shakemap/validate.py
  openquake/server/static/js/engine.js
Labels: bug

#10391 Fix the behavior of `Build rupture from the USGS` in case the USGS id is changed after building the rupture
  openquake/calculators/postproc/plots.py
  openquake/engine/impact.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/local_settings.py.aelo_impact
  openquake/server/settings.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_form_level_2.html
  openquake/server/templates/engine/includes/impact_run_form.html
  openquake/server/templates/engine/includes/impact_rupture_params_from.html
  openquake/server/urls.py
  openquake/server/views.py
Labels: bug

#10401 Import `timezonefinder` at runtime as it was before
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10403 Added method AssetCollection agg_by_geom
  openquake/calculators/base.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/event_based_risk.py
  openquake/calculators/export/risk.py
  openquake/calculators/post_risk.py
  openquake/calculators/views.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/openquake.cfg
  openquake/engine/tests/impact_test.py
  openquake/risklib/asset.py
Labels: enhancement

#10405 Fixing an issue with the usgs_stations_to_oq_format
  openquake/commands/info.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/data/usp000gvtu-stations.json
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
Labels: bug

#10402 Make sure to build the rupture with user-specified values if available
  openquake/baselib/tests/flake8_test.py
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10406 Added an input `mmi_file` for use in OQ Impact
  debian/changelog
  openquake/calculators/postproc/plots.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/engine/tests/impact5/job.ini
  openquake/engine/tests/impact5/shp.zip
  openquake/engine/tests/impact_test.py
  openquake/risklib/asset.py
Labels: enhancement, inputs

#10410 Storing `mmi_values` in pre_execute
  openquake/calculators/base.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/impact_test.py
  openquake/risklib/asset.py
Labels: enhancement

#10411 Extended `source_model.serialise_to_nrml` to accept mesh_spacing
  debian/changelog
  openquake/hmtk/sources/source_model.py
  openquake/hmtk/tests/sources/test_source_model.py
Labels: enhancement, inputs

#10409 Improve the way input parameters are presented in the email on job completion…
  openquake/hazardlib/shakemap/parsers.py
  openquake/server/views.py
Labels: enhancement

#10413 Fixed `damages-rlzs` in case of multiple perils
  openquake/calculators/event_based_damage.py
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/risklib/riskmodels.py
Labels: bug, outputs

#10412 Provide a clearer error message in case the rupture can not be converted from the USGS format
  openquake/commonlib/readinput.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
Labels: enhancement

#10414 Download, use and export/extract `mmi_tags`
  doc/api-reference/rest-api.rst
  doc/user-guide/advanced/useful-oq-commands.rst
  openquake/calculators/base.py
  openquake/calculators/export/__init__.py
  openquake/calculators/export/risk.py
  openquake/calculators/extract.py
  openquake/engine/impact.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/data/usp0001ccb-shp.zip
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs_impact.html
  openquake/server/templates/engine/includes/impact_rupture_params_from.html
  openquake/server/views.py
Labels: enhancement

#10417 Fixing bug in the std of Thingbaijam et al. (2017)
  openquake/hazardlib/scalerel/thingbaijam2017.py
Labels: bug

#10416 Accepted `source_model_file` in place of `source_model_logic_tree_file`
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/infrastructure_risk_test.py
  openquake/commands/reduce_sm.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/hazardlib/__init__.py
  openquake/hazardlib/logictree.py
  utils/filter_trt
Labels: internal, inputs

#10422 Improved `oq info sources`
  openquake/commands/info.py
Labels: documentation

#10424 Temporarily disabled `get_mmi_values` for many assets
  openquake/calculators/base.py
Labels: performance, critical

#10423 Added a `losses_by_site` extractor (i.e. 1000x speedup)
  debian/changelog
  openquake/calculators/extract.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commands/extract.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/qa_tests_data/scenario_risk/case_master/expected/losses_by_site.org
Labels: enhancement, outputs

#10426 Fixed `get_mmi_values`
  openquake/calculators/base.py
  openquake/risklib/asset.py
Labels: bug

#10428 [WIP] correction to indexing to get fault-to-site distance for multifault disagg by source
  openquake/hazardlib/source/multi_fault.py
Labels: bug

#10431 Added command `oq info apply_uncertainty`
  debian/changelog
  openquake/commands/info.py
Labels: documentation

#10432 Changed `mmi_tags` to have only 12 columns
  debian/changelog
  doc/api-reference/rest-api.rst
  openquake/calculators/base.py
  openquake/calculators/extract.py
  openquake/risklib/asset.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: outputs

#10430 Revert some variable names to match described notation
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: internal

#10435 Do not create `hcurves-rlzs` and `hcurves-maps` needlessly
  openquake/calculators/classical.py
Labels: bug

#10437 Fixed `ContextMaker.get_pmap`
  doc/release-notes/whats-new-2.4.md
  doc/release-notes/whats-new-3.3.md
  openquake/hazardlib/contexts.py
Labels: bug, backport

#10434 Not splitting multi-fault sources in preclassical
  openquake/calculators/preclassical.py
Labels: bug

#10441 Moved BLOCKSIZE in config.memory.max_multi_fault_ruptures
  debian/changelog
  openquake/engine/openquake.cfg
  openquake/engine/tests/aelo_test.py
  openquake/hazardlib/source/multi_fault.py
  openquake/qa_tests_data/mosaic/HazardMosaic/test_models/cea24/in/ssm/faults/cea24_small_sections.xml
  openquake/qa_tests_data/mosaic/HazardMosaic/test_models/cea24/in/ssm/faults/small_test.hdf5
  openquake/qa_tests_data/mosaic/HazardMosaic/test_models/cea24/in/ssm/faults/small_test.xml
  openquake/qa_tests_data/mosaic/HazardMosaic/test_models/cea24/in/ssmLT_little_test.xml
  openquake/qa_tests_data/mosaic/Projects/AELO/aeloy3/py/Run_Jobs/CEA/gmmLT.xml
  openquake/qa_tests_data/mosaic/Projects/AELO/aeloy3/py/Run_Jobs/CEA/site10/job_dos_vs30_760_small.ini
  openquake/qa_tests_data/mosaic/Projects/AELO/aeloy3/py/Run_Jobs/CEA/site10/sites_CEA_dos.csv
Labels: internal

#10436 [WIP] Keep multifault tags only for faults with ruptures
  openquake/hazardlib/source/multi_fault.py
Labels: bug

#10442 Managing better far away point-like sources
  openquake/calculators/classical.py
  openquake/calculators/preclassical.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
Labels: performance

#10443 Fixed `oq show rlz:` when the gsim logic tree was not properly reduced
  debian/changelog
  openquake/calculators/classical.py
  openquake/calculators/event_based.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/views.py
  openquake/hazardlib/gsim_lt.py
  openquake/hazardlib/source_reader.py
  openquake/qa_tests_data/classical/case_05/MA1_br1.xml
  openquake/qa_tests_data/classical/case_05/__init__.py
  openquake/qa_tests_data/classical/case_05/expected/uhs.csv
  openquake/qa_tests_data/classical/case_05/gmpe_logic_tree_MPS19.xml
  openquake/qa_tests_data/classical/case_05/job.ini
  openquake/qa_tests_data/classical/case_05/smlt.xml
Labels: bug

#10439 Use a separate button to retrieve station data from the USGS and avoid downloading the rupture when using the ShakeMap
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_form_level_2.html
  openquake/server/templates/engine/includes/impact_run_form.html
  openquake/server/urls.py
  openquake/server/user_profile/models.py
  openquake/server/views.py
Labels: enhancement

#10445 Added type checks to `logs.dbcmd`
  openquake/commonlib/logs.py
Labels: enhancement, internal

#10446 Extended the exposure reader to accept .csv.gz files
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/calculators/tests/classical_test.py
  openquake/calculators/tests/event_based_risk_test.py
  openquake/hazardlib/tests/site_amplification_test.py
  openquake/qa_tests_data/event_based_risk/case_9/exposure_model.csv
  openquake/qa_tests_data/event_based_risk/case_9/exposure_model.csv.gz
  openquake/qa_tests_data/event_based_risk/case_9/exposure_model.xml
  openquake/qa_tests_data/event_based_risk/case_miriam/amplification.csv
  openquake/risklib/asset.py
Labels: enhancement, inputs

#10447 Slightly optimized `calc_average`
  openquake/hazardlib/source/point.py
Labels: performance

#10448 Fixed call to `v1/calc/list` breaking the DbServer
  debian/changelog
  openquake/commonlib/logs.py
  openquake/server/db/actions.py
  openquake/server/views.py
Labels: critical, backport

#10451 Do not store the `backarc` parameter when not needed
  debian/changelog
  doc/user-guide/configuration-file/hazard-common-config.rst
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/data/classical_job.ini
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/site_test.py
  openquake/qa_tests_data/event_based_risk/case_master/job.ini
Labels: enhancement

#10452 Renamed the sources in LogicTreeCase2ClassicalPSHA
  demos/hazard/LogicTreeCase2ClassicalPSHA/source_model.xml
  demos/hazard/LogicTreeCase2ClassicalPSHA/source_model_logic_tree.xml
Labels: documentation

#10433 Rename two API endpoints and add field descriptions to the exported json files
  doc/api-reference/rest-api.rst
  openquake/calculators/export/__init__.py
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
  openquake/engine/tests/impact_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk_tags.csv
  openquake/server/templates/engine/get_outputs_impact.html
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#10453 Fixing build_global_exposure
  openquake/commonlib/oqvalidation.py
  openquake/risklib/riskmodels.py
Labels: internal

#10454 Fix typo in conditioned_gmfs
  openquake/hazardlib/calc/conditioned_gmfs.py
Labels: bug

#10455 Enhanced `build_global_exposure` to work at admin level 2
  debian/changelog
  openquake/baselib/hdf5.py
  openquake/commonlib/expo_to_hdf5.py
Labels: inputs

#10456 Exposed the output `avg_gmf`
  debian/changelog
  openquake/calculators/base.py
Labels: outputs

#10459 Also when using the ShakeMap, get sites close to the surface of the rupture
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/templates/engine/includes/impact_form_level_2.html
Labels: bug

#10458 Add unit test for use of ModifiableGMPE within an AvgGMPE
  openquake/hazardlib/tests/gsim/mgmpe/modifiable_gmpe_test.py
Labels: enhancement, documentation

#10457 Extracting asset lon,lat at 5 digits
  openquake/commonlib/util.py
Labels: outputs

#10461 Refine slow tasks
  openquake/hazardlib/contexts.py
Labels: performance

#10462 Minimal change in AbrahamsonGulerce2020
  openquake/hazardlib/contexts.py
  openquake/hazardlib/gsim/abrahamson_gulerce_2020.py
Labels: performance

#10464 Removing references to SMTK
  openquake/baselib/python3compat.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/geo/surface/planar.py
Labels: documentation

#10465 Update setup.cfg
  setup.cfg
Labels: dependencies

#10463 Replaced pyshp with fiona
  debian/changelog
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/shakemapconverter_test.py
  requirements-py310-linux64.txt
  requirements-py310-macos_arm64.txt
  requirements-py310-macos_x86_64.txt
  requirements-py310-win64.txt
  requirements-py311-linux64.txt
  requirements-py311-macos_arm64.txt
  requirements-py311-macos_x86_64.txt
  requirements-py311-win64.txt
  requirements-py312-linux64.txt
  requirements-py312-macos_arm64.txt
  requirements-py312-macos_x86_64.txt
  requirements-py312-win64.txt
Labels: dependencies

#10466 Restored 64 bit poes
  openquake/hazardlib/contexts.py
  openquake/hazardlib/map_array.py
  openquake/hazardlib/tom.py
  openquake/qa_tests_data/disagg/case_5/expected/Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/Mag_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Lon_Lat-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist-0.csv
  openquake/qa_tests_data/disagg/case_5/expected/TRT_Mag_Dist_Eps-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectra-1-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-0-1.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-0.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum-1-1.csv
Labels: bug

#10467 Get impact calc description from the USGS when possible; hide some inputs from the email notifications
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/server/views.py
Labels: enhancement

#10155 Site response models + modification to Modifiable GMPE for AUS23
  debian/changelog
  openquake/hazardlib/gsim/aus23/NGA-East_Backbone_Model.geometric.3000.mps.hdf5
  openquake/hazardlib/gsim/aus23/__init__.py
  openquake/hazardlib/gsim/aus23/aus23_nga_east.py
  openquake/hazardlib/gsim/eshm20_craton.py
  openquake/hazardlib/gsim/mgmpe/hashash2020.py
  openquake/hazardlib/gsim/mgmpe/modifiable_gmpe.py
  openquake/hazardlib/gsim/mgmpe/stewart2020.py
  openquake/hazardlib/gsim/nga_east.py
  openquake/hazardlib/gsim/usgs_ceus_2019.py
  openquake/hazardlib/tests/gsim/aus23/__init__.py
  openquake/hazardlib/tests/gsim/aus23/aus23_nga_east_test.py
  openquake/hazardlib/tests/gsim/mgmpe/hashash2020_test.py
  openquake/hazardlib/tests/gsim/mgmpe/stewart2020_test.py
Labels: enhancement

#10471 When plotting assets, also plot stations if available
  openquake/commands/plot_assets.py
Labels: enhancement

#10473 Instead of just 'Loaded' display 'N stations were loaded'
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/static/js/engine.js
  openquake/server/views.py
Labels: enhancement

#10475 Removed the --config-file option from the oq engine command
  debian/changelog
  doc/getting-started/running-calculations/command-line.rst
  openquake/commands/engine.py
Labels: bug

#10476 Using the updated exposure.hdf5 file
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
Labels: internal

#10478 OQImpact: aggregating by ID_2
  debian/changelog
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
Labels: enhancement, outputs

#10479 Including `affectedpop` and `injured` in exposure.hdf5
  utils/build_global_exposure
Labels: inputs

#10480 Added OQ_WORKERPOOL_ERROR
  openquake/baselib/workerpool.py
Labels: internal

#10483 Introduced alias NGAEastAUS2023GMPE
  openquake/hazardlib/gsim/aus23/aus23_nga_east.py
  openquake/hazardlib/valid.py
Labels: enhancement

#10468 Update NowickiJessee2018Landslides model and add AllstadtEtAl2022Landslides
  doc/underlying-science/secondary-perils.rst
  doc/user-guide/inputs/secondary-perils-inputs.rst
  openquake/sep/classes.py
  openquake/sep/landslide/displacement.py
  openquake/sep/landslide/probability.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: enhancement

#10485 Add API endpoint `impact_run_with_shakemap` that runs a calculation given the usgs_id only
  openquake/hazardlib/shakemap/validate.py
  openquake/server/templates/engine/includes/aelo_form.html
  openquake/server/templates/engine/includes/impact_form_level_0.html
  openquake/server/templates/engine/includes/impact_form_level_1.html
  openquake/server/templates/engine/includes/impact_form_level_2.html
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: enhancement

#10486 Manually unzip shapefiles on Windows
  openquake/hazardlib/shakemap/parsers.py
Labels: bug, inputs
