Repository gem/oq-engine, pull requests merged in 2025-02, with the labels that each got.

#10305 Some more small fixes for backarc site param use in NZ 2022 NSHM
  debian/changelog
  openquake/hazardlib/gsim/nz22/atkinson_2022.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_parker.py
Labels: bug

#10306 Renamed sub-peril earthquake->groundshaking
  openquake/calculators/extract.py
  openquake/calculators/multi_risk.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/event_based_damage/case_11/structural_consequence_model.csv
  openquake/qa_tests_data/event_based_damage/case_13/structural_consequence_model.csv
  openquake/qa_tests_data/event_based_damage/case_14/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_15/consequences_by_taxonomy.csv
  openquake/qa_tests_data/event_based_damage/case_16/consequences.csv
  openquake/qa_tests_data/infrastructure_risk/case_1/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/consequence_multiple_loss_types.csv
  openquake/qa_tests_data/infrastructure_risk/case_2/job.ini
  openquake/qa_tests_data/infrastructure_risk/demand_supply/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/directed/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/eff_loss_random/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/five_nodes_demsup_directed/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/five_nodes_demsup_directedunweighted/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/five_nodes_demsup_multidirected/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/multidirected/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/multigraph/nonfunctional.csv
  openquake/qa_tests_data/infrastructure_risk/undirected/nonfunctional.csv
  openquake/qa_tests_data/multi_risk/case_1/consequence_model.csv
  openquake/qa_tests_data/multi_risk/case_1/consequence_model_2.csv
  openquake/qa_tests_data/scenario_damage/case_13/consequence_recovery_time.csv
  openquake/qa_tests_data/scenario_damage/case_14/consequence_model.csv
  openquake/qa_tests_data/scenario_damage/case_16/consequence_recovery_time.csv
  openquake/qa_tests_data/scenario_damage/case_17/consequence_displaced.csv
  openquake/qa_tests_data/scenario_damage/case_17/consequence_fatalities.csv
  openquake/qa_tests_data/scenario_damage/case_18/consequence_displaced.csv
  openquake/qa_tests_data/scenario_damage/case_18/consequence_fatalities.csv
  openquake/qa_tests_data/scenario_damage/case_22/consequences.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_22/job_r.ini
  openquake/qa_tests_data/scenario_damage/case_22/mapping_multiple_perils.csv
  openquake/qa_tests_data/scenario_damage/case_4b/consequence_model.csv
  openquake/qa_tests_data/scenario_damage/case_9/consequences_by_taxonomy.csv
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
  openquake/risklib/tests/scientific_test.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: outputs, inputs

#10309 Removed microseconds from the timestamp
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10311 Fixed `AttributeError: module django.core.mail has no attribute outbox`
  .github/workflows/docs.yml
  openquake/server/__init__.py
Labels: internal

#10310 Saving rupture_idxs as compresses strings
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/sourcewriter.py
Labels: performance

#10312 Renamed .taxonomies->.riskids where appropriated
  openquake/calculators/base.py
  openquake/risklib/__init__.py
  openquake/risklib/riskmodels.py
Labels: internal

#10313 Renamed aristotle->impact in the engine
  .github/workflows/engine_pr_test.yml
  .github/workflows/engine_weekly_test.yml
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_risk.py
  openquake/commands/compare.py
  openquake/commands/mosaic.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/commonlib/tests/logictree_test.py
  openquake/commonlib/tests/readinput_test.py
  openquake/engine/impact.py
  openquake/engine/tests/impact1/aggrisk.txt
  openquake/engine/tests/impact1/job.ini
  openquake/engine/tests/impact2/aggrisk.txt
  openquake/engine/tests/impact2/job.ini
  openquake/engine/tests/impact3/aggrisk.txt
  openquake/engine/tests/impact3/job.ini
  openquake/engine/tests/impact4/aggrisk.txt
  openquake/engine/tests/impact4/job.ini
  openquake/engine/tests/impact_test.py
  openquake/hazardlib/contexts.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/site.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
  openquake/server/local_settings.py.aelo_impact
  openquake/server/management/commands/createnormaluser.py
  openquake/server/settings.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/get_outputs_aristotle.html
  openquake/server/templates/engine/includes/aristotle_form_level_1.html
  openquake/server/templates/engine/includes/aristotle_form_level_2.html
  openquake/server/templates/engine/includes/aristotle_run_form.html
  openquake/server/templates/engine/index.html
  openquake/server/templates/registration/normal_user_creation_email_impact.txt
  openquake/server/templates/registration/normal_user_creation_email_subject_impact.txt
  openquake/server/templates/registration/password_reset_email_impact.txt
  openquake/server/templates/registration/password_reset_subject_impact.txt
  openquake/server/tests/settings/local_settings_aristotle.py
  openquake/server/tests/settings/local_settings_impact.py
  openquake/server/tests/test_impact_mode.py
  openquake/server/urls.py
  openquake/server/v1/calc_urls.py
  openquake/server/views.py
Labels: internal

#10314 Fixed `consdict`
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based_damage/case_16/consequences.csv
  openquake/qa_tests_data/event_based_damage/case_16/contents_fragility_model.xml
  openquake/qa_tests_data/scenario_damage/case_13/consequence_recovery_time.csv
  openquake/qa_tests_data/scenario_damage/case_13/expected/aggrisk-stats.csv
  openquake/qa_tests_data/scenario_damage/case_13/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_16/job.ini
  openquake/qa_tests_data/scenario_damage/case_16/taxmap.csv
  openquake/qa_tests_data/scenario_damage/case_22/consequences.csv
  openquake/qa_tests_data/scenario_damage/case_4b/consequence_model.csv
  openquake/risklib/__init__.py
  openquake/risklib/riskmodels.py
Labels: internal

#10316 Fixed bug in the sourcewriter breaking the MBTK
  openquake/hazardlib/sourcewriter.py
Labels: bug

#10315 Added a check on the number of perils by risk_id
  debian/changelog
  openquake/risklib/riskmodels.py
Labels: inputs

#10319 Added check on the consequence functions for missing taxonomies
  openquake/calculators/base.py
  openquake/commonlib/readinput.py
  openquake/risklib/asset.py
  openquake/risklib/riskmodels.py
Labels: enhancement, inputs

#10296 ARISTOTLE: add to level 2 interface the possibility to choose among different workflows
  bin/arist
  openquake/engine/impact.py
  openquake/hazardlib/scalerel/__init__.py
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/hazardlib/valid.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_form_level_1.html
  openquake/server/templates/engine/includes/impact_form_level_2.html
  openquake/server/templates/engine/includes/impact_run_form.html
  openquake/server/templates/engine/includes/impact_rupture_params_from.html
  openquake/server/tests/test_impact_mode.py
  openquake/server/views.py
Labels: enhancement

#10320 Implemented quantiles in scenario_risk, visible in aggrisk_tags
  debian/changelog
  doc/api-reference/rest-api.rst
  openquake/calculators/checkers.py
  openquake/calculators/extract.py
  openquake/calculators/post_risk.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/engine/tests/impact1/aggrisk.txt
  openquake/engine/tests/impact1/aggrisk_tags.txt
  openquake/engine/tests/impact2/aggrisk.txt
  openquake/engine/tests/impact2/aggrisk_tags.txt
  openquake/engine/tests/impact3/aggrisk.txt
  openquake/engine/tests/impact3/aggrisk_tags.txt
  openquake/engine/tests/impact4/aggrisk.txt
  openquake/engine/tests/impact4/aggrisk_tags.txt
  openquake/engine/tests/impact_test.py
  openquake/hazardlib/stats.py
  openquake/hazardlib/tests/stats_test.py
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk_tags.csv
  openquake/qa_tests_data/scenario_risk/case_1g/job_haz.ini
  openquake/qa_tests_data/scenario_risk/case_master/job.ini
  openquake/server/views.py
Labels: enhancement, outputs

#10321 Fixed checkers.check to generate .org files
  openquake/calculators/checkers.py
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact1/aggrisk_tags.txt
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
  openquake/server/tests/test_impact_mode.py
Labels: internal

#10324 Added utils/fix_consequences
  debian/changelog
  utils/fix_consequences
Labels: internal, inputs

#10325 Increased `pmap_max_mb`
  openquake/calculators/classical.py
  openquake/engine/openquake.cfg
  openquake/hazardlib/source_reader.py
Labels: performance

#10326 Fixed bug in classical_damage with sampling
  debian/changelog
  openquake/calculators/classical_damage.py
  openquake/calculators/tests/classical_damage_test.py
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-000.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-001.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-002.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-003.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-004.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-005.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-006.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/damages-rlz-007.csv
  openquake/qa_tests_data/classical_damage/case_master/expected/uhs-mean.csv
  openquake/qa_tests_data/classical_damage/case_master/job_haz.ini
Labels: bug

#10327 Fixed the wrong message "Reduced the number of point sources from XX to YY"
  openquake/calculators/preclassical.py
Labels: internal

#10323 Improve visualization of the losses table
  openquake/calculators/export/__init__.py
  openquake/server/templates/engine/get_outputs_impact.html
  openquake/server/views.py
Labels: enhancement

#10329 Give feedback through the WebUI if the uploaded rupture xml is malformed
  openquake/hazardlib/shakemap/parsers.py
Labels: bug

#10333 Changed the aggrisk_tags exporter
  doc/api-reference/rest-api.rst
  openquake/calculators/extract.py
  openquake/engine/tests/impact1/aggrisk_tags.org
  openquake/engine/tests/impact2/aggrisk_tags.org
  openquake/engine/tests/impact3/aggrisk_tags.org
  openquake/engine/tests/impact4/aggrisk_tags.org
  openquake/qa_tests_data/event_based_risk/case_1/expected/aggrisk_tags.csv
  openquake/server/tests/test_impact_mode.py
  openquake/server/views.py
Labels: outputs

#10332 Adding rate of occurrence to the table produced with the median spectrum
  debian/changelog
  openquake/calculators/export/hazard.py
  openquake/calculators/postproc/median_spectrum.py
  openquake/calculators/tests/postproc_test.py
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-PGA.csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.1).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.2).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.3).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.4).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.5).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(0.75).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(1.0).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(1.2).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(1.5).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(1.75).csv
  openquake/qa_tests_data/postproc/case_median_spectrum/expected/median_spectrum_disagg-grp0-SA(2.0).csv
Labels: outputs

#10334 fix missing attributes when running NZ22 with disagg_by_src
  debian/changelog
  openquake/calculators/tests/disagg_test.py
  openquake/hazardlib/gsim/nz22/nz_nshm2022_kuehn_2020.py
  openquake/qa_tests_data/disagg/README.md
  openquake/qa_tests_data/disagg/case_16/__init__.py
  openquake/qa_tests_data/disagg/case_16/gmmLT.xml
  openquake/qa_tests_data/disagg/case_16/job_dsg.ini
  openquake/qa_tests_data/disagg/case_16/sites_dsg.csv
  openquake/qa_tests_data/disagg/case_16/ssm/slab_mps.xml
  openquake/qa_tests_data/disagg/case_16/ssmLT.xml
Labels: bug

#10335 Harmonize files used for email notifications
  openquake/server/management/commands/createnormaluser.py
  openquake/server/templates/registration/.gitignore
  openquake/server/templates/registration/normal_user_creation_email_content.txt.aelo.tmpl
  openquake/server/templates/registration/normal_user_creation_email_content.txt.default.tmpl
  openquake/server/templates/registration/normal_user_creation_email_content.txt.impact.tmpl
  openquake/server/templates/registration/password_reset_email_content.txt.aelo.tmpl
  openquake/server/templates/registration/password_reset_email_content.txt.default.tmpl
  openquake/server/templates/registration/password_reset_email_content.txt.impact.tmpl
  openquake/server/templates/registration/password_reset_email_subject.txt.aelo.tmpl
  openquake/server/templates/registration/password_reset_email_subject.txt.default.tmpl
  openquake/server/templates/registration/password_reset_email_subject.txt.impact.tmpl
  openquake/server/urls.py
Labels: internal

#10114 Add Attenuation Model of Campbell Bozorgnia 2003 For All Conditions
  doc/api-reference/openquake.hazardlib.gsim.rst
  openquake/hazardlib/gsim/campbell_bozorgnia_2003_world.py
  openquake/hazardlib/tests/gsim/campbell_bozorgnia_2003_world_test.py
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_R_H.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_R_V.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_SS_H.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_SS_V.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_T_H.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_MEAN_T_V.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_STD_TOT_H.csv
  openquake/hazardlib/tests/gsim/data/CB03_W/CB03_STD_TOT_V.csv
Labels: enhancement

#10338 Refined source weights via contexts.EPS
  openquake/hazardlib/contexts.py
Labels: performance

#10337 When the PAM authentication backend is used, do not force the user to actualize email notification templates
  openquake/server/management/commands/createnormaluser.py
  openquake/server/urls.py
Labels: internal

#10342 Hiding shapely warnings
  debian/changelog
  openquake/hazardlib/geo/mesh.py
Labels: internal

#10341 Fixed the weight stored in `source_info`
  openquake/hazardlib/contexts.py
  openquake/hazardlib/source_reader.py
Labels: internal

#10344 Fixed minimum magnitude filtering
  debian/changelog
  openquake/hazardlib/contexts.py
  openquake/qa_tests_data/classical/case_03/expected/hazard_curve-PGA.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_PGA.csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_curve-mean_SA(0.2).csv
  openquake/qa_tests_data/logictree/case_13/expected/hazard_map-mean.csv
Labels: bug

#10343 Minor edits to whats-new-3.23.md
  doc/release-notes/whats-new-3.23.md
Labels: documentation

#10345 Add the possibility to specify the user level when using the command `createnormaluser`
  openquake/server/management/commands/createnormaluser.py
Labels: internal

#10347 When using ShakeMap, hide mosaic_model, trt, truncation_level and station-related fields
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_run_form.html
Labels: enhancement

#10348 Removed explicit dependency on pytz
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
Labels: dependencies

#10351 Update CONTRIBUTORS.txt
  CONTRIBUTORS.txt
Labels: documentation

#10354 Hiding a sqlite DeprecationWarning
  openquake/commonlib/dbapi.py
Labels: internal

#10355 Added a sanity check on the stored source weight
  openquake/calculators/base.py
Labels: internal

#10356 In engine_weekly_test.yml add a step to actualize default templates for email notificatios before starting the webui
  .github/workflows/engine_weekly_test.yml
Labels: bug

#10357 Fix modified_gsim to work with gsim which requires a specific distance parameter
  debian/changelog
  openquake/hazardlib/tests/valid_test.py
  openquake/hazardlib/valid.py
Labels: bug

#10352 Some improvements to the OQ-Impact level 2 interface
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_rupture_params_from.html
  openquake/server/views.py
Labels: enhancement

#10359 Made it possible to pass the models to the global_ses script
  openquake/commands/show_attrs.py
  openquake/engine/global_ses.py
Labels: enhancement, inputs

#10360 Make it possible to run impact calculations ignoring stations
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/server/static/css/engine.css
  openquake/server/static/js/engine.js
  openquake/server/templates/engine/includes/impact_run_form.html
  openquake/server/views.py
Labels: enhancement

#10358 Update arteta_2021.py
  openquake/hazardlib/gsim/arteta_2021.py
Labels: bug

#10254 Add landslide models
  doc/underlying-science/secondary-perils.rst
  openquake/calculators/tests/event_based_test.py
  openquake/hazardlib/site.py
  openquake/qa_tests_data/event_based/case_26/cali_newmark_steep.csv
  openquake/qa_tests_data/event_based/case_26/gmmLT_2019_IA.xml
  openquake/qa_tests_data/event_based/case_26/job_land.ini
  openquake/qa_tests_data/infrastructure_risk/case_2/job.ini
  openquake/qa_tests_data/infrastructure_risk/case_2/site_model.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/aggrisk.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/dmg.csv
  openquake/qa_tests_data/scenario_damage/case_22/fragility_model_landslide.xml
  openquake/qa_tests_data/scenario_damage/case_22/job_h.ini
  openquake/qa_tests_data/scenario_damage/case_22/site_model.csv
  openquake/sep/calculators.py
  openquake/sep/classes.py
  openquake/sep/landslide/common.py
  openquake/sep/landslide/displacement.py
  openquake/sep/landslide/newmark.py
  openquake/sep/landslide/probability.py
  openquake/sep/landslide/rockfalls.py
  openquake/sep/landslide/static_safety_factor.py
  openquake/sep/tests/data/test_site_params.csv
  openquake/sep/tests/landslide/test_displacement.py
  openquake/sep/tests/landslide/test_newmark.py
  openquake/sep/tests/landslide/test_static_safety_factor.py
  openquake/sep/tests/test_sep_suite_2.py
Labels: enhancement

#10364 Fix the `Use point rupture from the USGS` approach
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/views.py
Labels: bug

#10366 Introduced `config.memory.gmf_data_rows`
  debian/changelog
  openquake/calculators/event_based.py
  openquake/engine/openquake.cfg
Labels: internal

#10361 Extended the output loss types to `affected` and `injured`
  debian/changelog
  openquake/calculators/base.py
  openquake/calculators/tests/scenario_risk_test.py
  openquake/commonlib/oqvalidation.py
  openquake/commonlib/readinput.py
  openquake/qa_tests_data/scenario_risk/case_12/Exposure_Albania.xml
  openquake/qa_tests_data/scenario_risk/case_12/Exposure_Res_Albania.csv
  openquake/qa_tests_data/scenario_risk/case_12/__init__.py
  openquake/qa_tests_data/scenario_risk/case_12/expected/aggrisk-.csv
  openquake/qa_tests_data/scenario_risk/case_12/expected/aggrisk-ID.csv
  openquake/qa_tests_data/scenario_risk/case_12/expected/aggrisk-OCCUPANCY.csv
  openquake/qa_tests_data/scenario_risk/case_12/expected/avg_losses.csv
  openquake/qa_tests_data/scenario_risk/case_12/job.ini
  openquake/qa_tests_data/scenario_risk/case_12/site_model.csv
  openquake/qa_tests_data/scenario_risk/case_12/vulnerability_affected_moderate.xml
  openquake/qa_tests_data/scenario_risk/case_12/vulnerability_injured.xml
  openquake/risklib/riskmodels.py
  openquake/risklib/scientific.py
Labels: enhancement, inputs

#10365 Fix the management of rake, dip and strike
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/shakemap/validate.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/hazardlib/tests/shakemap/validate_test.py
  openquake/server/static/js/engine.js
Labels: bug

#10370 Produce and upload demos zip file also for engine-3.23
  .github/workflows/demos_ltr_latest.yml
Labels: internal

#10372 Added `valid.indexes`
  openquake/hazardlib/nrml.py
  openquake/hazardlib/sourceconverter.py
  openquake/hazardlib/valid.py
Labels: internal

#10375 Made `Surface.get_width` mandatory
  openquake/hazardlib/geo/surface/base.py
Labels: internal

#10373 Added `InfrastructureMultiPeril` demo
  demos/risk/InfrastructureMultiPeril/README.md
  demos/risk/InfrastructureMultiPeril/consequence_multiple_loss_types.csv
  demos/risk/InfrastructureMultiPeril/exposure.xml
  demos/risk/InfrastructureMultiPeril/exposure_demo_edges.csv
  demos/risk/InfrastructureMultiPeril/exposure_demo_nodes.csv
  demos/risk/InfrastructureMultiPeril/fragility_model_landslide.xml
  demos/risk/InfrastructureMultiPeril/fragility_model_liquefaction.xml
  demos/risk/InfrastructureMultiPeril/fragility_model_structural.xml
  demos/risk/InfrastructureMultiPeril/gmpe_logic_tree_ascr.xml
  demos/risk/InfrastructureMultiPeril/job.ini
  demos/risk/InfrastructureMultiPeril/mapping_multiple_loss_types.csv
  demos/risk/InfrastructureMultiPeril/rupture.xml
  demos/risk/InfrastructureMultiPeril/site_model.csv
Labels: documentation

#10374 Fix formatting errors in landslide documentation
  doc/underlying-science/secondary-perils.rst
Labels: documentation

#10380 Fix the `Use finite rupture from the USGS` approach getting rupture geometries from `rupture.json`
  openquake/hazardlib/shakemap/parsers.py
  openquake/hazardlib/tests/shakemap/parsers_test.py
Labels: bug

#10382 Implemented kendra-splitting of multifault sources
  debian/changelog
  openquake/calculators/tests/__init__.py
  openquake/calculators/tests/classical_test.py
  openquake/hazardlib/source/multi_fault.py
  openquake/hazardlib/source_reader.py
  openquake/hazardlib/sourceconverter.py
  openquake/qa_tests_data/classical/case_75/expected/context.org
  openquake/qa_tests_data/classical/case_75/job.ini
  openquake/qa_tests_data/classical/case_75/ruptures_0.xml
Labels: enhancement, inputs

#10383 Extended `avg_gmf` to the secondary perils
  debian/changelog
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/qa_tests_data/event_based/case_26/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_31/expected/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_33/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_26/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_27/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_29/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario/case_30/expected/avg_gmf.csv
  openquake/qa_tests_data/scenario_damage/case_22/expected/avg_gmf.csv
Labels: outputs

#10387 Skipped avg_gmf tests on macos
  openquake/calculators/event_based.py
  openquake/calculators/tests/scenario_test.py
  openquake/qa_tests_data/scenario_risk/conditioned/expected/avg_gmf.csv
Labels: internal

#10388 Generating hazard curves and maps from GMFs
  openquake/calculators/event_based.py
  openquake/calculators/tests/event_based_test.py
  openquake/commonlib/calc.py
  openquake/qa_tests_data/event_based/case_26/avg_gmf.csv
  openquake/qa_tests_data/event_based/case_26/job_liq.ini
  openquake/qa_tests_data/event_based/case_26/liquefaction_sites.csv
Labels: enhancement, outputs

#10386 Fix feedback in case of issues occurring while converting the rupture from the USGS format
  openquake/hazardlib/tests/shakemap/parsers_test.py
  openquake/server/static/js/engine.js
Labels: bug

#10390 Storing the IMTs in `gmf_data`
  doc/contributing/developing-with-the-engine.rst
  openquake/calculators/base.py
  openquake/calculators/event_based.py
  openquake/calculators/event_based_damage.py
  openquake/calculators/export/hazard.py
  openquake/calculators/extract.py
  openquake/calculators/tests/event_based_test.py
  openquake/calculators/tests/scenario_damage_test.py
  openquake/calculators/tests/scenario_test.py
  openquake/calculators/views.py
  openquake/commands/shakemap2gmfs.py
  openquake/commands/tests/commands_test.py
  openquake/commonlib/calc.py
  openquake/commonlib/oqvalidation.py
  openquake/hazardlib/calc/gmf.py
  openquake/hazardlib/tests/gsim/can15/nbcc_aa13_test.py
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowCrust.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowFault.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_ActiveShallowOffshore.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_StableShallowCrust.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionInterface.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionIntraSlab30.csv
  openquake/hazardlib/tests/gsim/data/CAN15/NBCC2015_AA13_SubductionIntraSlab50.csv
  openquake/qa_tests_data/scenario_damage/case_14/job_wrong.ini
  openquake/risklib/riskmodels.py
  openquake/risklib/tests/scientific_test.py
Labels: internal

#10392 Refactored the hcurves exporter
  openquake/baselib/hdf5.py
  openquake/calculators/event_based.py
  openquake/calculators/export/hazard.py
Labels: internal

#10393 Supported old column names in gmf_data
  openquake/calculators/extract.py
  openquake/server/tests/views_test.py
Labels: bug, outputs
